### ISSUE TITLE
PHP error after updating

### ISSUE THREAD

**Issue by saitoh183** [d8ahazard/Phlex#1]
just updated to the latest build and now i get a blank screen after i login
using PHP 7.0 with nginx as reverse proxy
when i check the logs:

`[error] 26661#26661: *84 FastCGI sent in stderr: "PHP message: PHP Fatal error:  'break' not in the 'loop' or 'switch' context in /opt/Phlex/api.php on line 1555" while reading response header from upstream, client: 192.168.13.1, server: my.domain.com, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "my.domain.com"`

**Comment by d8ahazard** [comment]
Already fixed

**Comment by saitoh183** [comment]
Thanks,
one more thing, does GH work now? i saw the message is removed from the readme.
