### ISSUE TITLE
socket_create() error

### ISSUE THREAD

**Issue by kylerw** [d8ahazard/Phlex#10]
[22-Mar-2017 17:31:30 America/Chicago] PHP Fatal error:  Uncaught Error: Call to undefined function socket_create() in /config/www/Phlex/cast/mdns.php:16
Stack trace:
#0 /config/www/Phlex/cast/Chromecast.php(54): mDNS->__construct()
#1 /config/www/Phlex/api.php(1463): Chromecast::scan()
#2 /config/www/Phlex/api.php(1437): fetchCastDevices()
#3 /config/www/Phlex/api.php(1349): fetchDevices('clients')
#4 /config/www/Phlex/api.php(1485): refreshDevices('clients')
#5 /config/www/Phlex/api.php(260): fetchClientList()
#6 {main}
  thrown in /config/www/Phlex/cast/mdns.php on line 16

sockets is installed/enabled.

**Comment by d8ahazard** [comment]
See the readme, you need sockets enabled for Cast.

**Comment by kylerw** [comment]
@d8ahazard Yeah, saw that. Had to install it manually in the docker container using: apk add php-sockets 

That downloads sockets.so file and adds required ini to enable but still seeing the error.

**Comment by lellimecnar** [comment]
I'm seeing the same thing. `php5-sockets` is installed, but I'm still getting the error, and nothing works.

**Comment by Imacellist** [comment]
I'm running into the same issue and I believe I have correctly set up the sockets. Is there a test to see if it works, or can someone link to instructions to properly enable sockets on xampp?

**Comment by d8ahazard** [comment]
Hello all - is this still an issue for you?

**Comment by tboyce021** [comment]
I'm using your docker-plex image and getting this issue. It looks like `php-sockets` is already installed.

**Comment by tboyce021** [comment]
Well, I got rid of the undefined function errors by running

```
apk add php5-sockets
apk add php5-json
```

but now I'm just seeing 
```
 DEBUG ] device.php::fetchCastDevices - Returns: ["Error"]
```

**Comment by tboyce021** [comment]
It is showing another device now, simply called "E", but trying to switch to it quickly switches it back to my Nexus Player without anything in the logs.

**Comment by d8ahazard** [comment]
So, this is documented for as to how to get working with non-docker instances.  

For the docker image, I've updated it to fix sockets - this still doesn't get cast devices working.   

But, as it's a docker issue, and not so much Phlex, I'm going to close this issue, as I'm going to discuss with @ChrisRidings and see if we can come up with another way of resolving problems with docker.

**Comment by tboyce021** [comment]
Just FYI, it looks like Home Assistant has the same issue with chromecast+Docker. The only workarounds there I know of are to run the container with the "host" networking option or manually specify the IP address of the chromecasts so they can be used without actually discovering them first. For now, just updating the Docker image to use a port other than 80 or making it configurable would help, that way it can be run in "host" mode without conflicting with other services.

**Comment by d8ahazard** [comment]
I'm working on it now, almost got multicast going.  Or, specifically, I had
it going once by issuing commands manually, just trying to get it to work
OOB now.
