### ISSUE TITLE
Installation issue on Raspberry Pi

### ISSUE THREAD

**Issue by someCynic** [d8ahazard/Phlex#100]
After installing apache and PHP7, starting up Phlex, it initially seemed to load correctly, except for constant "Internal Server Errors (500)" when attempting to call the api for polling, preventing any updates on the page coming from the server.

At least in my case, it was related to `mb_strlen` being missing from PHP7's default install after following the instructions within the README.

The solution was to install the package separately:
`sudo apt-get install php7.0-mbstring`

Just thought it would be useful in case you want to add it to the installation steps for the RPI.

**Comment by d8ahazard** [comment]
Hey, thanks for the tip!  I've updated the readme to reflect the extra step with commit 6def4fd.
