### ISSUE TITLE
Feature Request: PlexKodiConnect support

### ISSUE THREAD

**Issue by nstern2** [d8ahazard/Phlex#101]
Phlex works great with casting or the native app on my nvidia shield, but I run plex via the plexkodiconnect add-on in kodi.  Plex via my phone shows plexkodiconnect as a viable player I can control, but phlex does not see it at all.

Thanks for creating such a wonderful app!

**Comment by d8ahazard** [comment]
FWIW, I have tried this a few times with PKC, but haven't had a lot of luck so far.  It's weird.  Everything says it should work, but it doesn't.  Maybe I'll take another crack at this tomorrow.

**Comment by tzortst** [comment]
+1 for this

**Comment by d8ahazard** [comment]
Fixed with #0beeafd74dbdb9b93f00f1adccff5de62ef2b5f3.
