### ISSUE TITLE
Feature Request: Emby Support

### ISSUE THREAD

**Issue by CaptInsano** [d8ahazard/Phlex#102]
I know this would be a lot of work, but any chance of Emby integration along with Plex as the media server?

Lots of previously Plex only apps are changing to include Emby. 
eg; PlexRequests --> Ombi

Would be great to see this great project work with Emby!

**Comment by d8ahazard** [comment]
As it is, I've actually got some methods in place to scrape *all* uPnP devices off the network, as I was using this to find cast devices before switching to the more problematic mDNS stuff.  But, that code is still there, so I could maybe re-enable it under an Emby setting, get Emby installed, and go from there.  What the heck.  Why shouldn't Phlex support *all* of the players?  :D

**Comment by PhyberApex** [comment]
Is there any progress made here?

**Comment by d8ahazard** [comment]
Will need to research this in conjunction with shifting the login mechanism to rely on plex.tv.

**Comment by mukowman** [comment]
+1
Used to be an Plex man but moved to Emby.
Would be happy to support for this, no pressure though.
May have to change the name to Flemby......
