### ISSUE TITLE
Not playing on tv

### ISSUE THREAD

**Issue by oxhey** [d8ahazard/Phlex#106]
Phlex is installed and running. It has been linked to my Google account.

I can ask it to tell me what's on deck and it responds correctly. 

However when I ask it to play something it says ok and nothing happens. 

On the phlex app it shows the TV show that I told it to play. I have also made sure that my webos TV is the selected cast device, both through the the phlex app and by asking home to select it as the device. 

Running in fresh xampp on windows 10. PMS also runs on this system.

**Comment by d8ahazard** [comment]
I'm going to need for you to try playback, and then send me full log files to my donate address.  

You can find it in the readme.  It's going to be an issue with your webos TV, I'll just need to add a filter for it in the log to figure out the right way to play back to it.
