### ISSUE TITLE
No authentication for Web interface

### ISSUE THREAD

**Issue by blackbarn** [d8ahazard/Phlex#11]
It would be nice to have authentication for the web management/config portion and allow Assistant to talk with the API key. So we prevent anyone hitting our public endpoint and fiddling with the settings.

Unless i missed something to allow this somewhere?

**Comment by d8ahazard** [comment]
That's how it works currently.  The web/config is tied to your Plex username.  The API key is what lets google/IFTTT talk to your client via the server.

**Comment by blackbarn** [comment]
Ah i see. I don't have another to test with. But since this plex login page is public, what occurs *if* some random person stumbles upon it and logs in? Does it support multiple plex accounts? Would it overwrite mine? etc. Granted logging into some unknown portal with their plex creds would normally be a deterrent :)

**Comment by d8ahazard** [comment]
If a random person stumbled across the portal for Phlex and logged in with their Plex account, a new section would be created for them in config, and a new api token generated for them.  They'd not have access to your devices or settings.

**Comment by blackbarn** [comment]
Thanks, appreciate the explanations.
