### ISSUE TITLE
Australian English

### ISSUE THREAD

**Issue by billyabong** [d8ahazard/Phlex#110]
Not as much an issue but a feature request.  Whenever I ask Google Home to talk to flex tv I get the error "Isn't available for devices setup with Australian English".  Happy to help as a beta tester if it'll speed it up.

**Comment by d8ahazard** [comment]
It's not me, it's Google.  Action developers don't currently have the
ability to support any language aside from US English.  Workaround ATM is
to switch the language in the ghome app.

**Comment by billyabong** [comment]
Shame!  I was wondering if that was the case.  Okay, thank you.

**Comment by njcarter92** [comment]
Really want this too!! American version doesn’t always understand the accent
