### ISSUE TITLE
Flex TV Assistant App missing

### ISSUE THREAD

**Issue by tyler43636** [d8ahazard/Phlex#111]
When I try to access the Flex TV google assistant app, I get the following error: ```Flex TV is no longer available```. I opened the assistant settings and scrolled all the way to the "fl" section and it was no where to be found. Did google pull the assistant app?

**Comment by Cyberchaos** [comment]
I'm trying to set up Phlex now for the first time, and I get this same response when I say "Hey Google, talk to Flex" in the setup process.  I'm so confused. I don't know if I missed up in setup somewhere or what's going on.

**Comment by d8ahazard** [comment]
Google pulled the action this morning, without warning.  I am working to
get it re-added to the store.  In the meanwhile, you can use IFTTT per the
readme.  Sorry about the issues.

**Comment by FSurani** [comment]
The IFTTT is no longer working for me. In the Phlex Web UI I'm getting:  {"error":"Invalid API Token Specified, please re-link your account through the Phlex Web UI."}

**Comment by thomaslittle** [comment]
:( any update on getting flex back into assistant? sucks that they randomly just pulled it without warning. you've put alot of hard work into this project and it's greatly appreciated!

**Comment by muyiwao221** [comment]
Haha damn, I bought a google assistant just for this application I really hope it makes it back.

**Comment by muyiwao221** [comment]
For IFTTT, is there no support for the Flex TV response to be played on the Assistant? It seems the only response google assistant can give is the one I tell it to when I create the applet.

**Comment by d8ahazard** [comment]
It's been re submitted, I hope to see it tested and available by Tuesday or
Wednesday of this week.

**Comment by RobertSmits** [comment]
It's back

**Comment by Cyberchaos** [comment]
It's back, but now I'm having "I'll work on that for you" issues despite functionality working and the correct JSON strings being served. It might be unrelated to this though. I've mailed you d8ahazard, I hope that's okay.

**Comment by tyler43636** [comment]
Its back and working for me.
