### ISSUE TITLE
Movies with hyphens not downloading

### ISSUE THREAD

**Issue by muyiwao221** [d8ahazard/Phlex#112]
Movies with hyphens (at least while using IFTTT) makes Phlex try to download each side of the hyphen seperately. For example, "Download Spider-Man 2" breaks down into "Spider" and "Man 2" when downloading. In both cases it obviously does not find a result and returns nothing. Just a heads up.

Thanks

**Comment by muyiwao221** [comment]
On what OS are you running Phlex?
Ubuntu Server 16.04
Are you using a new instance of XAMPP, or an existing webserver?
Apache2 Webserver
If Using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
Yes
If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
Same OS. 16.04
Is Phlex using http or https?
https
If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files. Paste anything that looks related as well.

Interestingly enough it works just fine when I type "Download Spider-Man 2" into the web UI. But saying it over google home breaks it up into Spider and Man 2. Weird.

**Comment by d8ahazard** [comment]
That is weird.  I just tested via the UI and Ghome, and had nothing like that occur.  Do you still have logs for this?  If so, shoot them to the donate address listed in the readme.  :D

**Comment by d8ahazard** [comment]
@muyiwao221 - Sorry, forgot to tag you so you get a notification.

**Comment by muyiwao221** [comment]
Hey yeah. Sorry just saw this - I am unable to replicate it now. Additionally the logs for this are so far back (I've been doing a lot of testing) that I cant seem to find them haha. You can go ahead and close this one out. I just tried 3 different movies with hyphens in them each 3 times and it worked every time. Might have just been a bug that happened the first few times I put it through IFTTT. Thanks again.

**Comment by muyiwao221** [comment]
Actually maybe the update you just pushed fixed it - regardless thanks for the hard work, this thing is cool.
