### ISSUE TITLE
Australian English/ ifttt ??

### ISSUE THREAD

**Issue by njcarter92** [d8ahazard/Phlex#116]
Feature request....any chance to get Australian English implemented??? the American assistant doesn't recognise my accent very well... pause = paws

Also when asking phlox to play a movie I do not have via 'IFTTT' it will just run the command without results...eg it will not ask to download the movie...it will just do nothing.

**Comment by d8ahazard** [comment]
Aussie support is on Google, not me.  :(  

The fix is to switch to US English for now.  

Using IFTTT, I don't have the ability to send custom speech, so it can only ever repeat back the command you sent.  Again, out of my hands, which is why I wrote an Assistant feature.  Sorry!
