### ISSUE TITLE
Try casting TTS to A Targeted Assistant Device

### ISSUE THREAD

**Issue by muyiwao221** [d8ahazard/Phlex#118]
Hey, first of all love the work you do. This is dope, I love it more and more every day. A feature request I think would be cool is to be able to have the option to push the response from Phlex to a chromecast (or even just audio to a chromecast audio) - but only if there is an error or a follow up question. I say this because since we really cant get a response using IFTTT - there are a couple cases where I'd like to know what's going on behind the scenes without necessarily whipping out my phone or computer to check the web ui (WHICH IS DOPE AF BTW). Not sure if its possible but just a suggestion. Interacting with Phlex is so much easier (and quicker) through IFTTT so for most things I want to stick with it - however not being able to hear the response can sometimes make it tricky. Let me know what you think, and keep up the good work!

**Comment by d8ahazard** [comment]
Framework for broadcasting to *all* chromecasts is already implemented in the new Cast plugin...researching if we can target the "requesting" Ghome to implement this properly.
