### ISSUE TITLE
Flex tv isn't responding yet it still works

### ISSUE THREAD

**Issue by phairplay** [d8ahazard/Phlex#121]
Hi when I issue a command for a tv show flex response saying 

Flex tv isn't responding right now. Try again soon

Yet it still works and the logs show the response I would of expected 

You said: "Start Elementary"
My reply: "You got it, Playing Dead Man's Tale."

Asking to play a movie gives me the correct response 

How do I resolve this?

**Comment by phairplay** [comment]
Hi sorry to be a pest 
Have I done something wrong to get this issue or is it fixable?

**Comment by phairplay** [comment]
[phlex log.txt](https://github.com/d8ahazard/Phlex/files/1212859/phlex.log.txt)
hi as requested on plex forum ive uploaded a log which shows me requesting elementary

i get "flex tv isn't responding" yet it fires up the ep within a few seconds  

i've put *removed* in replace of my personal data

**Comment by jfjallid** [comment]
I have the same or a similar problem on my Google Home.
When I ask to play a tv show I get the response: "Flex TV isn't responding right now. Try again soon." but it starts playing the episode. When I ask Flex TV to stop the playback I get the reponse "Consider it done." and the episode is stopped.

**Comment by damijares** [comment]
Hi There, 

I have a similar issue, basically works on ifttt and trough the console but Google Home trigger the action and replies "Flex isn't responding right now". 

Updating to the last build,  re-registering server, unlink and link it back on Google assistant app. 

Still nothing. 😕

Any help will be appreciated it. 

Let me know if I can offer any further information. 

Thanks for your help in advance.

**Comment by d8ahazard** [comment]
@phairplay - Is this still a problem for you?  I've adjusted the timeouts and set canned responses so you should get *something* said back to you...

@damijares - Same question...I see in the logs that you've had a few successful commands, at least from my perspective.  Is it always timing out?

I've dialed back the "timeout" on the server by another second, give a try and let me know if the issue persists.

**Comment by damijares** [comment]
@d8ahazard, last commit pull and everything working fine*. 

It did always time out(on the assistant side), but the commands will execute.

*have you change/added some commands? i.e. "what's on deck" doesn't work but "What's new" works.

Thanks for the reply and as always awesome work.

**Comment by phairplay** [comment]
Hi I'm still getting flex tv isn't responding but it plays the tv show

**Comment by phairplay** [comment]
Also it keeps telling my password is incorrect when I try to log in but I know it's not

**Comment by phairplay** [comment]
hi im still getting the same error  message when requesting a tv show im using the latest. build

**Comment by damijares** [comment]
@d8ahazard it works for a bit now is back
![screenshot_20171004-154436](https://user-images.githubusercontent.com/29271941/31160336-657b4ebe-a91b-11e7-8345-5c5ac86e0054.jpg)

**Comment by FrostyWolf** [comment]
Same issue.  On Deck, Stop, Fetch all work without issue.  Asking Flex to play anything throws me a "Isn't responding right now" error.

It seems to not have a issue sending the command, but when it is supposed to tell google home to say "Sure, playing _____" it either errors or times out.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
