### ISSUE TITLE
Util.php file - Syntax error

### ISSUE THREAD

**Issue by kevinb77** [d8ahazard/Phlex#123]
Parse error: syntax error, unexpected '?' in C:\xampp\htdocs\Phlex\util.php on line 14

Not sure what I am doing wrong, but I keep on getting this error...

**Comment by Martyfree123** [comment]
I get the same thing on Line 17...

**Comment by d8ahazard** [comment]
You need php *7*

**Comment by Martyfree123** [comment]
Ok, so I was running php 5 by mistake. I upgraded and installed php 7 but I still get the same error...

**Comment by Martyfree123** [comment]
Ok, I fixed it by just using MAMP instead of XAMPP
