### ISSUE TITLE
Australian English

### ISSUE THREAD

**Issue by CapnSammeh** [d8ahazard/Phlex#126]
I've found that devices set up for "Australian English" prompt an error when attempting to communicate with Flex TV;

"Flex TV isn't available on devices set up in Australian English. Sorry about that". 

Minus some linguistics/slang, Australian English and American English are quite similar, and while I'm happy to use my Google Home in American English, the Australian English handles some more heavily accented individuals in my household much better. 

Just wondering if this is something is resolvable by the Phlex dev?

**Comment by anthrox** [comment]
I have this same problem

**Comment by d8ahazard** [comment]
Known issue... Language support is 100% up to Google.

**Comment by aashley** [comment]
Google have enabled actions for Australian English and the Phlex integration works
