### ISSUE TITLE
German translation 

### ISSUE THREAD

**Issue by ZerNico** [d8ahazard/Phlex#127]
I'd like to help translating Phlex to German.

**Comment by celevra** [comment]
what is exactly todo to translate it?

**Comment by celevra** [comment]
ok, 3rd Party Plugins are limited to us english accounts that means if you want to use it in german you have to use ifttt and than you can setup the phrases yourself

**Comment by d8ahazard** [comment]
Hey!  FWIW - there *is* a language feature half-baked into the Phlex side of things as well.  

Basically, you'd just need to go into the /lang folder of Phlex, make a copy of en.php, and then start banging out translations.  Some of the responses need to be finished yet, but I believe a lot of the work is already done.

For those who are *really* intrepid, you can see in api.php where I've taken *most* of the strings and moved them to reference the lang file via $lang['stringName'] - for other translations, some of these need to be pulled out and finished yet.

THEN, whenever DE support is added by Google for assistant, I have a copy of the API.ai agent set up that will need to be translated - this is a major undertaking.

But, volunteers are welcome!!

**Comment by kaiomatico** [comment]
Hey, google home in Germany now supports "Actions", so third party apps. I tried to activate Phlex with the phrase "Rede mit Flex TV" (talk to flex tv) but it says it doesn't understand. I can help translate if help is needed :)

**Comment by d8ahazard** [comment]
Hello there!

Phlex doesn't fully work in German yet - but I'm working on it with the
help of Nico.  If you'd like to be added to the test for German, just send
me an email at donate.to.digtialhigh@gmail.com, and I can get you added to
the beta.

Once added, it still may not be 100% functional as I work out the bugs that
come with translating an application that also uses "speech" as it's input
medium...but phrases like "Mit Flex TV sprechen" and "Frage Flex TV nach
spielen batman begins" will work.  :D

**Comment by kaiomatico** [comment]
Thanks a lot for your quick response. In the meantime I got pychromecast and a python script working for my needs to play local files, so I'm not in a hurry anymore. But as soon as Phlex is released as final release for German users I will be happy to try it out. Thanks for your effort.

**Comment by d8ahazard** [comment]
Had it added to the agent, started trying to deploy to google...got distracted, wound up breaking everything down in order to fix issues, will have to re-build the agent, re-translate, and actually get it approved by Google this time.

Flagged for V2.

**Comment by ndom91** [comment]
If you need an extra hand with german translation i can help as well.

**Comment by shapetheLOLa** [comment]
Id like to help aswell. Just got my google home and was hoping plex already works ootb. If you need a help let me know!

**Comment by shapetheLOLa** [comment]
Any news here?
