### ISSUE TITLE
Asking phlex to download/fetch a movie by voice does not work anymore

### ISSUE THREAD

**Issue by XmemphistoX** [d8ahazard/Phlex#13]
Unable to find anything when using voice.  However if I use the Phlex webpage to request a download it does.

By Voice
01:58:43 AM - 03/30/2017
Initial command: "ask Flex TV to fetch the movie get out"
Parsed command: "Fetch the media named ."
Search status:  Nothing found to fetch.

Speech Response:  Unfortunately, I was not able to find anything with that title to download.
{JSON}

By Phlex webgui
Initial command: "get out"
Parsed command: "Fetch the first movie or show named get out"
Search status: success

**Comment by d8ahazard** [comment]
This should be fixed.  Verified the command "Ask Flex TV to fetch the movie get out" works to fetch "Get Out (2017)" on Couchpotato and Radarr.
