### ISSUE TITLE
Error 22, the requested URL returned error

### ISSUE THREAD

**Issue by jfjallid** [d8ahazard/Phlex#134]
Earlier today Phlex worked fine but all of a sudden I get the following response from my Google Home Flex TV: "Error 22, the requested URL returned error. 500 internal server error".

I also noticed that I can no longer access the Web Gui of Phlex, I'm only greeted by a login screen I can not get past. It will notify me if I try to use incorrect credentials, but when I input the correct credentials and press "DO IT!", it will just display a message "One moment..." and then hang indefinitely.

**Comment by asdub** [comment]
+1 Having the exact same issue.

**Comment by jfjallid** [comment]
I see that Phlex received an update earlier today and now when I tested it the problem is gone. However, the update replaced my customized ip addresses for plexServerUri and plexServerPublicUri resultning in the "media unavailable" problem.

**Comment by tyler43636** [comment]
+1 Same error every time.

**Comment by tyler43636** [comment]
Ok, looks like playback is working. It's downloading that's generating errors for me. 

```
28-Sep-2017 22:37:52 America/Detroit] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /config/www/Phlex/api.php:4113
Stack trace:
#0 /config/www/Phlex/api.php(4003): radarrDownload('martian', Array)
#1 /config/www/Phlex/api.php(577): downloadMovie('martian', Array)
#2 /config/www/Phlex/api.php(1657): parseFetchCommand('martian', 'movie')
#3 /config/www/Phlex/api.php(253): parseApiCommand(Array)
#4 /config/www/Phlex/api.php(27): initialize()
#5 {main}
  thrown in /config/www/Phlex/api.php on line 4113
```

**Comment by jfjallid** [comment]
@d8ahazard 
No recent errors for me in the log file but there are some uncaught errors about "Call to undefined function locale_get_default()" from 27-Aug-2017.

**Comment by CaptInsano** [comment]
Just to report, I am getting this same error anytime I add a download through Phlex:

As above, the only error I can fish out of the logs is the following:

```
[04-Oct-2017 16:57:35 Europe/London] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /config/www/Phlex/api.php:4116
Stack trace:
#0 /config/www/Phlex/api.php(4006): radarrDownload('big buck bunny', Array)
#1 /config/www/Phlex/api.php(583): downloadMovie('big buck bunny', Array)
#2 /config/www/Phlex/api.php(1663): parseFetchCommand('big buck bunny', 'movie')
#3 /config/www/Phlex/api.php(259): parseApiCommand(Array)
#4 /config/www/Phlex/api.php(33): initialize()
#5 {main}
  thrown in /config/www/Phlex/api.php on line 4116
```

Would appreciate any advice because when I'm trying to show off Phlex to friends and family through my Google Home it makes me look pretty stupid when it reports "Error 22 ...."!!

**Comment by naaronne** [comment]
+1 same here

**Comment by naaronne** [comment]
I think my error is related to the issue that every time Phlex updates, it clears my sonarr and radarr API keys...
