### ISSUE TITLE
Feature Request: IFTT- Different URL for different players

### ISSUE THREAD

**Issue by Mdleal** [d8ahazard/Phlex#14]
I would like a way to send a web request to individual players and not have to switch player.  I was thinking a url for each player.

**Comment by Mdleal** [comment]
So I was thinking when you click the button under "Click to copy IFTTT URL" it give you a list of players and when you click the player that copies the url for that player.

**Comment by d8ahazard** [comment]
This can be closed.  The current iteration of Phlex now supports the "say" command via IFTTT, which will parse anything you say with API.ai, just like if you were using an OK google command.  It just won't read back a custom reply.  But, you can say "play batman begins on living room tv", and if "living room tv" is the name of your cast device or player, it should play to that device.  I'll try to update the documentation for the new api.ai command later.
