### ISSUE TITLE
Chromecasts aren't getting discovered

### ISSUE THREAD

**Issue by jasongi** [d8ahazard/Phlex#141]
On what OS are you running Phlex?
**FreeBSD (FreeNAS 9.3)**
Are you using a new instance of XAMPP, or an existing webserver?
**Not using XAMMP, but I am using PHP 7.0 + Apache 2.4**
If Using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
**PHP is reading and writing fine, I can link up to google account and couchpotato/sonnar - it's just that it doesn't discover any chromecasts**
If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
**N/A**
Is Phlex using http or https?
**http**
If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files. Paste anything that looks related as well.
**Phlex logs don't have any errors, under the cast bits it just is always returning an empty array, even though there are Chromecasts on the same subnet and the MDNS packets are being sent and the Chromecast responses are being sent (I can sniff them from another computer)**
```
Sat, 23 Sep 2017 17:41:29 +0000util.php::fetchCastDevices
Returns: []
Sat, 23 Sep 2017 17:41:24 +0000Chromecast.php::scansub
Function fired.
Sat, 23 Sep 2017 17:41:24 +0000Chromecast.php::scan
Function fired.
Sat, 23 Sep 2017 17:41:24 +0000util.php::fetchCastDevices
Function fired.
```

I'm going to try and debug this some more today, just posting this issue to see if any other FreeNAS/FreeBSD users have come across it.

**Comment by jasongi** [comment]
Update: looking at the tcpdump, I'm definitely getting the responses from the devices, but readIncoming call is returning nothing.

**Comment by jasongi** [comment]
updated 2: I have worked around this by putting my chromecast on a static IP and hard coding it into the fetchCastDevices, this was the code:
```
    function fetchCastDevices() {
        $returns = false;
        if (!(isset($_GET['pollPlayer']))) write_log("Function fired.");
        $castOne = [
                'friendlyname' => 'Lounge',
                'ip' => '10.1.1.48',
                'port' => '8009',
        ];
        if (!$result) $result = array();
        $result['Chromecast-Ultra-0253e523bcd2a67f55c0385e6435a33a._googlecast._tcp.local'] = $castOne;
```

Obviously you'd have to change the key/ip/port/friendlyname to your devices
It's now working pretty well, although the API is running quite slow which means although it loads the show when you ask it to play, the google assistant doesn't speak the response as it times out.

**Comment by d8ahazard** [comment]
Heeeeeeey!  

This is a weird one, and I've seen this on FreeBSD in the past.  

I just pushed out an update that adds a teeny little bit of logging to mdns.php/__construct() that will spit out the detected OS version.  Possible it's not seeing you're on FreeBSD and so it's not binding the socket correctly.

Obv, you'll have to undo your static addition, but hopefully, it'll get us to the bottom of it.

Also, just modified the check for the OS name to make sure it's not tripping on something stupid like case or spacing.  ;)

**Comment by jasongi** [comment]
Hey mate 

I did think that might be the case so I already chucked a log statement in there to see if it was reading the inside of that if (PHP_OS === "Darwin" || PHP_OS === "FreeBSD")
statement and it definitely is :(

**Comment by d8ahazard** [comment]
@jasongi Well then, let's try it the *other* way round once.  Just change the check for "FreeBSD" to "foo" once, the do a rescan, see if any change.  Maybe what's good for one FreeBSD box is not good for all freeBSD boxes?

**Comment by jasongi** [comment]
logs with unaltered code:
```
Fri, 29 Sep 2017 13:40:35 +0000util.php::fetchCastDevices
Returns: []
Fri, 29 Sep 2017 13:40:30 +0000mdns.php::__construct
PHP is detecting the OS as FreeBSD
Fri, 29 Sep 2017 13:40:30 +0000Chromecast.php::scansub
Function fired.
Fri, 29 Sep 2017 13:40:30 +0000Chromecast.php::scan
Function fired.
Fri, 29 Sep 2017 13:40:30 +0000util.php::fetchCastDevices
Function fired.
```

logs with the === FreeBSD part removed
```
[Fri, 29 Sep 2017 13:45:05 +0000] [DEBUG] [util.php::fetchCastDevices] - Function fired.
[Fri, 29 Sep 2017 13:45:05 +0000] [DEBUG] [Chromecast.php::scan] - Function fired.
[Fri, 29 Sep 2017 13:45:05 +0000] [DEBUG] [Chromecast.php::scansub] - Function fired.
[Fri, 29 Sep 2017 13:45:05 +0000] [DEBUG] [mdns.php::__construct] - PHP is detecting the OS as FreeBSD
[Fri, 29 Sep 2017 13:45:10 +0000] [DEBUG] [util.php::fetchCastDevices] - Returns: []
```

I'm wondering if there is anything stopping this running inside a freeBSD jail. I have security.jail.allow_raw_sockets enabled even though I'm pretty sure it isn't needed.

**Comment by slinskiy** [comment]
jasongi what exact file did you hardcode your chromecast into please.

**Comment by jasongi** [comment]
@slinskiy the function fetchCastDevices is in util.php

**Comment by slinskiy** [comment]
@jasongi Thank you!

**Comment by guanghuang** [comment]
@jasongi  How did you get the chromecast key (e.g. Chromecast-Ultra-0253e523bcd2a67f55c0385e6435a33a._googlecast._tcp.local') Thanks,

**Comment by guanghuang** [comment]
@jasongi Just got it via tcpdump. Thanks

**Comment by scotthorn** [comment]
I'm having the same issue described here, plex and google linking seem to work fine, but no chromecasts discovered. I'm using xampp on Windows 7.

@jasongi Thanks for the temporary fix. Where did you get the key for your chromecast? I've only seen the mac address for mine. i.e. 'Chromecast-Ultra-0253e523bcd2a67f55c0385e6435a33a._googlecast._tcp.local'

**Comment by scotthorn** [comment]
Following @jasongi's example of the returning data structure, I changed the line `array_push($returns, $deviceOut);` to `$returns[$key] = $deviceOut;`, which is working on my setup (Windows 7, xampp, git zip).

Just to note, values returned by `Chromecast:scan()` are inconsistent. It always sees my one chromecast (video), but at times all four of the items on my network (1 chromecast, 2 home minis, 1 group of the minis) that are seen by my phone apps when casting have appeared, either together or just one. Most of the time, it's only the chromecast found, which works for my needs of casting video. Just noting the inconsistency.

**Comment by jasongi** [comment]
Hey mate

If you're on windows you could always use winpcap to get the chrome cast
info from the mdns packet it sends out.

Jason

On 26 Dec 2017 23:53, "Scott Horn" <notifications@github.com> wrote:

I'm having the same issue described here, plex and google linking seem to
work fine, but no chromecasts discovered. I'm using xampp on Windows 7.

@jasongi <https://github.com/jasongi> Thanks for the temporary fix. Where
did you get the key for your chromecast? I've only seen the mac address for
mine. i.e. 'Chromecast-Ultra-0253e523bcd2a67f55c0385e6435a3
3a._googlecast._tcp.local'

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/d8ahazard/Phlex/issues/141#issuecomment-353982771>, or mute
the thread

**Comment by Jon87** [comment]
Did you get to the bottom of the issue without having to hardcode the chromecasts. I'm on Freenas too and would ideally like to avoid this. Cheers!

**Comment by wcomartin** [comment]
was this resolved? it was not ideal having to add chromecasts as devices manually

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
