### ISSUE TITLE
Cast to Android TV not working.

### ISSUE THREAD

**Issue by cjackson234** [d8ahazard/Phlex#142]
Everything for Phlex seems to be working except media playback.

Logs indicate playback was a success. However, the loading animation spins and then it says "Unable to cast. This media is currently unavailable."

Account link: Google assistant
Install type: Unraid Docker
Playback Device: Nvidia Shield (Android TV)

**Comment by d8ahazard** [comment]
Try enabling "No Plex.Direct" in Settings > Plex.

**Comment by cjackson234** [comment]
Unfortunately, it's giving me the same result.

**Comment by groan** [comment]
I'm experiencing the same issue. Tried the No Plex Direct setting.

> {
>   "serverURI": "https://192-168-1-12.ffef4e2a8571431e9ab4234e0f4b5cb6.plex.direct:32400",
>   "serverToken": "ddayzHj8LH5P4Nzw4WC6",
>   "clientURI": "http://192.168.1.12:32500",
>   "clientName": "SHIELD Android TV",
>   "initialCommand": "to play Brooklyn Nine-Nine",
>   "timestamp": "Fri, 20 Oct 2017 00:32:53 +0200",
>   "commandType": "play",
>   "parsedCommand": "Play a media item with the title of 'brooklyn ninenine.'",
>   "mediaStatus": "ERROR: No results found, prompting to download.",
>   "speech": "I didn't find anything named ' brooklyn ninenine' to play. Should I try to fetch it for you?'",
>   "timecode": 1508452373
> }

**Comment by jonfairbanks** [comment]
I am seeing a combo of this and #77. From Flex UI JSON it seems like it was successful, but nothing plays on the Nvidia Shield.

**Comment by groan** [comment]
My json above is just one iteration of what i'm seeing.
the voice prompt says it's sending the show to phlex but nothing shows up on the tv. I didn't see a step to register my server, nor did it re-prompt me to connect my account after I told GHome to talk to phlex, so I'm not sure if my steps completed.

**Comment by cjackson234** [comment]
@d8ahazard It's working great now. Nice work!
