### ISSUE TITLE
Chromecast Audio

### ISSUE THREAD

**Issue by kevinmclane** [d8ahazard/Phlex#146]
Is anyone having issues with audio devices?  Everything works on casting a song to a video capable device such as Chromecast and my Pixel phone.  If I change player to an audio only device such as Chomecast Audio or Google Home it confirms the player command.  I can verify in the web gui.  I then ask to play a song, it confirms the command then nothing happens.  A follow up question of "what is playing" returns "nothing is playing".

Phlex through xampp and plex are on the same win10 machine

**Comment by Praenei** [comment]
Hi Kevin, you are more successful than me.  Just got Phlex to work for movies on xampp/plex but music is just hanging on a video capable Chromecast - I get the Plex symbol appearing with a revolving loading icon & nothing else.  I can select my audio Chromecast in Phlex but after a few seconds it reverts back to my video one.  Not much help but I thought you might like to know that you are not alone.

Loving the app though.

**Comment by d8ahazard** [comment]
Closed, since you can now assign static devices, and because music casting has been updated.
