### ISSUE TITLE
Settings Web UI Not Completely Loading 

### ISSUE THREAD

**Issue by RobotRamone** [d8ahazard/Phlex#148]
This is a minor issue, but when I load my Phlex server the Settings Web UI menus are incomplete.
It's as though the page never fully loaded.  For example, under Settings>Phlex the menu is cut off after Webhooks.  I can see some of the selections ie Public Address and Device Rescan, the radio buttons work, but I'm not sure if they are associated with the correct menu header.  Not sure why the page is broken on my end. 

Any help would be greatly appreciated.

**Comment by Crippin901** [comment]
I too am having this same issue. Everything is appearing but as if some UI elements are overlapping each other. Running on windows 10

**Comment by d8ahazard** [comment]
What browser are you guys using?

**Comment by RobotRamone** [comment]
Chrome.

The phlex UI is working properly now for me.  But I’m still getting an error regarding my port forwarding.

The Apache server keeps scanning and changing the port number.  I was reading about it right now.  Someone said it’s a DB issue with MySQL.  But I don’t need MySQL for this, correct?

 

Any help would be awesome.

 

Mark

**Comment by RobotRamone** [comment]
Maybe an Apache binding issue?

 

What should my server settings be?  My port is 8012.  But the XAMPP ports are rotating --- won’t stay bound to 8012.

 

# If your host doesn't have a registered DNS name, enter its IP address here.

#

ServerName http://192.168.1.132:8012/phlex

 

Or 

 

ServerName localhost:8012

 

Or

ServerName localhost:8012/phlex

**Comment by d8ahazard** [comment]
![image](https://user-images.githubusercontent.com/1633844/31779712-635d82c4-b4b9-11e7-9a5e-699b243d1b38.png)

Port settings for Xampp are here.  Why they're "rotating" is beyond me, but my suspicion would be that something else is bound to port 80 on your server?  

I'd maybe try setting the main port to 5666 in Xampp config, see if that helps.

**Comment by RobotRamone** [comment]
Sabnzb is bound to 80.  It’s why I switched the Apache to 8012.  I do in fact have it set up that way in the actual Xampp config file too.  

I’ll keep tinkering.

 

The only thing wonky with my Phlex install is I no longer see that radio button to check for public IP.

 

Unable to connect to Client at http://xx.xx.xx.xx/Phlex, please check the setting for 'Public Address' in the Phlex UI.

**Comment by mrzoops** [comment]
Having the same issue with incomplete or jumbled UI in settings. Tried in Chrome and also on Edge. 
![capture](https://user-images.githubusercontent.com/8879242/31793667-d948f016-b4ed-11e7-942d-f9b458c6d587.PNG)
