### ISSUE TITLE
Can't get Phlex to play via Google Assistant.

### ISSUE THREAD

**Issue by DKOliver** [d8ahazard/Phlex#152]
If i use Phlex TV through the browser i can use commands just fine, and it plays on my chromecast.

On my Phone if i say "ok google talk to flex tv"

the app comes up, says the greeting message then immediately leaves the conversation

if i then say "ok google ask flex tv to play Arrested Development" it says:

"Okay. Here's Flex TV"

"Okay i'll try to play Arrested Development for you"

And then nothing happens. If i do the same thing in the browser it works just fine. 

And in the log nothing happens. 

Phlex is running on Windows 10
Newest version of XAMPP
And the proper modules are enabled
Plex is using HTTP

**Comment by jacko1980** [comment]
I am also having this problem except when I type the command in the browser it responds correctly but no media plays.

**Comment by scfigg** [comment]
Same here. I can ask it to play a movie, and it will, but it can't stop or do other functions.

**Comment by Peggle2K** [comment]
Same issue here. I think it's because ive deployed phlex so many times and tried to link it on a number of machines its just screwed the backend up. I'm guessing when you tell the home to talk to flex tv the initial message is the master server talking, then it routes you to your on phlex instance.

**Comment by Peggle2K** [comment]
It isn't much but I'll offer a $5 bounty to fix this. I've emailed details to donation email.

**Comment by Peggle2K** [comment]
Adding to this, when I type through the browser and ask it to play a movie it trys, but Plex on the chromecast just has the 'Spinny wheel'

**Comment by Peggle2K** [comment]
Two distinct errors here:

`401 Unauthorized` response: 415 416 417 Invalid authentication token -- The API token Phlex is trying to use is being rejected by Plex

This is my google home passing the wrong API key for Phlex and Phlex rejecting the connection:
Unauthenticated access detected

I have unlinked and relinked both so many times, but it isn't making a difference.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
