### ISSUE TITLE
Play next episode of

### ISSUE THREAD

**Issue by renefloor** [d8ahazard/Phlex#153]
Hi, 
First of all I want to say Phlex is awesome.
I have a feature request (or maybe just need some explanation on how to do it).
I can play the first and the last episode of a tv show and I can ask what's on deck if I recently viewed this series. How can I play the next episode what's on deck of that show? I would like to say "play the next episode of (...)" to play the first episode after the one I watched last.

**Comment by d8ahazard** [comment]
Ask it to play that show.

The default behavior for TV episodes is to find the next on-deck item of that show if it exists, otherwise, I think it defaults to the first unwatched episode, or just the first available episode.  There's a lot going on in this app.  :D
