### ISSUE TITLE
Question about unlinking and relinking

### ISSUE THREAD

**Issue by ekollee** [d8ahazard/Phlex#154]
Hey, I originally set up phlex on a remote server and linked it through google home. I removed that server and setup on my new server and now I can't figure out how to re-link google home. Every time I ask to play something Flex TV can't find it. I can manually play things through the web interface by typing "Play Batman Begins" and it works. Just not working through the Home. 

Do you know how to re-link the Home to the new server?

**Comment by ekollee** [comment]
Nevermind, seemed to figure itself out

**Comment by d8ahazard** [comment]
Glad you got it sorted!
