### ISSUE TITLE
Long pause for login into new Raspberry Pi 3 setup.

### ISSUE THREAD

**Issue by dejones1971** [d8ahazard/Phlex#156]
Dear d8ahazard,

Firstly thanks for all the building on this code project. I have follow your ReadMe doc on setting up Phlex on Raspberry Pi. I follow the directions to the letter. I'm getting the log in screen with request for username and password (Plex Server). However once entered this request, I get the message "One Moment" then nothing more. Below is a copy of the error log feedback.

Can you please help me?

Thanks,

Daniel

[15-Oct-2017 20:17:14 UTC] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/Phlex/util.p$
Stack trace:
#0 /var/www/html/Phlex/api.php(4522): signIn('ZGFuaWVsLmUuam9...')
#1 /var/www/html/Phlex/api.php(22): checkSignIn()
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 672
[15-Oct-2017 20:17:17 UTC] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/Phlex/util.p$
Stack trace:
#0 /var/www/html/Phlex/api.php(4522): signIn('ZGFuaWVsLmUuam9...')
#1 /var/www/html/Phlex/api.php(22): checkSignIn()
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 672
[15-Oct-2017 20:17:18 UTC] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/Phlex/util.p$
Stack trace:
#0 /var/www/html/Phlex/api.php(4522): signIn('ZGFuaWVsLmUuam9...')
#1 /var/www/html/Phlex/api.php(22): checkSignIn()
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 672
[15-Oct-2017 20:32:43 UTC] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/Phlex/util.p$
Stack trace:
#0 /var/www/html/Phlex/api.php(4522): signIn('ZGFuaWVsLmUuam9...')
#1 /var/www/html/Phlex/api.php(22): checkSignIn()
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 672

**Comment by d8ahazard** [comment]
You're missing the XML extension.

Did you follow this step?

![image](https://user-images.githubusercontent.com/1633844/31772941-bedf54e6-b4a6-11e7-9562-b70c50e780fe.png)

**Comment by dejones1971** [comment]
Yes I completed that step:

**Comment by dejones1971** [comment]
Hi d8ahazard,

I've discovered I was using the Jessie version of Raspbian. By switching to Stretch the issue/problem has been corrected.

**Comment by dejones1971** [comment]
Thanks!
