### ISSUE TITLE
sorry where do I enable sockets in php.ini file

### ISSUE THREAD

**Issue by dynamicskies** [d8ahazard/Phlex#157]
> **"If you are experiencing issues with cast devices not showing up in Phlex, you should first verify that the php sockets module is installed and enabled. If you used XAMPP, it should be included, you just need to edit your php.ini file to enable it."**

Im not sure what part of the file do I go to to enable it. 
I also have some other things going on maybe.

Right now I can't see any of my chrome casts  and i cant log into google but amazon login works. i was able to log into plex. 
 My port 80 is being used so i changes it to 1088
was only told in instructions to change Listen 80 so it looks like this now in httpd.conf
#Listen 12.34.56.78:80
Listen 1088
should i have change all the 80s to 1088 in that file

**Comment by d8ahazard** [comment]
https://stackoverflow.com/questions/1361925/how-to-enable-socket-in-php

Might be called .so instead of .dll if you're running on Linux.

**Comment by dynamicskies** [comment]
OMG thanks so much everything works now i just / still cant lnk google. just says 

phlexserver.cookiehigh.us took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

**Comment by d8ahazard** [comment]
Server was having issues last night, this has been resolved.
