### ISSUE TITLE
Can't Link Acct, https://phlexserver.cookiehigh.us Connection times out

### ISSUE THREAD

**Issue by MDamon** [d8ahazard/Phlex#158]
Upon clicking 'Link Google' or 'Link Amazon' my browser attempts to browse to https://phlexserver.cookiehigh.us with an api key and server address but the connection times out.  I can't load the top level page either.  Any issue with your server currently causing an issue perhaps or is it my ISP?

**Comment by bcb2000** [comment]
I'm getting the same problem
`# wget https://phlexserver.cookiehigh.us/
--2017-10-19 21:49:19--  https://phlexserver.cookiehigh.us/
Resolving phlexserver.cookiehigh.us (phlexserver.cookiehigh.us)... 192.99.197.11
Connecting to phlexserver.cookiehigh.us (phlexserver.cookiehigh.us)|192.99.197.11|:443... failed: Connection timed out.
Retrying.

--2017-10-19 21:51:27--  (try: 2)  https://phlexserver.cookiehigh.us/
Connecting to phlexserver.cookiehigh.us (phlexserver.cookiehigh.us)|192.99.197.11|:443...
`
... etc ...

**Comment by MDamon** [comment]
Also not getting a background image from plexchat.com or any interface window.  Just the header up top.  Curious if the code for hosting the rest of this project is available?  Looks like an awesome project just hoping to get it to work

**Comment by d8ahazard** [comment]
Fixed!

**Comment by MDamon** [comment]
Thank you!  I'm getting background images now and an error message through the link account button that it can't connect to my Phlex by public IP.. I just tested it through my mobile and it seems to be working though.  Any other suggestions?  Appreciate your time

**Comment by MDamon** [comment]
Seems to be working now, thank you again!
