### ISSUE TITLE
Cant Link to Google

### ISSUE THREAD

**Issue by TBrozovich** [d8ahazard/Phlex#159]
Hi I am having an issue linking to Google. When I click on link, it opens up a page that times out. It is https://phlexserver.cookiehigh.us/ and then my api token.

If I could get any direction on how to get this set up that would be awesome.

Thanks for your hard work!

**Comment by d8ahazard** [comment]
Server was having issues, should be resolved.

**Comment by chrismpcooke** [comment]
Hi, when I go to link google, I'm getting an error from https://phlexserver.cookiehigh.us saying Error, sql bullshit!  Any help greatly appreciated!

**Comment by mmnaseri** [comment]
Same here. I guess it's the same as Oct 18: server issues.
