### ISSUE TITLE
Resume jumps to a weird playback location

### ISSUE THREAD

**Issue by aziwoqpd** [d8ahazard/Phlex#163]
I'm about 30 minutes into the movie, and stop everything to leave.
When I come back and ask phlex to "Play zzz", it starts playing but immediately ends. The timeline, which appears for a few seconds, has a large number in it, like 300+ minutes.

I'm guessing it's seeking to an incorrect position? Rather than just resuming where I left off?
I'll try to get logs next time

**Comment by aziwoqpd** [comment]
Choosing media:
[Fri, 20 Oct 2017 04:23:09 +0200] [INFO] [api.php::fetchHubResults] - Final results: [{"ratingKey":"883","key":"\/library\/metadata\/883","type":"movie","title":"Sleeping Beauty","viewOffset":"2868249","lastViewedAt":"1508464653","year":"2017","thumb":"\/library\/metadata\/883\/thumb\/1508117642","art":"\/library\/metadata\/883\/art\/1508117642","duration":"4510165","originallyAvailableAt":"2017-10-15","addedAt":"1508117641","updatedAt":"1508117642","createdAtAccuracy":"epoch,local","createdAtTZOffset":"0","summary":"","exact":true,"searchType":""}]

**Comment by aziwoqpd** [comment]
Seems to be unit confusion.

For this log entry:
[Fri, 20 Oct 2017 07:14:28 +0200] [DEBUG] [api.php::fetchInfo] - We have a winner: {"ratingKey":"883","key":"\/library\/metadata\/883","type":"movie","title":"Sleeping Beauty","viewOffset":"166153","viewCount":"2","lastViewedAt":"1508476444","year":"2017","thumb":"\/library\/metadata\/883\/thumb\/1508117642","art":"\/library\/metadata\/883\/art\/1508117642","duration":"4510165","originallyAvailableAt":"2017-10-

I can see it's going for a viewOffset of 166153. I saw on the TV that Plex was trying to seek to 46:09:13, which is the number you get if viewOffset is in seconds.  I think it would be the correct number if it was treated as milliseconds, though.

**Comment by aziwoqpd** [comment]
so uh, not sure what the units are supposed to be, but dividing viewOffset by 1000 in api.php before sending it out to plex solved the problem for me

**Comment by skaggsb** [comment]
Ya, I was having this issue as well so I added the following line to the playMedia method just before the switch statement:

$media['viewOffset'] = $media['viewOffset'] / 1000;

Resuming playback works perfectly now.  I'm not sure if this is the best spot to do this fix, but it's the best place I could find after skimming the code.

**Comment by sundalic** [comment]
I'm seeing the same issue. Where do you make the edit above?

**Comment by skaggsb** [comment]
You add the line in the api.php file in the playMedia() method, just above the switch statement.

**Comment by sundalic** [comment]
thanks skaggsb, only just got around to looking at this again (the joys of having two 2 year olds at home) and that worked perfectly.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
