### ISSUE TITLE
Phlex has issues with IPv6-enabled devices

### ISSUE THREAD

**Issue by skalldri** [d8ahazard/Phlex#167]
I've been working on getting Phlex setup in my home system. I have a server running Plex and a media center running on an NVidia Shield TV.

Once everything was setup, I could never get Phlex to answer "what's playing", even when the Shield was selected. I've tracked this down to an issue with the IP address that is returned in the status call.

in api.php:castStatus(), after receiving the result from the server, castStatus() checks to see if this is a player or a cast type by checking if the IP address returned by the player is an exact match for the address in the 'hosts' attribute. 

The hosts attribute contains standard IPv4 addresses, but the server query is returning IP addresses in the format:

::ffff:(ipv4 address)

To test if this fixed it, I tried changing the test from an equality test to a contents test. This did work: Phlex immediately detected the playing content on my Shield, but the Plex app on Shield immediately got into a crash loop until I undid my changes.

I'll continue working on this, and put up a pull request once I've solved it. I'm filing this bug to keep tabs on the issue, and to let people know of a potential fix.

**Comment by jvreeken** [comment]
I'm having the same problem.  looking forward to a fix.

**Comment by jcott28** [comment]
I've got the Shield as well, having the ame problem.  Tonight I might see about disabling ipv6 on my router and see if I can get it to work.

**Comment by d8ahazard** [comment]
Noted for V2.

**Comment by d8ahazard** [comment]
So, I'm guessing there are probably still IPV6-related issues, but I don't have a great way of testing this currently. Anybody out there having issues?
