### ISSUE TITLE
Unable to Link Account now

### ISSUE THREAD

**Issue by XmemphistoX** [d8ahazard/Phlex#17]
Not sure what happened but I am trying to link my account again and it is saying this now.  The public address is accessible from outside my Lan.

Unable to connect to Client, please check the setting for 'Public Address'.

**Comment by rampage1999** [comment]
I am having that problem also.

**Comment by XmemphistoX** [comment]
Just wanted to mention that I can access it from outside my LAN.

**Comment by d8ahazard** [comment]
@XmemphistoX @rampage1999  - Can you guys try hitting the "unlink" option for Flex TV in the Ghome app, then try linking again - first from the Phlex app, then through ghome app?

**Comment by d8ahazard** [comment]
Going to close this - please create a new issue if problems persist.
