### ISSUE TITLE
Login window not loading

### ISSUE THREAD

**Issue by s3627014** [d8ahazard/Phlex#176]
Can't seem to get the login window to load at all.
 The logs are all empty and ip:80/Phlex just has the backdrop image and no login frame.

**Comment by d8ahazard** [comment]
Press F12 in a browser window - look at the Javascript console, tell me if
you're seeing any errors...

**Comment by s3627014** [comment]
No errors tagged as js came up, but something about failing to get a couple of css files did. 
![image](https://user-images.githubusercontent.com/25190380/32112384-dd9d6ca4-bb88-11e7-8d6e-f95bba08d8ef.png)

**Comment by teejo75** [comment]
I've just had this exact issue after resetting my install to a fresh state. The fix is to clear your cookies.

**Comment by d8ahazard** [comment]
Give it a go now.  I did some stupid things that were breaking config on new installs.  This should be fixed now.
