### ISSUE TITLE
Can't trigger Phlex from Assistant - French

### ISSUE THREAD

**Issue by tartinesKiller** [d8ahazard/Phlex#177]
Hello,

First of all, my Google Assistant language is set to French. When it is in English, when I say "Talk to Phlex TV", it starts Phlex. But in French, it says that it can't help me with that. 
I first thought that it was because third-party apps aren't supported yet in English, but - for example - Akinator (the web "genie") is available in French.
Is there anything to do to register Phlex as an available app?

Thanks in advance.

**Comment by d8ahazard** [comment]
It's not fully translated/released in French yet...wip.

**Comment by tartinesKiller** [comment]
OK, didn't know it wasn't released yet, sorry for useless issue! Thanks for your answer

**Comment by shyne99** [comment]
Hello, I know this is a closed issue, but , i really do love your project and what you are trying to bring here. I mean this is just amazing, what you did and what is still to be made !!! I am a junior developer and I really wanna help here, especially with the translation part (French is my mother tongue). 
If you need more help on this part to bring this to the french speeling people, I offer you my humble help.
