### ISSUE TITLE
No Players to Control in Drop Down

### ISSUE THREAD

**Issue by crhammock** [d8ahazard/Phlex#178]
On what OS are you running Phlex?
Windows 7

Are you using a new instance of XAMPP, or an existing webserver?
New instance of XAMPP

If Using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
I believe I have enabled all the modules by un commenting the below lines from the php.ini file
extension=php_sockets.dll
extension=php_curl.dll
extension=php_xmlrpc.dll

However, I am not clear how to confirm if the modules are installed, I believe it is assumed they are all present in the XAMPP instance

If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
N/A

Is Phlex using http or https?
http

In an effort to try and resolve the issue I have installed Phlex on both my NAS (QNAP running a version of linux) and my Windows 7 desktop.  The same setup and changes (such as those to the php.ini) have been made to both instances, however I figure it is easier to resolve on Windows 7 which is the platform detailed in this issue.  Both instances list the same available Players from the Select Player to Control Drop Down (That player being Plex Web Chrome).  All systems sit on a flat network with no firewalls between them.  The plex app on my Mobile shows 4 available devices one Plex Media Player, one Plex Home Theatre, One Plex for XBOX and the Plex Web (Chrome).

Plex Media Player and Plex Media Server are installed on the same machine (QNAP NAS)

Logs
[Phlex.log](https://github.com/d8ahazard/Phlex/files/1427957/Phlex.log)

**Comment by crhammock** [comment]
The more I try and troubleshoot this the more I feel that it maybe that the PMP and PMS are on the same server, as this would mean the same IP and same port.  Although non of my other device with a plex client have issues separating the two.  I also notice there are other issues currently open with people not being able to see PMP instances from Phlex.

Maybe this is an oversight in the code used to list new players, I notice in the log it seems to check to make sure the detected device isn't a DVR.

**Comment by crhammock** [comment]
Surely this has something to do with "Connection failed with error code 405" does anyone know what this means?

I have since added a Raspberry Pi running Plex embedded Media player and my samsung S5.  The samsung shows as a player and works the RPI does not.  The first time I added the RPI and scanned I got  Connection failed with error code 0.  All subsiqent scans come back with Connection failed with error code 405.

I also notice that all check urls which work are plex.direct (not really sure what this is).  Where as all the scans which fail connect directly to the IP of the device.  Which when I visit I get the xml of the device, presumable the issue is with the reading of the xml file?

**Comment by chimpy** [comment]
Same problem here @crhammock let me know if you find something out.

**Comment by chimpy** [comment]
What seems super weird to me is that the logs in the UI are detailing all the Cast devices (Google Home and another Cast speaker), as well as the Plex players (Apple TV).

However it doesn't list the Cast devices, and the when Phlex tries to connect to the Player it gets a 403 error. So I took the URL and visited it myself. Which works, I see the Plex XML served up by Plex. Phlex is on the same network so I don't understand where the 403 is coming from.

**Comment by chimpy** [comment]
OK so it can cast to Google Home but that's it. Weird.

**Comment by pensivemonk** [comment]
I have been playing a fair bit with Phlex and excited about the possibilities, but I believe that many of my Plex players are not being detected. I was hunting through the code and it would appear that Phlex may not actually be hunting on the correct ports for Plex Media Player (32433). I have two Apple TV devices running the Plex app and one Raspberry PI running Plex Media Player embedded. None of these show up in the list.

I did some control testing and did an override on the discover ports for Cast devices from 1900 to 32433 and several of the hidden devices were detected, but the responses were not in the format Phlex was expected and they were ignored (listed in the logs, but not enabled in the devices menu).

Would it be possible to list exactly which devices are supported by Phlex other can Cast-compatible devices?

pm

**Comment by pensivemonk** [comment]
I should add that control of my Plex media server to Chromecast devices such as my Google Home Assistant work fine.

**Comment by crhammock** [comment]
I have tried to stay clear of casting issues in this post as I understand they use a different set of communications and will confuse the issue here.

@chimpy not sure a 405 error and a 403 error will be the same thing, I am assuming they are HTTP error but could just as easily be plex specific errors.  I was hoping someone with more experience could tell me.

@pensivemonk I am not sure the ports are wrong (at least from this non casting issues) as if the ports where wrong the urls in the log wouldn't return anything when you connect to them directly, as far as I can make out 32433 is used for non encrypted (http) and 32400 is used for encrypted (https) I would assume chromecast would use some different ports as I understand they use multicast dns.

I, like you wonder it maybe an issue with supported devices.  I would be interested for anyone who can successfully get a player in their list to post the xml output so we can see if we can find something common against the working examples?  Also @pensivemonk is you RPI with embeded Plex one of the devices showing in the list as I am running this also and can't get it to show.

**Comment by pensivemonk** [comment]
@crhammock, the only devices I have been able to list were either Plex Web browser instances (Chrome) and ChromeCast devices. None of my other Plex Media players are listed. I have a bit more testing to do to see if Plex Media Player for Windows is detected. My new RPI running PMP embedded is not detected, which is my pain point as that is the player connected to my in home stereo that really is the only one I want to work! ;)
I also haven't had a lot of luck playing content to my Google Home Assistant as it is an audio-only device. Apparently Phlex prefers video compatible ChromeCast devices..

**Comment by pensivemonk** [comment]
I should point out that my RPI PMP works just fine on its own, connecting to my Plex server, playing content and being available as a "Cast" destination in the Plex App or Plex Web Apps..

**Comment by pensivemonk** [comment]
So, this gets more interesting.. I decided to try the tested URL and got the following from the Plex Media Player instance in question:

<MediaContainer><Player deviceClass="pc" machineIdentifier="l3jvbp6tkqetwfnpulp36jem" platform="windows" platformVersion="7sp1" product="Plex Media Player" protocolCapabilities="navigation,playback,timeline,mirror,playqueues" protocolVersion="1" title="saw-PC" version="2.1.1.703-79cdfa5c"/></MediaContainer>

This is verbatim as there is little here that would be any risk. In addition, I tried the URL for my RPi PMP with the same auth token, and got the following:

<MediaContainer><Player deviceClass="pc" machineIdentifier="3amtaykspwtbj546r15nah5m" platform="libreelec" platformVersion="8.0" product="Plex Media Player" protocolCapabilities="navigation,playback,timeline,mirror,playqueues" protocolVersion="1" title="Jukebox" version="1.3.11.758-4be89b5c"/></MediaContainer>

**Comment by chimpy** [comment]
I did the exact same thing. Encountered the error and then manually visited the URL in a browser and got sensible looking information back.

I don’t understand why Phlex isn’t reporting connection successful.

**Comment by pensivemonk** [comment]
Hopefully this will assist...  I have been tracing the php code and I believe I have found what is going wrong, though I am not sure entirely why.

The function used to test and check the URL of potential devices is called 'check_url' in the file util.php. That function is looking for the following parameters:

`function check_url($url, $post=false) {..`

However, I found a call to this function on line 1986 in 'api.php' that calls the function and passes the URL of the potential device and a second variable that is the auth token. 

Unfortunately the 'check_url' function interprets that token as a "true" for using the POST method, which messes up detecting the players, causing the 405 error (incorrect method).

This can be validated by changing line 605 in 'check_url' to print out the $post variable to the log and see that it is showing the auth token value instead of a boolean.

`write_log("Connection failed with error code ".$httpCode.": ".$url." with post=".$post,"ERROR");`

Note, this is only for programmers or those troubleshooting, please don't modify your code unless you  are ok with breakin'  stuff. ;)

**Comment by crhammock** [comment]
@pensivemonk seems like we are in exactly the same boat.  I to have many plex instances all working from other devices and visible as cast devices from everything but phlex.

I too can only get the Chrome Web browser to show and I too only really need the RPI embedded to work.  Only difference is I can't get my chromecast device to show.  But I don't want to waste time on that now.  I think my next step will be to try and do some PCAPs of the comms between two working PLEX devices trying to "cast" and compare the urls and responses with what Phlex is doing.

**Comment by pensivemonk** [comment]
@crhammock I believe we will need @d8ahazard to review my notes on the code to see if there may be an underlying reason for this or if there is an actual bug in the code. I was able to modify my local version of the code in the 'api.php' and that removed the 405 errors from the log AND my Apple TV-based Plex Apps and my Windows 7 Plex Media Player was detected and registered. However, control is spotty, so it is possible that my hack has broken something else. I have not yet been able to properly detect my RPi Plex Media Player with Phlex.

**Comment by crhammock** [comment]
Did some pcaps and further testing.  Here is some more info for @d8ahazard.

The reason we are getting a 405 error is because Phlex is trying to do an HTTP POST to the Plex devices, which they are refusing.  When you visit the URL from your browser you are obviously doing an HTTP GET.  I notice in the util.php that the chromecast detection stuff also seems to use an HTTP GET.  I will take a look at modifying the code in the util.php but I would suggest if all phlex needs is the xml from the devices then a GET maybe a more compatible method than POST, it certainly doesn't seem to be excepted by default by many of my vanilla configured Plex devices.

**Comment by crhammock** [comment]
@pensivemonk.  Just changed line 592 of the util.php file to the below (just changed true to false) guess what now my RPI shows in the list of players and I can play to it.

curl_setopt($ch, CURLOPT_POST, false);

@d8ahazard I suggest either a similar modification to the code is made permanent or if there is good reason to use POST rather than GET that you include some sort of If statement so if a 405 is returned the script attempts a GET.

Thanks to pensivemonk for your help on this and d8ahazard for a nice piece of work.

**Comment by chimpy** [comment]
You guys are awesome. I will do that modification and report back just for additional feedback.

**Comment by d8ahazard** [comment]
Interesting.  I wonder when in the heck that got changed, because it
*should* be doing a GET.

I'm not able to make the change to the codebase right now, but if someone
wants to make a pull request, I can get it merged.

Thanks for the dilligence, guys.

**Comment by crhammock** [comment]
@d8ahazard don't really know what I am doing in Github but think I have done what you asked.  Thanks Again

**Comment by pensivemonk** [comment]
@crhammock cool! BTW are you running RasPlex on RPi or Plex Media Player embedded? I am afraid that my testing still is blind to my RPi, but I am running the lastest PMP embedded, which I believe uses different ports..

**Comment by crhammock** [comment]
I am running PMP emdedded, PasPlex appears to me to be based on Plex Home Theatre which is no longer supported.  Can't vouch for what ports RasPlex and Plex Home Theatre use but as far as I can make out on PMP 32433 is used for non encrypted (http) and 32400 is used for encrypted (https).
