### ISSUE TITLE
Unable to use Phlex in British English :(

### ISSUE THREAD

**Issue by cjacko87** [d8ahazard/Phlex#18]
Brit here, bought a Google Home on launch day.

Would love to be able to us Phlex but the 'Talk to Flex TV" command just confims back that the plugin isn't available to British English users... :(

Are there any plans to support this any time soon?

**Comment by msh100** [comment]
I doubt there is any technical limitation other than checking a box somewhere. Please could you enable this for English (UK) @d8ahazard ❤️?

**Comment by msh100** [comment]
fyi @cjacko87 you should still be able to achieve something using IFTTT

**Comment by d8ahazard** [comment]
Change language in the home app to use US English...

**Comment by msh100** [comment]
That's not really a good suggestion as it would affect everything else. Is there any reason you wouldn't be willing to simply enable known support for British English?

**Comment by d8ahazard** [comment]
Because Google hasn't given me a way to.

**Comment by cjacko87** [comment]
Thanks both. Switching to US does work, tried that already, but then i lose other UK functionality. FY IFTTT route also doesn't work unless i switch language to US. Guess I'm waiting on Google!

**Comment by msh100** [comment]
Oh interesting, IFTTT is working here (doesn't complain about language) but I have other issues with Phlex itself not working (unable to cast) after it attempts to send the stream context to the chromecast

**Comment by msh100** [comment]
@d8ahazard is it possible to document the API.ai setup? Would be good to be able to setup that part in British English if it is not possible for you

**Comment by d8ahazard** [comment]
@msh100 - Unfortunately, the API.ai bot changes at a pretty rapid pace, so providing it's source would be difficult to maintain and keep up-to-date with my changes.  Also, the google account linking stuff requires a secret to talk to "Flex TV' and the action, so the bot itself isn't very useful without the linkage to support talking to clients.  

UK English is at the top of my radar - when proper support for it is made available by Google, I will ensure that it is available.  In the meanwhile, I'm going to close this as there isn't much I can do about it.

**Comment by Wackymax** [comment]
https://developers.googleblog.com/2017/08/actions-for-british-english.html
