### ISSUE TITLE
make requests more intuitive

### ISSUE THREAD

**Issue by ArchonMegalon** [d8ahazard/Phlex#181]
Hi!

I'm new to Google Home in general and Phlex, but I'm a long time PLEX-User. I was able to set it up and it basically works - sort of.

First of all: it's awesome! Wow! I can't begin to wonder, how you pulled that off! But - since you guys got THAT far, I get greedy... ;)

I asked my GF to use google home and got her saying this:
**"Ok, Google - tell plex** _(no "TV")_ **to play** _(the last episode of)_ **last week tonight on the living room tv."**

Of course, that didn't work, because she should have said
"Ok Google, tell plex tv play last week tonight"

Well, the first sentence is much more intuitive, and it should be easy to implement some changes to make it work.

First the "to": if Phlex gets a request "to play" instead of "play" - just trim the word "to" out of the request.

Second the "on living room tv": if Phlex doesn' find the media "last week tonight on the living room tv" in my library, it should check for the word "on" and either change it's cast destination if it knows the device or rescan the network and report something back like "I don't know \"living room tv\" but I'm searching the local devices again". 

Third the "Plex TV": is there a way to change it (or my google home) to react to the keyword "PLEX" without TV?

**Comment by d8ahazard** [comment]
Both are doable and already implemented..

**Comment by ArchonMegalon** [comment]
Thanks for your answer. I have wrongly configured it through ifttt. As soon as I did it right it worked. I'm humbly apologizing for not noticing it. 

Two other things I noticed where that... 

1) as long as I couldn't connect to my PLEX media I often got the error "couldn't find XY in your media library" (which is totally fine and correct), but also "do you want me to download it" or "should I fetch it", although I had no fetchers installed. Maybe alter it to only bring the "download it"-part, IF Phlex actually has the opportunity to do so?

2) (maybe it's again my setup) it seems like Phlex is unaware of the watched progress of PLEX. The commands "pause" and "continue" work fine, as long as the cast to chromecast is ongoing. But when I tell it to "play film XY" and I have already watched 30 min of that film it always starts from the beginning. "continue film XY" didn't change that behavior either. It would be great if Phlex would either just start where I left off or ask me - like the PLEX-GUI - "do you want to resume or start at the beginning?"

Is there a way to cast to "plexcast" (don't know how to say it) I  mean not chromecast, but the PLEX-media App running on a PC, that has the living room TV connected to it.
