### ISSUE TITLE
php extension is not loaded?

### ISSUE THREAD

**Issue by arissaraiva** [d8ahazard/Phlex#183]
Hello I´m very new to all of these, I´m trying to log into my account and gives me this message: "php extension is not loaded. The sockets php extension, which is required is not loaded. Please enable it in php.ini.

How can I enable it?

**Comment by abrenoch** [comment]
https://stackoverflow.com/questions/6185319/how-to-locate-the-php-ini-file-xampp

remove the `;` before the extensions (which essentially makes the line a comment):
```
 extension=curl.so
 extension=openssl.so
```
