### ISSUE TITLE
how to tell to play a song/album that doesn't have an english name

### ISSUE THREAD

**Issue by fopsdev** [d8ahazard/Phlex#184]
hi
thanks for this awesome project.
got it running so far.
now how can i tell flex tv to play a album with a german name (eg. "laune der natur") ?
google home always translates this "laune der natur" to some stupid english words...
i have english and german named albums, so switching language isn't a solution
thanks for any enlightment

**Comment by d8ahazard** [comment]
Switching language in phlex should only affect how the app parses
commands.  Currently, only English is supported via Google home, but I have
a beta of the app that I'm looking for German and French testers/trainers.
Searching for media is all dependent on how it is displayed in Plex.  Email
me at the donate address in the readme if you'd like to help with assistant
testing.

**Comment by fopsdev** [comment]
ok but that oesn't solve the issue with mixed language albums.
what would solve it is something like:
"ok google, ask flex tv to play germanstart laune der natur germanend in living room" whereas germanstart and germanend are the on the fly lang switchers...
but i guess that google home isn't ready for something like that

**Comment by d8ahazard** [comment]
Yeah, unfortunately, switching languages isn't something Google supports, and as the app relies on their parsing, it's largely out of my hands.

I will be adding support for German and French with the forthcoming release of V2.
