### ISSUE TITLE
New install - error

### ISSUE THREAD

**Issue by flavbap** [d8ahazard/Phlex#189]
Hello, I have a blank page with this error.

![image](https://user-images.githubusercontent.com/33558449/32679098-6a24190c-c665-11e7-90bd-96855d369aa7.png)

**Comment by teejo75** [comment]
As a workaround for now, in your `C:\xampp\htdocs\Phlex` folder, add a new folder called 'logs'.

**Comment by flavbap** [comment]
hi, it's ok thank you very much!
