### ISSUE TITLE
install problems :(

### ISSUE THREAD

**Issue by tonga1981** [d8ahazard/Phlex#191]
hi
got my self some problems installing this. would love some help understanding this.

Warning: syntax error, unexpected '=' in config.ini.php on line 11 in C:\xampp\htdocs\Phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php on line 131

Fatal error: Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: config.ini.php in C:\xampp\htdocs\Phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php:133 Stack trace: #0 C:\xampp\htdocs\Phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php(891): Config_Lite->read('config.ini.php', 0) #1 C:\xampp\htdocs\Phlex\util.php(872): Config_Lite->__construct('config.ini.php') #2 C:\xampp\htdocs\Phlex\index.php(4): checkSSL() #3 {main} thrown in C:\xampp\htdocs\Phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php on line 133

**Comment by abrenoch** [comment]
It sounds like phlex may have produced an invalid `config.ini.php` file - I would suggest removing that file (make a backup if it makes you feel better), and trying again. If that doesn't help, you could post your config file - but make sure you remove any plex token before doing so!

**Comment by d8ahazard** [comment]
Sorry for the late reply, but yeah, the issue is a corrupt config file.  Deleting it and reloading should fix the issue, make sure you've updated Phlex to the latest version first.
