### ISSUE TITLE
Unable to create file C:\xampp\htdocs\Phlex\logs\Phlex.log because No such file

### ISSUE THREAD

**Issue by tigearis** [d8ahazard/Phlex#193]
Hi, I new to this and maybe i am missing something.

I followed the instructions but i keep getting this error when i go to navigate to the web interface:

Warning: touch(): Unable to create file C:\xampp\htdocs\Phlex\logs\Phlex.log because No such file or directory in C:\xampp\htdocs\Phlex\util.php on line 375

Warning: chmod(): No such file or directory in C:\xampp\htdocs\Phlex\util.php on line 375

Warning: filesize(): stat failed for C:\xampp\htdocs\Phlex\logs\Phlex.log in C:\xampp\htdocs\Phlex\util.php on line 376

Any help would be appreciated

**Comment by sargcatfish** [comment]
As a temporary workaround you can create the logs directory manually.

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
