### ISSUE TITLE
cannot log into phlex after it was working

### ISSUE THREAD

**Issue by PetrusVermaak** [d8ahazard/Phlex#194]
IP address was changed

Originating IP - 192.168.8.155
[Mon, 13 Nov 2017 17:07:07 +0100] [DEBUG] [api.php::require_once] - Invalid API Token, forcing logout.
[Mon, 13 Nov 2017 17:07:47 +0100] [DEBUG] [api.php::require_once] - INCOMING REQUEST!!
[Mon, 13 Nov 2017 17:07:47 +0100] [DEBUG] [api.php::require_once] - Sorry, couldn't validate user.
[Mon, 13 Nov 2017 17:07:47 +0100] [ERROR] [api.php::require_once] - ERROR: Unauthenticated access detected.

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
