### ISSUE TITLE
plexserver.cookiehigh.us down

### ISSUE THREAD

**Issue by ThrDev** [d8ahazard/Phlex#195]
https://phlexserver.cookiehigh.us/api.php?apiToken=x&serverAddress=x

It would be really nice to not have to rely on your server for the integration in the case that it goes down, such as now.

Would it be possible that you would be willing to share your api.ai agent with us, exported with everything, so we would be able to run our own api.ai agents in case your site goes down?

**Comment by jneljeff** [comment]
Man, what timing... I have been pulling my hair out all evening trying to figure out why nothing was working... Really unfortunate to have to rely on someone else's private hosting for this whole thing to function... Even the background image wont load without it.

**Comment by d8ahazard** [comment]
Fixed!

I've got a ping monitor set up now, shouldn't have issues again.

**Comment by jneljeff** [comment]
Thanks! Now I can finally try to get it to control my TV!
