### ISSUE TITLE
Connectivity issues after inactivity (less than 60 minutes)

### ISSUE THREAD

**Issue by jneljeff** [d8ahazard/Phlex#198]
Phlex seems to operate normally running in docker on Ubuntu 16,  but commands do not reach Plex Media Player on Windows 10 after a period of inactivity (in this case after one episode of Walking Dead).  The attached log shows 3 commands to play the latest episode of The Good Doctor immediately after the previous episode finished.  In the past I have kept the Web UI open and the commands still don't work after a period of inactivity, but work again after moving around with a remote.

The PC does not go to sleep and is connected via hardwire to the network which rules out a sleeping network interface.

The server IP in the log is the default gateway of the docker container. PMS is installed on the host.

[Phlex.log](https://github.com/d8ahazard/Phlex/files/1473289/Phlex.log)

Attempt 1: (Failure) Phlex web UI is closed and Plex Media Player has not been touched manually.
Attempt 2: (Failure) Phlex web UI is closed and Plex Media Player was moved to the main menu with remote.
Attempt 3: (Success) Phlex web UI is open and devices re-scanned before command was executed.

**Comment by jneljeff** [comment]
After another round of losing my devices I'm curious if there is a reason we are "scanning" for anything... would it not make sense to be able to set a static ip address for a given device and let Phlex send requests to it whether it's online or not?

**Comment by d8ahazard** [comment]
Yes. Having a wide assortment of devices, including cast video, cast audio, ghome, home mini, roku, android TV, and the various Desktop/OS instances, I can tell you that while you'd think the devices are always just on and there - they're often not. If the Plex app isn't running, if your network is weird, if any of dozens of other things happen, your player could be "unavailable".

To combat this, I've revised a number of things in the app, including caching and scanning of devices, and implementing a helper cast plugin for your Media server that will solve a lot of these issues.

As such, I'm going to close this, as it should no longer be an issue once V2 is final.
