### ISSUE TITLE
Issue when I enable "Use Chromecast Devices"

### ISSUE THREAD

**Issue by ericnotthered** [d8ahazard/Phlex#2]
If I enable the "Use Chromecast Devices" Toggle, when I then subsequently click on the icon to select a player, I get a dropdown with:

> SELECT A PLAYER TO CONTROL
> FATAL ERROR:  UNCAUGHT ERROR:  CLASS 'NET_DNS2_RESOLVER' NOT FOUND IN /OPT/LAMPP/PHLEX/API.PHP (1339)

If I uncheck the chromecast toggle, my Android player shows up successfully in the dropdown.

**Comment by d8ahazard** [comment]
Closed, issue has been superseded by #33 - currently working on a fix.
