### ISSUE TITLE
Unable to link multiple google accounts

### ISSUE THREAD

**Issue by Johnson90512** [d8ahazard/Phlex#200]
I followed your instructions here https://github.com/d8ahazard/Phlex/issues/45   but it didn't work. It only works with one or the other. When the second account is trying to be added it links fine, but then breaks the first account.

**Comment by d8ahazard** [comment]
This should work now, but I want to make sure it does before releasing V2.

**Comment by Johnson90512** [comment]
Works after this latest update. Appreciate the hard work!
