### ISSUE TITLE
Unable to login to Phlex website - "DL function not available"

### ISSUE THREAD

**Issue by thefoxman88** [d8ahazard/Phlex#201]
I am unable to login with my Plex username/password. This is setup on a pi and had no issues with the install until this point.

Logs from Phlex.log
> [Thu, 16 Nov 2017 13:38:18 +1100] [ERROR] [util.php::checkFiles] - The xml PHP extension, which is required for Phlex to work correctly, is not loaded. Please enable it in php.ini, restart your webserver, and then reload this page to continue.
[Thu, 16 Nov 2017 13:42:42 +1100] [INFO] [util.php::load_lib] - Extension is not loaded, attempting to load xml...
[Thu, 16 Nov 2017 13:42:42 +1100] [WARN] [util.php::load_lib] - DL function not available.

Below are the things I changed to the stop php.ini file
=====================================
>pi@raspberrypi:/var/www/html/Phlex/logs $ grep open_base /etc/php/7.0/apache2/php.ini
; open_basedir, if set, limits all file operations to the defined directory
;open_basedir =
open_basedir = /var/www/html/Phlex/
pi@raspberrypi:/var/www/html/Phlex/logs $ grep extension= /etc/php/7.0/apache2/php.ini
;   extension=modulename.extension
;   extension=msql.dll
;   extension=msql.so
;   extension=/path/to/extension/msql.so
;extension=php_bz2.dll
;extension=php_curl.dll
;extension=php_fileinfo.dll
;extension=php_ftp.dll
;extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
;extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
;extension=php_mbstring.dll
;extension=php_exif.dll      ; Must be after mbstring as it depends on it
;extension=php_mysqli.dll
;extension=php_oci8_12c.dll  ; Use with Oracle Database 12c Instant Client
;extension=php_openssl.dll
;extension=php_pdo_firebird.dll
;extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
;extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_shmop.dll
;extension=php_snmp.dll
;extension=php_soap.dll
;extension=php_sockets.dll
;extension=php_sqlite3.dll
;extension=php_tidy.dll
;extension=php_xmlrpc.dll
;extension=php_xsl.dll
extension=curl.so
extension=openssl.so
pi@raspberrypi:/var/www/html/Phlex/logs $

Phlex_error.log output, removed username e-mail and password.
=============================================

> pi@raspberrypi:/var/www/html/Phlex/logs $ tail Phlex_error.log
#0 /var/www/html/Phlex/api.php(4596): signIn('Y2hyaXNqZm94QG9...')
#1 /var/www/html/Phlex/api.php(32): checkSignIn('xxxxx@outlo...', 'xxxxxxx')
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 707
[16-Nov-2017 13:32:08 Australia/Melbourne] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/Phlex/util.php:707
Stack trace:
#0 /var/www/html/Phlex/api.php(4596): signIn('Y2hyaXNqZm94QG9...')
#1 /var/www/html/Phlex/api.php(32): checkSignIn('xxxxx@outlo...', 'xxxxxxx')
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 707

**Comment by d8ahazard** [comment]
Please refer to step 3 in the readme instructions on using with a raspberry PI.  You need to enable/add the php_xml extension, as the log states.

**Comment by LucaKaufmann** [comment]
fixed this issue by installing php7.0-xml:
`sudo apt-get remove php-xml`
`sudo apt-get install php7.0-xml`

then
`sudo systemctl daemon-reload`
`sudo service apache2 restart`
