### ISSUE TITLE
Having problems recognizing TV show titles on request

### ISSUE THREAD

**Issue by IBentMyWookie** [d8ahazard/Phlex#202]
I have tried requesting the Title of the show, the title with the episode name, the title with the season and episode number, latest episode of the show title.  none of them seem to work.  The most recent show was You're the Worse  S04E12.

**Comment by d8ahazard** [comment]
Looks like the issue is with the apostrophe in the word "You're".  I've just pushed an update that will fix this - #205


Feel free to re-open if the problem persists.
