### ISSUE TITLE
Half connected

### ISSUE THREAD

**Issue by twaynebauer** [d8ahazard/Phlex#205]
I really appreciate the work put in to this app! 
I hope my issue is either user error or something to help move it forward. I think I'm half connected. My Home Mini doesn't appear to recognize Phlex (constantly replies that it "isn't available right now, try again soon"), but I have gotten it to respond to voice commands to play/pause/resume multiple movies. It was never able to "talk to flex tv." With that, I never got any notice to link the account again.
So, while some back-end stuff is clearly going through, there's an issue hanging out.

**Comment by NByz** [comment]
Hate to just add a "me too", but I also got very close to getting everything working in my first couple days - the Phlex server would occasionally present my Google Home commands, but just not do anything other than display them on the web interface.  So I deleted Phlex from Xampp and started again.  Now I'm right where you are...

Have you gotten anywhere?  I'll share my success or failure today.

**Comment by twaynebauer** [comment]
Nope - nothing here. Voice commands _mostly_ work, but still doesn't show the account is linked.

**Comment by NByz** [comment]
I got it to go from consistently giving: "...isn't available right now" and displaying my command on a card in the Phlex web interface to consistently giving: "Ok.  Getting Flex TV.  An error has occured, please report the following message to the developer" and not displaying the command on the web interface.

But damned if I know what change made that happen.  I was keeping track of all of my changes in notepad and have tried reversing each one of them to see which, and couldn't reverse the symptom.

This is definitely a challenging install.

**Comment by abrenoch** [comment]
Have you guys tried re-linking your google accounts (just open the phlex settings and link google account again)? I have found myself needing to this periodically to keep everything connected (not certain what prompts this).

**Comment by NByz** [comment]
I sure did quite a few times.  Most of the time I got the Nick Cage face.  But I would also intermittently get failures.  I wasn't able to consistently reproduce the settings changes that resulted in success vs. failure.  But all of my serious testing of other changes happened after recent Nick Cage faces.

**Comment by jonchampagne** [comment]
+1

**Comment by NByz** [comment]
d8ahazard made some changes to util.php.  If you re-download it, you get error logging back.  

I can now see that I'm getting 2 x "ERROR: Unauthenticated access detected. Originating IP"  and 2 x "Recaching due to missing servers." in a reasonable period of time that included one verbal "Ok. Getting Flex TV. An error has occured, please report the following message to the developer" from the mini.

**Comment by d8ahazard** [comment]
Made quite a few updates recently that should have addressed this.

Feel free to re-open or create new if you're still having issues.
