### ISSUE TITLE
Radarr not adding and searching just adding 

### ISSUE THREAD

**Issue by henrikrox** [d8ahazard/Phlex#208]
All fetched movies trough phlex only gets added, this is fine for new movies that havnt come out yet, but terrible for old movies.

Then i need to wait for nzbsite to add a new file for that old movies, which can take 100 days.

In Radarr, there is a "add and search" button when importing movies, hopefully this can be added to phlex?

**Comment by abrenoch** [comment]
Phlex does behave this way already (I can confirm this), perhaps it is adding it under a different quality profile and radarr is excluding the matches for some reason?

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
