### ISSUE TITLE
Undefined index on windows fresh build with xampp

### ISSUE THREAD

**Issue by pedroash** [d8ahazard/Phlex#209]
Hi guys,

I did a fresh install of phlex but am having problems after i login with my plex username and password
the page displays:

Notice: Undefined variable: _SESSION in C:\xampp\htdocs\Phlex\api.php on line 4320

Notice: Undefined index: rescanTime in C:\xampp\htdocs\Phlex\api.php on line 1785

Notice: Undefined index: autoUpdate in C:\xampp\htdocs\Phlex\util.php on line 1800

Notice: Undefined index: useCast in C:\xampp\htdocs\Phlex\api.php on line 1791

Notice: Undefined index: cleanLogs in C:\xampp\htdocs\Phlex\util.php on line 495

Notice: Undefined index: noLoop in C:\xampp\htdocs\Phlex\api.php on line 1799

Notice: Undefined index: cleanLogs in C:\xampp\htdocs\Phlex\util.php on line 495

Notice: Undefined index: servers in C:\xampp\htdocs\Phlex\api.php on line 1864

Notice: Undefined index: clients in C:\xampp\htdocs\Phlex\api.php on line 1864

Notice: Undefined index: newToken in C:\xampp\htdocs\Phlex\api.php on line 74

Notice: Undefined index: newToken in C:\xampp\htdocs\Phlex\api.php on line 75

Notice: Undefined index: hookUrl in C:\xampp\htdocs\Phlex\body.php on line 242

Notice: Undefined index: hookPlayUrl in C:\xampp\htdocs\Phlex\body.php on line 254

Notice: Undefined index: hookPausedUrl in C:\xampp\htdocs\Phlex\body.php on line 267

Notice: Undefined index: hookStopUrl in C:\xampp\htdocs\Phlex\body.php on line 279

Notice: Undefined index: hookFetchUrl in C:\xampp\htdocs\Phlex\body.php on line 291

Notice: Undefined index: hookCustomUrl in C:\xampp\htdocs\Phlex\body.php on line 303

Notice: Undefined index: hookCustomPhrase in C:\xampp\htdocs\Phlex\body.php on line 307

Notice: Undefined index: uiSettingHookCustomResponse in C:\xampp\htdocs\Phlex\body.php on line 309

Notice: Undefined index: plexDvrReplaceLower in C:\xampp\htdocs\Phlex\body.php on line 402

Notice: Undefined index: plexDvrRecordPartials in C:\xampp\htdocs\Phlex\body.php on line 408

Notice: Undefined index: dvr_endoffset in C:\xampp\htdocs\Phlex\body.php on line 418

Notice: Undefined index: couchList in C:\xampp\htdocs\Phlex\api.php on line 3977

Notice: Undefined index: couchList in C:\xampp\htdocs\Phlex\api.php on line 3981

Notice: Undefined index: couchProfile in C:\xampp\htdocs\Phlex\api.php on line 3983

Notice: Undefined index: radarrList in C:\xampp\htdocs\Phlex\api.php on line 3986

Notice: Undefined index: radarrList in C:\xampp\htdocs\Phlex\api.php on line 3990

Notice: Undefined index: radarrProfile in C:\xampp\htdocs\Phlex\api.php on line 3992

Notice: Undefined index: sickList in C:\xampp\htdocs\Phlex\api.php on line 3954

Notice: Undefined index: sickList in C:\xampp\htdocs\Phlex\api.php on line 3958

Notice: Undefined index: sickProfile in C:\xampp\htdocs\Phlex\api.php on line 3960

Notice: Undefined index: sonarrList in C:\xampp\htdocs\Phlex\api.php on line 3968

Notice: Undefined index: sonarrList in C:\xampp\htdocs\Phlex\api.php on line 3972

Notice: Undefined index: sonarrProfile in C:\xampp\htdocs\Phlex\api.php on line 3974

Notice: Undefined index: uiSettingLogupdate in C:\xampp\htdocs\Phlex\body.php on line 676

Notice: Undefined index: plexDvrUri in C:\xampp\htdocs\Phlex\api.php on line 3292

Notice: Undefined index: updateAvailable in C:\xampp\htdocs\Phlex\api.php on line 3295

Any help would be great, Thanks

**Comment by jvreeken** [comment]
I'm having the same problem... fresh install on latest master...

**Comment by Darksleep** [comment]
Same here

**Comment by abrenoch** [comment]
You all most likely need to modify your `php.ini` config file to have `error_reporting` set to `E_ERROR`. You are seeing lower logging level behavior (`E_NOTICE` or `E_ALL`).

**Comment by fopsdev** [comment]
same here

**Comment by wild9** [comment]
@abrenoch Thanks for the help but changing this (and restarting Apache) does not remove the messages. The other issue as mentioned in #207 "ERROR: Service name not recognized" appearing when any PLEX or Fetcher "Test" Buttons are clicked still remains.

**Comment by d8ahazard** [comment]
Fixed.  The trick is to tell setDefaults() in util.php to use E_ERROR.  Had the lower logging level enabled b/c I thought it might help with debugging, didn't realize some installs don't like to pipe all warning output to Phlex_error.log like I prefer.

**Comment by NByz** [comment]
Thanks!

**Comment by pedroash** [comment]
Thanks d8ahazard  All is working now

Many Many Thanks
