### ISSUE TITLE
Can't see remote Plex Server

### ISSUE THREAD

**Issue by theCheek** [d8ahazard/Phlex#210]
Hi, new user here so possibly something I am doing wrong.

Followed the guide and got this all set up - it can see my chromecast devices, and also I can communicate with Phlex via my google home mini's assistant - so far so good!

The issue I am having is that I cannot see my externally hosted plex server. I have a local instance of Plex running on my PC which Phlex did pick up, but nothing else. I tried switching off the local instance in case that was causing the issue, but now there is no nothing listed underneath Playback server of the Plex settings in Phlex. Also, when clicking the 'Test' button of this page, I get the message: 'Error, Service Name not Recognised'

I am running this on the web server portal of my synology's Diskstation. It supports PHP7.0, apache and I have enabled all the relevant dependancies. 

When looking at the config.ini.php, even thought I stopped my local instance of Plex, it still seems to have the details stored, with no other reference to the remote Plex server. Here is my (edited for privacy) config: https://pastebin.com/f2gWZy0z

See below my environment info

On what OS are you running Phlex?
Synology DSM 6.0 (Linux version 3.10.77 (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #8754 SMP Tue Oct 24 11:10:09 CST 2017)

Are you using a new instance of XAMPP, or an existing webserver?
Existing web server (Webstation application for Synology, with PHP7.0, Apache server, and all relevant extensions enabled (curl, sockets and openssl)
If Using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
As far as I can see, yes. The fact that the config.ini.php holds personal configuration details shows it can read and write.

If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
The remote Plex server is running on Ubuntu LTS 16
Is Phlex using http or https?
http
If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files. Paste anything that looks related as well.
The last line of the error.log looks suspicious: https://pastebin.com/9bti9uH2

Thanks for any help!

**Comment by KaraokeStu** [comment]
I have the exact same issue, my Ubuntu Plex Server is not showing up

**Comment by Xarin** [comment]
Similar issue here running the docker version of phlex and it cant see my local server but it can see a friends plex server.

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
