### ISSUE TITLE
Validate Server address is still valid, multi-user linking on the mothership

### ISSUE THREAD

**Issue by sokool101** [d8ahazard/Phlex#211]
Ubuntu 16.04.3 LTS
Running Apache and PHP7.0 using the instructions for the Raspberry Pi with just a few different directory locations because Ubuntu likes to be different.

No matter what command I dictate I'm getting "I'll try to ask Flex TV to ::whatever I said:: " in response. The command works and the correct responses show up in Phlex Web but Google never says it. I'm guessing it has to do with permissions with google. I never got a card popup in my Home App to link my account the second time.  When I go to myaccount.google.com/permissions Phlex TV only has access to basic account info. Not sure if it needs a higher level or not. Should I remove access and try again or will that bork the whole thing? Is there a way to force the card to pop up? Is that even my problem?

**Comment by d8ahazard** [comment]
Should be fixed now - I think the issue was with the logging level I'd inadvertently changed...

**Comment by sokool101** [comment]
In my quick testing when I got home asking "what's on deck" it all seems to work correctly now. Thanks for the quick fix. I'll be sure to put a little something extra in your Holiday card this year. ( Will be sending a donation shortly ). 

Also kinda of related... When using IFTTT there is no way to get it to actually reply other than the response you put in the recipe for the applet, correct?

**Comment by d8ahazard** [comment]
Hey, appreciated!

No, there's no way to get it to read back anything other than what you ask
it.  If there were, I'd never have bothered releasing it as an Action.  ;)

**Comment by sokool101** [comment]
Makes sense. Thanks again!

I guess I'll close this now since it's good to go.

**Comment by sokool101** [comment]
LOL spoke too soon. It's doing it again. The only thing I did was link my wife's google account. IDK if that's related or not. Anything I can give you that can help?

**Comment by ThrDev** [comment]
It's doing it for me as well but it seems to be intermittent.

**Comment by noone942** [comment]
It's doing it for me as well

**Comment by Antimus** [comment]
I'm getting this too now, reboots don't seem to fix it
