### ISSUE TITLE
Undefined index @attributes util line 669

### ISSUE THREAD

**Issue by DanDon** [d8ahazard/Phlex#212]
I receive this error on a fresh install on Windows with apache server through Xampp ... installation all went smooth....

`Notice: Undefined index: @attributes in C:\xampp\htdocs\phlex\util.php on line 669
 ERROR`

**Comment by abrenoch** [comment]
Duplicate of https://github.com/d8ahazard/Phlex/issues/209

**Comment by d8ahazard** [comment]
Fixed.
