### ISSUE TITLE
"ERROR: Service name not recognized" when clicking test under the Plex or Fetcher menus

### ISSUE THREAD

**Issue by wild9** [d8ahazard/Phlex#213]
It was mentioned under another issue #207 that was resolved (Thanks!) but this part remains.

When clicking on "Test" under any of the Fetchers or on the Plex tab the message : "ERROR: Service name not recognized" is displayed.

Strangely Couch Potato integration is still functional despite this and the button being turned "off"

**Comment by mpt245** [comment]
I had this issue as well - I'm not sure if there was a recent change or refactor, but basically the Test button element the "data-" prefix on its value, e.g. '  data-value="Couch"   ' rather than '   value="Couch"   ' which it has now.

This only seems to affect the tests as you said, but it definitely derailed me during setup.

**Comment by KaraokeStu** [comment]
Same problem here 👍

**Comment by kiteboy** [comment]
Im getting this too - whats the workaround above exactly??? - what file is that section in??

**Comment by FrostyWolf** [comment]
Getting the same error when trying to test Plex/Fetchers.  Doesn't seem to affect whether or not it works though.

**Comment by kiteboy** [comment]
Still having isssues - I enable the fetchers but seems to do nothing for me and when I logout and go back in all the fetcchers that II previously tried to enable are still disabled

**Comment by KaraokeStu** [comment]
@kiteboy Yup - getting the same here

**Comment by jvreeken** [comment]
Same for me too.  Sonarr and Radarr still work but show as being turned off... when I turn them on and click test, it gives be a popup error at the bottom of the page that says "ERROR: Service name not recognized"

**Comment by Thracky** [comment]
There's an error in main.js on line 159 when retrieving the "value" for the test button. Currently it is the following:

`                if ($(this).hasClass("testInput")) {
                        value = $(this).data('value');
`
I changed it to the following and it seems to work:
`                if ($(this).hasClass("testInput")) {
                        value = $(this).val();
`

**Comment by kiteboy** [comment]
Still not doing it for me at least anyway - can somebody else try??

**Comment by trippinshrumes** [comment]
didn't do it for me either

**Comment by bobpaul** [comment]
if I checkout 1f0b000f694b from early Dec then it works. If I checkout the latest (3d9bb59c1c86bd90) then I can't even log in.

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
