### ISSUE TITLE
Library Browsing Commands

### ISSUE THREAD

**Issue by PlexYeah** [d8ahazard/Phlex#215]
I have a large movie library, so it would be nice to be able to browse the entire library with commands such as forward, back, next page, previous page, etc. Also, browse by genre. The other thing that would be nice is if if could figure out movies based upon most of the variable being completed. As it its now, unless I say the exact name of the movie it's not capable of finding the movie. When I started programming my AutoVoice/Tasker profiles with natural language commands it made all of the difference in the world: https://console.dialogflow.com. Might this help? Over all great job!

**Comment by d8ahazard** [comment]
I've got quite a bit more smarts in the searching now.  Left/right/up/down are not something I want to implement, simply because the idea is you should just be able to say what you want and it comes up.

However, the searching stuff should be much better now, so I'm going to close this.
