### ISSUE TITLE
No Servers, Clients or DVR returned?

### ISSUE THREAD

**Issue by teshiburu** [d8ahazard/Phlex#217]
Whenever i hit "rescan devices" none appear, and this appears in the logs 

> Final device array: 
{
  "servers": [],
  "clients": [],
  "dvrs": []
}

Yet, if i manually browse to https://plex.tv/api/resources?includeHttps=1&includeRelay=0&X-Plex-Token=XXXXXXXXXXXXXXXXXXXXXX

Which is listed in the logs as well, it also lists all of my devices and clients...

I've also posted my phlex.log file here at pastebin: https://pastebin.com/fQFxfnGs

Any ideas? could it be due to my Dual WAN setup that handles load balancing? maybe client devices are presented with different external IPs?

**Comment by KaraokeStu** [comment]
I've had exactly the same issue I'm afraid :(

**Comment by teshiburu2017** [comment]
@KaraokeStu  - similar setup? DUAL WAN? PFSENSE?

**Comment by KaraokeStu** [comment]
No, but it fails on Linux and seems to work on Windows

**Comment by teshiburu** [comment]
See im running mine using IIS on server 2012 r2 and still cant get it to work :( it used to and does when it feels like it

**Comment by teshiburu** [comment]
Any ideas? @d8ahazard

**Comment by d8ahazard** [comment]
Is windows Firewall on?  Are you seeing any issues in the log connecting to plex.tv?

**Comment by d8ahazard** [comment]
Closing, duplicate of #165 .
