### ISSUE TITLE
Control plex music

### ISSUE THREAD

**Issue by Darksleep** [d8ahazard/Phlex#219]
Would you be able to add control of plex music any time soon?

**Comment by d8ahazard** [comment]
Define control? You should be able to play music now.

**Comment by teshiburu** [comment]
I'd like to see some kinda way to use Phlex to cast directly to a google home device for music thatd be cool :)

**Comment by d8ahazard** [comment]
This is already implemented.

**Comment by teshiburu** [comment]
Really? so i can ask it to play music on its self?

**Comment by d8ahazard** [comment]
Really.  ;)

**Comment by teshiburu** [comment]
@d8ahazard  - i will have to have a look at that, do i have to specify it as the playback client in the UI?

**Comment by d8ahazard** [comment]
Or, if you know the "network name" of your player, you can say "Play Eminem
on Kitchen Home" and it should set the client and start playback.  :D
