### ISSUE TITLE
Says "Playing" but Status reads "Error"

### ISSUE THREAD

**Issue by anixan** [d8ahazard/Phlex#22]
When I ask it to say play an episode of the Simpsons it does find it and says playing however nothing shows on the TV and the Status field in the JSON just reads "Error".

Any idea how I debug into the full error description for this?

I have just been going through the JSON and the URL to invoke the playback return a "400 (Bad Request)"

and this is the breakdown of the URL being sent(I modified the tokens :) ):

```html
http://192.168.0.7:32400/player/playback/
playMedia?key=%2Flibrary%2Fmetadata%2F810&
offset=0&
machineIdentifier=21c50d62314dc92abace8df17e70e44a90ede086&
protocol=http&
address=192.168.0.7&
port=32400&
containerKey=%2FplayQueues%2F998%3Fown%3D1%26window%3D200&
token=transient-f1a5492c-5e36-4795-a433-708229dea4a1&
commandID=1
```

**Comment by d8ahazard** [comment]
You should see a whole ton of information in the files Phlex.log and Phlex_Error.log, which will be generated in the root directory of Phlex.  Obviously make sure you scrub anything from that before posting as well.  

Getting a 400 error trying to re-post the playback URL isn't wholly uncommon, some of the players I use a post with custom headers to get it to play.  What kind of device are you playing to, and what kind of server are you hosting Phlex from?

**Comment by anixan** [comment]
Hi :)

Thanks for the fast reply, struggling as to how I access the logs on a synology docker image :(

I think it would be a really useful feature to have a simple webview that displays the contents of the Log files from the UI.

Your help here is greatly appreciated :+1:

**Comment by anixan** [comment]
Hi,

Not sure if you have had chance to look into this but this still is not working. I have tried the command several times with no luck. Also now it seems I cannot see any players in the list to cast to which is strange. I have included the log from the Phlex.log and Phlex_Error.log below:

**Phlex.log**
`I/Thu, 04 May 2017 10:59:25 -0500: api.php::fetchDVRList: Re-checking DVR List.                      
I/Thu, 04 May 2017 10:59:25 -0500: api.php::fetchDVRList: Here's what we've got: {"name":"Jaris","pr
oduct":"Plex Media Server","id":"31c59d63284dc87abace8ff17e70e44a62ede999","token":"iDRBbazaBMpfxRgL3
BdU","selected":true,"uri":"http:\/\/192.168.0.7:32400","publicAddress":"162.273.252.271"}           
I/Thu, 04 May 2017 10:59:25 -0500: api.php::fetchDVRList: URL is http://192.168.0.7:32400/tv.plex.pro
viders.epg.onconnect:4?X-Plex-Token=iDRBbazaBMpfxRgL3BdU `

**Phlex_Error.log**

`[04-May-2017 10:05:25 America/Chicago] PHP Notice:  Undefined index: plexUserName in /config/www/Phle
x/util.php on line 10`

I would really like to get this working as it would be a great addition to my home automation :)

**Comment by d8ahazard** [comment]
@anixan - 

Please give the latest codebase a try.  I've made quite a few changes to the lookup and fetching for devices across the board, as well as fixed detection of cast-based devices for Docker.  I'm hoping that all of these changes combined will have you working again.

If not, please provide a full copy of the Phlex.log file so I can further examine the issue.

**Comment by farmjope** [comment]
I'm running into the same exact issue.  The Google Home says that it's playing successfully, but Phlex says "Playback status: error".  Below attached is my full Phlex.log converted to a .txt so I can upload it
[Phlex - Copy.txt](https://github.com/d8ahazard/Phlex/files/1007966/Phlex.-.Copy.txt)

**Comment by farmjope** [comment]
I think this is the issue:

Tue, 16 May 2017 20:03:18 -0500 [ DEBUG ] api.php::playMediaQueued - Playback URL is https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:32400/player/playback/playMedia?key=%2Flibrary%2Fmetadata%2F2040&offset=0&machineIdentifier=8b91a9b11fa77d11705b4e4a21112eef51d3f7f0&protocol=https&address=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&port=32400&containerKey=%2FplayQueues%2F6%3Fown%3D1%26window%3D200&token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&commandID=4
Tue, 16 May 2017 20:03:18 -0500 [ DEBUG ] api.php::playMediaQueued - Result value is <?xml version='1.0' encoding='utf-8'?>
<Response code="2000" status="FrameworkException: Unable to find player with identifier lshs643j81ysnhfr">
  <Traceback>Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-4613ce077\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request
    result = f(**d)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-4613ce077\System.bundle\Contents\Code\playerservice.py", line 50, in process_remote_command
    raise FrameworkException('Unable to find player with identifier %s' % identifier)
FrameworkException: Unable to find player with identifier lshs643j81ysnhfr
</Traceback>
</Response>

Tue, 16 May 2017 20:03:18 -0500 [ DEBUG ] api.php::playMediaQueued - Result is error

**Comment by d8ahazard** [comment]
Hello, just revisiting my issues, is this a problem for you guys?

@farmjope @anixan
