### ISSUE TITLE
change default played episode for news-shows

### ISSUE THREAD

**Issue by ArchonMegalon** [d8ahazard/Phlex#220]
Hi!

I think that when I ask plex tv to play lucifer, house or whatever TV-Show I have it starts the next unwatched episode. So far so good, but that's actually NOT what I would like for news-shows like 
the daily show with trevor noah,
the late night show (stephen colbert),
Seth Meyers or last week tonight with John Oliver. Basically shows, that comment the current news and politics. Because even if I missed yesterdays show, I want to see the current one. 

Now - I do understand that it's hard to guess for a program, but - is there a way to make this happen? Maybe for shows with some keywords in them like "tonight, daily show, night show, ..."

**Comment by d8ahazard** [comment]
Using verbiage like "the lastest episode of" or "the newest" should accomplish this for you.
