### ISSUE TITLE
Cast to device

### ISSUE THREAD

**Issue by pquinn1212** [d8ahazard/Phlex#222]
Hi All, 

Firstly this is great, 

I do need a little help if ok , 
I can cast to plex Web but cant to my playstation or xbox do i need to do anything in particular.

Also i cant use the web interface in firefox only chrome. 

Any help would be great1

**Comment by d8ahazard** [comment]
If the device shows up in the list of devices in your Plex web interface, then it *should* show up in Phlex. If not, then I'd be interested in seeing your logs to determine the issue. Specifically, the results of "Scandevices" and the subsequent "CheckIP". Send me an email to the donate address listed in the readme if you still need help.

**Comment by d8ahazard** [comment]
Also, just used it in Firefox(Desktop, the latest version, and it looked and worked great.  What's the issue?

**Comment by d8ahazard** [comment]
Okay, it's been almost a week, haven't heard back on this.  I'm going to close this now.  Feel free to re-open or create a new issue if you want.
