### ISSUE TITLE
Evaluate MAMP as replacement for XAMPP

### ISSUE THREAD

**Issue by elkz** [d8ahazard/Phlex#224]
I've just tried setting Phlex up for the first time, had no issues what so ever until I got to the part where I need to link my account. Amazon button seems to work fine and sends you through to a login page but Google isn't responding and just leaving me with a white page?

**Comment by elkz** [comment]
Still having the same issue. Followed by:

> 
Warning: fopen(C:\xampp\htdocs\Phlex\logs\Phlex.log.php): failed to open stream: Permission denied in C:\xampp\htdocs\Phlex\util.php on line 441
successUnable to connect to Client at *:5000/Phlex/, please check the setting for 'Public Address' in the Phlex UI.

* I am able to connect from outside of my home network yet I am still unable to link my Google Account.

**Comment by rsteele11413** [comment]
So I had this issue for a while and tried a lot to fix it. What finally worked for me was installing MAMP instead of xampp.

**Comment by rsteele11413** [comment]
If you give it a try, just make sure you stop apache on xampp and set your correct ports through MAMP Preferences.

**Comment by elkz** [comment]
This has actually worked, I'm just having trouble getting it to cast to the device at the moment but I think that's because of the sockets being off/closed. I'm just trying to solve that problem next.

**Comment by rsteele11413** [comment]
What device are you casting to? I noticed that I had a couple of devices, such as an LG tv and xbox one, that would not work correctly. I did try my android tv box and it is working near perfectly.

**Comment by elkz** [comment]
I'm trying to cast to RasPlex on a Raspberry Pi, I'm not entirely sure It's going to work with this - especially as I can't narrow down what ports RasPlex is using. I may have to seek another player.

**Comment by rsteele11413** [comment]
Yeah the only device I was able to get working was the android box. I'm going to try Apple tv next.

**Comment by elkz** [comment]
I'll let you know how It goes, RaspberryPi could be one of the cheapest ways next to an Android box.

**Comment by kmungo** [comment]
@rsteele11413 You are AWESOME!!! I was not able to get the Test Connection to work until I installed MAMP and set up there. Once I did, bam. It worked!!

**Comment by Herumakilo** [comment]
Perfect, problem solved. Now for some testing.
Thanks rsteele11413

**Comment by skynetsvs** [comment]
Ive had issues as well not being able to connect my google account to the plex Tv I login to the plex
and click on google or test and fails every time and fails everytime. I will try to setup mamp is there any specific instructions for Phlex to see the folder?

**Comment by castro2kaiba** [comment]
I had the same issue relating to failure to open Phlex.log.php due to permissions. Going to the file location showed that Phlex.log.php had been created as a directory rather than a file. Replacing it with an empty file with the same name seemed to remedy my situation. I don't know if this will apply anyone else but might be helpful.
