### ISSUE TITLE
How to play to a specific device?

### ISSUE THREAD

**Issue by eliluong** [d8ahazard/Phlex#226]
On what OS are you running Phlex?
Raspbian Stretch
Are you using a new instance of XAMPP, or an existing webserver?
Using PHP & Apache
If Using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
Yes
If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
N/A
Is Phlex using http or https?
http
If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files. Paste anything that looks related as well.
**I have two Plex Media Players set up. Can I tell Phlex to play to a certain one?**

**Comment by bobpaul** [comment]
Look at the list of commands from the readme.md. Specifically:

> "Change Player"/"Change Server": "switch player", "choose player", "change player", "select player", "pick player", "swap player"

**Comment by fun4stuff** [comment]
Those commands currently don't work. At least not for me

**Comment by akang6** [comment]
I'd love to be able to tell Phlex "watch xyz on living room tv" or "watch xyz on bedroom tv". Right now it just looks for items in my library titled "xyz on living room tv" instead of knowing to play it to a specific device.

**Comment by bwguy** [comment]
I agree, I have about 10 different devices that Plex can play to but I can only seem to get it to work if I manually login to the admin screen and select device I want it to work on which defeats the object of having it connected to google home.

We need to be able to give each device a short name / friendly name such as Lounge TV, Bedroom TV, Office TV etc.  From there being able to say, play a film on Bedroom TV and then phlex will play a film on  the bedroom TV etc.

**Comment by bobpaul** [comment]
What currently works for me (rev 9aec9ff9):

"Ask phlex tv to switch player"
-"OK, I'll get phlextv!"
-"Change  player, sure. What device would you like to use? Mainscreen, Bedroom, [other devices...] ...."
"Bedroom"
-"Okay, I've switched the client to Bedroom"

**Comment by bwguy** [comment]
Yeah I can do that but it lists the exact model ID of each of the TV's.

My memory is not that good to remember which model is which lol

**Comment by d8ahazard** [comment]
Rename them in the Google home app so they have unique names?

On Jan 29, 2018 5:25 AM, "bwguy" <notifications@github.com> wrote:

Yeah I can do that but it lists the exact model ID of each of the TV's.

My memory is not that good to remember which model is which lol

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/d8ahazard/Phlex/issues/226#issuecomment-361216919>, or mute
the thread

**Comment by bwguy** [comment]
My TV's dont show up in the google home app.  I'm not using chrome cast, I'm using Plex for Samsung TV.

**Comment by d8ahazard** [comment]
You can rename cast devices using the Google Home App.  Android TV devices have this under Settings -> About -> Device Name. 

Plex app for other devices should generally have an option in it's settings to rename it - or check network settings for the TV itself. 

If this still doesn't solve your issue, submit a feature request after V2 of the app drops to specify a "friendly name" for devices. It's something I'd considered adding directly in V2, but am hoping the issue(s) will be satisfactorily resolved without needing more code in that department.
