### ISSUE TITLE
Logs in log directory are publicly readable

### ISSUE THREAD

**Issue by Thracky** [d8ahazard/Phlex#229]
Needless to say since we're exposing Phlex to the internet, we probably don't want to allow random people to download log files.

Suggested fix would be to create the log directory in the repo and add .htaccess with `deny from all`

I'm running Phlex on nginx and added the following to my config:
```
        location ~ /Phlex/logs/ {
                  deny all;
        }
```

**Comment by d8ahazard** [comment]
Fixed with d2936d7, no need to add access rules, which might be confusing for some folks...
