### ISSUE TITLE
Cannot link Phlex server/account

### ISSUE THREAD

**Issue by XmemphistoX** [d8ahazard/Phlex#23]
Hi there,

I still cannot link my account from the webui.  Previously I linked my account and was tied to a specific API Key.  However, I had to redo everything - I got a new API key and when I try to register now I get the following error message.

"ERROR: unrecognized API token!Unable to connect to Client, please check the setting for 'Public Address'."

To note - I also tried unlinking my account from the ghome app and relinking from the webui.

**Comment by d8ahazard** [comment]
Try now.  I've manually updated the DB to use your current server address and API token.  I may have accidentally caused issues while cleaning stuff up from some previous coding errors.

**Comment by XmemphistoX** [comment]
Still getting the same errors. It must be me - Let me redo xampp at some point and try this again.

**Comment by XmemphistoX** [comment]
Ok I redid xampp - It linked fine this time.  I'll test it when I get home tonight.  Thanks man!

**Comment by psykalag** [comment]
May be obvious, but be sure to add "http://" to the beginning of your public address. So it should be:

Http://YourIp:Port#/phlex

I finally got it. 

Also, if you get a successful test, but can't login, just keep trying to link your account and it will eventually connect. It's just a bit spotty

**Comment by d8ahazard** [comment]
Hmm.  I thought I had written it to be pretty agnostic when it comes to
parsing URL's.  By default, if you don't provide a protocol (http/https) in
the URL, I'll try connecting to https:// first, and then http if that
fails.

Same with ports.  If 443 or 80, you don't need to specify it, the protocol
assumes as much.

Last - you really shouldn't have to spam the server to link your account...

**Comment by psykalag** [comment]
Thanks for getting back to me so quickly and for making this thing in the
first place!

TBH, I am not the most tech savvy person, so I assumed it was user error on
my part. You may be correct that the http:// and port# level of specificity
are redundant, but changing it is what eventually got it to work for me, so
I wanted to share. Nothing worse than seeing your exact problem and then
not seeing the solution.

As for the spamming, IDK. The test showed success, but ti took about 4
tries for the actual link to work.

Looking forward to getting this up and running and blowing people's minds.

While i have you: I see you have a workaround for IFTTT, but would it work
the same on Tasker? I'm already pretty deep into tasker so I'd prefer to
use that if possible.

Thanks again. I will be donating for sure BTW bc this is fantastic.
