### ISSUE TITLE
manifest.json publicly readable

### ISSUE THREAD

**Issue by Thracky** [d8ahazard/Phlex#230]
manifest.json contains a URL with a Phlex API key. Visiting the URL contained in manifest.json gives you a bunch of output which includes full URLs for our Plex instances **including** the Plex API token. 

Since all documentation and setup involves Apache, I really suggest doing a review of what files should be accessible by anyone and everyone, and including appropriate .htaccess files where necessary.

**Comment by d8ahazard** [comment]
Fixed with d2936d7, no .htaccess configs needed.
