### ISSUE TITLE
https://phlexserver.cookiehigh.us/ times out

### ISSUE THREAD

**Issue by cbrherms** [d8ahazard/Phlex#231]
Looks like auth server is having issues again like in #159 

It's connectable only over http which causes google linking to fail as it auto trys to connect to https during the back and forth.

First thought it might be related to my nginx reverse proxy as it's my ssl endpoint but only just seen that closed issue, otherwise would have reported sooner.

**Comment by halethrain** [comment]
Yes, server is definitely having issues

**Comment by d8ahazard** [comment]
This is related to the VPS, as like #159, it's been resolved.
