### ISSUE TITLE
The word "to" in my command is being parsed to Phlex and not playing my title

### ISSUE THREAD

**Issue by charlesmkelley** [d8ahazard/Phlex#233]
For instance, if I say "Hey/OK Google, Tell Flex TV to play Batman Begins", what gets parsed to Phlex and what I see on the Web UI for Phlex is the command it got was "to play Batman Begins" and, therefore, doesn't play the title.

However. If I say "Hey/OK Google, Tell Flex TV to stop", it parses "to stop" to Phlex but, in this case, the command _is_ recognized and Phlex stops.

Any idea how to solve?

**Comment by noone942** [comment]
I've noticed it's a little more lenient when you use "ask" instead of "tell" with the word "to" also you can just say "ask flex tv play batman begins" and it will work alright. Not a real fix and it should still be looked into but a workaround for your in the meantime.

**Comment by d8ahazard** [comment]
Hello. I've updated the language parsing model to include "to play" and "to start" as synonyms for the "play" command.

Just verified that this resolves the issue when requesting "to play batman begins" in the Web GUI and assistant.
