### ISSUE TITLE
Account linking doesn't work

### ISSUE THREAD

**Issue by philastrophist** [d8ahazard/Phlex#234]
Unable to connect to Client at https://xxxxxxxx:5667, please check the setting for 'Public Address' in the Phlex UI.

I'm using HTTPS on raspberry pi (your dockerfile template but built upon armhf instead - see my fork)

I am using the UI through the above address with no problems, so why isn't this working?

command = `docker run -d  --privileged --name=Phlex --net=host -P -v phlex_data:/config phlex:latest tail -f /dev/null`

`error.log` is blank

edited: the `error.log` was left over from a previous install. I did a fresh install and it is now empty

**Comment by philastrophist** [comment]
Update: My `config.ini.php` file contains:
````
'; <?php die('Access denied'); ?>
[general]
deviceID = "ef270c826b0a79a056b3f3c1"
revision = "ba329ea609147fb2513705035e888baf6d0b7d4a"

[user-_-USER]
plexUserName = "USER"
plexToken = "PLEXTOKEN"
plexEmail = "EMAIL"
plexAvatar = "https://192.168.0.34:5667//img/cache/c219b1584612e88c35f055bdae79a9ca.png"
plexCred = "PLEXCRED"
apiToken = "APITOKEN"
publicAddress = "https://192.168.0.34:5667/"
dlist = "SEEMSSECRET"
```

Should it have that line at the top and why is my public address not changed?

**Comment by bobpaul** [comment]
The URL in publicAddress needs to be accessible from the internet. 192.168.0.34 is a non-routable address from your local network. Setup port forwarding on your router and change the publicAddress URL to your external address/port.

**Comment by philastrophist** [comment]
That is what I have done, the public address displayed in the UI is the external one. 
I’ve even tried changing it directly in config.php.ini
I’ve also setup port forwarding making it accessible for outside as I said above. 
It still doesn’t work

**Comment by bobpaul** [comment]
Do other settings change in the config.php.ini properly? Perhaps file permissions are wrong. Your http server needs write permission to config.php.ini

**Comment by philastrophist** [comment]
I've done a chmod 777 and the result is the same. Also, I've noticed that my plex server doesn't appear under the plex tab

**Comment by d8ahazard** [comment]
I've updated the docker image to change permissions, and additional logging for account linking, as well as fixing some issues server-side.  This should be fixed.

If you still have issues writing to config.ini.php, please create a new issue.
