### ISSUE TITLE
Issue Playing Video using "From" specific Time

### ISSUE THREAD

**Issue by noone942** [d8ahazard/Phlex#236]
When I say "play batman begins from 1 hour" to my Google Home, it plays batman begins and says the correct time in return to me but when it tries to start playing the video appears to be trying to start from like 300+ hours and it loads then immediately stops since it's past the end of the run time for the video.

I will grab the logs and attach them here and look in the code to see if I can find the problem as well.

**Comment by noone942** [comment]
I found the issue and it is that the offset is being multiplied by 1000. From what I can tell it may be coming from the api.php file. I can't find where in the code it is doing it at the moment and it seems like it may also be slightly related to the volume issue being incorrectly set as well.

**Comment by noone942** [comment]
Yup the problem was that in the api.php file, when the $mod was being added to the $offset it was being multiplied by 1000 when it didn't need to be. I removed that and the problem was fixed. If you update this to your code then that will be fixed.

**Comment by d8ahazard** [comment]
FIXED with 2f33bd2.
