### ISSUE TITLE
Playing Specific Episodes doesn't always work

### ISSUE THREAD

**Issue by bobpaul** [d8ahazard/Phlex#237]
I'm able to play specific episodes of the Simpsons and Futurama using a command like "play Season 3 Episode 4 of Futurism". But I can't do the same for 30 Rock.

I can use episode titles, like "Blind Date" and it starts playing. But if I ask for it by season/episode number, it fails as:

```
You said: "to play season 1 episode 3 of 30 Rock."
My reply:  "I didn't find anything named ' season 1 episode 3 30 rock' to play. Should I try to fetch it for you?
```

**Comment by d8ahazard** [comment]
This is more to do with how Google/API.AI detects your inputs as media titles, and not so much how Phlex searches.  You can verify this by searching for "30 rock" in the *PLEX* web UI.  Whatever you get there is what Phlex will find for any search.

**Comment by bobpaul** [comment]
I don't understand how to verify as you suggest. When I search "30 rock" in the PLEX web ui it shows exactly 1 result and indicates it has 8 seasons. I can click the series thumbnail, choose the season 1 thumnail, and then it shows Episode 3 is titled "Blind Date"

```You said: "Play season 1 episode 3 of Futurama."
My reply:  "Yes master, Playing  I, Roommate.```

but

```You said: "Play season 1 episode 3 of 30 Rock."
My reply:  "I didn't find anything named ' season 1 episode 3 30 rock' to play. Should I try to fetch it for you?'```

It seems whatever recognizes the word "of" and separates "30 rock" from "season 1 episode 3" isn't doing the right thing in all cases.
