### ISSUE TITLE
try to play a plex playlist

### ISSUE THREAD

**Issue by fopsdev** [d8ahazard/Phlex#238]
hi
i've created a plex music playlist. now whats the voice command to play it?

**Comment by beast2252** [comment]
I'm also curious about this. I've tried a number of different ways of phrasing it, but none seem to work. Is this something that is currently supported?

**Comment by d8ahazard** [comment]
That's a good one. It doesn't currently, but I'll create some playlists and
get it added.  :D

**Comment by d8ahazard** [comment]
Added with dac8cec.

**Comment by fopsdev** [comment]
ok thanks for working on this one. what's the voice command then?

**Comment by mattpurnell** [comment]
It is great that it's been added, but how do we invoke it?

Here are some attempts this morning:


You said: "Play music playlist alternative."
My reply: "Unfortunately, I couldn't find 'alternative' in the library. Should I try to fetch it for you?"

You said: "Play music alternative playlist."
My reply: "I couldn't find anything called 'music alternative' in your libraries. Shall I search for it in your fetchers?"

You said: "Play the rock playlist."
My reply: "I'm sorry, but I didn't find any results for 'rock'. Should I try to fetch it for you?"

You said: "Play music playlist chilled."
My reply: "Unfortunately, I couldn't find 'chilled' in the library. Would you like me to add it to your watch lists?"

You said: "Play music genre chilled."
My reply: "I'm sorry, but I didn't find any results for 'genre chilled'."

You said: "Play playlist rock."
My reply: "Unfortunately, I couldn't find 'rock' in the library. Shall I search for it in your fetchers?"

You said: "Play playlist."
My reply: "I couldn't find anything called 'that request' in your libraries. Would you like me to add it to your watch lists?"

You said: "Play playlist Chilled."
My reply: "Unfortunately, I couldn't find 'Chilled' in the library. Should I try to fetch it for you?"

You said: "Play playlist chilled."
My reply: "I`m sorry, but I didn`t find any results for `chilled`. Should I try to fetch it for you?"

You said: "Play chill playlist."
My reply: "I`m sorry, but I didn`t find any results for `chill`. Should I try to fetch it for you?"

You said: "Play chilled genre."
My reply: "Unfortunately, I couldn`t find `chilled genre` in the library."
