### ISSUE TITLE
Request: Subtitles

### ISSUE THREAD

**Issue by dracos1985** [d8ahazard/Phlex#24]
Voice command to turn subtitles both on and off.

**Comment by d8ahazard** [comment]
Added with commit dd74b918ac25fce4ae73b0940525355ddcc5b738 

Probably doesn't work for Chromecast devices, only selects Subs with the "eng" tag.  Will need separate parser for IFTTT commands as well.  BUT...for Ghome users with normal plex players who want English subs...it should work.  :P

**Comment by d8ahazard** [comment]
TODO: Use the special mod for the web UI to log if there's a way to enable subtitles remotely on cast devices, otherwise close this.

**Comment by d8ahazard** [comment]
After researching further, I've determined it's not possible to enable subtitles while casting media on-the-fly.  As such, closing.
