### ISSUE TITLE
Language selection not working

### ISSUE THREAD

**Issue by The1Authority** [d8ahazard/Phlex#241]
When I select another language in the setting it's not changing the language. Phlex stay in english and the selected language is not german.

Here are some log data 
[DEBUG] [api.php::initialize] - VAR CHANGE: appLanguage =
[DEBUG] [util.php::saveConfig] - Config saved successfully by api.php::initialize
[INFO] [util.php::getDefaultLocale] - No saved locale set, detecting from system.
[INFO] [util.php::getDefaultLocale] - Locale set from default:
[WARN] [util.php::getDefaultLocale] - Couldn't detect a default or saved locale, defaulting to English.

**Comment by d8ahazard** [comment]
Fixed with 0360fd3.
