### ISSUE TITLE
Skip ahead

### ISSUE THREAD

**Issue by leadingbump** [d8ahazard/Phlex#242]
I try to use the command skip ahead and all the other variations in the read me file but it doesn't work. Looking at the json file on the main phlex Gui it says 

{
  "initialCommand": "Skip forward",
  "parsedCommand": "skip forward",
  "playResult": {
    "url": "No URL",
    "status": "success"
  },
  "mediaStatus": "SUCCESS: Not a media command",
  "commandType": "control",
  "clientURI": "blahblah",
  "clientName": "",
  "serverURI": "blahblah",
  "serverToken": "blahblah",
  "timestamp": "Thu, 07 Dec 2017 04:00:45 -0700",
  "speech": "Consider it done.",
  "timecode": 1512644445
}

Nothing happens. Play and pause Controls work fine.

**Comment by d8ahazard** [comment]
On what kind of device?
I just tried it on my version, and it works as expected?

**Comment by bwguy** [comment]
When I use skip forward or back, it actually stops / cancels what I'm watching.  This is for my Samsung TV. 
{
  "initialCommand": "skip back",
  "parsedCommand": "skip backward",
  "playResult": {
    "url": "http://192.168.1.3:32400/player/playback/skipPrevious?X-Plex-Token=YHvrp3w98SFhxt7fWZpp&commandID=28",
    "status": "success"
  },
  "mediaStatus": "SUCCESS: Not a media command",
  "commandType": "control",
  "clientURI": "http://192.168.1.3:32400",
  "clientName": "",
  "serverURI": "http://192.168.1.3:32400",
  "serverToken": "YHvrp3w98SFhxt7fWZpp",
  "timestamp": "Fri, 22 Dec 2017 07:10:38 +0800",
  "speech": "Okay.",
  "timecode": 1513897838
