### ISSUE TITLE
cannot set public ip

### ISSUE THREAD

**Issue by joebase** [d8ahazard/Phlex#243]
![image](https://user-images.githubusercontent.com/13510237/33734467-194b12ca-db95-11e7-8adf-f4483acd67a7.png)

**Comment by joebase** [comment]
try all port but ist not working

**Comment by abrenoch** [comment]
You port is not forwarded on your firewall correctly - I know because I just tried it :wink:

You may want to remove that image or obfuscate your IP

**Comment by d8ahazard** [comment]
@joebase - What @abrenoch said.  Give this a read:

https://www.pcworld.com/article/244314/how_to_forward_ports_on_your_router.html
