### ISSUE TITLE
Playback Server

### ISSUE THREAD

**Issue by Imburr** [d8ahazard/Phlex#247]
My Plex runs on FreeNAS and is presented on my local LAN. I also share this out directly via the internet, and integrate with plex.tv. Inside of my account, I have two servers- mine and a buddies. I got Phlex up and running fine, but for playback servers it only lists my friends server. Is there a trick to allow mine to show up?

Also, I do not play media directly on Plex, but rather in the Plex app on my Roku Premier. Roku is integrated through Harmony with Google Assistant, but it does not allow for easy fine grained control, and certainly not search.

Any tips?

**Comment by d8ahazard** [comment]
Kick of a device scan via the GUI -> Client list, and then note in the logs if it reports a connection error for a particular device...

Basically, "Checking URL for device living room tv"....

Then the following line should report status.  I'm curious if it's failing to check your Server's IP, and if so, what IP/format it's using.

For Roku, you should be able to control the Plex app on it, provided the Plex app is running on your Roku and connected to the same playback server as Phlex is pointed at.

So, I'd expect that once we get your server to detect, you should be good to go.

**Comment by MethodDan** [comment]
I'm experiencing exactly the same issue as @Imburr with a new Phlex install at home. It only sees a remote server my friend runs and not the server on my LAN which works fine with all other clients on the network, Smart TV, Android apps, PS4 etc.

Both my Plex server and new Phlex install are Ubuntu Server 16.04 virtual machines running via KVM on a home server. I've logged into both via SSH and they can ping each other, the also do NSLOOKUP of each other perfectly showing the correct local IP addresses. So they can talk fine over the network it's really weird.

It's probably some weird networking thing, I'll do some testing and report back with logs etc. Anything specific that would help you diagnose?

Thanks for all your work on this project, I appreciate it! :)

**Comment by MethodDan** [comment]
It seems to be an authentication issue in my case, still haven't fixed it but getting closer maybe.

I did what you advised and did "rescan for devices" via the Phlex web UI. To my joy it saw my local Plex server this time. I set the playback server to betterthanlife (my local server) and looking at the logs it's giving 401 unauthorised errors whenever it tries to check the URL on that server.

From my Plex server log I found this:

> Dec 15, 2017 21:09:25.171 [0x7f38cc7ff700] DEBUG - Auth: authenticating user as guest
> Dec 15, 2017 21:09:25.172 [0x7f38cc7ff700] DEBUG - Request: [192.168.1.46:34008 (Subnet)] GET /library/sections (8 live) Signed-in Token ()
> Dec 15, 2017 21:09:25.172 [0x7f38cc7ff700] DEBUG - Completed: [192.168.1.46:34008] 401 GET /library/sections (8 live) 0ms 249 bytes

192.168.1.46 is the local IP of my Phlex install. So it's being refused connection because of an invalid token or login issue. Any idea how I could fix this?

Thanks

**Comment by zackbcom** [comment]
Getting this:
Connection failed with error code 0: https://192-168-2-3.<code>.plex.direct:32400?X-Plex-Token=
I change my local IP to my public IP and tested it in the browser and got back a valid response.

**Comment by zackbcom** [comment]
From what it seems, There is an issue with using the correct token on the correct server.
There is an instance when it's using the Token from server1 on server2 query.
[ERROR] [util.php::doRequest] - An exception occurred: Client error: `GET http://**server1LocalIP**:32400/clients?X-Plex-Token=**server2Token**` resulted in a `401 Unauthorized` response:

**Comment by MethodDan** [comment]
This is what's happening with my error I'm sure. It's trying to use the token from server 1 to request things from server 2 so it's always going to come back unauthorised.

**Comment by zackbcom** [comment]
I seem to have finally pinpointed the issue that has been plaguing my multi server setup. I have a pull request for the fix. #273

**Comment by MethodDan** [comment]
Thanks for your hard work on this, l appreciate it! Will update my server and test it :)

**Comment by Jon87** [comment]
Just installed today from github and getting the same error;

Connection failed with error code 0: https://192-168-0-101.f187d4aef00e4d73a99b5c43ef9667a0.plex.direct:32400?X-Plex-Token=xxxxxxxxx

**Comment by edmonddc** [comment]
Got mine to work. On the settings, go to the Plex tab and enable "No HTTPS/Relay". 

Hope this helps.

**Comment by Imburr** [comment]
That allowed Phlex to see my server, but I still cannot connect.

Wed, 03 Jan 2018 17:56:33 +0100util.php::curlGet

Unexpected HTTP code: 401, URL: http://192.168.2.154:32400?X-Plex-Token=xxxx

Wed, 03 Jan 2018 17:56:33 +0100util.php::curlGet

Unexpected HTTP code: 401, URL: http://192.168.2.154:32400/library/sections?X-Plex-Token=xxxx

**Comment by edmonddc** [comment]
Was your phlex server updated to the latest (9aec9ff)?

**Comment by Imburr** [comment]
I just reinstalled from scratch using Zip:

Wed, 03 Jan 2018 19:02:20 +0100util.php::curlGet
Unexpected HTTP code: 401, URL: http://192.168.2.154:32400?X-Plex-Token=xxxx

Wed, 03 Jan 2018 19:02:20 +0100api.php::testConnection
URL is: http://192.XXX.X.XXX:32400?X-Plex-Token=XXXXXXXXXXXXXXXXXXXX

**Comment by MethodDan** [comment]
Just thought I should report back, after enabling "no HTTPS/Relay" Phlex is able to find my local server and it plays stuff to a Chromecast on the TV. I think the patch from @zackbcom fixed it, it changes the server auth token properly now. Thank you man!!

Sorry to those still trying to get it working. It definitely needed to be on the latest version for me. Best of luck to everyone!

**Comment by pghattas** [comment]
I am having the same issue as @Imburr. I have phlex running as docker version 9aec9ff.  I have two rokus and two chromecasts.  It will see my roku if something is playing but not if it is idle (plex web player sees both all the time) and never finds my chromecast.  So the roku it does see I have selected and I use google assistant or just type in the command (play a movie) and get util.php:curlGet 401 error.  I have both Use Cast devices and no HTTPS/relay enabled.

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
