### ISSUE TITLE
can not link google email with Phlex..

### ISSUE THREAD

**Issue by skynetsvs** [d8ahazard/Phlex#249]
Hi,

I have spent many hours trying to resolve why I can not check the public link
for phlex. I have checked the web host and I can see the PC running phlex and the port and 
actually access from outside but when I go to link it it keeps failing..

driving we nuts what am I missing I ask google home..... ok google talk to phlex tv..
and it says its not connected to your account.  please help anyone
Ive prent many late nights........

**Comment by Herumakilo** [comment]
Hi all,

I am having the same issue.
I can browse to the machine from outside of the network. When I try to link my google account I get the following:
http://my.domain/Phlex/, please check the setting for 'Public Address' in the Phlex UI.

If I click on http://my.domain/Phlex/ it opens the Phlex webpage...
Any suggestions?

Heru

**Comment by skynetsvs** [comment]
Same thing I can’t help hoping someone else shed some light

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fun4stuff** [comment]
It's a bug in the software. There are a lot of recent issues posted all dealing with problems linking or staying linked with Google.

**Comment by skynetsvs** [comment]
Why does it work for others and not us.....was thinking it’s my internet provider or modem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Herumakilo** [comment]
It won't be either of those, skynetsvs. Your modem's firewall is the only thing that could cause an issue, so assuming you've set the port forward as per  the instructions, it shouldn't affect it.

**Comment by skynetsvs** [comment]
Yes well i can see an index file i put in there in that folder opens up as a html but won't link my Google account drives me nuts

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Herumakilo** [comment]
I don't know if it's related, but I also get the following error:
Notice: Undefined variable: _SESSION in C:\xampp\htdocs\Phlex\util.php on line 365

**Comment by fun4stuff** [comment]
I don't think it is working for anyone else... Not reliably. I've had a few friends who are all having the same issues....can't link with Google (at least not without it crashing after a few hours) and it cannot find cast devices (other than Plex in a web browser) without manually typing it in....doesn't report new recently downloaded content.

**Comment by d8ahazard** [comment]
I'm curious, can you not what your API Token is, link, do ...whatever it is
that seems to make it break... and then note your API Token again?  Account
linking is *really* just tied to storing that in a DB alongside your google
account ID, so if the APIToken is breaking/resetting for some reason, that
would explain it.

**Comment by fun4stuff** [comment]
So, I was able to get it linked to google successfully after reinstalling. Tested connectivity was successful./ Noted by API token. Didn't really do anything... after about 15 mins I tried testing connectivity and it said failed. Looked at my API token and it's different!

**Comment by d8ahazard** [comment]
What platform are installed on? Are you on hangouts? I've been looking at
the logs, saw you trying to register, shot you a message there if you want
a little help trying to diagnose this.

**Comment by skynetsvs** [comment]
Can some explain how and what to do with the token? Maybe that’s why mine won’t connect

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fun4stuff** [comment]
I believe, the token is supposed to be generated 1 time automatically when you first log on and link with google. For some reason, I'm getting an error where it results in me generating a new API token ever so often which then requires me to re-link with google to get it to continue to work.

**Comment by d8ahazard** [comment]
This should be fixed with e412429 and some server side fixes.  As there are several different issues with this same thread, I'll be trying to combine them into one.

**Comment by skynetsvs** [comment]
Im sorry how do I ad the token in the first place or is this not really required?


John Cecotti
Owner\Director
zarmma.com
MB:0419-358-864


________________________________

**Comment by skynetsvs** [comment]
Is there any explanation anywhere that shows you how to install the token and get it all working?
and this might sound silly... to install Phlex to work with google home is there a good step by step instruction that will work if followed correctly? Ive been going by a youtube clip thats not listed anymore. I have a gmail account trying to link to phlex on a PC at home on my network. any help would be really apreciated. thank you

**Comment by d8ahazard** [comment]
Check out the readme on github, that should have instructions.

There's no token to install, it's auto-generated, and issues with it should
be fixed in the latest version.

**Comment by Herumakilo** [comment]
Hi,
Just extracted the latest .zip and now no longer get a login page.
Any suggestions?
Thanks

**Comment by Herumakilo** [comment]
I should clarify, I do see the /index, but no login 'pop up'

**Comment by skynetsvs** [comment]
What am I doing wrong I can see a website from outside to sample
But can not link my google account to Plex tv what and I doing wrong

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by skynetsvs** [comment]
I can host a website from my Plex media pc running xampp  but can’t link my google home to my gmail account I say ok google talk to my flex tv and and tells we I’m not connected I’ve tried everything ANYBODY WHAT IS WRONG OR IS THIS ACTUALLY NEVER GOING TO WORK

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
