### ISSUE TITLE
Linked wrong google account

### ISSUE THREAD

**Issue by nickmodernized** [d8ahazard/Phlex#25]
I feel like an idiot, but in all my excitement to test this out, I linked my work Google account instead of my personal Google account...where all of my devices actually live.  If I'm reading the code right, everything gets stored in the root config.ini.php, but it looks like all the stuff I would need to change is on the server and when I click the link to relink I get the success URL.

How can I best resolve the issue?  I'm not seeing an obvious way I can resubmit or relink an account or a different Google account.

If I can figure this out, I might be able to help out here and there from testing and development.

Thanks!  KILLER APP!

**Comment by d8ahazard** [comment]
I've deleted the records for your email address in the database, go ahead and relink through the app UI, then through the ghome app.  ;)
