### ISSUE TITLE
Request: Sonarr/ Radarr Notification 

### ISSUE THREAD

**Issue by galacticwarzone** [d8ahazard/Phlex#250]
I was thinking it would be neat if Phlex could notify you when it fetches/completes a movie/ tv show

ie: "The movie Dunkirk was grabbed". 

and

"The movie Dunkirk has finished downloading. It is now added to your library."

Would this be possible through IFTTT?

**Comment by d8ahazard** [comment]
Possible, and implemented with 875aad7.  Will update readme as time allows, basically, just click the white "copy" button in settings->fetchers and then paste it into the webhook URL field for radarr/sonarr/couchpotato.

Must have a static cast device defined.
