### ISSUE TITLE
Post Install Errors

### ISSUE THREAD

**Issue by Vyvbast** [d8ahazard/Phlex#251]
Sorry if this has been discussed. I'm getting the following errors:

Warning: file_put_contents(config.ini.php): failed to open stream: Permission denied in /opt/lampp/htdocs/Phlex/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 270
Exception Message: failed to write file `config.ini.php' for writing.
Warning: fopen(/opt/lampp/htdocs/Phlex/config.ini.php): failed to open stream: Permission denied in /opt/lampp/htdocs/Phlex/util.php on line 499

Warning: file_put_contents(/opt/lampp/htdocs/Phlex/config.ini.php): failed to open stream: Permission denied in /opt/lampp/htdocs/Phlex/util.php on line 501

Warning: session_start(): open(/opt/lampp/temp//sess_a5da16ff2b95f6f4f6a1bd16545e5f70, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/Phlex/index.php on line 16

Warning: session_start(): Failed to read session data: files (path: /opt/lampp/temp/) in /opt/lampp/htdocs/Phlex/index.php on line 16
Welcome to Phlex!

My questions would be:
1. where is the config.ini.php file? 
2. Permissions have been set correctly for location /opt/lampp....... why would I still get permission denied?

**Comment by d8ahazard** [comment]
The config file should be created at the root of the Phlex installation
directory. You need to set permissions to that directory for whatever
service your web server is running as to have write permissions.
