### ISSUE TITLE
Can't specify version of movie

### ISSUE THREAD

**Issue by philmillerinspace** [d8ahazard/Phlex#254]
If I say something like "Ask Flex TV to download the Mummy". It downloads the 2017 version. I can't say "Ask flex tv to download the Mummy 1999". Is there a command or way to specify the year of a film to ensure the correct one is making the REST API call to Radarr?

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
