### ISSUE TITLE
Needs support for Plex for LG

### ISSUE THREAD

**Issue by rsteele11413** [d8ahazard/Phlex#257]
I finally got everything working, however, it will not play anything on the Plex For LG tv  player. If there is any way to add support for it I would appreciate it.

**Comment by bobpaul** [comment]
I have the same problem, but with Plex for Vizio. I open the Plex app on my TV and very quickly my plex server can see it and I can make the same API call used by api.php's scanDevices() to verify the plex for vizio player is seen.

```
$ curl 'http://192.168.1.10:32400/clients?X-Plex-Token=[TOKEN]' | grep -i vizio 
<Server name="" host="127.0.0.1" address="127.0.0.1" port="32400" machineIdentifier="ccn947go8blalgilac4tk5rq" version="3.13.7" protocol="plex" product="Plex for Vizio" deviceClass="pc" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,mirror,playqueues" />
<Server name="" host="192.168.1.10" address="192.168.2.250" port="32400" machineIdentifier="ccn947go8blalgilac4tk5rq" version="3.13.7" protocol="plex" product="Plex for Vizio" deviceClass="pc" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,mirror,playqueues" />
```

I did notice that if I use the `plex.tv/api` URLs, then it shows the Vizio even when my TV is off , whereas the local url only shows the Vizio after I turn on the TV and switch to the Plex app.

```
$ curl 'https://plex.tv/api/resources?includeHttps=1&includeRelay=0&X-Plex-Token=[TOKEN]'|grep vizio -i
  <Device name="Plex for Vizio (Vizio MTK)" product="Plex for Vizio" productVersion="3.13.7" platform="Vizio Presto" platformVersion="0" device="Vizio (Vizio MTK)" clientIdentifier="ccn947go8blalgilac4tk5rq" createdAt="1491086019" lastSeenAt="1513457857" provides="client,player" owned="1" publicAddress="[MYIP]" publicAddressMatches="1" presence="0" accessToken="[TOKEN]">

**Comment by matrottier** [comment]
i have a LG (model LF5950) and it's working. I pushed some movie on my TV from the web interface of phlex.
(google home not tested again)
what is your TV model ?

**Comment by bobpaul** [comment]
@matrottier what revision of phlex are you using? I don't remember what rev I was on during the test, but I'm currently on a way old rev that I found to be more stable.

**Comment by d8ahazard** [comment]
@bobpaul @rsteele11413 @matrottier - Send an email to donate.to.digitalhigh@gmail.com with contact info - hangouts preferred. I'd like to add you as beta testers for the web version, specifically so I can make sure playback works for your devices with the new cast plugin.

Closing this for dev sanity.
