### ISSUE TITLE
Request: On unpause, delay and don't verbally respond.

### ISSUE THREAD

**Issue by bobpaul** [d8ahazard/Phlex#258]
When you give the command "Ask Phlextv to play" playback immediately resumes, and then the Google home says "OK, I'll ask Phlex TV". Then Phlex says "Sure thing". Meanwhile the movie is playing and you just missed 8 seconds of dialog.

I don't think there's anything that can be done about Google's reply. But I think you can make Phlex not respond. And you could add a delay so that it flows more like: "Hey google, ask phlextv to play". "Ok, I'll ask phlex tv". [Movie resumes playing]

**Comment by d8ahazard** [comment]
Good one. I don't think I can return an empty reply with Assistant, but I'll make sure to make the reply a one-word "OK".

Alternatively, IFTTT can be set up to do this without a reply. ;)

**Comment by d8ahazard** [comment]
Closed, added the "Use short replies" checkbox.
