### ISSUE TITLE
Provide 'casting' support for plex set top devices.

### ISSUE THREAD

**Issue by tit1** [d8ahazard/Phlex#259]
I have an OpenPHT and a Rasplex device and it would be nice to allow playback on these devices. They appear as a castable device within the plex web interface and i have found them more reliable in video and audio decoding then the chrome casts.

I'd be happy to do some research and see how they may be accessed visa the Plex Api.

**Comment by d8ahazard** [comment]
Send an email to donate.to.digitalhigh@gmail.com with contact info (hangouts preferred). I'd like to have you test with the web-only version. This is probably already addressed in V2 with the new cast plugin.
