### ISSUE TITLE
Sickrage downloading issue

### ISSUE THREAD

**Issue by Sandermand** [d8ahazard/Phlex#26]
Got this up and running nice and smooth but i have an issue with Sickrage. I am not able to download any tv shows, even after linking up and inputting API key and everything. Couch potato can add movies to my "Wanted" list just fine.

I tried via IFTTT:

Initial command: "game thrones season 6"
Parsed command: "Fetch Season 6 of the show named "
Search status: Show not found

Initial command: "season 1 humans"
Parsed command: "Fetch Season 1 of the show named "
Search status: Show not found

And i tried several variations of "Ask Flex Tv...":

Initial command: "latest episode humans"
Parsed command: "Fetch the first movie or show named latest episode humans"
Search status: no results

Initial command: "ask Flex TV to download the TV show Game of Thrones season 6"
Parsed command: "Fetch the media named ."
Search status: Nothing found to fetch.
Speech Response: Unfortunately, I was not able to find anything with that title to download.

When i pull the log from trying to find "episode 2 of season 6 of game of thrones", this is what i get. I get a response from the search and a 100 percent match on the title, but the search container comes back with "Show not found":

/Fri, 21 Apr 2017 14:53:20 -0500: api.php::parseApiCommand: Function fired.
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::parseApiCommand: Full request text is {"originalRequest":{"source":"google","data":{"surface":{"capabilities":[{"name":"actions.capability.AUDIO_OUTPUT"}]},"inputs":[{"arguments":[{"raw_text":"download","text_value":"fetch","name":"action"},{"raw_text":"season 6 episode 2 of Game of Thrones","text_value":"season 6 episode 2 of Game of Thrones","name":"command"},{"raw_text":"download season 6 episode 2 of Game of Thrones","text_value":"download season 6 episode 2 of Game of Thrones","name":"trigger_query"}],"intent":"assistant.intent.action.MAIN","raw_inputs":[{"query":"ask Flex TV to download season 6 episode 2 of Game of Thrones","input_type":2}]}],"user":{"access_token":"467f458260d16a69531da90aaaad0283fc107c9387","user_id":"P8OxeVu6ZlOttvsoefO2tH4m9KbG+SzQrtCiiD5EHCo="},"conversation":{"conversation_id":"1492804398375","type":1}}},"id":"aa1f3583-3b8b-460a-a500-b723348ebf7c","timestamp":"2017-04-21T19:53:18.835Z","lang":"en","result":{"source":"agent","resolvedQuery":"download season 6 episode 2 of Game of Thrones","action":"Playmedia","parameters":{"action":"fetch","command":"season 6 episode 2 of Game of Thrones"},"contexts":[{"name":"promptfortitle","parameters":{"command.original":"season 6 episode 2 of Game of Thrones","action.original":"download","action":"fetch","command":"season 6 episode 2 of Game of Thrones"},"lifespan":3},{"name":"waitforplayer","parameters":{"command.original":"season 6 episode 2 of Game of Thrones","action.original":"download","action":"fetch","command":"season 6 episode 2 of Game of Thrones"},"lifespan":3},{"name":"google_assistant_welcome","parameters":{"command.original":"season 6 episode 2 of Game of Thrones","action.original":"download","action":"fetch","command":"season 6 episode 2 of Game of Thrones"}},{"name":"yes","parameters":{"command.original":"season 6 episode 2 of Game of Thrones","action.original":"download","action":"fetch","command":"season 6 episode 2 of Game of Thrones"},"lifespan":3},{"name":"actions_capability_audio_output","parameters":{"command.original":"season 6 episode 2 of Game of Thrones","action.original":"download","action":"fetch","command":"season 6 episode 2 of Game of Thrones"}}],"metadata":{"intentId":"b8151275-afad-4f3f-bd9a-3a17f390cb75","webhookUsed":"true","webhookForSlotFillingUsed":"false","intentName":"PlayMedia"},"fulfillment":{"messages":[[]]},"score":1},"status":{"code":200,"errorType":"success"},"sessionId":"1492804398375"}
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::parseApiCommand: Raw speech is ask Flex TV to download season 6 episode 2 of Game of Thrones
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::parseApiCommand: Final params should be an action of fetch, a command of season 6 episode 2 game thrones, and a control of 
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::parseFetchCommand: Function Fired.
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::parseFetchCommand: Found the word season.
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::parseFetchCommand: Found the word episode.
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::parseFetchCommand: Searching explicitely for a show.
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::downloadSeries: Using Sick for Episode agent
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: Function fired
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: {"data": {"langid": 7, "results": [{"first_aired": "2011-05-07", "indexer": 1, "name": "Game of Thrones: Cartoon Parody", "tvdbid": 311939}, {"first_aired": "2016-10-18", "indexer": 1, "name": "Hip Hop Tribe 2: Game of Thrones", "tvdbid": 320829}, {"first_aired": "2011-04-17", "indexer": 1, "name": "Game of Thrones", "tvdbid": 121361}]}, "message": "", "result": "success"}
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: Similarity between results is 44
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: This is the highest matched result so far.
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: Similarity between results is 43
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: Similarity between results is 100
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: **This is an exact match.**
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: Got response for search: Game of Thrones
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: Check contains {"data": {}, "message": "Show not found", "result": "failure"}
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: Check result is 
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: And an episode. 2
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: Episode search worked, result is {"data": {}, "message": "Show not found", "result": "failure"}
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::sickDownload: Art should be findable at http://192.168.1.199:8083/api/1c658a5c58708ce3cd5e83c6a6c35c9f/?cmd=show.getbanner&tvdbid=121361
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::parseFetchCommand: Result {"status":"**Show not found**","mediaResult":{"@attributes":{"data":[],"message":"Show not found","result":"failure","art":"http:\/\/192.168.1.199:8083\/api\/1c658a5c58708ce3cd5e83c6a6c35c9f\/?cmd=show.getbanner&tvdbid=121361","type":"show"}}}
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::returnSpeech: Final Speech should be: Unfortunately, I was not able to find anything with that title to download.
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::returnSpeech: Expect response is 
I/Fri, 21 Apr 2017 14:53:20 -0500: api.php::returnSpeech: JSON out is {"speech":"Unfortunately, I was not able to find anything with that title to download.","contextOut":[{"name":"yes","lifespan":2},{"name":"yes","lifespan":2},{"name":"promptfortitle","lifespan":0}],"data":{"google":{"expect_user_response":false}},"displayText":"Unfortunately, I was not able to find anything with that title to download.","source":"whatever.php"}

**Comment by muyiwao221** [comment]
I am having this issue using IFTTT with sonarr. I get an ERROR: No Results Found  for just about every TV show I try to search. Any idea whats up?

**Comment by muyiwao221** [comment]
Movies, however work just fine. The only issue is when I ask it to download a movie (again through IFTTT) it downloads it, but it doesn't show up on the UI. Literally nothing shows up - however when I check my download client, it is in fact downloading. Sorry I keep bombarding you with issues im setting everything up today. Should I just wait till Phlex is back on the Google app store?

**Comment by Sandermand** [comment]
This has actually started working. Partially anyway. I can now download series, but not individual episodes.

**Comment by muyiwao221** [comment]
^ actually same

**Comment by d8ahazard** [comment]
Done and done.  Triple tested.  Asking to download "latest/newest/last season" is not implemented currently.
