### ISSUE TITLE
Recent updates seem to have broken play back of audio tracks

### ISSUE THREAD

**Issue by TonyFrend** [d8ahazard/Phlex#261]
I think something broke re: playing an audio track with a recent update (build 875aad7 - still present in build 6efb445).

The UI card indicates that the requested audio track is playing OK and the JSON listing seems fine (reporting the correct track and the selected cast device) but the audio track is not on fact played on the selected device (no sound).

Also, the animated 'progress' pane that usually appears at the bottom of the screen no longer appears.

I have also noticed that when Phlex is trying to play my audio track the CPU load on my NAS ramps up to 80 to 90% (usually the load is < 10% when playing audio). I can also cast my audio tracks OK direct from Plex to my chromecast devices (where the CPU load is also < 10%). This suggests that Phlex is 'causing' this excessive CPU load.

[Phlex.log.txt](https://github.com/d8ahazard/Phlex/files/1568270/Phlex.log.txt)

Truncated log file attached.

Otherwise great update :)

Edit: 20 Dec 2017 More recent updates have fixed this issue

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
