### ISSUE TITLE
Devices list not using correct names

### ISSUE THREAD

**Issue by Antimus** [d8ahazard/Phlex#262]
I have an Android TV that has been renamed from "Bravia 4K GB" to "Living Room TV"

All other devices that can cast see the TV with it's new name, apart from Phlex which uses the old one.

1. On what OS are you running Phlex?
Microsoft Windows 2012 R2 Standard
2. Are you using a new instance of XAMPP, or an existing webserver?
New instance of XAMPP
3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes
4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files. Paste anything that looks related as well.
api.php::scanDevices
Final device array:

{
  "servers": [
    {
      "name": "Plex Server",
      "id": "xxx",
      "token": "xxx",
      "product": "Plex Media Server",
      "httpsRequired": false,
      "publicAddress": "http://xxx",
      "owned": true,
      "platform": "Windows",
      "publicAddressMatches": true,
      "connections": [
        {
          "protocol": "http",
          "address": "192.168.0.200",
          "port": "32400",
          "uri": "http://192.168.0.200:32400",
          "local": "1"
        },
        {
          "protocol": "http",
          "address": "xxx",
          "port": "32400",
          "uri": "http://xxx",
          "local": "0"
        }
      ],
      "uri": "http://192.168.0.200:32400",
      "publicUri": "http://192.168.0.200:32400"
    }
  ],
  "clients": [
    {
      "name": "BRAVIA 4K GB",
      "id": "d646fbbc43351428-com-plexapp-android",
      "token": "xxx",
      "product": "Plex for Android",
      "httpsRequired": false,
      "publicAddress": "xxx",
      "owned": true,
      "platform": "Android",
      "publicAddressMatches": true,
      "connections": [
        {
          "protocol": "http",
          "address": "192.168.0.21",
          "port": "45756",
          "uri": "http://192.168.0.21:45756",
          "local": "1"
        }
      ],
      "uri": "http://192.168.0.21:45756"
    },
    {
      "name": "Bedroom speaker",
      "product": "cast",
      "id": "0621e0150f4627062c9b3700e942a696",
      "token": "none",
      "uri": "https://192.168.0.14:8009"
    },
    {
      "name": "Home group",
      "product": "cast",
      "id": "1",
      "token": "none",
      "uri": "https://192.168.0.14:42206"
    }
  ],
  "dvrs": []
}

BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION
6. What are the last six digits of your server's API Token? (Settings -> Phlex)
bf2b67

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
