### ISSUE TITLE
Cannot switch players

### ISSUE THREAD

**Issue by fun4stuff** [d8ahazard/Phlex#264]
When trying to switch the players by voice from google home or manually typing the command in the Phlex GUI, I get the following error:

{
  "serverURI": "https://192-163-1-50.a39970cbb9a40c8a09392228.plex.direct:32400",
  "serverToken": "rLhFyuKq91TyA))7884",
  "clientURI": "http://192.163.1.100:8009",
  "clientName": "",
  "initialCommand": "switch player to living room",
  "timestamp": "Tue, 19 Dec 2017 17:51:42 +0000",
  "commandType": "player",
  "parsedCommand": "Switch player.",
  "mediaStatus": "Not a media command.",
  "speech": "There was an error retrieving the list of devices, please try again later.",
  

Both my chromecasts are entered in as static devices. I'm running phlex as a docker container on my synology NAS.

**Comment by fun4stuff** [comment]
So instead of asking flex tv to change the player, you have to say "ask flex tv to play [show or movie] on [name of player]." Then it works.

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
