### ISSUE TITLE
Request for Phlex to hombridge to control via Siri

### ISSUE THREAD

**Issue by dazza120** [d8ahazard/Phlex#265]
Hi,

I would like it if you can bring Phlex to hombridge so it can be used by siri and eventually the homepod when that comes out is that 👍

**Comment by fun4stuff** [comment]
I was also looking into this as I use homebridge. There may be a way to control alexa with homebridge (and therefore also phlex)... Haven't had time to look into it yet.

**Comment by d8ahazard** [comment]
Noted for V2.

**Comment by dazza120** [comment]
Hi would this be a complete rework? I just wanted to know if i can do my json file with the phlex config thats already out and just update phlex with V2. I'll loving HomePod and this will be great to control it

**Comment by d8ahazard** [comment]
The api endpoints in Phlex that other apps can use (Like IFTTT and I'm
assuming homebridge?) should remain the same - the bulk of the work is with
internal functionality for stability and performance improvements.
