### ISSUE TITLE
Fatal error generating config.inc.php on new install

### ISSUE THREAD

**Issue by Tawmu** [d8ahazard/Phlex#269]
I'm trying to configure Phlex for the first time, and when I log in with the Plex account details I get the 'One moment please' popup, but then I get the fatal PHP error outlined below. It looks as if the configuration file is failing to be generated properly since this is all that gets written in all operating systems:

`
'; <?php die('Access denied'); ?>
[general]
deviceID = "removed"

[user-_-LarryD£$]
plexUserName = "removed"
plexToken = "removed"
plexEmail = "removed@removed.com"
plexAvatar = "https://127.0.0.1/Phlex//img/cache/removed.png"
plexCred = "removed="
apiToken = "removed"
`

#### 1. On what OS are you running Phlex?
Tried Raspbian, Ubuntu, and Windows

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
Tried a clean LAMP install on Ubuntu 17.04 and Raspbian. New PHP 7.0 XAMPP install on Windows.

#### 2b. If not XAMPP, what WebServer stack are you using?
XAMPP on Windows, Apache/PHP7 on Linux.

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes.

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes.

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

`
Fatal error: Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: config.ini.php in C:\xampp\htdocs\Phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php:133 Stack trace: #0 C:\xampp\htdocs\Phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php(891): Config_Lite->read('config.ini.php', 0) #1 C:\xampp\htdocs\Phlex\util.php(751): Config_Lite->__construct('config.ini.php', 2) #2 C:\xampp\htdocs\Phlex\api.php(425): checkSetDeviceID() #3 C:\xampp\htdocs\Phlex\api.php(56): setSessionVariables() #4 {main} thrown in C:\xampp\htdocs\Phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php on line 133` (same error on Linux too)

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
N/A

**Comment by Tawmu** [comment]
Turns out it doesn't like the fact the Plex username ends in a $.

**Comment by d8ahazard** [comment]
Noted for V2...

**Comment by d8ahazard** [comment]
We're using JSON-based storage and a whole new wrapper class...so this should be good now...
