### ISSUE TITLE
Reverse Proxy Support

### ISSUE THREAD

**Issue by cwallace** [d8ahazard/Phlex#27]
Can we get support for reverse proxies on Sonarr/Radarr/Sickrage/Couchpotato?

All of my services are hidden behind a reverse proxy with basic authentication. Rather than supplying a host and port could we maybe provide a URL like this:

https://user:pass@hostname/sonarr/

I've tried entering such a URL and supplying 443 as the port and it doesn't seem to work.

**Comment by d8ahazard** [comment]
Have you tried just providing the reverse proxy URL?  I don't have https set up for my apps currently, but at least for http, I can use http://sonarr.my.hostname.com in settings with no issues.  Let me know if this doesn't help, it's possible it could be https specific.  But typically, you don't need to specify 80 or 443, it's inferred with http and https...

**Comment by cwallace** [comment]
Ya after reading the code it looks like the problem I'm running into is that the URLs are hard coded to http. I've got it disabled for the time being. Might work up some sort of solution.

**Comment by d8ahazard** [comment]
Mind if I contact you on hangouts?

**Comment by cwallace** [comment]
Not at all: chris@wallace.ws

**Comment by d8ahazard** [comment]
Sent you a request, says "pending".

**Comment by d8ahazard** [comment]
This should be fixed.
