### ISSUE TITLE
Can't link multiple google home accounts.

### ISSUE THREAD

**Issue by scotthorn** [d8ahazard/Phlex#272]
Preface:
Running server on Windows 7, XAMPP, sockets enabled, downloaded repo zip (no docker), php writing successfully, ports forwarded, all working for first google user (had to hardcode chromecast info in fetchCastDevices, mentioned on another existing issue). API: e13920

Problem:
After linking my google user, linking an additional one does not work. After another computer logged into another Google user presses "Link Google", the popup window says:
`Unable to connect to Client at http://my.public.url, please check the setting for 'Public Address' in the Phlex UI.`

The public URL is the same one I'm logged into and using successfully from an external internet connection. My first google user continues to work fine, but when I checked on the Link Google button there, the popup window now has the same behavior. URL for this error is https://phlexserver.cookiehigh.us/api.php with my correct API token and server address as query parameters.

**Comment by bobpaul** [comment]
Update to the latest revision (9aec9ff9) and try again. It seems to be working right now for existing Phlex installs.
