### ISSUE TITLE
Cannot Play Music

### ISSUE THREAD

**Issue by unfoun** [d8ahazard/Phlex#284]
I'm running Flex on Ubuntu 16.04 and I'm not able to play music to either of my roku devices or any of my 4 Google home devices. The roku apps seem to crash when I request an artist and the home devices chime like something is about to cast to them, but the music never starts.

Movies and TV shows, and downloads through Radarr and Sonarr all work flawlessly

**Comment by unfoun** [comment]
P.S. the commands I sent to Flex to play music all show in the log and appear to have been successful

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
