### ISSUE TITLE
Can't play music by artist

### ISSUE THREAD

**Issue by soccercjs2** [d8ahazard/Phlex#285]
1. On what OS are you running Phlex?
I am running windows 10.

2. Are you using a new instance of XAMPP, or an existing webserver?
A new instance of XAMPP.

3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes.

4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes.

5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

Having issue with the command: 
    play the black eyed peas
    play the artist the black eyed peas

I am successful if I say: 
    play just can't get enough
    play just can't get enough by the black eyed peas

Here is the log for the command I am having an issue with

1379
[Sat, 30 Dec 2017 02:39:44 +0100] [INFO] [api.php::parseApiCommand] - Full API.AI request: [JSON]
1380
[Sat, 30 Dec 2017 02:39:44 +0100] [INFO] [api.php::parseApiCommand] - Final params should be an action of play, a command of The Black Eyed Peas, a type of , and a control of .
1381
[Sat, 30 Dec 2017 02:39:44 +0100] [INFO] [api.php::parseApiCommand] - Final media result: false
1382
[Sat, 30 Dec 2017 02:39:44 +0100] [INFO] [api.php::plexSearch] - URL is https://10-0-0-232.2cb47713f9884b01b8046525417ad7ce.plex.direct:32400/hubs/search?query=black+eyed+peas&limit=30&X-Plex-Token=CVPKwkqVM7bRUHDUBa32
1383
[Sat, 30 Dec 2017 02:39:45 +0100] [INFO] [api.php::fetchMediaExtra] - URL is https://10-0-0-232.2cb47713f9884b01b8046525417ad7ce.plex.direct:32400/library/metadata/3652?X-Plex-Token=CVPKwkqVM7bRUHDUBa32
1384
[Sat, 30 Dec 2017 02:39:45 +0100] [INFO] [api.php::fetchMediaExtra] - URL is https://10-0-0-232.2cb47713f9884b01b8046525417ad7ce.plex.direct:32400/library/metadata/3652?X-Plex-Token=CVPKwkqVM7bRUHDUBa32
1385
[Sat, 30 Dec 2017 02:39:45 +0100] [INFO] [api.php::plexSearch] - Return array: [JSON]
1386
[Sat, 30 Dec 2017 02:39:45 +0100] [INFO] [api.php::queueMedia] - URL is https://10-0-0-232.2cb47713f9884b01b8046525417ad7ce.plex.direct:32400/library/metadata/3652?X-Plex-Token=CVPKwkqVM7bRUHDUBa32
1387
[Sat, 30 Dec 2017 02:39:45 +0100] [INFO] [api.php::queueMedia] - URL is https://10-0-0-232.2cb47713f9884b01b8046525417ad7ce.plex.direct:32400/playQueues?type=audio&uri=library://e8ca7d3a-5122-4bb0-a5cd-183fa0c4186d/item/%2Flibrary%2Fmetadata%2F3652&shuffle=0&repeat=0&includeChapters=1&own=1&X-Plex-Client-Identifier=9963527460a0d9a128feb7b7&X-Plex-Product=Phlex&X-Plex-Version=1.0.0&X-Plex-Platform=Web&X-Plex-Platform-Version=1.0.0&X-Plex-Device=PhlexWeb&X-Plex-Device-Name=Phlex&X-Plex-Device-Screen-Resolution=1520x707,1680x1050,1920x1080&X-Plex-Token=CVPKwkqVM7bRUHDUBa32
1388
[Sat, 30 Dec 2017 02:39:45 +0100] [INFO] [api.php::returnSpeech] - My reply is going to be 'You got it, Playing The Black Eyed Peas.'.
1389
[Sat, 30 Dec 2017 02:39:45 +0100] [INFO] [api.php::queueMedia] - URL is https://10-0-0-232.2cb47713f9884b01b8046525417ad7ce.plex.direct:32400/library/metadata/3652?X-Plex-Token=CVPKwkqVM7bRUHDUBa32
1390
[Sat, 30 Dec 2017 02:39:45 +0100] [INFO] [api.php::queueMedia] - URL is https://10-0-0-232.2cb47713f9884b01b8046525417ad7ce.plex.direct:32400/playQueues?type=audio&uri=library://e8ca7d3a-5122-4bb0-a5cd-183fa0c4186d/item/%2Flibrary%2Fmetadata%2F3652&shuffle=0&repeat=0&includeChapters=1&own=1&X-Plex-Client-Identifier=9963527460a0d9a128feb7b7&X-Plex-Product=Phlex&X-Plex-Version=1.0.0&X-Plex-Platform=Web&X-Plex-Platform-Version=1.0.0&X-Plex-Device=PhlexWeb&X-Plex-Device-Name=Phlex&X-Plex-Device-Screen-Resolution=1520x707,1680x1050,1920x1080&X-Plex-Token=CVPKwkqVM7bRUHDUBa32
1391
1392
[Sat, 30 Dec 2017 02:40:17 +0100] [INFO] [api.php::playMedia] - Playback Result: [JSON]

6. What are the last six digits of your server's API Token? (Settings -> Phlex)
90822b

**Comment by muppet3000** [comment]
Also seeing this exact same issue

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
