### ISSUE TITLE
Unable to fetch movies, kind of

### ISSUE THREAD

**Issue by pbysh** [d8ahazard/Phlex#286]
So I have gone through the installation steps and got Phlex mostly working on a clean raspberry 3 install. I have access to phlex from the internet, mydomain:xxxx/Phlex, and have linked Radarr and Sonarr accounts that both seem to work when I Test the links. I have also linked my Google account.

When I tell my Google Home to tell Flex TV to download a movie, it comes back with an error message but (sometimes) the download gets queued in Radarr anyways. But it never says it actually did it.

#### 1. On what OS are you running Phlex?

raspbian

#### 2. Are you using a new instance of XAMPP, or an existing webserver?

clean apache2 per the installation guide

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?

Yes

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?

Yes

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

    607 [Sun, 31 Dec 2017 00:19:18 +0000] [DEBUG] [api.php] - Sorry, couldn't validate user.
    608 [Sun, 31 Dec 2017 00:19:18 +0000] [ERROR] [api.php] - ERROR: Unauthenticated access detected. Originating IP - 192.99.197.11
    609 [Sun, 31 Dec 2017 00:19:18 +0000] [DEBUG] [api.php] - Invalid API Token, forcing logout.

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)

2f055d

**Comment by bobpaul** [comment]
I can confirm this issue still occurs on rev 9aec9ff9

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
