### ISSUE TITLE
Invalid API

### ISSUE THREAD

**Issue by darkboomba** [d8ahazard/Phlex#287]
Hello,

I decided to completely reinstall Phlex as it didn't work properly. After some troubleshooting with port forwarding I finally got it set up correctly again. Phlex is linked with google and I'm able to talk to Phlex TV on Google Home. The connection to my Plex server is also succesful.

When I tell Phlex TV to play a show it says it will try to play it for me, but nothing happens. In the Web UI of Phlex no request appears (on the main page). In the logs I found there is some problem with the API key.

I removed the API key from the log I'll post here but the API that was in there is different from the one in Phlex Web UI > Settings. Could this be the problem? And if yes how would I fix this.

https://pastebin.com/AAvCTWJj

Thank you for reading!

- DarkBoomba

**Comment by damianodonoghue** [comment]
I think this is the same as my problem. I tried the docker container and linked it with my account when I found out the docker contain didn't work with chromecasts (At least not for me) I setup a new machine and relinked it to my account but I didn't keep mu config fill with the original api key. I just relinked with a new one. For me If I stop and then start apache and then go and link my account again it will work for one command then then give me the error the next time. Can you try that and see is it the same.

**Comment by fun4stuff** [comment]
In order to use phlex with a docker container you have to add your chromecast as a static device. You can do this with the chromecast's local ip which you can find in your router. Look at a list of all the devices that connect to your router and your chromecasts and their respective local IPs will on it.

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
