### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by justlookingaround12** [d8ahazard/Phlex#288]
Sorry if this is a simple problem, but it may help other beginners like myself. 

#### 1. On what OS are you running Phlex?
Ubuntu server LTS
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
New
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Ok so i have PHP 7.0, how do i give it write access? How do i know which user to give it to using chown command?
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes

So after following the installation guide, i have all the files in /opt/lampp/htdocs/Phlex (this was done by cloning using git)

when i go to 192.168.100.8:80, i just see "Index of /" and "Apache/2.4.18 (Ubuntu) Server at 192.168.100.8 Port 80" on the bottom
What can i do to actually access Phlex?

in a previous install attempt (formatted now), i managed to actually get to Phlex and it would give me permission errors, which is part of my question as well: How and who do i give permission to on the folder /opt/lampp/htdocs ? 
Thanks

**Comment by darkboomba** [comment]
Make sure to go to 192.168.100.8:80/Phlex/

**Comment by simo26246** [comment]
If you're running an ubuntu server, it would be 

`sudo chown [insert user here] -R /opt/lampp/htdocs` to give ownership, you might then have to add access (I use `sudo chmod -R 777 /opt/lampp/htdocs` <--- assuming you're not network admin, and don't care who has access to read/write, 777 should be fine.
