### ISSUE TITLE
What is ideal setup in terms of OS?

### ISSUE THREAD

**Issue by Imburr** [d8ahazard/Phlex#290]
What is the ideal setup in terms of OS and web hosting platform? I typically use CentOS 7 and a combo of Nginx/Apache/FPM for my web hosting. But docker also seems relatively easy to use and update.

I have an ESXI server so I can spin up any platform and configure it any way- which is considered the BEST for Phlex?

**Comment by d8ahazard** [comment]
Haha...this is subjective to situation, and waiting on the developer.

In the current version, casting is a PITA, but seems to work best on Linux, webserver doesn't matter so much as making sure PHP is configured correctly. 

However, sockets are hit or miss and subjective to all kinds of weird variables, and so I dropped them entirely and moved the cast stuff to work from inside the Plex Media server via a custom plugin.

It's not ready yet, but the V2 is in the /beta branch, and should work for most of the things right now, although it's still definitely a work in progress, and should be considered more a demo/alpha than a working product.

Honestly, I'd say the *best* way to install it - once V2 is ready for the public - would be in a docker instance. It comes with everything you need, it's self-contained, and without the socket dumbness, it should just work.

**Comment by d8ahazard** [comment]
'Nix

**Comment by Imburr** [comment]
I am unable to run the docker image, though I can run other docker images.

cdill@ubuntu16docker:~$ docker run digitalhigh/phlex
standard_init_linux.go:178: exec user process caused "exec format error"
