### ISSUE TITLE
Google home does not detect Flextv

### ISSUE THREAD

**Issue by aldoushx** [d8ahazard/Phlex#291]
Hello,
Great tutorial and good functionnalities, but i don't manage to make Flex work with my google home or my phone assistant : 
My google account is linked.
My devices are listed : chromecast and home
My phlex file can be accessed from the outside of the local network.
When i launch a movie on the chromecast via the Phlex page with the keyboard, it works.
...
But ! When i ask google home to talk to flextv, it does not understand the command, and does nothing.
An idea of what i have made wrong ?
Or where to force the link between phlex and Home ?
Or where to verify the link ?
Thank you !

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
