### ISSUE TITLE
Playback not working/error connecting?

### ISSUE THREAD

**Issue by simo26246** [d8ahazard/Phlex#292]
## ISSUE TEMPLATE

If submitting a feature request, these are not required.

#### 1. On what OS are you running Phlex?
Android TV - Android 5.1

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
Using Apache2 and php on RaspberryPi3

#### 2b. If not XAMPP, what WebServer stack are you using?
See above

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
1b8824

**************
Playback won't start on any of my devices. The web interface thinks it's playing, but it doesn't actually start and when trying to stream to my TV I get the below error?
```
Fri, 05 Jan 2018 12:01:31 +1030 Chromecast.php::__construct
Failed to connect to remote Chromecast: Connection refused
```

For reference I'm using a Kogan TV (based on a Samsung panel) 
  
*** EDIT ***
I fixed the failed to connect by rerstarting my server (doh!)

Still having playback issues though - could this be plex user related?

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
