### ISSUE TITLE
Kodi plex add on not found by phlex

### ISSUE THREAD

**Issue by phairplay** [d8ahazard/Phlex#293]
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?

I’m using kodi with the phlex add on on my Sony tv which plays 4K nicely. The problem is phlex doesn’t see it in the scans.

Is there way to fix this?

**Comment by phairplay** [comment]
hi,
could you please help with this?
im able to get plex kodi to show up but i cant contol it. is there anyway around it?
![capture](https://user-images.githubusercontent.com/9025847/35650535-56ff32ee-06d4-11e8-92ee-35b01eeca329.JPG)

**Comment by d8ahazard** [comment]
Have you tried the beta branch w. Cast plugin?

**Comment by phairplay** [comment]
Hi yes I switched to the beta it found the living room which is my tv and showed what was playing. Yet I still couldn't control anything.

Clicking on the controls on the web UI didn't do anything

**Comment by d8ahazard** [comment]
Ah!  Controls are wip in the beta web UI, need a little revision yet...
Probably have that fixed up today...

**Comment by phairplay** [comment]
When I asked flex tv to stop pause ect
she said okay
When I asked to play the flash
She's said okay I'll try to play the flash

**Comment by d8ahazard** [comment]
Original issue is fixed, subsequent issues will be addressed with the V2 release. As such, closing.
