### ISSUE TITLE
Android TV box -> not starting up

### ISSUE THREAD

**Issue by mitchy112** [d8ahazard/Phlex#294]
Hey there,

When i manually start playing for example suits on my tv box, and say paus playing suits, it pauses suits:
Command Result:

{
  "url": "http://192.168.31.202:50792/player/playback/pause?X-Plex-Token=tokencommandID=32",
  "status": "success"
}
Same goes for playing when puased.

But when i stop playing and say to plextv start playing suits. it doesnt work. 
{
  "url": "http://192.168.31.202:50792/player/playback/playMedia?key=%2Flibrary%2Fmetadata%2F9190&offset=1249448&machineIdentifier=a39ca91f06c67319e544f1ecc1bf6a7aad2ac7d4&protocol=https&address=192-168-31-244.2b476400013f4e31905e793a1cfa8e87.plex.direct&port=443&path=https%3A%2F%2F192-168-31-244.2b476400013f4e31905e793a1cfa8e87.plex.direct%3A32400%2F%2Flibrary%2Fmetadata%2F9190&token=transient-aafcae70-cb43-478e-8aa7-3a7a2851778c",
  "status": "success"
}

It seems to succesfully work if i may believe the logging. But it just doesnt start anything on my tv box.

**Comment by OrganicKobze** [comment]
I have the same issue with Android TV built in to Sony.

**Comment by trevormiller6** [comment]
same issue on ATV nvida sheild

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
