### ISSUE TITLE
Fetch Error 20

### ISSUE THREAD

**Issue by hitnrun30** [d8ahazard/Phlex#296]
## ISSUE TEMPLATE

Ok, I have setup everything correctly and setup my fetches from both sides.  I use Radarr to get movies, and asked Phlex to get a movie, I get an Error 20 message with a 500 url error.

Heres the kicker, it added the movie correctly to Radarr.

If submitting a feature request, these are not required.

#### 1. On what OS are you running Phlex?
Windows 10
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
existing
#### 2b. If not XAMPP, what WebServer stack are you using?
NGINX
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
yes
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
yes and my machine is available outside of my network
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

I found this in the log

thrown in C:\HTPC\nginx\html\Phlex\api.php on line 4186
[07-Jan-2018 06:01:49 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in C:\HTPC\nginx\html\Phlex\api.php:4186

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
a369c1

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
