### ISSUE TITLE
SSL Certificate error: 51

### ISSUE THREAD

**Issue by Vauxite** [d8ahazard/Phlex#297]
Hello!

#### 1. On what OS are you running Phlex?
Ubuntu 16.04 LTS

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
New instance (included in [docker image](https://hub.docker.com/r/digitalhigh/phlex/)).

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Assuming this is done within the docker image, so yes.

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

> An error has occured. Please report the following message to the developer 'Error 51: SSL: certificate subject name '*' does not match target host name 'cetter.ddns.net'

Debug is enabled in phlex, however there is no output when the error occurs.

**How to trigger?**
Issuing any command from Google assistant to phlex. For example: 
> Ask Flex TV what's on deck

**Additional information**

- Reverse proxy is configured (according to ticket #125).
- A-rating according to ssl labs.
- Ports are forwarded and verified.
- Accessible from outside (public).

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
27e983

Please let me know if you need anything else. I'm sorry if this is out of scope.

**Comment by Vauxite** [comment]
I enabled debugging in nginx and there is no request made when attempting to issue a voice command.
All looks okey in the ssltester from ssllabs
https://www.ssllabs.com/ssltest/analyze.html?d=cetter.ddns.net

**Comment by Vauxite** [comment]
A bit my fault. You have to specify the port (443) even though you tell Phlex https://domain.com. After that it was cakewalk to solve the issue.

**Comment by mmatthers** [comment]
Hi Vauxite - Am getting the same error -  are you saying you need to change the docker https port from 5667 to 443?

**Comment by Vauxite** [comment]
No. I had to tell Phlex that the my public domain is listening on port 443. I though that was implied when using https:/mydomain.com. However I had to use https://mydomain.com:443

**Comment by mmatthers** [comment]
Thanks for the response. The issue I have is that I have a LetsEncrypt certificate on the DNS name I’m using, and i think the issue is that the docket container has a self signed one which is why it’s not happy when it tries to connect over SSL. 
I noticed you were using Docker too which is why I asked about port 5667 as that’s the default SSL port it uses. Where about did you tell  Phlex to use 443?  In the web interface?  And if so, did you specify it as https://mydomain.com:443
Thanks

**Comment by d8ahazard** [comment]
TBH, using a self-signed SSL cert completely defeats the purpose of using
HTTPS. I highly recommend either disabling https, or using a let'sencrypt
cert.

**Comment by mmatthers** [comment]
Absolutely. This is what I was looking into last night. Is there an article you can point me to to put my certificate into the docker image?
Thanks

**Comment by mmatthers** [comment]
I guess the other issue is that LE certs only last a few months before they expire so there’d have to be a way of automating the updating of the cert into the docker image. Sounds tricky.

**Comment by mmatthers** [comment]
Hi
Please ignore previous email about copying over the cert. I currently only have a single DNS entry pointing to my external facing router. I guess I’d need a second DNS entry and a new LE cert to be able to get this running from docker. 

Really appreciate the effort in getting this up and running. I disabled https integration last night and have Flex TV responding through Google home but it doesn’t change anything on Plex. Am unclear how it knows which Plex client to play it on too. Am guessing it’s my IFTTT. May need to start again now I’m using just http. I simply changed the IFTTT URL and port forwarded 5666 through.  Don’t expect an answer via email as I’m sure you’re really busy, but would love to hear back from you 😊
Cheers.

**Comment by Vauxite** [comment]
I use [nginx reverse proxy](https://www.nginx.com/resources/admin-guide/reverse-proxy/) on the host system. No certificates in the docker containers.

You still get encrypted connection by using self-signed SSL. However that's another discussion.
