### ISSUE TITLE
PHP Extension not loaded

### ISSUE THREAD

**Issue by OrganicKobze** [d8ahazard/Phlex#298]
#### 1. On what OS are you running Phlex?

Windows 10

#### 2. Are you using a new instance of XAMPP, or an existing webserver?

New instance of XAMPP

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?

I believe so. The socket dll was inside the ext folder within PHP. However extension=php_socket.dll was not in my PHP.ini at all. I tried adding the line in myself but this didn't work either. 

Any help would be greatly appreciated. I might note that I'm using nginx separately to run Plexpy...

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)

bf9eba

**Comment by OrganicKobze** [comment]
The sockets extension was inside of the php.ini file. I was being stupid...

However it's uncommented and my phpinfo tells me that my sockets are enabled.

It's just sending me a notification telling me otherwise everytime I load Phlex and therefore not allowing me to see cast devices.

**Comment by OrganicKobze** [comment]
Fixed with re-installation.

**Comment by KrunchMuffin** [comment]
what exactly did you reinstall? Phlex or PHP?

**Comment by OrganicKobze** [comment]
I just ended up re-installing the whole thing. I was already using nginx for a webserver for organizr so I just installed it on there in the end. I think it was likely an issue with access to certain files.

**Comment by KrunchMuffin** [comment]
Ya using nginx myself as well. Guess i'll keep plugging away. Thanks.
