### ISSUE TITLE
Sony Android TV - Can't play media

### ISSUE THREAD

**Issue by OrganicKobze** [d8ahazard/Phlex#299]
## ISSUE TEMPLATE

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. On what OS are you running Phlex?
Windows
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
New XAMPP
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
I have.
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
4b5322

Everything is working perfectly, apart from playing to my Sony Android TV. It will let me play/pause/stop any media. However when I ask it to play something it doesn't open. However Phlex logs says that it has succeeded. I can also see the media that's playing on the TV via the now playing at the bottom of Phlex UI.

Can anyone help me with this please?

**Comment by mitchy112** [comment]
Same here:
https://github.com/d8ahazard/Phlex/issues/294

**Comment by OrganicKobze** [comment]
Any update on this? Or does anyone know of a workaround? Completely un-usable for Android players...

**Comment by d8ahazard** [comment]
Working on a mega update as we speak...

**Comment by OrganicKobze** [comment]
Best news of 2018! Appreciate all the work dude.

**Comment by OrganicKobze** [comment]
@d8ahazard do you have any kind of time frame for when you're be releasing the update?

**Comment by d8ahazard** [comment]
There's a beta branch currently available that you can check out, although it's still a WIP.

**Comment by OrganicKobze** [comment]
Thanks for the update! So... I now have the ability to play and resume playback. However asking to play anything is ignored. It's all understood by Phlex as I can see the command on the Phlex UI. However it doesn't actually change it. Still, progress...

**Comment by d8ahazard** [comment]
Beta is WIP, and the original issue has been fixed by it. Control commands will have been totally redone in the new release, and as such...closing.
