### ISSUE TITLE
Movie/TV Show identification trigger

### ISSUE THREAD

**Issue by XmemphistoX** [d8ahazard/Phlex#3]
There doesn't seem to be a way to specifically identify a movie from a tv show. 

IE) I have or don't have a movie named the same as a tv episode.  In my example, I was just testing it out to download a movie I didn't have.  

My voice syntax (I do not have the movie in my library and was expecting a prompt to download)
OK Google, ask flex tv to play the movie Ballerina
OK Google, ask flex tv to play the movie Ballerina 2016
OK Google, ask flex tv to play the movie Ballerina
OK Google, ask flex tv to play Ballerina

All commands would play
Law & Order SVU - Ballerina (TV Show)

**Comment by d8ahazard** [comment]
Is this still an issue?  I think I may have fixed it a few days ago.  If not, let me know, and I'll dig in again.  :D

**Comment by XmemphistoX** [comment]
Seems to be better however saying the same syntax it is now playing the movie "Experimenter"  Log below.

Initial command: "tell Flex TV to play movie ballerina"
Parsed command: "Play the tag named ."
Search status:  Fuzzy result found
Playback URL:  http://192.168.1.137:32500/player/playback/playMedia?key=%2F...
Playback status:  success
Speech Response:  No problem, Playing  ().
{JSON}

**Comment by d8ahazard** [comment]
This is fixed in the current codebase.  Thanks for the feedback!
