### ISSUE TITLE
Phlex doesn't check if movie already exists at download request.

### ISSUE THREAD

**Issue by technoten** [d8ahazard/Phlex#300]
When asking Phlex to download a movie (using couchpotato) it will add the movie to the fetch list regardless of whether or not you already have the movie in your couchpotato library. Would it make more sense to return a "You already have **this movie**" response instead of adding the movie again?

**Comment by Chrisazy** [comment]
I'd like to bump this because I intent to fix it and I hope the official developer also does. I've investigated some and plan to submit a pull request in a few days, @technoten just FYI in case I bet the dev, since they are swamped ;)

**Comment by d8ahazard** [comment]
Please refer to the beta branch if working on pr's, as the main branch is
no longer being developed.  Also, with the beta, I've not worked out a
number of issues with fetchers, so any help there is welcome.  😁

**Comment by technoten** [comment]
@Chrisazy Thanks for taking a look at it. Have you been able to find documentation for Couchpotato's API?

**Comment by d8ahazard** [comment]
@technoten @Chrisazy - CP's api documentation is built into the app. If your couch server is at couch.myserver.com - the documentation is couch.myserver.com/docs . Feel free to email donate.to.digitalhigh@gmail.com if you want to discuss what I'm doing and why...

**Comment by d8ahazard** [comment]
Disregard, I'm completely overhauling fetchers...this won't even be a thing to think about in the V2 release...
