### ISSUE TITLE
Can't sign in with google

### ISSUE THREAD

**Issue by Ryazte** [d8ahazard/Phlex#301]
1. On what OS are you running Phlex? Windows **10**

2. Are you using a new instance of XAMPP, or an existing webserver? **New instance of XAMPP**

3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex? **I have no idea how to do that, i've tried to look up how to do it and have found nothing helpfull**

4. Have you followed the (networking)[Talking-To-The-Outside-World] section? **Yes**

6. What are the last six digits of your server's API Token? (Settings -> Phlex) **c5e906**

**Comment by pranqie** [comment]
3 - If using W10 XAMPP GUI click "Config" on the apache line.  Choose php.  Text editor opens, ctrl-f, type "sockets" and and remove the semicolon in front of "extension=sockets" then save the file and close.  Stop apache, start apache.  retry.

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
