### ISSUE TITLE
Local network Plex instance not working

### ISSUE THREAD

**Issue by pentium3nl** [d8ahazard/Phlex#302]
## ISSUE TEMPLATE

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. On what OS are you running Phlex?
Raspbian GNU/Linux 9 \n \l

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
I used the Raspbian howto on deploying and installing Apache2, PHP 7.0 and GIT.
Webinterface seems to be working perfectly, only issue i had was that modssl.so is not existing but working:
root@raspberrypi:/var/www/html/Phlex# echo "<?php phpinfo();?>" | php | grep -i ssl
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2
SSL => Yes
SSL Version => OpenSSL/1.0.2l
SSL Support => enabled
core SSL => supported
extended SSL => supported
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.1.0f  25 May 2017
OpenSSL Header Version => OpenSSL 1.1.0f  25 May 2017
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
Native OpenSSL support => enabled

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/openssl.so' - /usr/lib/php/20151012/openssl.so: cannot open shared object file: No such file or directory in Unknown on line 0

So i removed the extension in the php.ini.

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes i did:
open_basedir = /var/www/html/Phlex/

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes and my Google Home is connected

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

[Fri, 12 Jan 2018 12:20:55 +0000] [INFO] [api.php::initialize] - Incoming API request detected.
[Fri, 12 Jan 2018 12:20:55 +0000] [INFO] [api.php::parseApiCommand] - Full API.AI request: {"id":"xxx","timestamp":"2018-01-12T12:20:55.4Z","lang":"en","result":{"source":"agent","resolvedQuery":"play american dad","action":"Playmedia","parameters":{"action":"play","command":"american dad"},"contexts":[{"name":"promptfortitle","parameters":{"command":"american dad","command.original":"american dad","action.original":"play","action":"play"},"lifespan":3},{"name":"google_assistant_welcome","parameters":{"command":"american dad","command.original":"american dad","action.original":"play","action":"play"},"lifespan":5},{"name":"waitforplayer","parameters":{"command":"american dad","command.original":"american dad","action.original":"play","action":"play"},"lifespan":2},{"name":"yes","parameters":{"command":"american dad","command.original":"american dad","action.original":"play","action":"play"},"lifespan":3},{"name":"playmedia-followup","parameters":{"command":"american dad","command.original":"american dad","action.original":"play","action":"play"},"lifespan":2}],"metadata":{"intentId":"xxx","webhookUsed":"true","webhookForSlotFillingUsed":"false","webhookResponseTime":279,"intentName":"PlayMedia"},"fulfillment":{"messages":[[]]},"score":0.8652341670649},"status":{"code":206,"errorType":"partial_content","errorDetails":"Webhook call failed. Error: Webhook response was empty."},"sessionId":"xxx","originalRequest":{"data":{"inputs":[{"raw_inputs":[{"query":"play american dad"}]}]}}}
[Fri, 12 Jan 2018 12:20:55 +0000] [INFO] [api.php::parseApiCommand] - Final params should be an action of play, a command of american dad, a type of , and a control of .
[Fri, 12 Jan 2018 12:20:55 +0000] [INFO] [api.php::parseApiCommand] - Final media result: false
[Fri, 12 Jan 2018 12:20:55 +0000] [INFO] [api.php::plexSearch] - URL is https://192-168-150-100.xxx:32400/hubs/search?query=american+dad&limit=30&X-Plex-Token=xxx
[Fri, 12 Jan 2018 12:20:58 +0000] [ERROR] [util.php::doRequest] - An exception occurred: cURL error 28: Operation timed out after 3001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
[Fri, 12 Jan 2018 12:20:58 +0000] [ERROR] [util.php::doRequest] - Error getting response from URL fetch.
[Fri, 12 Jan 2018 12:20:58 +0000] [INFO] [api.php::plexSearch] - Found matches for cast or genre, discarding other results.
[Fri, 12 Jan 2018 12:20:58 +0000] [INFO] [api.php::plexSearch] - No results found for query.
[Fri, 12 Jan 2018 12:20:58 +0000] [INFO] [api.php::plexSearch] - Return array: []
[Fri, 12 Jan 2018 12:20:58 +0000] [INFO] [api.php::returnSpeech] - My reply is going to be 'I couldn't find  american dad  in your library. Should I try to add it to the watch lists?'.

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
904736

#### 7. Describe problem
If i connect Flex TV to an external Plex source, everything is working (like friends or cloud).
When i want to have the unit talk to my local plex server, it does not want to do anything and it gives me a timeout. Already tried to open non HTTPS connections and with every URL i see failing, i get perfect results through my web browser on my laptop.

**Comment by Chrisazy** [comment]
I've been having a similar problem for months. I can only see external Plex servers and not my own. I've tried to diagnose this issue and it honestly appears to be on the Plex side, but I'm not sure how related the two issues are. I'll dig in more tomorrow and post results, but consider this a bump with slightly different symptoms.

**Comment by d8ahazard** [comment]
Sounds like you guys could be candidates for the beta version.

Check out the beta branch, and then install the cast plugin on your local
server:

https://github.com/d8ahazard/Cast.bundle

That URL works in Unsupported App Store, too.  ;)

**Comment by pentium3nl** [comment]
As the beta version was even worse then the master brand, i went investigating myself.
Seems that when Plex want to connect to a local instance, the timeout is set too short.

The timeout in  the script is now set to 4 seconds, so it will fail after 3001ms. My browser with the same url takes 8 seconds.
Therefor the following fix:

vi util.php
rule 2124
Copy this rule with a # infront as backup.
Change $timeout to a normal value, i did 10000.

Example code:
        #$client = new GuzzleHttp\Client(['timeout' => $timeout, 'verify' => $cert]);
        $client = new GuzzleHttp\Client(['timeout' => 10000, 'verify' => $cert]);

So Chrisazy, when in your browser the url getting fired is working, then apply this fix.

PS. the beta does not even want to save any setting, keep getting stuck on Japenese. Writes configuration file perfectly and still resets options. Went back to master immediately.

**Comment by d8ahazard** [comment]
I'm going to close this, as while the /beta version isn't ready yet, the timeout issues in the curlGet will have been addressed and obliterated by code reworkings several times over.
