### ISSUE TITLE
Odd Issue When Casting to Google Home

### ISSUE THREAD

**Issue by teshiburu** [d8ahazard/Phlex#303]
## ISSUE TEMPLATE

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. On what OS are you running Phlex?
Server 2012r2

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
Existing Server 

#### 2b. If not XAMPP, what WebServer stack are you using?
IIS

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes 

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes 

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.
```
[Fri, 12 Jan 2018 16:21:05 +0000] [DEBUG] [api.php] - INCOMING REQUEST!!
[Fri, 12 Jan 2018 16:21:05 +0000] [DEBUG] [api.php] - Sorry, couldn't validate user.
[Fri, 12 Jan 2018 16:21:05 +0000] [ERROR] [api.php] - ERROR: Unauthenticated access detected.  Originating IP - 192.99.197.11
[Fri, 12 Jan 2018 16:21:05 +0000] [DEBUG] [api.php] - Invalid API Token, forcing logout.
[Fri, 12 Jan 2018 16:21:05 +0000] [DEBUG] [Chromecast.php::pong] - Function fired.
[Fri, 12 Jan 2018 16:21:10 +0000] [DEBUG] [Chromecast.php::getCastMessage] - Response: ZTr@n$p0rt-0Tr@n$p0rt-0"'urn:x-cast:com.google.cast.tp.heartbeat(2{"type":"PING"}@
[Fri, 12 Jan 2018 16:21:10 +0000] [DEBUG] [Chromecast.php::getCastMessage] - Pongcount: 1
[Fri, 12 Jan 2018 16:21:10 +0000] [DEBUG] [Chromecast.php::pong] - Function fired.
[Fri, 12 Jan 2018 16:21:15 +0000] [DEBUG] [Chromecast.php::getCastMessage] - Response: ZTr@n$p0rt-0Tr@n$p0rt-0"'urn:x-cast:com.google.cast.tp.heartbeat(2{"type":"PING"}@
[Fri, 12 Jan 2018 16:21:15 +0000] [DEBUG] [Chromecast.php::getCastMessage] - Pongcount: 2
[Fri, 12 Jan 2018 16:21:15 +0000] [DEBUG] [CCPlexPlayer.php::play] - R is ZTr@n$p0rt-0Tr@n$p0rt-0"'urn:x-cast:com.google.cast.tp.heartbeat(2{"type":"PING"}@
[Fri, 12 Jan 2018 16:21:16 +0000] [DEBUG] [api.php] - INCOMING REQUEST!!
[Fri, 12 Jan 2018 16:21:16 +0000] [DEBUG] [api.php] - Using token from GET
[Fri, 12 Jan 2018 16:21:20 +0000] [DEBUG] [CCPlexPlayer.php::play] - R is
[Fri, 12 Jan 2018 16:21:21 +0000] [DEBUG] [CCPlexPlayer.php::play] - R is
[Fri, 12 Jan 2018 16:21:22 +0000] [DEBUG] [CCPlexPlayer.php::play] - R is
[Fri, 12 Jan 2018 16:21:23 +0000] [DEBUG] [CCPlexPlayer.php::play] - R is
[Fri, 12 Jan 2018 16:21:24 +0000] [DEBUG] [CCPlexPlayer.php::play] - R is

```
#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
111f61

**Comment by teshiburu** [comment]
Forgot to say that when i ask to play music with the google home selected as the client, it says it will ask Flex TV to try and play it then i get that log in the flex log.

**Comment by d8ahazard** [comment]
Closing, since you already know about the beta and the cast plugin. ;)
