### ISSUE TITLE
Alternative to using port forwarding for Phlex?

### ISSUE THREAD

**Issue by chicago1356** [d8ahazard/Phlex#305]
I am running Phlex on a Raspberry Pi 3 (with Raspbian Stretch). My Pi and Google Home are connected to my own router which is connected to my apartment's Wi-Fi (double NAT). I can't setup port forwarding on my apartment's network, so even if I set it up on my own router I won't be able to access my server from outside the network.
**Is there an alternative to using port forwarding to setup and use Phlex?**

Thanks

**Comment by bobpaul** [comment]
Your Phlex install needs to be accessible from the internet. That is the only way Google can send commands your Phlex instance. 

You should talk to whoever controls your apartment's router. 
Alternatively, if your apartment's router supports UPnP, you might be able to use that to open a port. But I'm not sure how you'd get your router to send UPnP commands out its WAN interface.

**Comment by d8ahazard** [comment]
*Technically*, yes, the alternative to port forwarding would be to set up a reverse proxy.

But this approach also requires you have a way to shuffle internet traffic into your apartment at a publicly accessible address. 

Not my design - this is what's required for it to work with IFTTT and/or Google Assistant.

Sorry.  :(
