### ISSUE TITLE
Subtitles voice command and fetchers settings issues

### ISSUE THREAD

**Issue by Drmene** [d8ahazard/Phlex#306]
I have 2 unrelated questions/issues.
a) The settings for the fetchers are giving me issues. If I set radarr path, it no longer gives me the option to set the profile. I need to set the radarr path because the default path on my radarr instance is a sub folder. When I do set a radarr path, the profiles no longer give a drop down option (they seem to be wiped from the config file too)

b) I can't get voice commands to enable subtitles. Subtitles are all named as filename.lang.ext. I've included the relevant log enteries from my phlex.log

#### 1. On what OS are you running Phlex?
Windows 7

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
New

#### 2b. If not XAMPP, what WebServer stack are you using?
n/a

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

[Fri, 19 Jan 2018 14:04:15 +0100] [DEBUG] [api.php] - INCOMING REQUEST!!
[Fri, 19 Jan 2018 14:04:15 +0100] [DEBUG] [api.php] - Using token from POST
[Fri, 19 Jan 2018 14:04:15 +0100] [INFO] [api.php::setSessionVariables] - No DVR found, checking for available devices.
[Fri, 19 Jan 2018 14:04:15 +0100] [INFO] [api.php::parseApiCommand] - Full API.AI request: {"originalRequest":{"source":"google","version":"2","data":{"surface":{"capabilities":[{"name":"actions.capability.MEDIA_RESPONSE_AUDIO"},{"name":"actions.capability.AUDIO_OUTPUT"}]},"inputs":[{"rawInputs":[{"query":"ask Flex TV to turn on subtitles","inputType":"VOICE"}],"arguments":[{"rawText":"turn on subtitles","textValue":"turn on subtitles","name":"trigger_query"},{"rawText":"turn on subtitles","textValue":"subtitles on","name":"Controls"}],"intent":"actions.intent.MAIN"}],"user":{"lastSeen":"2018-01-19T12:59:56Z","idToken":"***","accessToken":"****","locale":"en-US","userId":"***"},"conversation":{"conversationId":"1516367041262","type":"NEW"},"availableSurfaces":[{"capabilities":[{"name":"actions.capability.AUDIO_OUTPUT"},{"name":"actions.capability.SCREEN_OUTPUT"}]}]}},"id":"f3084827-52d6-4d13-bd37-000ad3a9afca","timestamp":"2018-01-19T13:04:01.496Z","lang":"en-us","result":{"source":"agent","resolvedQuery":"turn on subtitles","action":"Playmedia","parameters":{"Controls":"subtitles on"},"contexts":[{"name":"promptfortitle","parameters":{"Controls":"subtitles on","Controls.original":"turn on subtitles"},"lifespan":3},{"name":"google_assistant_welcome","parameters":{"Controls":"subtitles on","Controls.original":"turn on subtitles"},"lifespan":5},{"name":"waitforplayer","parameters":{"Controls":"subtitles on","Controls.original":"turn on subtitles"},"lifespan":2},{"name":"yes","parameters":{"Controls":"subtitles on","Controls.original":"turn on subtitles"},"lifespan":3},{"name":"actions_capability_audio_output","parameters":{"Controls":"subtitles on","Controls.original":"turn on subtitles"}},{"name":"google_assistant_input_type_voice","parameters":{"Controls":"subtitles on","Controls.original":"turn on subtitles"}},{"name":"playmedia-followup","parameters":{"Controls":"subtitles on","Controls.original":"turn on subtitles"},"lifespan":2},{"name":"actions_capability_media_response_audio","parameters":{"Controls":"subtitles on","Controls.original":"turn on subtitles"}}],"metadata":{"matchedParameters":[{"dataType":"@Controls","name":"Controls","value":"$Controls"}],"intentName":"PlayMedia","intentId":"b8151275-afad-4f3f-bd9a-3a17f390cb75","webhookUsed":"true","webhookForSlotFillingUsed":"false","nluResponseTime":52},"fulfillment":{"messages":[[]]},"score":1},"status":{"code":200,"errorType":"success"},"sessionId":"1516367041262"}
[Fri, 19 Jan 2018 14:04:15 +0100] [INFO] [api.php::parseApiCommand] - Final params should be an action of control, a command of subtitleson, a type of , and a control of subtitles on.
[Fri, 19 Jan 2018 14:04:15 +0100] [INFO] [api.php::returnSpeech] - My reply is going to be 'You got it.'.
[Fri, 19 Jan 2018 14:04:16 +0100] [INFO] [api.php::sendCommand] - Command Result: {"status":"error"}

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
4fe284

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
