### ISSUE TITLE
Cant find an item to play because of incorrect search term.

### ISSUE THREAD

**Issue by hitnrun30** [d8ahazard/Phlex#307]
## ISSUE TEMPLATE

Ok, I think that Phlex is great but found a weird bug.  I asked it to play Marvel's Agent of Shield.  It's re was:

 "I couldn't find  marvel's agents shield  in your library. Should I try to add it to the watch lists?

Notice that it is missing the "of"  that is what I think the issue is.

#### 1. On what OS are you running Phlex?
Windows 10
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
Existing
#### 2b. If not XAMPP, what WebServer stack are you using?
nginx
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.
No error just not finding this item, finds and works for other items.

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
a369c1

**Comment by d8ahazard** [comment]
This has been fixed in the /beta branch, with commit acd5044. Might not make it to master till beta is done, but closing for my own sanity in working on the V2 release.
