### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Duffyx** [d8ahazard/Phlex#309]
Under what License is Phlex distributed?
I need this as I'm creating a port for FreeBSD.
I couldn't find anything around licensing on the FAQ's etc.

**Comment by d8ahazard** [comment]
Never had a need before...although it's probably a good idea so it can't be outright stolen, hey? 

Updated - GPL3. 

Also, might be advisable to wait till the new version is dropped, as a lot is going to change. You can refer to the /beta branch for testing.
