### ISSUE TITLE
Feature request - Add "download latest episode" command support

### ISSUE THREAD

**Issue by kdthomas21** [d8ahazard/Phlex#31]
Great app! I've been looking for something like this since i got Google home! Quick request, which may already be implemented. Can you request to download the latest episode of a show? Rather than having to say the specific episode or downloading the entire thing?

Thanks!

**Comment by d8ahazard** [comment]
Just so you know, I've got this "half" implemented now.  That is, it works a treat in my test version for SickRage, but not for Sonarr.  I'm working with Sonarr currently, but it's a more difficult beast in terms of individual episode requests - meaning I've got to rewrite a bit more of the Sonarr fetching stuff anywho.  But, should have this pushed and closed either tonight or tomorrow.  :D

**Comment by kdthomas21** [comment]
Woohoo sounds good! Thanks man! Having some issues setting it up though! Google home and everything is talking, connection successful for sonarr and radarr, but whenever I do a search with Phlex I get no results found, both on the pc and through google home. Any ideas?

Thanks again!

**Comment by d8ahazard** [comment]
Done and done and DONE.
