### ISSUE TITLE
Unexpected 403 from api.api.ai

### ISSUE THREAD

**Issue by 9numbernine9** [d8ahazard/Phlex#310]
#### 1. On what OS are you running Phlex?
FreeBSD 11.1

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
Existing Webserver

#### 2b. If not XAMPP, what WebServer stack are you using?
Nginx 1.13.8

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes!

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes!

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.
```
898 [Tue, 23 Jan 2018 13:12:05 -0500] [ERROR] [util.php::curlGet] - Unexpected HTTP code: 403, URL: https://api.api.ai/v1/query?v=20150910&query=Play+My+Media+Here&lang=en&sessionId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
899 [Tue, 23 Jan 2018 13:12:05 -0500] [WARN] [api.php::queryApiAi] - Null response received from API.ai, re-submitting. 
900 [Tue, 23 Jan 2018 13:12:05 -0500] [ERROR] [util.php::curlGet] - Unexpected HTTP code: 403, URL: `https://api.api.ai/v1/query?v=20150910&query=Play+My+Media+Here&lang=en&sessionId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
`1d4b22`

----------
Not exactly sure what's going on, but all of my queries against api.api.ai are returning a 403 value. I've tried reinstalling Phlex and generating a new API key, but no change in behaviour. Everything was working previously, so I don't think anything has changed on my end. If you need more information for debugging please let me know!

**Comment by d8ahazard** [comment]
Please try the following:

In util.php, find the line starting with  "function curlGet(".

Referring to this article:

https://stackoverflow.com/a/16916915/2405805

Add the lines:

`$ua = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.13 (KHTML, like Gecko) Chrome/0.A.B.C Safari/525.13';
`
just before the curl_init.

And then anywhere in in where it's setting the curl options (CURL_SETOPTS), add this line:

`curl_setopt($ch, CURLOPT_USERAGENT, $ua);
`

My suspicion is that other OSes add some kind of useragent declaration that make API.ai happy, but that with FreeBSD, you'll need to add it manually.

At least, that's my guess. Adding these two bits of code and trying it should help me narrow it down. Unfortunately, I don't have that OS around to test against...

**Comment by 9numbernine9** [comment]
Sorry for not responding to your comment sooner. I've been trying to reproduce this issue since you made your suggested fixes, but I can't even reproduce the problem I was having any more! Phlex has been working flawlessly for me the last couple weeks.

**Comment by d8ahazard** [comment]
Ohai! Closed.
