### ISSUE TITLE
"register server" button missing

### ISSUE THREAD

**Issue by WoLpH** [d8ahazard/Phlex#312]
I'm guessing it was renamed to "Link Google", but there's no "register server" button as mentioned in the readme:

> Once you've got the address entered, click the "register server" button. 

Looking at previous issues I assume the button did exist at some point:
https://github.com/d8ahazard/Phlex/search?q=%22register+server%22&type=Issues&utf8=%E2%9C%93

**Comment by pranqie** [comment]
Ditto.

**Comment by d8ahazard** [comment]
Readme's updated...
