### ISSUE TITLE
Error, sql bullshit!

### ISSUE THREAD

**Issue by Cojack4711** [d8ahazard/Phlex#313]
Hi

When I click on the LINK GOOGLE when setting up a new window appears and there it says:

Error, sql bullshit!

Can you help me?
I use Win10 and xampp

**Comment by spenceman1013** [comment]
I am getting the same issue right now. I am not seeing anything in the Phlex logs about the error.

I am running Debian and XAMPP.

**Comment by Bender1061** [comment]
I'm seeing this exact issue. My guess is something is going on with phlexserver.cookiehigh.us right now. Hope someone fixes it.

**Comment by bobpaul** [comment]
Can you post the actual error text? I searched through the code and I can't find the phrase "sql bullshit!", so I think you're hiding some details.

**Comment by nathancashmore** [comment]
+1 running with Win10 and XAMPP

**Comment by d8ahazard** [comment]
Should be fixed. Re-rolled the webserver, which reinstalled mySql. Amazingly, that set a strict flag where a field couldn't be set to empty when trying to insert a new user record.

This flag has been un-set.
