### ISSUE TITLE
Cannot Link Google Home to Phlex TV

### ISSUE THREAD

**Issue by mattcallaway** [d8ahazard/Phlex#319]
Ubuntu 17
Docker
0e1d19

I've made it to the final step but when I click Link in the Google Home app it redirects me to the phlexchat dot com page instead of the authorization page. Thanks for making this project and for any help you can provide.

**Comment by mattcallaway** [comment]
*Sorry* Flex TV not Phlex TV

**Comment by silentjon** [comment]
same issue for me, posting to follow.

**Comment by mattcallaway** [comment]
Used this URL and it worked. 

https://phlexserver.cookiehigh.us/api.php?apiToken=[API]&serverAddress=[IP:PORT]

**Comment by t3ix** [comment]
nothing happens when i click on link google
someone can help me please

**Comment by d8ahazard** [comment]
Phlex has quite a verbose logging system. I'd recommend providing a bit
more information from those logs so I can help you resolve the issue.

**Comment by t3ix** [comment]
it's ok i resolved it, can you give me your email to talk about phlex 
thanks

**Comment by d8ahazard** [comment]
Donate.to.digitalhigh@gmail.com
