### ISSUE TITLE
Other "English" languages are not supported

### ISSUE THREAD

**Issue by MrMaxP** [d8ahazard/Phlex#32]
Anything other than an American English device gives an error. I.e. When you issue the command "Talk to Flex TV" on a Google Home device set up for British English, Gooogle Home responds "Flex TV isn't available on devices setup for British English".

**Comment by christopherbruce** [comment]
This was discussed already over [here](https://github.com/d8ahazard/Phlex/issues/18) — It's a limitation of Google's API. The solution now is to just switch to US English, or use the IFTTT hooks.

**Comment by MrMaxP** [comment]
Thanks. I didn't see the other issue raised. Poking around a bit it seems as though there are no firm plans as when Actions will support other languages...
https://plus.google.com/+WaynePiekarski/posts/3Dozat8LjHh
