### ISSUE TITLE
Chromecast device not detected

### ISSUE THREAD

**Issue by killpilot80** [d8ahazard/Phlex#320]
hi guy,

i just finish to install Phlex into docker contener (in the QNAP). the install is ok, and web service work fine, my plex account is ok, i see my server.

for install i used this contener

https://hub.docker.com/r/digitalhigh/phlex/

into my pfsense i nat and open 5666 and 5667 port. the acces from outside is ok and work fine.

my issu is, phlex do not discovery my player device (chromecast second gen and chromecast ultra).

into the log there are :
Fri, 02 Feb 2018 15:17:34 +0100util.php::fetchCastDevices
Returns: []
Fri, 02 Feb 2018 15:17:34 +0100Chromecast.php::scan
Scan result: Array
Fri, 02 Feb 2018 15:17:29 +0100mdns.php::__construct
PHP is detecting the OS as Linux
Fri, 02 Feb 2018 15:17:29 +0100Chromecast.php::scansub
Function fired.
Fri, 02 Feb 2018 15:17:29 +0100util.php::fetchCastDevices
Function fired.

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)

is 2eea7e

ps : sorry i'm french and my english is worse :P

thank for your help.

**Comment by d8ahazard** [comment]
Cast functionality is highly unstable, and as such, has been moved to a custom Plex plugin that you install on your local Plex Media server.

I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
