### ISSUE TITLE
Limit www writable area

### ISSUE THREAD

**Issue by Duffyx** [d8ahazard/Phlex#321]
At the moment if I understand correctly, the whole top www directory needs to writable.
I imagine that Phlex saves some files here for setting-up/configuring.
Altough I feel that these files could also be written in a subdirectory of the top www directory.
This would benefit the security of the running webserver. Could you look into this?

**Comment by d8ahazard** [comment]
Just committed to beta a patch that moves all write-required files to /rw in the project dir.

In total, /log and /rw will need write access...also, manifest.json if you want service worker to run.
