### ISSUE TITLE
Phlex on root server // no port forwarding possible

### ISSUE THREAD

**Issue by schealex** [d8ahazard/Phlex#324]
Hey there,

first of all, you did an awesome job on this peace of tech!

i'm getting cable internet and i don't have a ipv4 adress.
my router is connected via a vlan ipv6 to a hub at my provider.
there is no technical possability to reach my network from the "outside".

is it still possible to use Phlex if i throw it on a webserver?
does Phlex need to be ON the local network?

Any help would be greatly appreciated!

Regards,

Alex

**Comment by schealex** [comment]
i've now tried to go the full ipv6 route but the server that is responsible for the google linking only give me a white page:

https://phlexserver.cookiehigh.us/api.php?apiToken=xxxxx&serverAddress=http://[xxx:xxx:xx:xxx:x:xxxxx:xxxxx]:8033/

and yes the adress http://[xxx:xxx:xx:xxx:x:xxxxx:xxxxx]:8033/ is working via browser from outside my network

**Comment by d8ahazard** [comment]
I never considered IP v6 when any of the linking stuff was written.  More
than likely I will need to make sure that I'm filtering and checking for
IPv6 and acting accordingly.

**Comment by schealex** [comment]
I see. I'm a developer too but I've never worked with socket and ip stuff for like networking stuff.
Would it be hard / take long to adjust the system?

Btw I tried making a subdomain and setting a AAAAA record to my ipv6 address. The subdomain works fine in a browser but the account linking doesn't work. Still white page

**Comment by d8ahazard** [comment]
I'll put this on the to-do list for V2...

**Comment by d8ahazard** [comment]
On a quick investigation, I think I'll probably utilize this library to do
the URL validation...

https://github.com/Fleshgrinder/php-url-validator/blob/master/src/Fleshgrinder/Validator/URL.php

**Comment by ndom91** [comment]
Why not try ngrok? https://ngrok.com/

I think its built especially for times like this :)
