### ISSUE TITLE
Playing trailers

### ISSUE THREAD

**Issue by mitchy112** [d8ahazard/Phlex#326]
I feel stupid for posting this, I dont know if this is something from Phlex or plex but i will post it here.
When i play via my android tv box with a voice momand (which is fixed because of this awesome developper) it doesnt want to play trailers, which i do have when i select manually on my tv box. How do i do this?

**Comment by d8ahazard** [comment]
Ah. You mean the optional feature to start trailers before a movie/show plays, like a normal movie??

That's a good one. I only turned this on for a few days, then got annoyed by it and turned it off.

I'm curious - if you use Plex.tv and connect to your player, then play something - do trailers work then?

If it works with Plex.tv site, then it's an issue on my part and I need to fix it. If it doesn't, then it's just how Plex made it work and it's unlikely I can do anything about that, short of seeing if Plex has trailers listed somewhere, then scraping them, having you set a default number to play in *Flex TV*, and then manually firing trailers before a movie, etc. 

Which is a lot of work when I'm already pretty busy with the redesign.

If you can check it out and let me know how it works with Plex.tv, we can go from there.

**Comment by mitchy112** [comment]
Hi d8ahazard, thanks for your fast response.
I don't really know what you mean by connect to your player by plex.tv.
If i play via plex.tv (web player) it  plays the trailer if that's what you are asking,. If it's not could you explain what you mean? -> I can set it up in the web player anyways. (it's an option)
And i know you are busy, you can put this on low level if it can be made in Phlex.

Anyways, only good vibes from here you've done a great job on Phlex!

**Comment by Elinombrable** [comment]
Even if it's a setting done at server side, i think each client can specify their own setup for this. Please, check if when you play a movie directly from your Android TV box, the trailers are played.

**Comment by d8ahazard** [comment]
Closing, as this is a feature of the player/server setup, not the app.
