### ISSUE TITLE
Play latest Episode Command not working

### ISSUE THREAD

**Issue by crhammock** [d8ahazard/Phlex#328]
I think I have Phlex working well, it is consistently able to play any movie from my plex library without issue. My problem appears to be with any tv shows, specifically the command "play the latest episode of ...". For example if I ask "play the latest episode of Star Trek Discovery" I get a generic response like "sure thing" and nothing happens. If I ask "play Star Trek Discovery season 1 episode 14" (or whatever the latest episode is) it plays as seemless as a movie.

I raised this issue previously and was asked to upgrade from the master to the beta brunch, I have since done this and still encounter the error.  I have attached logs from the time period of the error.

#### 1. On what OS are you running Phlex?
QNAP

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
Existing Webserver

#### 2b. If not XAMPP, what WebServer stack are you using?
Apache

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
I believe so

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.
I have attached and pasted the logs around the time of recreating the issue

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
7bb5

**Comment by crhammock** [comment]
[Broken.txt](https://github.com/d8ahazard/Phlex/files/1734760/Broken.txt)
 Attached file taken from Phlex.log.php, there are no logs in Phlex_error.log.php

**Comment by d8ahazard** [comment]
Fixed with V2!
