### ISSUE TITLE
Docker:  pm.max_children too low causing long delays

### ISSUE THREAD

**Issue by Fmstrat** [d8ahazard/Phlex#330]
Phlex responds very very slowly after it's been running for a bit. For instance, asking to play a movie from Google Home takes about 3 minutes to start playback. Restarting the docker containers fixes the issue temporarily.

For a fix, I set the value to 50 in `/etc/php7/php-fpm.d/www.conf` and that seemed to do the trick. No idea what a good number should be, but 5 seems to be too low.

#### 1. On what OS are you running Phlex?

Docker, behind an nginx docker image

#### 2. Are you using a new instance of XAMPP, or an existing webserver?

n/a

#### 2b. If not XAMPP, what WebServer stack are you using?

n/a

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
n/a

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?

Yes

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

```
==> php/error.log <==
[28-Feb-2018 13:40:10] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
```

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)

dd9a69

**Comment by Fmstrat** [comment]
So, while this is an issue, it doesn't correct the log delays. No idea what's going on as the logs don't show anything.

**Comment by d8ahazard** [comment]
Is this still an issue? I've now got the app in V2, so if you're still having problems, feel free to open an issue on the git for the Docker image, and we can work through it there:

https://github.com/d8ahazard/docker-phlex
