### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by Imburr** [d8ahazard/Phlex#331]
cdill@ubuntu16docker: docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
hammy556/docker-phlex-beta   latest              6f433bf23594        11 days ago         123 MB
digitalhigh/phlex            latest              6df5d677a1df        6 weeks ago         123 MB
cdill@ubuntu16docker: docker run hammy556/docker-phlex-beta
standard_init_linux.go:178: exec user process caused "exec format error"
cdill@ubuntu16docker: docker run digitalhigh/phlex
standard_init_linux.go:178: exec user process caused "exec format error"
cdill@ubuntu16docker:

I do not think its a phlex issue, but rather Docker. Have you seen this before and perhaps can throw me a hint?

**Comment by shapetheLOLa** [comment]
I've seen this on a raspberry pi when using a AMD64 image. But you're using ubuntu 16.x so I assume its no raspberry.

**Comment by samip5** [comment]
That has something to do with trying to use a wrong architecture image.

**Comment by d8ahazard** [comment]
Is this resolved?

If not, please create an issue on the git for the docker image so I can track it properly:

https://github.com/d8ahazard/docker-phlex
