### ISSUE TITLE
Errors with google assistant

### ISSUE THREAD

**Issue by redricka** [d8ahazard/Phlex#336]
If submitting a feature request, these are not required.

#### 1. On what OS are you running Phlex?
Raspbian Stretch - 
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
New. 

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes. 

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section? Yes

I am just having an issue with google assistant, when i ask her to talk to flex tv and play something. Flex tv comes back and says "unexpected error has occured", parsing error etc most likely an out of date installation. I used the most current steps of installing, and configuring. 
Anyone know why this has occured?

**Comment by redricka** [comment]
google responds with this 

An error has occurred. Please report the following message to the developer: "Hmmm, it looks like there was an issue parsing the response from your phlex client. This is most likely due to an out-of-date installation. Please check that phlex is at the latest version. The error message was Syntax error. 


Any help? I used the latest installation of phlex

**Comment by d8ahazard** [comment]
I think I fixed this server-side a while ago.

If not, please open a new issue so I can track fresh problems...
