### ISSUE TITLE
change cast device from....

### ISSUE THREAD

**Issue by stardobas** [d8ahazard/Phlex#339]
simple question... I'm windows user, today I've install phlex, I have two unsolved question.
I use google home, It work with ifttt and phlex, I'm italian (very difficult for my google home to understand two language together)...

I need to know how to change device (I've 5 chromecast) using ifttt text field ...if I write "play star wars on Tv sala", it works.... but if I write "play star wars on tv cucina" it doesn't work... but TV cucina and TV SALA are either cast device listed inside phlex...
Phlex search is very bad for me...don't find a lot of my files listed inside plex... I think is a language problem..isn't it?
**please specify me the correct syntax for command ** send in text field like:
http://xxxx:6666/api.php?say&apiToken=851cc11286d7df2b297bd0892309d41676272b9af9&command={{TextField}}

TEXT FIELD can be used to change cast device? folder type (like film or music)? or can only play/stop/pause and search film?

**Comment by gabryk91** [comment]
Ciao @stardobas tu che impostazioni hai messo nella parte web hook di phlex? Ho fatto una applet IFFFT di tipo "I want to watch $", google home capisce e mi risponde la frase che ho impostato, sul cell mi arriva la notifica IFFFT che l'applet è partita, ma quello che ho chiesto non viene riprodotto. Sto diventando matto :-(

**Comment by stardobas** [comment]
Quella scritta.. richiesta tipo get... Json... poi http://xxxx:6666/api.php?say&apiToken=851cc11286d7df2b297bd0892309d41676272b9af9&command= 

Al posto di x.x.x.x metti l'ip, dove c'è 6666 metti la tua porta, dopo Token= metti il token del tuo Phlex, dopo command= lasci 
 {{TextField} poi devi aprire la porta (che hai scelto sul router) ...in phlex devi scegliere il device su sui riprodurre... detto questo funziona... anche se non come voglio io e l'ho levato.... forse giusto per la musica può andare bene...

**Comment by gabryk91** [comment]
Ma la frase di attivazione che hai usato qual'è? Ho visto che il comportamento di gh varia molto a seconda della frase che imposto. A volte mi risponde ok! e poi non fa niente, a volte mi dice che quello che ho chiesto non è disponibile (ripetendo il nome del film).

**Comment by d8ahazard** [comment]
Examples:

**IFTTT Trigger:** Tell Plex to play $"
**URL:** http://xxxx:6666/api.php?say&apiToken=851cc11286d7df2b297bd0892309d41676272b9af9&command=play+{{TextField}}

**IFTTT Trigger:** Tell Plex to download $"
**URL:** http://xxxx:6666/api.php?say&apiToken=851cc11286d7df2b297bd0892309d41676272b9af9&command=download+{{TextField}}

**IFTTT Trigger:** Pirate the movie named $"
**URL:** http://xxxx:6666/api.php?say&apiToken=851cc11286d7df2b297bd0892309d41676272b9af9&command=downlad+the+movie+{{TextField}}

Hope this helps! I'll be trying to update the Wiki this weekend with better documentation for everything.
