### ISSUE TITLE
Unable to connect to client

### ISSUE THREAD

**Issue by znorris** [d8ahazard/Phlex#34]
`Unable to connect to Client, please check the setting for 'Public Address'.`

I'm writing a `Dockerfile` to contribute to your repository and I've run into the above error when setting up for the first time.

I've tried 2 scenarios:
1. Apache listening on port 80. Externally available on port 32769.
2. Apache listening on port 32769 and externally available on the same.

Testing included:
1. Contacting `http://localhost:32769` from the machine running apache. This test works.
2. Contacting `http://<my_public_ip>:32769` from a machine outside of my local network. This test works.

**Comment by d8ahazard** [comment]
In the Phlex UI, are you setting the "public address" field to use "http://<my_public_ip>:32769"?  

Also, FWIW, I do have a docker repo already at http://github.com/d8ahazard/docker_phlex - I'm by far from being a docker expert - if you'd like to work from that, feel free to fork and submit a PR.  ;)

**Comment by znorris** [comment]
Yes, that was one of the things I tried.

I also tried what is in the [docs](https://github.com/d8ahazard/Phlex#setting-it-up-with-google-assistant), `http://<my_public_ip>/Phlex:32769`, and variations on it such as `http://<my_public_ip>:32769/Phlex:32769`. However, using any form of  `http://<IP>:<PORT>/` seems to fail quickly which tells me there isn't an error in the docs.

Nice. I'll take a look at that Dockerfile.

**Comment by d8ahazard** [comment]
Can you please try updating your docker image and seeing if the newest commits help with your issue?  

You should be using http://<IP>:<PORT>/Phlex as your URL format.  I'll update the docs accordingly.

**Comment by chrisstaite** [comment]
I had this issue and it was because the config.ini had another section that had a different token in it for a cast device.  The issue seems to be the else part of the token check in api.php should be removed as it is checked further down when $valid is verified.

**Comment by d8ahazard** [comment]
Docker should now be updated and working for all clients.  

You will need to update to the latest image and review the changes - specifically, you need to create a new container WITHOUT any exposed ports.  Using --net=host seems to be the sliver bullet.  

Feel free to open a new issue if the problem persists.
