### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by abbyhomeav** [d8ahazard/Phlex#340]
#### 1. On what OS are you running Phlex?
windows 10

#### 2. Are you using a new instance of XAMPP, or an existing webserver?

new instance, i did previously have it installed using the old version and it worked sometimes but most of the time it didn't play the movie it just did nothing. Now i uninstalled everything including xampp and  reinstalled everything to use the beta version (hoping it would work better). i never saved the api key i thought i would just start from very beginning (is this causing the problem?)

#### 2b. If not XAMPP, what WebServer stack are you using?
N/A

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?

i have enabled the sockets following instruction related to  extension=php_sockets.dll

permission to the htdocs folder seem normal and the same as they were on the old install but i'm not sure i fully understand what your asking here.

I have attached error logs here

[Phlex.log.php.txt](https://github.com/d8ahazard/Phlex/files/1945421/Phlex.log.php.txt)
[Phlex_error.log.php.txt](https://github.com/d8ahazard/Phlex/files/1945422/Phlex_error.log.php.txt)
[Phlex_update.log.php.txt](https://github.com/d8ahazard/Phlex/files/1945423/Phlex_update.log.php.txt)

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section? 
yes its ok, im able to access the server from an external ip.  instead of getting the phlex login page im getting an error (see below)

Fatal error: Uncaught InvalidArgumentException: Unable to read specified file. in C:\xampp\htdocs\php\JsonConfig.php:28 Stack trace: #0 C:\xampp\htdocs\php\JsonConfig.php(20): JsonConfig->read() #1 C:\xampp\htdocs\php\homeApp.php(120): JsonConfig->__construct('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\php\homeApp.php(132): readConfig('general', 'deviceID', false) #3 C:\xampp\htdocs\index.php(9): checkSetDeviceID() #4 {main} thrown in C:\xampp\htdocs\php\JsonConfig.php on line 28

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)

i am not able to get into this anymore to find out.

I'm not great at this so apologies if this is something stupid.. 

i have also changed the Plex server name after i uninstalled the  orignal version but before i installed the beta, does that matter?
I have plex and phlex/xampp all running on the same pc if thats relevant.

thanks
yzbob

**Comment by yzbob** [comment]
1 other thing, i changed the friendly name of the plex server, preferred it to be different to the name of the player, does that matter?
another thing that might be useful, my plex server, plex player and phlex/xampp are all running on the same pc.

**Comment by abbyhomeav** [comment]
i seem to have solved this by deleting the config.ini.php

Now i have a new issue, When i access my flextv from outside (or inside) my network i get the login page, click "DO IT!" get successfully signed in on the plex page then i get sent back ot phlex page with the spinny login thing that just spins forever, and occasionally the backdrop changes.

looking in the log is it something to do with not getting an auth token?

<img width="997" alt="screen shot 2018-04-27 at 12 45 03 am" src="https://user-images.githubusercontent.com/38680185/39345071-688ee7a2-49b4-11e8-9301-530485441475.png">

on a side note, how do i get the log to show the correct time zone?

Thanks
yzbob

**Comment by abbyhomeav** [comment]
it seems every time i delete the config.ini file i am able to log back into phlex one time from one device but the rest of the devices just spin around at the login screen. when i do the i get a message saying **An update is available.
An update is available for Phlex. Click here to install it now.**

but there is nothing clickable,

When i click "test connectivity" nothing happens
when i click "link google" i just get a white screen with "ERROR"

Im wondering if these are all things i should be able to solve myself of if there is something wrong thats outwith my control? 

Would really appreciate if someone could point me in the right direction. 
Also is the the best place to be asking these type of questions?

thanks
yzbob

**Comment by d8ahazard** [comment]
This should be fixed.
