### ISSUE TITLE
PHP Extension not loaded

### ISSUE THREAD

**Issue by Firehawk39** [d8ahazard/Phlex#341]
Problem says "The Sockets PHP Extension,which is required for Phlex to work correctly,is not loaded.Please enable it in php.ini,restart your webserver and then reload this page to continue"
This happens when i every time click admin in Xampp application for Phlex Log in
Please help me to fix this problem.And thank you for making such a great idea in real life

**Comment by d8ahazard** [comment]
So...under Xampp control panel, go here, and edit your php.ini file:

**Comment by Firehawk39** [comment]
Sorry sir i really didn't get that, please explain me in brief.

**Comment by d8ahazard** [comment]
Look at the first picture:


Make it look like the second picture:

**Comment by Firehawk39** [comment]
Sir,After following your steps i have reached to the Phlex Home Page but now when i am trying to Link My Google i am experiencing this "Unable to connect to Client at <a href='http://localhost/'>http://localhost/</a>, please check the setting for 'Public Address' in the Phlex UI."

**Comment by d8ahazard** [comment]
https://github.com/d8ahazard/Phlex/wiki/Talking-To-The-Outside-World

**Comment by Firehawk39** [comment]
After inserting my public I.P Address in the Public Address i am still getting the error "unable to connect to client"

**Comment by d8ahazard** [comment]
Is this still a problem? The app is now in V2 mode, I recommend updating and opening a new issue if you're still having problems.

Also, you may want to consider the version I'm hosting for the world:

https://app.phlexchat.com
