### ISSUE TITLE
Phlex gets the command and do nothing

### ISSUE THREAD

**Issue by gabryk91** [d8ahazard/Phlex#342]
#### 1. On what OS are you running Phlex?
Windows
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
New
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.
I made an IFFFT applet : the activation phrase is "I want to watch $", google home answers ok! and on Phlex interface I can see that it gets the input, but nothing happens. 
Also, the only phrase that trigger something is "I want to watch $", everything else like "Tell Plex to play $" simply doesn't work.

The log:
```
Full API.AI request: 
{
  "id": "3f04029b-fa2f-4b06-91d5-8f148a265cbf",
  "timestamp": "2018-04-27T20:08:33.613Z",
  "lang": "en",
  "result": {
    "source": "agent",
    "resolvedQuery": "Blind spot",
    "fulfillment": []
  },
  "status": {
    "code": 200,
    "errorType": "success"
  },
  "sessionId": "b96ffdbd3f06c0ebd870270bf890607eba68",
  "originalRequest": {
    "data": {
      "inputs": [
        {
          "raw_inputs": [
            {
              "query": "Blind spot"
            }
          ]
        }
      ]
    }
  }
}
```

And also:

`Final params should be an action of , a command of , a type of , and a control of .`

On Phlex I can read:
You said: "Blindspot."
My reply:  " blindspot'.

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
16b98c

**Comment by gabryk91** [comment]
Result JSON:
{
  "serverURI": "http://x.x.x.x:32400",
  "serverToken": "bsxsGCEA6MW89eKrHktp",
  "clientURI": "https://x.x.x.x:8009",
  "clientName": "",
  "initialCommand": "Play Blind spot",
  "timestamp": "Fri, 27 Apr 2018 22:15:24 +0200",
  "commandType": false,
  "parsedCommand": "Command not recognized.",
  "mediaStatus": "ERROR: Command not recognized.",
  "speech": " Play Blind spot'.",
  "timecode": 1524860124
}

**Comment by gabryk91** [comment]
After countless try I get something by using 
"I want to watch $" and http://xxxx/Phlex/api.php?**play**&apiToken=blabla&command={{TextField}}
and
"I want to $" and http://xxxx/Phlex/api.php?control&apiToken=blabla&command={{TextField}} (it stops playing)

Now I'm asking: there's a way to play something when plex is already connected to the chromecast?
Right now the play command only works when plex is not connected

**Comment by d8ahazard** [comment]
Try this:

To play:
**Example:** "I want to watch $"
**URL:**  http://xxxx/Phlex/api.php?say&apiToken=blabla&command=PLAY+{{TextField}}

Control:
**Example:** "Tell Plex to $"
**URL:**  http://xxxx/Phlex/api.php?say&apiToken=blabla&command={{TextField}}

Fetch:
**Example:** "Tell Plex to download $"
**URL:**  http://xxxx/Phlex/api.php?say&apiToken=blabla&command=download+{{TextField}}
