### ISSUE TITLE
Sockets ext enabled, but still a warning

### ISSUE THREAD

**Issue by Ballzup** [d8ahazard/Phlex#343]
#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex) Cant get that far

I've been having issues connecting to google. And while I was messing around with that, i did a restart of my PC and now, when loading the Phlex UI i get a warning about the Sockets extension. but Ive tripple checked that I've enabled it. So i assumes there's a write access issue? If so How do i resolve that?

**Comment by Ballzup** [comment]
Update, Have attempted a fresh install of everything and still I'm having the same issue. If I click Admin in XAMPP to start Phlex UI the login screen shows up but I also get a pop up notification telling me I need to enable the Sockets Extension. I've done that by removing the ";" then restarted the server and refreshed the page but still it happens. 

If I manually enter the address in the browser I don't get the pop up.

Either way, when I log in with my Plex credentials it just hangs forever with "one moment..." at the bottom of the screen.

Few things worth noting (may or may not be relevant as a lot of this is beyond my scope of understanding):
- Confirm Plex is fully available outside my network (verified by phone) but this only works if I dont manually assign a port. Port 80 is blocked by my ISP and they wont unblock it for me so I've been working with the port that plex auto assigns for external access.
- Phlex was installed via git
- I'm pretty confident I've given write access to the Phlex folder (right clicked the folder and provided full access to Everyone and ensured its not read only)
- firewall rules are set to allow both incoming and outgoing connections for the applicable port

Any help that anyone can provide would be greatly appreciated. I've gone through as many reported issues as I can with no success.

**Comment by d8ahazard** [comment]
Try the V2 version...now without any of that pesky Sockets crap!

https://app.phlexchat.com
