### ISSUE TITLE
Beta problems

### ISSUE THREAD

**Issue by bear269** [d8ahazard/Phlex#344]
### IMPORANT, PLEASE READ FIRST:

Due to an overwhelming amount of issues with cast devices and network issues in general, I've begun
a complete overhaul of the codebase behind Flex TV. This includes delgating cast functionality to a custom
Plex Media Server plugin (https://github.com/d8ahazard/Cast.bundle), as well as a major reworking of device
scraping and storage, fetcher interactions, UI overhauls, and basically - rewriting a massive chunk of
the application.

Pending the release of Flex TV v2, I ask that you refrain from submitting issues regarding...well...most of the things.

Casting, device fetching, data storage, signin issues, media fetcher interactions, multiple languages...all
of these are receiving major love...and so until then, just sit tight.

I am still looking for OS-related issues (FreeBSD causes problems), and issues related to one-off players, smart TV's,
things that aren't related to casting or server connectivity. Also, feature requests.

That said - we now return you to your regularly scheduled program.

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 2. Are you using a new instance of XAMPP, or an existing webserver
New with php 7.2

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Its not verbatim but did put line in manually under ;extention=sockets
To read exention=php_sockets.dll as their is no line ;exention=php_sockets.dll in config.ini

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)cant acess anything right now installed beta

Fatal error: Uncaught InvalidArgumentException: Unable to read specified file. in C:\xampp\htdocs\phlex\php\JsonConfig.php:30 Stack trace: #0 C:\xampp\htdocs\phlex\php\JsonConfig.php(20): JsonConfig->read() #1 C:\xampp\htdocs\phlex\php\homeApp.php(120): JsonConfig->__construct('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\phlex\php\homeApp.php(132): readConfig('general', 'deviceID', false) #3 C:\xampp\htdocs\phlex\index.php(9): checkSetDeviceID() #4 {main} thrown in C:\xampp\htdocs\phlex\php\JsonConfig.php on line 30

**Comment by nick-potts** [comment]
You'll want to delete _rw/config.ini.php_ If you are running it in docker, that'll be _www/Phlex/rw/config.ini.php_

**Comment by d8ahazard** [comment]
This has been re-worked extensively, should be a non-issue now.

Feel free to re-open if I'm wrong.
