### ISSUE TITLE
My Tv is not shown in the device list

### ISSUE THREAD

**Issue by ziogianni** [d8ahazard/Phlex#345]
Hello guys, I got a very weird behavior since my Samsung TV with the Plex app installed on, it is not shown in the Phlex device list.

Something weird since I have the plex app installed on my android phone and i'm able to cast any video to the TV from there. This's true also from the Plex server directly, but not form Phlex where the device doesn't appears.

The sever is installed on a small Raspberry Pi - Version 1.12.3.4973

I have also tried to insert the TV's IP as indirect device, but even though I'm able to execute the command via the api.php, on the TV nothing is played.

This is what I found in the logs:

Tue, 01 May 2018 10:02:17 +0000

api.php::playMedia
Playback Result:

```
{
  "url": "http://192.168.1.85:32500/player/playback/playMedia?key=%2Flibrary%2Fmetadata%2F5&offset=80181&machineIdentifier=3d2446fb08900035a32240ed6af93a88fc&protocol=https&address=192-168-1-12.8f0354db5260a790bf5106deb.plex.direct&port=32400&containerKey=%2FplayQueues%2F85%3Fown%3D1%26window%3D200&token=transient-99f11-69a2-432c-b8ce-23a0e07e9318&commandID=1",
  "status": "error"
}

Tue, 01 May 2018 10:02:17 +0000

api.php::fireHook
ERROR, no URL!

```

**Comment by d8ahazard** [comment]
Hey there, sorry for the late reply. 

Please make sure you've updated to the new V2 version (still in the Main branch) and have the Cast plugin installed. https://github.com/d8ahazard/Cast.bundle on a plex server in the same network as your TV.

If this still doesn't help, please open a new issue and attach logs of the resulting device scan.
