### ISSUE TITLE
All functionality completely broken

### ISSUE THREAD

**Issue by j0sh2003** [d8ahazard/Phlex#346]
#### 1. On what OS are you running Phlex?  
Windows 7, Raspberry Pi, Docker

#### 2. Are you using a new instance of XAMPP, or an existing webserver?  
New and existing (have tried both)

#### 2b. If not XAMPP, what WebServer stack are you using?  
XAMPP and Hass.IO

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?  
Yes

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?  
Yes

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.
See below - I am not able to get to logs

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)  
c00b90

Phlex has been working beautifully for me for several months.  Then about a week ago, I told it to play a title, and it wouldn't play.  I tried telling it to play a different title, and it wouldn't play.  I tried the command "stop" which normally stops media, but it didn't work.

I took a look at the JSON messages (I do not have the complete logs anymore because I completely deleted htdocs folder several times and didn't think to back up the logs first), and would get a response like this:

"initialCommand": "Play Futurama",
"commandType": false,
"parsedCommand": "Command not recognized.",
"mediaStatus": "ERROR: Command not recognized.",
"speech": " Play Futurama'.", 

I tried uninstalling and reinstalling Phlex, uninstalling and reinstalling XAMPP, unlinking and relinking Google, installing on a completely different machine (my Raspberry Pi and another Raspberry Pi running docker), and I get the same JSON response.  I can access from outside my network (accessed over mobile data on phone) both Phlex and Plex.  Phlex seems to know all about my Plex library, as far as I can tell.

Lastly, and most recently, I completely removed Phlex again, this time, installing Phlex Beta.  This one is even worse. I get told over and over to install the Cast.bundle plugin, even though it's already installed, and I can see it in Plex Plugins.  The Link to Google button is completely missing.  All that's there is a link for Amazon. I tried looking at the Wiki to make sure I wasn't missing something, and the Google linking section has been completely removed.  Furthermore, no matter what I enter into my public address field, I get an error:  "Invalid entry specified for publicAddress."  I get this error whether I use my domain name, IP, include/exclude http://, include/exclude index.php; it doesn't matter what I put, I get the error.  I can't even view the logs.  If I try, I get this error message in the browser:  

Notice: Undefined index: request_METHOD in C:\xampp\htdocs\Phlex\php\util.php on line 453
Invalid API Token

I've tried everything I can think of, and I don't even know why this stopped working in the first place, as there weren't any changes to my XAMPP or Plex configuration and no network changes.  I've also ruled out client issues by getting the same exact errors on other machines.  The only thing I can think of is that something has changed server side of Phlex.  Please help!  This has been working wonderfully for months, and now I'm losing hair.

Thanks.

**Comment by bebetaz** [comment]
Same errors here. Cant link Google, cand link Couchpotato... continuously get invalid entry, for couch, for Phlex Public address... nothing works :(

**Comment by d8ahazard** [comment]
The main version has been updated.  I'd try re installing.

If in doubt, you can try the web version first:

Https://app.phlexchat.com

**Comment by j0sh2003** [comment]
The new version is working great, except for one thing.  util.php curlGet is returning 500.  
<Response code="2000" status="FrameworkException: Unable to find player with identifier 192.168.86.35:8009">
This is the correct IP address for the Chromecast.  I went into the plugin and tried "Rescan Devices" and now all I can get is "The plugin is not responding."  I uninstalled and reinstalled the plugin from the latest source in the repo.  Same result.  Any ideas?  Thanks for your help!

**Comment by bebetaz** [comment]
Working great for me thank you. Great piece of software by the way ;)

How is v2 coming along? waiting for headphone integration ;)

Also, I haven't tried but can you tell phlex to download a TV serie?

Cheers,
bebetaz

**Comment by cortexstack** [comment]
I'm also having issues linking my Google account with Phlex. I get error 500 when trying to link from any device (desktop through the web interface or through Google Home app on Android after trying to talk to Phlex TV on Google Assistant)

app.phlexchat.com sees my Chromecast, Google Home etc, but localhost/Phlex/ just gives me a "Cast Plugin Not Found!" error whenever I try to scan for devices.

Everything was installed from your most up to date versions three days ago. Not sure where to go from here.

**Comment by d8ahazard** [comment]
@cortexstack - You need to have a Plex server on the same network as the cast devices you want to control, with the Cast support plugin installed. 

Even if you don't have any media, you can still spin up a server just to host the plugin. I intend on releasing a stand-alone version of this in the future...

Otherwise...V2 is now live and this version deprecated, so I'm closing this. If you have other issues, feel free to open a new report.
