### ISSUE TITLE
No longer able to set static device

### ISSUE THREAD

**Issue by mclc** [d8ahazard/Phlex#348]
#### 1. On what OS are you running Flex TV?
Raspberry Pi (Raspbian 9.1)

After the new update, I am no longer able to set a static device for casting. This is a problem when the Plex Media Server is remote, while the Chromecast is local.

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
f78661

**Comment by d8ahazard** [comment]
Yes.  Yes it is.  Unfortunately, it's necessary until the cast plugin is
ported to stand alone. For now, I'd recommend setting up a local Plex
server just for the plugin...

**Comment by mclc** [comment]
I have now tried your suggested solutions which unfortunately doesn't seem to work when it tries to play something. From what I can read from log files, it looks like it tries to play the media from my local Plex Server (which doesn't have any content).

**Comment by d8ahazard** [comment]
Are you updated to the latest version of both the Cast.bundle *and* Flex TV? 

I recently resolved a few issues with casting and server/client lookups, I'd be very surprised if this isn't working for you now. My guess is, what you're seeing in the logs is it trying to send a command to <your-server-address>/chromecast/... to actually trigger playback.

Also, when searching for media, it'll *try* to look at all servers you have listed...but only retrieve the data from the relevant one, and tag that media item with a "source" that identifies the server it lives on.

I'd make sure you're updated, then try a few commands and paste back any relevant logs you get...

**Comment by mclc** [comment]
I have made a fresh installation of both Flex TV and Cast.bundle using the newest version on Github. However, it still doesn't work. It replies "Yes master, I shall play X for you." but nothing starts playing on my Chromecast.

I have uploaded the cast logs here: https://pastebin.com/96HDY8E4
192.168.0.151 is my local server with Cast.bundle and no content.

**Comment by d8ahazard** [comment]
Is there more to that log? I see it connecting and launching the app, but
then the log stops where I'd expect to see status messages regarding actual
playback...

**Comment by mclc** [comment]
I have these entries about 2 minutes later: https://pastebin.com/Dy0f0UMj
