### ISSUE TITLE
radarr issue

### ISSUE THREAD

**Issue by phairplay** [d8ahazard/Phlex#351]
#### 1. On what OS are you running Flex TV?
Windows 10
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
XAMPP
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)

53df8d

hi,
we've spoken on plex forum but i though it would be best to detail the issue here.

you've recently pushed on update to fix the fetch feature. i can confirm sonarr works fine, yet radarr still doesn't work. Radarr is linked and the connection is confirmed

also how do you get radarr and sonarr to work on appphlexchat.  locally phlex doesn't see my plex (nothing comes back when asked "whats on deck") yet via your web page it does, but radarr and sonarr don't.

**Comment by MarcMorgan** [comment]
Any update on this as im the same, sonorr picks up fine but unable to search, fetch from Radarr. Connection shows fine and connected successful but not able find any content
