### ISSUE TITLE
SSL problems with wildcard cert

### ISSUE THREAD

**Issue by seriouslyharmed** [d8ahazard/Phlex#353]
#### 1. On what OS are you running Flex TV?
Docker on Ubuntu 16.04 

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
XAMPP

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

Error 51: SSL certificate subject name * does not match target hostname my.hostname.xyz

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
0c9028

I've run into a problem when hosting Phlex locally. When I setup to the local instance the Google Home answers with the error message above. It seems that there is an error with how wildcard certificates are handled. I cannot find anything relevant in my logs about the issue though. This doesn't happen when using the version hosted by you.

**Comment by d8ahazard** [comment]
Try it now once, I've just added some fixes to the mothership...

**Comment by seriouslyharmed** [comment]
Updated and it works perfectly now.
Also realised that I had some wonky configuration in nginx which I corrected. It works with the wildcard cert now.
