### ISSUE TITLE
Run Phlex on Synology (without docker)

### ISSUE THREAD

**Issue by vletroye** [d8ahazard/Phlex#358]
I was able to use Phlex via https://app.phlexchat.com/index.php

I tried next the docker image on my Synology. It works really fine.

Now, I would like to use it directly within on my Synology's Webstation (to possibly create a spk package. for Synology). 

Unfortunately I have a blank page when accessing phlex installed on my NAS. I don't know in which direction to investigate... Any help to understand how this is assumed to work would be very appreciated.

#### 1. On what OS are you running Flex TV?

DSM 6.1 of Synology

#### 2. Are you using a new instance of XAMPP, or an existing webserver?

Not using XAMPP

#### 2b. If not XAMPP, what WebServer stack are you using?

Using a Synology virtual host (port 80) running apache 2.4 with php 7.0 + modules curl, openssl, sockets and phar loaded. I don't have a module xml available on my Synology... Is this simply the issue ? I don't see errors in the log files. Only this: 

[Thu, 31 May 2018 22:07:43 +0200] [DEBUG] [webApp.php::checkFiles] - Creating file /volume1/web/phlex/php/../logs/Phlex_error.log.php
[Thu, 31 May 2018 22:07:43 +0200] [DEBUG] [webApp.php::checkFiles] - Creating file /volume1/web/phlex/php/../logs/Phlex_update.log.php
[Thu, 31 May 2018 22:07:43 +0200] [DEBUG] [webApp.php::checkFiles] - Creating file /volume1/web/phlex/php/../rw/config.php
[Thu, 31 May 2018 22:07:43 +0200] [WARN] [JsonConfig.php::read] - Blank file, creating array.

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?

Yes. And all access are granted to read/write config file and log files.

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?

No. I am not yet at that step

**Comment by d8ahazard** [comment]
Hey hey!

You're in luck. My development platform happens to *be* DSM 6.1.

You need to make sure you have the PHP 7.x package installed from the
package center.

Then, in web station, make sure php 7 is enabled.

Under general settings, make sure PHP 7 is set as the default profile. (Not
necessary, but recommended. I leave the default Back-end server as NGINX.

Under vhosts, create a new one - I went with phlex.mydomain.net.

Set the document root to where you put Flex TV. I have mine in
volume1/Webroot/Phlex

Check the box for port (80/443)

Then, select php7 for PHP version. I'm using 'apache' as the web engine
here, but I'm not sure if it's necessary or not.

Also, under PHP Settings in Webstation, open up settings for PHP7.

I have all of the modules enabled, and added ":/volume1/Webroot" to the
open_basedir restriction. Or, maybe it was there. I forget, but it should
be there.


And that's it. That's how I've got my webstation set up for Flex TV.

Also, here's the JSON config for my working docker image:

`{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "",
   "cpu_priority" : 0,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : true,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" :
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "PS1",
         "value" : "$(whoami)@$(hostname):$(pwd)$ "
      },
      {
         "key" : "HOME",
         "value" : "/root"
      },
      {
         "key" : "TERM",
         "value" : "xterm"
      },
      {
         "key" : "S6_BEHAVIOUR_IF_STAGE2_FAILS",
         "value" : "2"
      },
      {
         "key" : "TZ",
         "value" : "America/Chicago"
      }
   ],
   "exporting" : false,
   "id" :
"62977e46b4547a1b093682e713a924525657afbde2732c678b01701555048f77",
   "image" : "38d15771a22f",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "FlexTV",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "default",
   "port_bindings" : [
      {
         "container_port" : 443,
         "host_port" : 5667,
         "type" : "tcp"
      },
      {
         "container_port" : 80,
         "host_port" : 5666,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "ulimits" : null,
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/Phlex",
         "mount_point" : "/config",
         "type" : "rw"
      }
   ],
   "volumes_from" : null
}
`

Looks like maybe the instructions are wrong, and you need to bind to 80/443
on the container side to whatever ports you want host-side.

**Comment by vletroye** [comment]
Many thx for your info !

I have quite the same setup as you, although done via a Virtual Website, as I may not define php 7.x and Apache as default for all websites on my NAS. 

I see two differences: 
- you have enabled all the modules. Which is not my case. I only enabled curl, openssl and phar. I don't have a module named xml for example. But I will try to enable them all asap (right now, I am configuring a new box to control smart devices at home.

- My config file is empty. I thought indeed that the config would be created via your web interface. I will start from your.

I come back for sure with the outcomes later this weekend.

V.

**Comment by vletroye** [comment]
Ok... so, it works but, I don't now why :D :D :D :D

I confirm PHP 7.0 is "Installed" via Package Manager (as well as 5.6) and "Running"

In my Web Station.
**Under Status:** 
- PHP 7.0 is "Installed" 

[Screenshot](https://i.imgur.com/sjZ36TK.png)

**Under General Settings**
- the Http back-end server is Apache 2.4 and PHP is PHP 5.6. I may not change these defaults otherwise my Wordpress won't run fine anymore... But it(s not a problem as, just like you, I am using a Virtual Host for Phlex

[Screenshot](https://i.imgur.com/25h1NgI.png)

**Under PHP Settings:**  
- it is configured. ("Enable PHP cache" and all modules loaded).
- I didn't customize the open_basedir because mine is the default one of DSM : /volume1/web. And it is working fine for all my other websites.

**Under Virtual Host** 
I have create a Virtual Host with Apache 2.4 as a web server, with PHP 7.0 .

[Screenshot](https://i.imgur.com/AKHcZ8r.png)

I was a bit lost because you mention the JSON config of your docker image ?! It's just for illustration purpose, right ? You don't call your Docker Image from you WebStation  ?! 

I did copy your config into config.php... But I got this in the log file:

[Sun, 03 Jun 2018 09:24:32 +0200] [ALERT] [JsonConfig.php::read] - JSON Decode failed!!
[Sun, 03 Jun 2018 09:24:37 +0200] [DEBUG] [webApp.php::checkFiles] - Creating file /volume1/web/phlex/php/../rw/config.php
[Sun, 03 Jun 2018 09:24:37 +0200] [WARN] [JsonConfig.php::read] - Blank file, creating array.

So, I decided to drop the complete web folder /phlex and to donwload again you master branch. I copied this new download into my web folder and.... it works ?!?!? 

I see that now, Phlex has created and filled a config file... Which was not the case previously. It was empty.

Such a great app ! 

V.

**Comment by soates1127** [comment]
Would it be possible to make this installable from a repo or something?

**Comment by d8ahazard** [comment]
@vletroye - Yes, I'm sorry, I think I may have been vague. The JSON can be imported into Synology Docker under containers, and should get you working on Docker, if you chose. This is totally separate from how I set up reverse proxy for the files.

In my environment, I have a docker container running, purely for testing, and then I *also* have the git repository set up under webstation, which is where I actually develop the application.

@soates1127 - Sure, it's *possible*. In fact, I think I've still got the docker "make a SPK" container sitting on my server somewhere. However, I just haven't had the time to sit down, go over the documentation, and figure out how to package it up.

It should be relatively simple to pull off, but would require knowing how to configure the package to auto-require PHP7, set up necessary web params, etc.

All of this is stuff I don't have time to focus on currently. :( 

But, I'd love help if you know of anybody who can do it. I'd imagine there are already other packages that are just web apps pulled from GIT.


However, if you install the "git server" SPK, then SSH into your Synology, it's entirely possible to just git clone this repository, configure as I described above, and then it'll just work. The self-hosted version also has the option to auto-update, which, when working, would then really remove most of the need for a SPK...

**Comment by vletroye** [comment]
I am also trying to create my own SPK... But so far, the app is not running... It's the first time I have to create a spk with dependencies on modules to be loaded with php...

**Comment by vletroye** [comment]
Yeehaaaaaaaaaaaaaaw !!! First step successful... the website runs now embedded in DSM (using PHP 7 on NGINX without dependency on the WebStation)

![Phlex in DSM](https://i.imgur.com/oJx5p8X.png)

It's too long to explain how here (and possibly it's only ok my DSM....). But basic info are here : https://github.com/vletroye/SynoPackages/wiki/MODS-Basic-Test-CGI

Now, I still have to look how to load the required modules with my SPK... I never investigated how to do this before.

**Comment by d8ahazard** [comment]
Dude, this is amazing!

**Comment by vletroye** [comment]
That's only a first step...... The most difficult part for me is to load the modules Curl, OpenSSL, Sockets... via the command php70-cgi

**Comment by d8ahazard** [comment]
If it helps, sockets is no longer a requirement. Just curl, openssl, and
XML.

**Comment by d8ahazard** [comment]
Also, I'm wondering if you just need to enable them in the php default
config in webstation??

**Comment by d8ahazard** [comment]
https://developer.synology.com/download/developer-guide.pdf

PP 94 - talks about configuring php by symlinking a customized php.ini file
within the package?

**Comment by vletroye** [comment]
Tadaaaa : 
![image](https://user-images.githubusercontent.com/9768028/40936796-cd435312-683c-11e8-8c59-6d3ee15f0786.png)

I simply load the Synology php.ini with php70-cgi... I will customize further my package later to use its own php.ini

Unfortunately... I have next the same issue I had with Web Station: a blank screen 

![image](https://user-images.githubusercontent.com/9768028/40936873-0d7d9c62-683d-11e8-8c77-20a04fe9aa79.png)

**Comment by vletroye** [comment]
LOL Gotcha !!! Simply a security issue wth the switch to Plex for signing in... 

I have a workaround ... Open Phlex in a new window instead of opening embedded... (I never found how to add trusted external websites into DSM, to open them embedded :( )

![image](https://user-images.githubusercontent.com/9768028/40936922-43f4a97a-683d-11e8-8bab-46fc92db9dfe.png)

**Comment by d8ahazard** [comment]
AWESOME!!!!!!

FWIW, I'm now referring to the app as "Flex TV" everywhere but the git
repo, just for "official" purposes. The app logo can also be found in the
/img directory in a whole array of sizes. ;)

**Comment by vletroye** [comment]
Ok, I will update the logo and the descriptions in the SPK.

Now, I have a choice to do.. 

Either run Flex TV embedded into DSM and accessible via the URL http://<Synology>:<AdminPort>/webman/3rdparty/MODS_Phlex/Phlex/index.php?pinID={GUID}

Or run Flex TV as a website in the WebStation and accessible via a simpler url http://<Synology>/FlexTV/index.php?pinID={GUID}

Dilemma...

**Comment by d8ahazard** [comment]
Is there some way to make it work the way download station does, where a
link can be created to MYNAS.MYDOMAIN.com/Download ?

**Comment by d8ahazard** [comment]
Via application portal -> Applications

**Comment by vletroye** [comment]
I am not sure to understand what you mean... I can ether open the Download Station embedded in the DSM, or into a new widows (browser tab) and then I see the URL : http://<MySyno>:<MyAdminPort>/?launchApp=SYNO.SDS.DownloadStation.Application&SynoToken=......

**Comment by d8ahazard** [comment]
Maybe it is just listed in application portal because it is an embedded app?

**Comment by vletroye** [comment]
no, otherwise, with my SPK, it would have been in there... as it is now embedded too in DSM... (I should maybe say "windowed")

**Comment by vletroye** [comment]
Ok, I have published the latest SPK with screenshots and named FLEX TV

![image](https://user-images.githubusercontent.com/9768028/40939076-e8520fca-6843-11e8-982d-dbbcd4195f71.png)

For the first run, it must be opened with a right click > Open in new window.

![image](https://user-images.githubusercontent.com/9768028/40939117-10189a38-6844-11e8-84f5-3087d94bb62a.png)

Once login done within Plex, then Flex TV may be opened windowed in DSM.

I didn't thy yet to configure IFTTT with the url http://<MySyno>:<MyAdminPort>/webman/3rdparty/MODS_Flex_TV/FlexTV/

**Comment by d8ahazard** [comment]
What is the package source URL for your MODS packages?

**Comment by vletroye** [comment]
Sources are here : https://github.com/vletroye/SynoPackages/tree/master/MODS%20Flex%20TV

NB: You need to add a folder \MODS Flex TV\package\ui\FlexTV with Flex TV sources into this package (on my workstation, I have created a symbolic link with Flex TV's github local repository. That's why the sources are not in my "MODS Flex TV".

NB.: The easiest would be to open the SPK with MODS.exe: https://github.com/vletroye/Mods

**Comment by vletroye** [comment]
I have create a second package.

The first one deploys PlexTV embedded in DSM: "MODS Plex TV Emb" (it's the one I created above)

The second one deploys Plex TV as a website in the Web Station. It requires the user to configure php 7.0 to load curl, opensl, etc... (as the SPk does not modify the php.ini): "MODS Plex TV"

Sources for both are on my github: https://github.com/vletroye/SynoPackages

IMO, the 2nd one is the most convenient...

**Comment by d8ahazard** [comment]
Have you looked at using the native spksrc method to create a package? I
cloned it yesterday and took a look at copying one of the native webapps,
and there are enough examples there for me to cludge something together.

However, I don't have the time currently to explore this fully. Still,
something tells me this might be the ideal way to go?

**Comment by vletroye** [comment]
Sure, this is the most "official" way to go. But I didn't spent time onto it when I started to create my own packages to add shortcuts onto web pages on the DSM desktop. 

spksrc is now better documented and will be much better supported than my own UI. However being now used to the work with a UI to develop, etc... I am reluctant to spent time in learning how to use command lines :)

V.

**Comment by d8ahazard** [comment]
I understand the sentiment. When I started Flex TV, I was used to working
largely in the GUI on Linux. (Shhhh).

But, when I was donated a VPS to work with, it didn't have the option to
run Linux with a GUI, so I just bit the bullet and started banging away
until I got things working. After a while, it becomes second-nature. :D

In terms of spksrc, I don't think there's actually a ton of command line
stuff. In *fact*, the repo for Spksrc can just be downloaded as a zip and
extracted. There are two folders, /spk and /mk, (I think) I made a copy of
one of the pacages in /spk that referenced "git" and "php", and started
hacking away. Really, all it needs is to have all of the synology-specific
params changed to work for FlexTV, and I could compile it.

I've got some other stuff I'm working on today, but possibly Friday I will
try forking and working on it a bit.

**Comment by djtale** [comment]
Hello,

I'm having exactly same issue on my DSM 6.1
I have apache 2.2 installed and php 5.6 and php 7.0 installed.
I'm using apache 2.2 and php 5.6 as default because of other virtualhosts on my server.

For phlex I have setup apache2 and php 7.0 but still I'm having this error :
Parse error: syntax error, unexpected '?' in /volume1/web/phlex/index.php on line 8

If I select php 7.0 as default, it is working but my other vhosts are not working anymore.

Could someone help me ?

Many thanks
