### ISSUE TITLE
Google linking issue

### ISSUE THREAD

**Issue by soates1127** [d8ahazard/Phlex#359]
#### 1. On what OS are you running Flex TV?
Rasbian
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
I believe so
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

Im not having trouble with a command, I am having an issue with linking my gmail account.  I was using the web hosted Flex app (it was working fine), but now I have a raspberry pi running Flex TV.  I can't get my gmail account unlinked from the web hosted Flex TV (I believe) and I can't link it to the raspberry pi.  I can see the server on my network, and if I type something to do, it works, but when I click the link google button a new page opens but never loads.  after a few minutes I get the following:

Unable to connect to Client at 
        <a href='https://xxx:80/Phlex'>https://xxx:80/Phlex</a> or <a href='http://xxx:80/Phlex'>http://xxx:80/Phlex.</a><BR> Please check the setting for 'Public Address' in the Phlex UI.{"speech":"Unable to look up user.","contextOut":[{"name":"playmedia","lifespan":2,"parameters":[]}],"data":{"google":{"expectUserResponse":false,"isSsml":false,"noInputPrompts":[],"richResponse":{"items":[{"simpleResponse":{"textToSpeech":"Unable to look up user.","displayText":"Unable to look up user."}}]}}}}

Oh, I've also tried the address multiple ways. xxx:80/Phlex, xxx:80, xxx:80/Phlex/, I tried making the Pi the DMZ, I definitely have the routing right, I have a TON of other ports routed around.

I went into my gmail account settings and removed Flex TV from the list, and it STILL works!  I don't understand how it still works even though its not linked to my account anywhere anymore, I even logged out of the web based Flex TV.  I have been playing around with this forever now and I just can't figure out how this is actually still working, and why I can't get the google link page to load so I can use my own server.  Please help!!

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
678fef

**Comment by soates1127** [comment]
Just an update, I can get to the Pi from inside my network, but if I turn wifi off on my phone and try it, I get nothing.  I forwarded 80 to the pi so why would it connect in my network, but not outside?

**Comment by soates1127** [comment]
When I goto http://xxx:80/Phlex/api.php?testclient&apiToken=mytokenhere I get "success" inside my network.

**Comment by d8ahazard** [comment]
Once the port is forwarded, you need to go to https://www.whatismyip.com,
copy the value for "Your Public IPv4 address", and swap that with the xxx
in http://xxx:80/Phlex...

The value you're currently using is the *private* IP of your raspi device.
Everything on your network has one. Forwarding port 80 links port 80 on
"Public IPV4" address with port 80 on "Raspi", and tells your router that
anything coming into "Public" should be bounced to raspi, and back. Hence
"forwarding".

Also, you should know that you can only forward traffic on a port to a
single device. Some ISP's/routers reserve port 80/443 for configuring stuff
from the outside.

So, if you cant hit "PublicIpv4:80/Phlex" from a phone, you may want to try
a different port other than 80 on the *public* side. So, in your router
config, you could try assigning port 5666 to "Public", and then keep port
80 on the raspi. So "forward all traffic from public:5666 to raspi:80",
bidirectional if that's an option.

And, I mean, that should work. I'd start with just trying 80:80, and if you
have trouble there, then try 5666:80.

**Comment by soates1127** [comment]
I am using a domain from asus to connect outside of the network, I access my synology from the outside no problem.  My issue was 80 is, intact jammed by my ISP so changing to another port and forwarding it to 80 worked!  Thank you for the help man, I really appreciate it!

**Comment by Hamitamaru** [comment]
I have the same problem currently where audio does not work for me but video does.

The noticable difference when reading the logs generated when I play a audio file vs. when I play a video file is that when I play music and fail the following happens:
`[Sat, 09 Jun 2018 01:01:32 -0500] [DEBUG] [Someone] [api.php::fetchPlayQueueAudio] - Trying to queue some meeedia: [JSON]
`
Where the JSON is:
```
{
  "album": "SomeAlbum1",
  "viewOffset": 0,
  "thumb": "SomeThumbThatWorks1",
  "artist": "SomeArtist1",
  "title": "SomeTitle1",
  "ratingKey": "4651",
  "source": "SomeSource1",
  "key": "/library/metadata/4651",
  "duration": "259344",
  "type": "track"
}
```
But then between that log line and this log line:
`[Sat, 09 Jun 2018 01:02:40 -0500] [DEBUG] [Someone] [api.php::sendMedia] - Item before sending: [JSON]
`
Where JSON is:
```
{
  "album": null,
  "queueID": "373",
  "art": null,
  "thumb": "SomeThumbThatWorks1",
  "title": null,
  "artist": null,
  "summary": null,
  "source": "SomeSource1",
  "key": "library/metadata/",
  "type": "track"
}
```
You'll notice the thumb is retained but the key is lost, along with a bunch of other data.
I think the important part was the key. It went from "/library/metadata/4651" to just "/library/metadata/" and 4651 is no where to be seen. Once the key is lost I can't see how it can play the file from Plex onto the Cast device. Though I'm not familiar with the actual code, so I might be missing something here.

When I compare similar "[api.php::sendMedia] - Item before sending" log lines for videos that play successfully it retains a proper key. I think this is why videos work for me but audio does not.

**Comment by Hamitamaru** [comment]
Probably also worth mentioning that I can play my "/library/metadata/4651" song by casting from my Android phone's Plex app to my ChromeCast. The same song won't cast to the same ChromeCast if the cast is initiated by Phlex.
