### ISSUE TITLE
Phlex TV server is down

### ISSUE THREAD

**Issue by Kazz3r24** [d8ahazard/Phlex#361]
### IMPORANT, PLEASE READ FIRST:

Due to an overwhelming amount of issues with cast devices and network issues in general, I've begun
a complete overhaul of the codebase behind Flex TV. This includes delgating cast functionality to a custom
Plex Media Server plugin (https://github.com/d8ahazard/Cast.bundle), as well as a major reworking of device
scraping and storage, fetcher interactions, UI overhauls, and basically - rewriting a massive chunk of
the application.

Pending the release of Flex TV v2, I ask that you refrain from submitting issues regarding...well...most of the things.

Casting, device fetching, data storage, signin issues, media fetcher interactions, multiple languages...all
of these are receiving major love...and so until then, just sit tight.

I am still looking for OS-related issues (FreeBSD causes problems), and issues related to one-off players, smart TV's,
things that aren't related to casting or server connectivity. Also, feature requests.

That said - we now return you to your regularly scheduled program.

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. On what OS are you running Flex TV?
Ubuntu Server 16.04
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
I'm using your instance
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

Just wanted to give you a heads up that this is the error I receive when attempting to use your Phex TV server.

`The site at https://app.phlexchat.com/index.php?pinID=328607822 has experienced a network protocol violation that cannot be repaired.`

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)

**Comment by Hamitamaru** [comment]
Okay so it isn't just me. I was also having trouble using Phlex TV (for use cases that were working not even 12 hours ago). I then tried to unlink account in my google home "Flex TV" action and then relink. The relink fails when it tries to load https://phlexchat.com and the page doesn't load.

**Comment by Hamitamaru** [comment]
Things are working again.

**Comment by Kazz3r24** [comment]
For me, the issue is still present even after clearing my browser cache. 
![image](https://user-images.githubusercontent.com/15070472/41196461-b4bac264-6c0e-11e8-8fc6-73d981b8a584.png)

**Comment by Hamitamaru** [comment]
Odd, it is working for me right now. Maybe you should unlink and relink your google account.

**Comment by Kazz3r24** [comment]
I never even got that far. This is what I get as soon as I link my Plex account.

**Comment by kburtonjr** [comment]
I cannot relink my account.

**Comment by d8ahazard** [comment]
I'm aware. Apache is doing some weird things with high memory usage. I'm
currently working the transition the server to light httpd...

**Comment by kburtonjr** [comment]
Some of that was on my part naming progress!

**Comment by amaino** [comment]
Think this is related, I cannot even log into the server now. When I load the page I get these in the console

https://pastebin.com/v2VtFfMi

And then when I try to press the login button I get this

https://pastebin.com/RM9u2D73

Was working this weekend.

**Comment by charlie2alpha** [comment]
Right now there seem to be SQL issues with the server, trying to link my Google account spits an SQL error.

**Comment by CohenBrianH** [comment]
phlexchat.com is still unreachable, and account linking doesn't work.

**Comment by d8ahazard** [comment]
Issues should be resolved. Had some stupid iptable rules that were blocking incoming connections/DNS resolution...

**Comment by KAJed82** [comment]
Down again?

**Comment by d8ahazard** [comment]
Effing POS host keeps crashing, working on a replacement...
