### ISSUE TITLE
Want to direct Flex TV Assistant to my server, keeps going to app.phlexchat.com

### ISSUE THREAD

**Issue by Axistilt** [d8ahazard/Phlex#363]
### IMPORANT, PLEASE READ FIRST:

Due to an overwhelming amount of issues with cast devices and network issues in general, I've begun
a complete overhaul of the codebase behind Flex TV. This includes delgating cast functionality to a custom
Plex Media Server plugin (https://github.com/d8ahazard/Cast.bundle), as well as a major reworking of device
scraping and storage, fetcher interactions, UI overhauls, and basically - rewriting a massive chunk of
the application.

Pending the release of Flex TV v2, I ask that you refrain from submitting issues regarding...well...most of the things.

Casting, device fetching, data storage, signin issues, media fetcher interactions, multiple languages...all
of these are receiving major love...and so until then, just sit tight.

I am still looking for OS-related issues (FreeBSD causes problems), and issues related to one-off players, smart TV's,
things that aren't related to casting or server connectivity. Also, feature requests.

That said - we now return you to your regularly scheduled program.

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. On what OS are you running Flex TV?

Android/Windows

#### 2. Are you using a new instance of XAMPP, or an existing webserver?

New instance of XAMPP

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?

Yep, got that all working good.

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?

All my network stuff is in good shape

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

Nah, more of a generalized dealio.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)

5c00ad

Ok, so I setup a server instance on my PC about 2 months ago.  However, since I am from Canada, google hadn't enabled the type of service that allows the "Flex TV" service to operate for us.  Other than that, everything was working hunky dory.  2 days ago I was playing around, and noticed you had set up your app.phlexchat.com page.  I thought this was a great idea and got setup on there, thinking that when google got things fixed around, I could use that instead of my webserver.  While setting it up, I realized that google had enabled assistant services in Canada, and that lo and behold, it worked!

Still working just fine!  But now app.phlexchat.com is not allowing logins?  So I wanted to use my webserver again (I want to setup Radarr and Sonarr), but even when I unlink the Flex TV assistant service and force it to forget me, and then re-connect it on my web server, it keeps sending requests to the app.phlexchat.com server instead.  Any thoughts on how I could force it to link to my webserver instead?  Or, failing that, if the app.phlexchat.com server will be up again soon?

**Comment by d8ahazard** [comment]
Had some server issues...should be resolved now.
