### ISSUE TITLE
Quality Profile for Radarr and Sonarr not saving

### ISSUE THREAD

**Issue by adrenalinenz** [d8ahazard/Phlex#366]
#### 1. On what OS are you running Flex TV?
Web version and locally installed Windows XAMMP
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
New and existing web server
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
n/a
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

```
[Fri, 22 Jun 2018 02:22:10 +0200] [INFO] [MYNAME] [api::testConnection] - Sonarr Profile List Found!: {"1":"Any","2":"SD","3":"HD-720p","4":"HD-1080p","5":"Ultra-HD","6":"HD - 720p\/1080p"}
[Fri, 22 Jun 2018 02:22:10 +0200] [INFO] [MYNAME] [api::testConnection] - Updating app data: {"sonarrProfile":1,"sonarrList":{"1":"Any","2":"SD","3":"HD-720p","4":"HD-1080p","5":"Ultra-HD","6":"HD - 720p\/1080p"},"sonarrRoot":"\/volume2\/TV\/"}
```

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
Can't seem to find this info.

**Comment by ewaroowar** [comment]
I'm also getting this issue.

Int he config.php The lists for sonar,radarr and lidarr populate but the profile values never change.

**Comment by d8ahazard** [comment]
Fixed!

**Comment by d8ahazard** [comment]
Update your installation of Flex TV, this was fixed today...
