### ISSUE TITLE
I Interrupted Google Auth... now I can't link Flex TV to Google Assistant

### ISSUE THREAD

**Issue by NickHuntDavis** [d8ahazard/Phlex#367]
On my phone (Sony Experia XZ2) I'm trying to link Flex TV to Google Assistant/Home.

I interrupted my mobile connection while authorising Google to link Flex V to Assistant/Home. 

Now, when I click the "link" button on the "Assistant services listing for Flex TV" _or_ on the "Home screen blue prompt" to link to Google, it no longer redirects to the Google Oauth page.
I only see a white screen, nothing loads.

Any ideas?
Last 6 digits of API token: 0c994d

**Comment by NickHuntDavis** [comment]
UPDATE:

I removed Phlex TV from my Google Authorized Apps list.
I was then able to see the auth screen again after clicking "link"
I selected my google account, the screen appears to be loading something for a bit, but nothing. Just a white screen.

**Comment by d8ahazard** [comment]
Try relinking through the Flex TV ui?

**Comment by plittlefield** [comment]
Great software, thanks!

Things work with your hosted web based phlexchat.com to a Chromecast device in my house. I followed the link to the web page on my laptop, I signed in to my PLEX account and it works... yay.

However. when I try to link Google Assistant to Flex TV in my mobile phone's Home app, it starts Chrome Browser then shows a blank page and does nothing.

What have I done wrong?

**Comment by Dave-Still** [comment]
In my case I had initial liking issues in set-up using XAMPP as I'd changed the Port from port 80. The instructions mention to update this in the Apache Service>Config settings (*.conf & php.ini files), but did not appear to mention updating the main XAMPP Contol Panel>Config>Service and Port Settings to mirror these on the Apache tab there. The symptoms manifested as the app working from typed input on the PC, but unable to link accounts to Google. Same issue ?
