### ISSUE TITLE
"What's on deck" is missing TV show names, returns only the episode titles

### ISSUE THREAD

**Issue by charlie2alpha** [d8ahazard/Phlex#368]
Updated to the latest git, and suddenly every time I ask Flex TV "What's on deck" it always says "Hmmm. Your server doesn't seem to have anything listed for that request.". But there are shows on deck, and the URL I see in the logs returns an XML with those items. I run the latest beta Plex server on Gentoo Linux,

I confirmed commit 6dce3ec2f6f1391f1da094cab8ee70c04c98eaa8 to be the issue by doing a rollback with git, it start working fine after I reverted.

**Comment by charlie2alpha** [comment]
Seems to be ... kinda fixed with 10720d1dc2e430c83b1052801fda7d009663c15f but there is one difference: Flex TV now returns only the episode tittles with no mention of the actual show name itself.

**Comment by mattpurnell** [comment]
I get complete silence..

**Comment by charlie2alpha** [comment]
This now appears fixed, closing.
