### ISSUE TITLE
phlex tv isnt responding right now?

### ISSUE THREAD

**Issue by bestballer** [d8ahazard/Phlex#370]
1. On what OS are you running Flex TV?  **Win 10**

2. Are you using a new instance of XAMPP, or an existing webserver?
**xamp v3.2.2**

3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
**i have enabled it, not sure how to ensure php wirite-access**

4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
**yes,  correct public ip a nd port being used**

5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files

6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
a08d52

so this is kind of a minor issue.     everything seems to be working. i request movie, and shows.    
my ports are open.  The only this is,  when i do ask "phlex tv antyhing.  it says "not responding right now"    but then it plays what i asked for.          its kind of annoying that every request gets that response.
another issue is, that when i link my google account to my "phlex home" server it states that the Account is linked to google home.    but i get "xxx.xxx.xxx.xx.5133 took to long to respond"    it never takes me back to the plexchat server unless i link my google account to the "phlex web" server.  And yes i tried just using Phlex web but it only works for my Plex for LG.  and does nothing when i ask a request on my bravia 4k 2015.  any help would be appriciated

**Comment by bestballer** [comment]
Fixed myself.     USed shorter replies in settings.  and used a different instance of xammp.

**Comment by abbyhomeav** [comment]
I am having the exact same problem, my voice commands work "ok google play game of thrones" and the show or movie plays but google home always says " flex tv isn't responding right now"

i have tried enabling the shorter replies but that doesn't help. Could you elaborate on what you mean by using a different instance of xampp. im using xampp 3.2.2

Thanks

Also if anyone else could offer any suggestions it would be appreciated.

**Comment by d8ahazard** [comment]
Flex TV has been temporarily taken offline for some updates. Please stand
by as we work to get things going again...

**Comment by abbyhomeav** [comment]
Thanks, appreciate the reply. I’ll wait and try another time.
I just finished setting it up again from scratch using git and xampp,  It was all working except as outlined below, then about an hour ago I got the message  “flex tv is no longer available”

Was starting to tear my hair out thinking I had screwed something up again.
😊

P.s.  I cant find the config.ini.php anywhere on my windows pc, does this file not exist when you install using Git?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Dave-Still** [comment]
Hi abbyhomeav,
At present I believe we're all getting the “flex tv is no longer available” withe the server offlined per the reply from d8ahazard. I believe we have a duplicate thread to this on issue #442 outlining where the issue appears to be manifesting.

Many thanks to d8ahazard for all his hard work on this app. I sincerely hope the issue can be resolved.

You mention being unable to find config.ini.php. If it's the main php config file you're after it's in xampp\php\php.ini. If it's the parameter file behind the ui it's in xampp\htdocs\Phlex\rw\config.php. If MySQL is enabled its stored on the db.

**Comment by abbyhomeav** [comment]
Thanks,

Those last 2 lines were very useful. My previous install it was xampp\php\php.ini
this time it looks like its xampp\htdocs\Phlex\rw\config.php

I had got it working about 30 minutes before they took it offline, Doh!

Thanks again.


________________________________

**Comment by Sman42** [comment]
Abbyhomeav,

What did you change in the config.php to make google assistant respond correctly?

**Comment by Dave-Still** [comment]
I couldn't get it to respond correctly, thus added to #442. Tried all the suggestions in this post, but suspect this issue is a little different as elsewhere on the forum it was mentioned that they were trying a file based control in the latest releases. From the symptoms it appears to have a bug or two. Tried on Pi, Windows 7, and even on the hosted server. all appeared to suffer the same issue. :-(
