### ISSUE TITLE
Plex addon for Kodi not found (PlexKodiConnect is found)

### ISSUE THREAD

**Issue by giejay** [d8ahazard/Phlex#371]
I'm not able to find my Plex instance which is an Addon for Kodi: https://kodi.tv/plex-add-on-for-kodi

PlexKodiConnect does show up, just like my regular Android app on my Shield:

{Name: "SHIELD Android TV", FriendlyName: "SHIELD Android TV", Id: "plexapp-android", Product: "Plex for Android", Type: "Client", …}
{Name: "PlexKodiConnect", FriendlyName: "PlexKodiConnect", Id: "idididi", Product: "PlexKodiConnect", Type: "Client", …}

My question is, is the Plex addon supported?

**Comment by d8ahazard** [comment]
It is not... It doesn't work on the Kodi side.
