### ISSUE TITLE
Unable to start Phlex with docker (Synology)

### ISSUE THREAD

**Issue by csgnyc** [d8ahazard/Phlex#373]
I have some experience with Docker (have a few other containers running) so, generally speaking, I know what I'm doing, but I can't get this container to start.

I've attached screenshots so you can see my setup.

![screen shot 2018-07-09 at 11 05 24 pm](https://user-images.githubusercontent.com/20961039/42487003-ef522400-83cc-11e8-8b86-f89c4143b892.png)
![screen shot 2018-07-09 at 11 05 36 pm](https://user-images.githubusercontent.com/20961039/42487004-ef6b5574-83cc-11e8-9b72-cf8067d93bf7.png)

1. On what OS are you running Flex TV?  Docker (Synology)

2. Are you using a new instance of XAMPP, or an existing webserver?  n/a

2b. If not XAMPP, what WebServer stack are you using?  n/a

3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?  Do I need to do this -- isn't this within the docker container?

4. Have you followed the (networking)[Talking-To-The-Outside-World] section? Using docker -- does this apply?

5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.  N/A

6. What are the last six digits of your server's API Token? (Settings -> Flex TV): Again, using Docker

**Comment by d8ahazard** [comment]
What does the log say?

Looks like you should be binding only to ports 443 and 80 inside the
container. Your volumes also look correct. I'd try binding ports 5666 - 80
and 5667 to 443, then try starting, lmk what the log says.

I run docker under Synology, so my test case should match yours. Only other
thing I'm seeing - in your setup, you're binding "docker/Phlex/config". In
mine, it reads "/docker/Phlex/config". Make sure when you bind the volume,
you select an actual existing path in the host OS...

**Comment by csgnyc** [comment]
I fixed so that 5666 maps to 80 and 5667 maps to 443.  Also, the docker/Phlex/config just seems to be my setup -- I checked other working docker containers and they look the same.

Error I get is
ERROR:  [pool www] please specify user and group other than root
ERROR: FPM initialization failed

If the problem is permissions,I don't understand to fix it -- I tried assigning PUID 99 and PGID 100 (I got these values from another working docker container) and it didn't help.

**Comment by d8ahazard** [comment]
Sorry for the delayed response...did you ever sort this out? It looks like for my version on Syno, I have no PGID or PUID set, so it's defaulting to the user/group ID of 911. 

I'd double-check that 911 somehow didn't get mapped to the root user, and set these to *your* user/group ID in Synology...
