### ISSUE TITLE
Fetching with Radarr/Sonarr

### ISSUE THREAD

**Issue by OrganicKobze** [d8ahazard/Phlex#378]
#### 1. On what OS are you running Flex TV?
Windows 10
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
app.plexchat.com
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
N/A
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
N/A
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)

Flex doesn't seem to be talking to Radarr/Sonarr. They are both linked and say successful when testing.

You said: "Fetch Munich."
My reply: "Hmmm. Your server doesn't seem to have anything listed for Munich."

However I try the command it just tells me that I don't have anything listed. 

Any help would be brilliant.

**Comment by Jarpetnee** [comment]
I have the same issue. I also have a successful link/test/button.

Only difference being I am using my own XAMPP server instead of the publicly hosted one.
