### ISSUE TITLE
Connected client, but Google home wont accept FlexTV commands

### ISSUE THREAD

**Issue by Slychocobo** [d8ahazard/Phlex#38]
OK, 

Better idea what's going .  Managed to finally get the Google Home to understand what I was asking, however it now responds with 

"Im really sorry, But Flex TV is not available to Google Home devices set to British English"

So, err.. Really confused what me being in the UK has to do with anything..?

-------------------------------------------------------------

A little unsure what is going on,

Setup Phlex according to the guide via Nginx.
Published OK, (Logs show it detecting Plex install etc)
Authorized Phlex to access my Google account without error.

But when I provide any trigger command "OK Google, Tell Flex TV to ....."  it responds with the generic "Im sorry, I dont know what to do with that"

**Comment by d8ahazard** [comment]
Google, in their infinite wisdom, decided to separate US and UK English functionality in the Actions SDK.  This wouldn't be so bad, but they also failed to provide us with a way to support UK English at the current time - meaning there's nothing for me to fix until Google gets their stuff together.  

Current "workaround" for this is to set the language in the Ghome app to US English.  If you don't want to do that, the only other alternative currently is to use the IFTTT hooks instead...

Closed till I can do something about it.
