### ISSUE TITLE
phlexchat.com down?

### ISSUE THREAD

**Issue by acrylicus** [d8ahazard/Phlex#380]
Hi - is phlexchat.com currently down? I can't access it from 2 locations, and my google home integration is not working.

**Comment by bestballer** [comment]
yeah same here,   link google says "searching for sockets" or "connecting to phlexchat.com"

**Comment by bestballer** [comment]
actually just looked deeper into it.   for some reason my ports have been blocked.   double check your ports and try again

**Comment by automatt1c** [comment]
I'm getting this error from plexchat

{"speech":"Unable to look up user.","contextOut":[{"name":"playmedia","lifespan":2,"parameters":[]}],"data":{"google":{"expectUserResponse":false,"isSsml":false,"noInputPrompts":[],"richResponse":{"items":[{"simpleResponse":{"textToSpeech":"Unable to look up user.","displayText":"Unable to look up user."}}]}}},"displayText":"Unable to look up user.","v2":true,"source":"phlexchat.com"}

**Comment by automatt1c** [comment]
To give some background, I was linked previously but I lost my Flextv Configuration and had to start over. I tried linking it directly on the google Home and says successful but its still trying to use the old API token and tells me "an error has occurred please report the error to the developer" when i try to issue any commands from the google home.  I also tried editing the Config file with the old API token but it seems to revert back.

**Comment by d8ahazard** [comment]
Go here:

https://myaccount.google.com/permissions

Search "Flex TV". Select "Remove Access". Re-run linking.

>

**Comment by automatt1c** [comment]
Still having the same error if i try to link it with flexTV. Now it doesnt seem to do anything when i try and link it with google home app. It has me login and loads but take me back to the google home app and link button is still there.

**Comment by automatt1c** [comment]
Looks like you have made some changes to Plexchat recently. I still cannot link my google account. Says 

Unable to connect to client at "DNS address":5666 
please check the setting for public address in the Phlex UI. 

I can access the Address on port 5666 from my Cell phone on a cellular connection without issues.
Heck i even tried to link my google account from My work computer/ network and get the same error.

**Comment by jorno** [comment]
same for me, linking google doesn't seem to work with my home server (no changes to ports or ip's or whatever and used to work just fine)
what I do notice is i can link google on the app.plexchat.com server, just nog my own.

**Comment by d8ahazard** [comment]
Anybody using self-signed SSL certs? I'd have to double-check, but I know
it doesn't like that...

**Comment by automatt1c** [comment]
I'm just using a http connection and the default setup on docker. I tried using SSL and forwarding those ports as well but it didn't make a difference. You would think it would make a self-signed cert if you didn't configure your own? At least thats how most web servers work.

**Comment by lightheaded** [comment]
Thanks d8ahazard, unlinking and relinking the account worked. The process involved a lot of white-screen waiting though..

**Comment by d8ahazard** [comment]
I'm going to close this, as it's become a sort of catch-all for random issues.

SSL issues should be fixed. If you have another problem, please create a new issue.
