### ISSUE TITLE
How to play a music playlist

### ISSUE THREAD

**Issue by mattpurnell** [d8ahazard/Phlex#381]
#### 1. On what OS are you running Flex TV?
Docker, on Synology NAS (Ubuntu)
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
Whatever is used on the docker image

#### 2b. If not XAMPP, what WebServer stack are you using?
see 2.

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Done as per docker, casting is OK

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
This is all fine too

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

Hey - firstly, great work. I am very glad something finally exists to bridge these gaps (between media library and Chromecast especially).

One of the main things I wanted, when moving to Plex, was to retain the ability to automate the casting of playlists, for when I get home, or via voice command. I had this sorted with the previous platform and came to REALLY love it.. music playing when I walk in the door, or via button on my phone.

I understand that we are supposed to be able to cast music playlists from Plex - but I can't get anywhere close.. how are we supposed to achieve this? If you can show me what I am doing wrong I will be very grateful 👍  👍 

I have included some conversations I have had with Miss Phlex. Note I have Playlists (Smart playlists based on Genre) called Chilled, Rock, Alternative etc:

You said: "Play Rock."
My reply: "Unfortunately, I couldn't find 'Rock' in the library."

You said: "Play Chilled."
My reply: "Which one did you want? Chilled Mixes (the artist), Various Chilled (the artist), - Chilled Ibiza II - CD 2 (2003) (the album), - Wicked chilled (the album), or - Serve Chilled 2 (2000) (the album)." NOTE: none - I wanted 'the playlist'

You said: "Play the music playlist rock."
My reply: "I'm sorry, but I didn't find any results for 'rock'. Do you want me to try downloading it for you?"

You said: "Play the playlist called rock."
My reply: "I couldn't find anything called 'called rock' in your libraries. Should I try to fetch it for you?"

You said: "Play the playlist named rock."
My reply: "I'm sorry, but I didn't find any results for 'named rock'. Do you want me to try downloading it for you?"

You said: "Play music playlist alternative."
My reply: "Unfortunately, I couldn't find 'alternative' in the library. Should I try to fetch it for you?"

You said: "Play music alternative playlist."
My reply: "I couldn't find anything called 'music alternative' in your libraries. Shall I search for it in your fetchers?"

You said: "Play the rock playlist."
My reply: "I'm sorry, but I didn't find any results for 'rock'. Should I try to fetch it for you?"

You said: "Play music playlist chilled."
My reply: "Unfortunately, I couldn't find 'chilled' in the library. Would you like me to add it to your watch lists?"

You said: "Play music genre chilled."
My reply: "I'm sorry, but I didn't find any results for 'genre chilled'."

You said: "Play playlist rock."
My reply: "Unfortunately, I couldn't find 'rock' in the library. Shall I search for it in your fetchers?"

You said: "Play playlist."
My reply: "I couldn't find anything called 'that request' in your libraries. Would you like me to add it to your watch lists?"

You said: "Play playlist Chilled."
My reply: "Unfortunately, I couldn't find 'Chilled' in the library. Should I try to fetch it for you?"

You said: "Play playlist chilled."
My reply: "Im sorry, but I didnt find any results for chilled. Should I try to fetch it for you?"

You said: "Play chilled playlist."
My reply: "Im sorry, but I didnt find any results for chill. Should I try to fetch it for you?"

You said: "Play chilled genre."
My reply: "Unfortunately, I couldnt findchilled genre` in the library."

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
f511a3

**Comment by d8ahazard** [comment]
This has been fixed and is working in the current revision (10EA395). For a playlist named "MCM", "play my MCM playlist" works. Tested with several other playlist names as well.

**Comment by mattpurnell** [comment]
Brilliant thanks! Is there a docker update coming soon?

**Comment by d8ahazard** [comment]
Docker is self-updating, just restart the container, or use the update
feature within the app. ;)

**Comment by mattpurnell** [comment]
Brilliant
