### ISSUE TITLE
Getting bad JSON back from web hooks

### ISSUE THREAD

**Issue by mattpurnell** [d8ahazard/Phlex#382]
#### 1. On what OS are you running Flex TV?
Synology (Ubuntu) with Docker.
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
Latest Docker
#### 2b. If not XAMPP, what WebServer stack are you using?
N/A
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
N/A
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes all that is fine
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)

Hi - just noticed that when I use python3 and webhooks to interact with Phlex, the JSON coming back seems unusable until I remove the backslashes preceding any single quotes.

For example:

Original (rejected as Valid JSON):
```
{
	"speech": "Here\'s a list of ondeck items: Outcast - The Road Before Us.......
```
Remove that backslash and the JSON is accepted. 
```
{
	"speech": "Here's a list of ondeck items: Outcast - The Road Before Us.......
```

..or is there something about JSON and/or Python that I need to learn here? :)

**Comment by Elinombrable** [comment]
This seems more a presentation problem than a code problem. It happened to me in other projects when i printed the Json output directly to the console, the printing function did this conversion (i think that even in debugging, i was getting these weird character conversions) but internally, the value was ok and the program worked. Where are you getting these values at?

**Comment by mattpurnell** [comment]
Hi

I get these values back when using python3 to converse with the webhooks, specifically the 'requests' library. So that my home automation can invoke Plex/Phlex, I created a simple script that sends the only script parameter through to Phlex, e.g. like python3 myscript.py "What's on deck?"

Yep - there is the distinct possibility that it is actually the python 'requests' library at fault. I shall update this post after reading up futher on 'requests'.. hopefully there are options to preserve original formatting or something,

Thanks for the tip!

**Comment by Elinombrable** [comment]
Are you using json.dumps in your code? If yes, then this post may be usefull for you (i think that was exactly my problem when i faced this errror in the past):

https://github.com/requests/requests/issues/4580

**Comment by d8ahazard** [comment]
Confirmed, this is an issue with python, not Flex TV...
