### ISSUE TITLE
Unable to set Quality Profiles

### ISSUE THREAD

**Issue by ewaroowar** [d8ahazard/Phlex#384]
#### 1. On what OS are you running Flex TV?
Unraid (Nginx Docker)
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
N/A
#### 2b. If not XAMPP, what WebServer stack are you using?
Nginx
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes, setup for external access correctly.
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)

I'm unable to get any quality profiles to set to Sonarr, Radarr or Lidarr.

I click Test and test is successful and populates the lists but changing the quality profile does nothing. The config also doesn't update the profile values (radarrProfile, sonarrProfile, lidarrProfile) and these persist to stay at a value of 1 which is any.

If I request flex tv to download anything then it sets the quality to Any in the fetchers.

I can see the config.php update when I click test and the "radarrList" value updates with the below data but still unable to set the quality.

            "radarrList": {
                "1": "Any",
                "2": "SD",
                "3": "HD-720p",
                "4": "HD-1080p",
                "5": "Ultra-HD",
                "6": "HD - 720p\/1080p"
            },

Sometimes when I change the quality it says "Value Saved Successfully" but that is not the case and the config doesn't change and the UI just reverts to blank on next refresh.

**Comment by d8ahazard** [comment]
Fixed!

**Comment by ewaroowar** [comment]
Great, thanks matey!
