### ISSUE TITLE
After authenticating with Plex, web server just spins

### ISSUE THREAD

**Issue by danepowell** [d8ahazard/Phlex#385]
#### 1. On what OS are you running Flex TV?
Ubuntu 16.04

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
Existing

#### 2b. If not XAMPP, what WebServer stack are you using?
Apache

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes, although not sure about sockets

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes except for opening router ports / port forwarding.

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.
> [08-09-2018 03:22:03.844500] [WARN] [danepowell] [index::require_once:require_once:setSessionData:scanDevices] - Plex.TV connection issue, breaking to save device list.

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
Unable to get since Flex is not starting

I got Phlex running on Apache, navigated to the web UI, authenticated with Plex, but then just stared at a spinning logo for a few minutes. As near as I can tell, nothing is happening. There's nothing on the screen except for the spinny logo. The only thing of interest in the logs is that line above. Any idea what's going on here? Do I need to set up port forwarding in order to even be able to access the local web UI?

**Comment by d8ahazard** [comment]
Flex TV can't communicate with the Plex.tv website. I'm not sure why, but the issue is going to be something in your setup or LAN...
