### ISSUE TITLE
Issues Hosting Phlex

### ISSUE THREAD

**Issue by ktr0x** [d8ahazard/Phlex#386]
1. On what OS are you running Flex TV?
**Centos 7**

2. Are you using a new instance of XAMPP, or an existing webserver?
**I am running a new instance of a webserver (not XAMPP)**

2b. If not XAMPP, what WebServer stack are you using?
**I am running an apache2 webserver with PHP7 (including cURL, sockets, XML, OpenSSL, etc)**

3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
**I have ensured the apache user has 777 access to all files in the HTML (webserver) folder**

4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
**That has not been required, as I only need local access, which has been tested and works perfectly**

5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files. Paste anything that looks related as well.
BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION
**Phlex is not working, so I cannot answer this.**

6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
**Phlex is not working, so I cannot answer this.**

I get HTTP error 500 when attempting to load the Phlex index.php page (as well as all of the other PHP files I tested that came with Phlex). PHP seems to be working as I can run the phpinfo(); file fine over the webserver. I tailed the error_log file and got this:

[:error] [pid 12517] [client 192.168.1.24:58666] PHP Warning:  file_put_contents(/var/www/html/Phlex/php/../rw/config.php): failed to open stream: Permission denied in /var/www/html/Phlex/php/webApp.php on line 640
[:error] [pid 12517] [client 192.168.1.24:58666] PHP Warning:  fileperms(): stat failed for /var/www/html/Phlex/php/../rw/config.php in /var/www/html/Phlex/php/webApp.php on line 646
[:error] [pid 12517] [client 192.168.1.24:58666] PHP Warning:  fileowner(): stat failed for /var/www/html/Phlex/php/../rw/config.php in /var/www/html/Phlex/php/webApp.php on line 647
[:error] [pid 12517] [client 192.168.1.24:58666] PHP Fatal error:  Uncaught Error: Call to a member function get() on boolean in /var/www/html/Phlex/php/webApp.php:107\nStack trace:\n#0 /var/www/html/Phlex/php/webApp.php(425): getPreference('general', 'value', 'http://localhos...', 'name', 'publicAddress')\n#1 /var/www/html/Phlex/php/webApp.php(12): serverAddress()\n#2 /var/www/html/Phlex/index.php(3): require_once('/var/www/html/P...')\n#3 {main}\n  thrown in /var/www/html/Phlex/php/webApp.php on line 107
[:error] [pid 12513] [client 192.168.1.24:58667] PHP Warning:  touch(): Unable to create file /var/www/html/Phlex/php/../rw/config.php because Permission denied in /var/www/html/Phlex/php/webApp.php on line 638
[:error] [pid 12513] [client 192.168.1.24:58667] PHP Warning:  chmod(): No such file or directory in /var/www/html/Phlex/php/webApp.php on line 639
[:error] [pid 12513] [client 192.168.1.24:58667] PHP Warning:  file_put_contents(/var/www/html/Phlex/php/../rw/config.php): failed to open stream: Permission denied in /var/www/html/Phlex/php/webApp.php on line 640
[:error] [pid 12513] [client 192.168.1.24:58667] PHP Warning:  fileperms(): stat failed for /var/www/html/Phlex/php/../rw/config.php in /var/www/html/Phlex/php/webApp.php on line 646
[:error] [pid 12513] [client 192.168.1.24:58667] PHP Warning:  fileowner(): stat failed for /var/www/html/Phlex/php/../rw/config.php in /var/www/html/Phlex/php/webApp.php on line 647
[:error] [pid 12513] [client 192.168.1.24:58667] PHP Fatal error:  Uncaught Error: Call to a member function get() on boolean in /var/www/html/Phlex/php/webApp.php:107\nStack trace:\n#0 /var/www/html/Phlex/php/webApp.php(425): getPreference('general', 'value', 'http://localhos...', 'name', 'publicAddress')\n#1 /var/www/html/Phlex/php/webApp.php(12): serverAddress()\n#2 /var/www/html/Phlex/index.php(3): require_once('/var/www/html/P...')\n#3 {main}\n  thrown in /var/www/html/Phlex/php/webApp.php on line 107

**Comment by d8ahazard** [comment]
Just curious...what was the issue? Maybe someone else encountering it could
benefit from knowing what the problem was. ;)

**Comment by ktr0x** [comment]
It was just a heap of PHP errors that were fixed when restarting my server.
