### ISSUE TITLE
Feature Request - Transcode quality selection

### ISSUE THREAD

**Issue by CornHead764** [d8ahazard/Phlex#390]
Since it's possible to use flex tv to stream media from a remote server to a local chromecast, would it be possible to add a feature to allow the selection of quality for the streamed content? I could see it being beneficial to have a voice command to do this, as well as a default within settings for each server. Maybe a list of all servers associated with your account, where you can select the default quality for each, so your local server can direct play, while remote ones will default to a specific transcode quality.

**Comment by d8ahazard** [comment]
I did some digging on this, and I don't think it's something that is easily implemented. Playback quality is going to be subjective to a number of factors, including (but not limited to) the available media quality, transcode restrictions server-side, and the device being played to. 

Trying to encapsulate this in a simple way would be too problematic. Most of these settings should be controllable via server or client settings.

Sorry. :(
