### ISSUE TITLE
Local and site not working

### ISSUE THREAD

**Issue by Dalethium** [d8ahazard/Phlex#394]
So I have entirely no idea what went on, but basically a issue I was having with my own local copy of this (running on php 7.1, apache 2.4, straight git clone) where basically whenever you authorize plex the site no longer responds and does not even resize

![image](https://user-images.githubusercontent.com/22735418/45229809-42938400-b2c7-11e8-8e1a-08169724108d.png)
I was just trying random things I could to make it work on my pc, including deleting cookies etc, and then when I finally gave up and tried to use your site - it did the same! The weird thing is I had it working fine this morning.

logs from my server: https://pastebin.com/cX6RMjfe

When I finally asked my google home max to play something after thoroughly destroying something somehow, it said (something like) "An error has ocurred, please report the following message to the developer" but then it gave no message

I hope any of this helps.

**Comment by d8ahazard** [comment]
That's odd. I just validated that login is working on both versions for me.

What browser are you using?

You could try appending ?logout to the URL (app.phlexchat.com?logout" -
that may clear stored data and reload...looks like something maybe got
stuck, but I'm not seeing anything definitive in the logs.

**Comment by Dalethium** [comment]
![image](https://user-images.githubusercontent.com/22735418/45232638-5f808500-b2d0-11e8-8b7a-b5384a55b1a8.png)
for the exact url you gave me

**Comment by d8ahazard** [comment]
try:

https://app.phlexchat.com?logout

**Comment by Dalethium** [comment]
Tried it, signed back into plex, got redirected to index.php with a url query string called "pinID", same thing happened

![image](https://user-images.githubusercontent.com/22735418/45250985-b0c75d80-b33e-11e8-8210-a30083bc9c1e.png)
If it matters, the page is sent without even a closing body tag

**Comment by d8ahazard** [comment]
Looks like some kind of error trying to sign in where the PHP is crapping
out and not rendering the body.

I've made some changes to how SSL is verified and some other stuff...give
it a try again. I'm going to be tied up for the next few hours, but what
would be really beneficial is to pick a time where you can try signing in
and I can grab the logs to see what the problem is...

**Comment by CaptInsano** [comment]
Just to chime in:

I am having the exact same problem and came to github looking for solution.

I have been hosting phlex via docker on my own server but it became completely non-responsive so I completely wiped and started again but could not log in (exact same symptoms as above).

I then tried the app.phlexchat.com version and same issue.

**Comment by Dalethium** [comment]
Hey, I just thought I'd let you know that the site is working now -- if it matters, I switched from using my google account to sign into plex (which I should not have been using in the first place) to my normal plex account. Perhaps there is something different with how they send back logins from a third party?

**Comment by stuartduff** [comment]
It seems the Link Google functionality may not currently be working either at the moment producing this message below when attempted. The Link Amazon functionality does still seem to function as expected, however.

<img width="696" alt="google-account-linking-failed" src="https://user-images.githubusercontent.com/1190565/45327222-949a0b00-b54e-11e8-9f3a-ac1d89dd7f14.png">

The SSL cert on phlexchat.com also seems to still be non-secure at the moment too.

<img width="513" alt="non-secure-ssl" src="https://user-images.githubusercontent.com/1190565/45327295-e2af0e80-b54e-11e8-9b30-1e5e5b092c29.png">

**Comment by anoteng** [comment]
Same here. Your hosted version just keeps spinning. Local version dies with some kind of memory leak somwhere.
[Tue Sep 11 05:10:04.783525 2018] [php7:error] [pid 25960] [client 192.168.0.164:53794] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/Phlex/php/util.php on line 685

**Comment by keita1029** [comment]
Same for me too, 
`[Tue Sep 11 17:31:04.068445 2018] [php7:error] [pid 6152:tid 1988] [client ::1:52548] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in C:\\xampp\\htdocs\\phlex\\php\\util.php on line 685
`

Tried some version of XAMPP but still not.

**Comment by d8ahazard** [comment]
Give it a whirl now. I've added a key to restrict the memory usage on the
function being called at that line.

**Comment by anoteng** [comment]
Nice your hosted version seems to work now. Doesn't look like the change has been commited to master yet?

**Comment by d8ahazard** [comment]
It has, plus some other fixes.

As a rule of thumb...the hosted version should *always* be running the
latest version. For clarity, I've just added a display that will show the
revision on the login screen.

**Comment by CaptInsano** [comment]
Still not working here I'm afraid:
Chrome v 68.0.3440.106 (using incognito mode to avoid caching probs)
Phlex: https://app.phlexchat.com Revision: 8500344

Log in via plex with email and password (someone prev said that Google login caused probs)

I get redirected from plex back to phlex to just the spinning progress sign, a non-resized background and the following in the console:

`
service-worker.js:33 https://app.phlexchat.com/index.php?pinID=1214111695
service-worker.js:33 https://app.phlexchat.com/css/loader_main.css
service-worker.js:33 https://app.phlexchat.com/css/lib/dist/critical.css
service-worker.js:33 https://img.phlexchat.com/
service-worker.js:33 https://app.phlexchat.com/css/lib/src/Roboto-Light.ttf
service-worker.js:33 https://app.phlexchat.com/index.php?pinID=1214111695
The FetchEvent for "https://app.phlexchat.com/index.php?pinID=1214111695" resulted in a network error response: an object that was not a Response was passed to respondWith().`
