### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by micatechno** [d8ahazard/Phlex#396]
### IMPORANT, PLEASE READ FIRST:

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 8. Please describe the issue.

**Comment by micatechno** [comment]
Hi,

I just installed phlex on xampp, and it works fine from the Phlex web page. I can launch plex on my Chromecast. But when I launch Phlex from google home, it launches plex but in chrome on my server. Not on Chromecast. On the phlex web page, I can select the device and force it to use chromecast. But not on google home. How can I force it to use Chromecast?

Many thanks in advance.

**Comment by d8ahazard** [comment]
Have you installed the Cast.bundle plugin on your Plex server?

https://github.com/d8ahazard/Cast.bundle
