### ISSUE TITLE
Unable to Link Phlex/Flex TV to Google Home within the App

### ISSUE THREAD

**Issue by eaglefox82** [d8ahazard/Phlex#397]
I am facing issues Linking the Phlex/Flex TV app within the Google Home app.
I am using the Web Service (hosted by yourself)

I get the pop up in my google home app and when clicking in link i am taken to https://phlexchat.com where nothing happens.

There the accounts are not linked

**Comment by MACE-Zer0** [comment]
Having the Exact same problem ... could use some help , and would help with donating if this was solved @d8ahazard
