### ISSUE TITLE
move from app.plexchat.com to own server fails

### ISSUE THREAD

**Issue by kverkind** [d8ahazard/Phlex#398]
#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 8. Please describe the issue. I want to link to own hosted server but i get the message that the server is not available from outside. This is not correct. The server is available from outside but i guess plexchat try to connect with token from app.plexchat.com. would be nice if we can administer our own tokens.

**Comment by d8ahazard** [comment]
You should just have to click the "Link Google Account" button from the UI of the version you want to use, and make sure the value for "Public Address" in settings is correct.

**Comment by kverkind** [comment]
Does not work for me. You can try accessing my server on http://94.224.11.19:32499

**Comment by kverkind** [comment]
Not related to server move. Issue with API responses
