### ISSUE TITLE
Phlex server reachable from outside. API request received but does not get outside network 

### ISSUE THREAD

**Issue by kverkind** [d8ahazard/Phlex#399]
1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com? Want to use own webserver
If hosting your own version, please answer the below questions. Otherwise, proceed to #8.
2. On what OS are you running Flex TV? Raspbian Stretch
3. Are you using a new instance of XAMPP, or an existing webserver? Apache2
3b. If not XAMPP, what WebServer stack are you using? NA
4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV? yes and data gets written 
5. Have you followed the (networking)[Talking-To-The-Outside-World] section? yes
6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files. Paste anything that looks related as well. No errors in log file. All working fine internal but outside connection API does not return any value (times out after a while)
BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION

7. What are the last six digits of your server's API Token? (Settings -> Flex TV 321a3d9
8. Please describe the issue. Installed Phlex on Pi and even on Synology in docker. Opened all the ports from outside. I can reach the application outside of my network. Was debugging on pi. When testing connectivity (to link google account)   I see the API request coming in and answer it with success.  However this response does not seem to get to plexchat.com Can this be related to a module missing in apache2 and/or is the reply blocked? Best way to debug this?

**Comment by kverkind** [comment]
Additional info: 
This is the request I receive: /api.php?testclient=true&apiToken=da8a28ef28a31d4cdf9277fac324bca8781f3c13d7 HTTP/1.1" 499 0 "-" "-"
Looks like sending ip address is missing. I see that in the other api calls.

**Comment by JCapriotti** [comment]
I think I'm seeing similar behavior with the Docker container. Request I see is:

`192.99.197.11 - - [10/Oct/2018:03:09:38 +0000] "GET /api.php?testclient=true&apiToken=xxxxxxxxxxxxxxxxx611ee2 HTTP/1.1" 499 0 "-" "-"
`

**Comment by kverkind** [comment]
error.log of nginx:
2018/10/10 11:40:10 [debug] 6088#6088: *11 http upstream check client, write event:0, "/api.php"
2018/10/10 11:40:10 [info] 6088#6088: *11 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 192.99.197.11, server: _, request: "GET /api.php?testclient=true&apiToken=XXXXXXXXX3c13d7 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "PublicIP:41234"

**Comment by JCapriotti** [comment]
I'm going to see about adding some extra logging to `api.php`. Might help pinpoint the problem and I'm not quite sure what else to look at.

I see `API Link Test successful` in there every time I click the "Link To Google" button. So it seems the title of the issue is very accurate....  the Phlex server is accessible from the internet, but the response is failing to send. 

Only for these link tests though... I'm getting responses from other URLs.

I do see a lot of these in the nginx error logs. They happen frequently and may pop up about 40 seconds after the link request, but I"m not sure quire if they correlate or not.
```
2018/10/11 03:08:46 [error] 317#317: *48140 upstream timed out (110: Operation timed out) while reading response header from upstream, client: x.x.x.x, server: _, request: "GET /api.php?apiToken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx611ee2&checkUpdates=true HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "x.x.x.x:5666", referrer: "http://x.x.x.x:5666/index.php"
```

**Comment by JCapriotti** [comment]
I found that during the request to `/api.php?testclient=true`, it seems to hang on [this line](https://github.com/d8ahazard/Phlex/blob/master/php/util.php#L453)

It tries to call `http://<public_ip>/api.php?device=Client&id=rescan&passive=true&apiToken=[REDACTED]`

I don't see any evidence in the logs of that call making it back around to the container. 

Might not be relevant but not quite sure what it should be doing.

**Comment by kverkind** [comment]
Same for me. Already tried on raspberry, docker and without firewall. No luck

**Comment by kverkind** [comment]
Jason, 
Thank you. It is working now for me as well.
Great job !

**Comment by kverkind** [comment]
Just reopen until change merged into main.

**Comment by kverkind** [comment]
And closed. Thanks
