### ISSUE TITLE
Fetching a missing movie VS direct fetch

### ISSUE THREAD

**Issue by XmemphistoX** [d8ahazard/Phlex#4]
Currently using Radarr

Fetching a movie directly using the direct command works.  I can say OK google, ask flex tv to fetch $movie.  I can see it added in my wanted Radarr list.

Asking Flex TV to watch a movie and if it doesn't exist will prompt me if it wants me add it to the watch list.  If I reply yes - It says it will try to add it and does nothing.  Below is my log.

` 06:14:54 PM - 03/16/2017
Initial command: "ask Flex TV to fetch underworld blood Wars"
Parsed command: "Fetch the media named ."
Search status:  Media added to fetcher.

Speech Response:  Okay, I've added Underworld: Blood Wars (2016) to the fetch list.
{JSON}

undefined
Initial command: "underworld blood wars"
Parsed command: "Fetch the first movie or show named underworld blood wars"
Search status: success

{JSON}

undefined
Initial command: ""
Parsed command: "Fetch the first movie or show named "
Search status: success

{JSON}

 06:12:20 PM - 03/16/2017
Initial command: "play underworld blood Wars"
Parsed command: "Play a media item with the title of 'underworld blood wars.'"
Search status:  No results found, prompting to download.

Speech Response:  I'm sorry, I was unable to find underworld blood wars in your library.  Would you like me add it to your watch list?
{JSON}`

**Comment by d8ahazard** [comment]
This should be fixed with today's commits.
