### ISSUE TITLE
Warning: session_start() [function.session-start]: The session id is too long or contains illegal characters"

### ISSUE THREAD

**Issue by jpb1977** [d8ahazard/Phlex#403]
#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
Hosting my own 
#### 2. On what OS are you running Flex TV?
CentOS 7
#### 3. Are you using a new instance of XAMPP, or an existing webserver?
XAMPP
#### 3b. If not XAMPP, what WebServer stack are you using?
n/ a
#### 4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
n/a
#### 5. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 8. Please describe the issue.
So I ran it via my Pixel 2 assistant and after saying talk to flex tv I got the error message below which of course made the app unusable as the assistant tried to read the whole error message.

I was able to run the program like once or twice then I got a lot of errors like this:
"Warning: session_start() [function.session-start]: The session id is too long or contains illegal characters"
Hobby programmer so I Googled it and came up with the following:
https://stackoverflow.com/questions/3185779/the-session-id-is-too-long-or-contains-illegal-characters-valid-characters-are/16318456#16318456

So changed code in api.php to this:
        $json = file_get_contents('php://input');
        $sessionId = json_decode($json, true)['originalRequest']['data']['conversation']['conversationId'] ?? $_GET['sessionId'] ?? false;

        $ok = @session_start();
        if(!$ok){
        session_regenerate_id(true); // replace the Session ID
        session_start();
        }
        if (!session_started()) {
                if ($sessionId) session_id($sessionId);
                session_start();
        }

Could probably simplify that with a || and one if.

Which solved the problem and made the program usable again. Again only hobby programmer so I don't fully understand the impact of the change nor if this is a bug or something affecting only my install.

**Comment by d8ahazard** [comment]
I'm actually working on an overhaul here:
https://github.com/d8ahazard/FlexTV

This is the exact solution I used. Not sure why it just randomly popped up.
;)
