### ISSUE TITLE
Dutch google assistant

### ISSUE THREAD

**Issue by filoor** [d8ahazard/Phlex#405]
Hi,

I cant find flex tv in the dutch google assistant

**Comment by matmuilwijk** [comment]
Mijn telefoon staat op Engels, maar die van mijn partner niet. Door haar de link te sturen kon zij wel de action koppelen. (simpel een share linkje) 

https://assistant.google.com/services/a/uid/00000000e3faabc3?hl=en

Above is the share link from my English phone. Should work!
