### ISSUE TITLE
Unable to parse response from server

### ISSUE THREAD

**Issue by Millerx23** [d8ahazard/Phlex#409]
### IMPORANT, PLEASE READ FIRST:

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
Own version.

#### 2. On what OS are you running Flex TV?
Win 10
#### 3. Are you using a new instance of XAMPP, or an existing webserver?
Yes, freshly installed version of XAMPP - 7.2.11-0-VC15 installer.
#### 3b. If not XAMPP, what WebServer stack are you using?
NA
#### 4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
I had to add it in as the php.ini file for my version of XAMPP did not have that line in it, I added it in with the rest of the extensions with no semi-colon.
#### 5. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 7. What are the last six digits of your server's API Token? (Settings -> Flex TV)
bef362

#### 8. Please describe the issue.

I initially was having a hard time with the “special characters …” errors being thrown, I added the recommended fix after digging through prior issues and google in the api.php and restarted Apache & Plex and I stopped getting that error. Now, I’m having issues when issuing “Play” commands it’s executing most of the time however, responds with an error “unable to parse the response from your server at http://xx.xx.xx.xx:8080/phlex”. 

This is the error from my Flex TV Logs: 
[11-10-2018 23:25:11.249900] [ERROR] [XXXXXXXXXXXXXXXXXXXXXXXXXX] [api::mapApiRequest:buildQueryMedia:sendMedia:fetchPlayerState:doRequest] - An exception occurred: cURL error 28: Operation timed out after 1000 milliseconds with 0 bytes received (see http://[REDACTED]/libcurl/c/libcurl-errors.html)
[11-10-2018 23:25:11.306900] [ERROR] [XXXXXXXXXXXXXXXXXXXXXXXXXX] [api::mapApiRequest:buildQueryMedia:sendMedia:fetchPlayerState:doRequest] - Error getting response from URL fetch.

My phlex_error.log just says php die('Access denied');  which was a couple hours ago before I started experiencing this latest issue.

It initially was playing videos issued via voice command, however it seems to have stopped.

**Comment by Millerx23** [comment]
It initially was playing videos issued via voice command, however it seems to have stopped.

**Comment by DieterKoblenz** [comment]
I am getting the same response now. This used to work without a problem, I did switch my Google account and server (Phlex) so that might be the issue.

**Comment by wdennis80** [comment]
Ditto, same error, "Unable to parse" followed by an extremely long string of gibberish.

**Comment by wdennis80** [comment]
Exact same problem, get an error "Unable to Parse" followed by gibberish when trying to get Google Assistant to talk to Phlex.

**Comment by BryanChiTown** [comment]
I am experiencing a similar issue. I am running my own Flex TV on windows 8.1, new instance of XAMPP, sockets enabled. I do not have a file named config.ini.php, I am not sure if that is part of the problem.

I have set permissions of the Phlex folder to 777 (which there is no guide within the setup instructions to do, but the guide says to make sure read and write permissions are set...)

Port 80 is forwarded to port 80. Windows firewall permission set. The cast plug-in is installed.

My issues are sporadic...

I will get a "I was unable to parse the response from your server at http://xx.xxx.xx.xxx/phlex" and nothing happens.

Or I will get the same message and the movie will start playing on the selected Chromecast.

Or I will get the message "...Session ID is to long...failed to read session data...api.php" and nothing happens

I am literally going crazy. Have spent part of 3 days to get this to work without errors. 

I have tried to go through the entire setup from scratch 3 times, unloaded and reloaded the Cast plugin, tried installing the "Flex plugin"...not sure if this is required to be used in place of the "Cast plugin" or in addition to it...

Any suggestions?  Thanks for your help!

**Comment by BryanChiTown** [comment]
> I am experiencing a similar issue. I am running my own Flex TV on windows 8.1, new instance of XAMPP, sockets enabled. I do not have a file named config.ini.php, I am not sure if that is part of the problem.
> 
> I have set permissions of the Phlex folder to 777 (which there is no guide within the setup instructions to do, but the guide says to make sure read and write permissions are set...)
> 
> Port 80 is forwarded to port 80. Windows firewall permission set. The cast plug-in is installed.
> 
> My issues are sporadic...
> 
> I will get a "I was unable to parse the response from your server at http://xx.xxx.xx.xxx/phlex" and nothing happens.
> 
> Or I will get the same message and the movie will start playing on the selected Chromecast.
> 
> Or I will get the message "...Session ID is to long...failed to read session data...api.php" and nothing happens
> 
> I am literally going crazy. Have spent part of 3 days to get this to work without errors.
> 
> I have tried to go through the entire setup from scratch 3 times, unloaded and reloaded the Cast plugin, tried installing the "Flex plugin"...not sure if this is required to be used in place of the "Cast plugin" or in addition to it...
> 
> Any suggestions? Thanks for your help!

Following up on my own issue....I downloaded what I believe is the beta version of Flex TV from https://github.com/d8ahazard/FlexTV , wiped the HTDOCS folder and copied the new files in there and everything seems to be working fine.

Thanks for making this product, donating now!
