### ISSUE TITLE
Voice command to select cast device

### ISSUE THREAD

**Issue by ColinSandercock** [d8ahazard/Phlex#410]
Is it possible to add a google voice command to select the google cast device. e.g. Ask flex tv to play <movie> on <device name>.
I have a couple google cast devices, and would simplify casting to be voice only (through google home).

Thanks

### IMPORANT, PLEASE READ FIRST:

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 8. Please describe the issue.

**Comment by evanjd** [comment]
For what it's worth, I just installed Phlex today and this worked out of the box for me. I literally say "Hey Google, Ask Flex Tv to play <<whatever I want played>> on <<device name>>" and it casts to the specified device.
