### ISSUE TITLE
HTTPS Certificate Invalid

### ISSUE THREAD

**Issue by rtrman** [d8ahazard/Phlex#421]
I just migrated from the hosted app to a locally-run version in an nginx container.
However, on attempting to link my google account, I get an ERR_CERT_DATE_INVALID on phlexchat.com.
Visiting phlexchat.com in a browser causes the same issue.
I expect this is an HTTPS certificate issue

**Comment by d8ahazard** [comment]
Fixed!

Migrated from Apache2 to Lighttpd a while back, forgot that I changed paths
to where the new cert was generated, didn't have the right listing for the
pemfile.
