### ISSUE TITLE
spanish language support?

### ISSUE THREAD

**Issue by helpman** [d8ahazard/Phlex#424]
#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
Using the app.phlexchat.com to check how it works before setting my own server

#### 8. Please describe the issue.
After choosing spanish as language, the bot replies, but nothing works. 
In this example, I asked it to play ghostbusters.

{
  "speech": "Tell dude to build me a speech string!",
  "cards": [],
  "playback": false,
  "suggestions": false,
  "wait": false,
  "contextName": "end",
  "mediaArray": false,
  "initialCommand": "reproducir cazafantasmas",
  "timeStamp": "Tue, 04 Dec 2018 15:12:28 -0600",
  "timecode": 1543957948,
  "stamp": "2018-12-04 03:12:28"
}

if I try to ask for it in english, this is what I get (but not playing anything whatsoever)

{
  "speech": "Muy bien entonces,",
  "cards": [
    {
      "title": " ()",
      "key": "library/metadata/",
      "subTitle": "",
      "formattedText": "",
      "image": {
        "url": "https://phlexchat.com/imageProxy.php?url=http%3A%2F%2F92.190.89.27%3A32400%2Fphoto%2F%3A%2Ftranscode%3Fwidth%3D600%26height%3D600%26minSize%3D1%26url%3D%252Flibrary%252Fmetadata%252F58424%252Fthumb%252F1543886537%26X-Plex-Token%3DzzE3kVqnz2kpNkgRez3o"
      }
    }
  ],
  "playback": {
    "title": null,
    "artist": null,
    "album": null,
    "key": "library/metadata/",
    "queueID": "1745",
    "source": "075bfc2080c3b4d968dacfa6ee07966d49658b89",
    "art": null,
    "thumb": "/library/metadata/58424/thumb/1543886537",
    "summary": null,
    "type": "track"
  },
  "suggestions": false,
  "wait": false,
  "contextName": "end",
  "mediaArray": [
    {
      "title": null,
      "artist": null,
      "album": null,
      "key": "library/metadata/",
      "queueID": "1745",
      "source": "075bfc2080c3b4d968dacfa6ee07966d49658b89",
      "art": null,
      "thumb": "/library/metadata/58424/thumb/1543886537",
      "summary": null,
      "type": "track"
    }
  ],
  "initialCommand": "play ghostbusters",
  "timeStamp": "Tue, 04 Dec 2018 15:13:27 -0600",
  "timecode": 1543958007,
  "stamp": "2018-12-04 03:12:27"
}

I would love to check everything works before messing with my own server ;D

**Comment by helpman** [comment]
The web app also has problems with accents (á, é, í, ó, ú) and ñ character

"La sabana africana es el escenario en el que tienen lugar las aventuras de Simba, un pequeÃ±o leÃ³n que es el heredero del trono. Sin embargo, se ve forzado a exiliarse al ser injustamente acusado de la muerte de su padre. Durante su destierro, harÃ¡ buenas amistades y, finalmente, regresarÃ¡ para recuperar lo que legÃ­timamente le corresponde."

(that was on what was being already playing when the app was launched. "Ã±" is ñ, Ã³ is ó, Ã¡ is á, Ã is í...)

**Comment by helpman** [comment]
edited. installed my own server, same result. at least now I know it's working like the web app :D :D :D 

I would be willing to help translating phlex into spanish

**Comment by naxhh** [comment]
I would love to talk to flex in spanish too. makes it easier for me. In fact i'm only using enlish support for this software.

What can we do to make this happen?
