### ISSUE TITLE
Accepting the voice and typed commands to giving the proper response but nothing is played on the device.

### ISSUE THREAD

**Issue by gamergeekv2** [d8ahazard/Phlex#425]
#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
https://app.phlexchat.com

#### 8. Please describe the issue.
Flex TV is accepting the voice and typed commands to giving the proper response but nothing is played on the device.  I have tried to change the cast device within Flex TV but this is not effecting it. I think this may be an issue with the cast plug-in. I cannot get into it by using serveraddress:32400/chromecast I get a 401 unauthroized error.  In the Plex Webapp I can see the the plugin and all devices but it gives me a "plugin is not responding message". This is a clean install of the newest version of cast.bundle that I can find. I have looked through all previous issues like this but they all seem to indicate that it was updated and fixed on the latest master.

**Comment by mist0706** [comment]
I have the same issue however using the self hosted version.
