### ISSUE TITLE
Connecting Phlex with a server at a remote location

### ISSUE THREAD

**Issue by spenjer1** [d8ahazard/Phlex#429]
### IMPORANT, PLEASE READ FIRST:

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
Yes, hosting my own.

#### 2. On what OS are you running Flex TV?
Windows 10 Professional 64-bit
#### 3. Are you using a new instance of XAMPP, or an existing webserver?
XAMPP
#### 3b. If not XAMPP, what WebServer stack are you using?
n/a
#### 4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes
#### 5. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.
n/a
*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 7. What are the last six digits of your server's API Token? (Settings -> Flex TV)
858061

#### 8. Please describe the issue.
My Plex server is at a remote location, being run off a FreeNAS server. I'm hosting Phlex locally on my windows machine. Is it possible to use Phlex with a remote server? When I look at what devices are available, it's showing the cast-capable devices at the location the Plex server is located, not the cast-capable devices in my own home. 

I thought hosting Phlex locally, it would scan my local network for the devices, then talk to Plex to cast the content to my screen. Any insight would be much appreciated. If there's a way to get this to work using remote-hosted Plex, a Wiki page tutorial would be very helpful.

**Comment by d8ahazard** [comment]
Currently...not possible.

However, I am working on a stand-alone version of the plugin for instances
like this...it should be made available in a week or two...or as soon as I
have enough time to finish it up. :D

**Comment by chimpy** [comment]
@d8ahazard Extremely interested in this! Subscribed to the thread.

I am currently using a remote server (because it has a Xeon) that streams to my local player (Apple TV). If I could install Phlex on my home server, or remote server, and be able to cast to/control my local player via my Google Homes that would be very very cool! Is this the kind of functionality you are aiming for? Will voice control for remote server Sonarr/Couchpotato be included also?
