### ISSUE TITLE
Feature Request: Music Artist/Album/Song Playback

### ISSUE THREAD

**Issue by hyvenglaven** [d8ahazard/Phlex#43]
Hi d8ahazard. First of all, this is a great project, and I've been following it with interest for months now. I finally installed it today, and it works great for queuing up TV shows and movies. I've also witnessed Phlex being able to play songs from my library, but not reliably. Would you consider adding this feature? I'd love to be able to say things like:

"Ask Phlex TV to play Don't stop Believin'"
"Ask Phlex TV to play songs by Journey"
"Ask Phlex TV to play my workout playlist on living room Chromecast"
etc.

Thanks again for all you've already done!

**Comment by d8ahazard** [comment]
Added with e6568f9.
