### ISSUE TITLE
Difficulty accessing music media within Plex Library from Flex TV

### ISSUE THREAD

**Issue by SymonVet** [d8ahazard/Phlex#430]
1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com? 

I am hosting my own installation of Flex TV on my server on which Plex is also hosted

If hosting your own version, please answer the below questions. Otherwise, proceed to #8.

2. On what OS are you running Flex TV?

My server is Linux CentOS 7.3 x86/64

3. Are you using a new instance of XAMPP, or an existing webserver? 

Existing installation of Apache 

3b. If not XAMPP, what WebServer stack are you using? 

Apache 2.4.6

4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV? 

yes

5. Have you followed the (networking)[Talking-To-The-Outside-World] section? 

yes

6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files. Paste anything that looks related as well.

BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION

7. What are the last six digits of your server's API Token? (Settings -> Flex TV) 

984f11

8. Please describe the issue.

It appears that Flex TV is unaware of media entries within my Plex libary that are identified as music. All videos recorded within my Plex library can be played without any difficulty via Flex TV, but... I am unable to play any of the music entries in my library via Flex TV. 

For example, I have a the Robbie Williams album Swing When You're Winning recorded within my Plex library as music. All tracks within this album are playable from within Plex. However, when I attempt to initiate their playing from Flex, I encounter the following problems:

Mon, 14 Jan 2019 10:00:10 +0000
You said: "Play robbie williams album swing when you're winning."
My reply: "I'm sorry, but I didn't find any results for 'robbie williams album swing when you're winning'."
{JSON}

Mon, 14 Jan 2019 09:59:44 +0000
You said: "Play robbie williams track mack the knife."
My reply: "Unfortunately, I couldn't find 'robbie williams track mack the knife' in the library."
{JSON}

Mon, 14 Jan 2019 09:59:17 +0000
You said: "Play mack the knife."
My reply: "Playing ."
{JSON}

Nothing is played in response to the last response above.

**Comment by RTPeat** [comment]
I'm getting similar issues - so for example asking Flex to play Swing When You're Winning by Robbie Williams produces "I'm sorry, but I didn't find any results for 'swing when you're winning by robbie williams'."

It will sometimes work if you ask just by track name, but trying to distinguish by artist it can't seem to manage.
