### ISSUE TITLE
Fresh Docker install but all pages are blank

### ISSUE THREAD

**Issue by AlexSterk** [d8ahazard/Phlex#432]
#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?

My own in Docker (note: plex is running on the same machine, not in Docker (I read somewhere that this can cause problems but I haven't gotten to that stage yet))

#### 2. On what OS are you running Flex TV?

Docker on a Raspberry Pi running Armbian

#### 3. Are you using a new instance of XAMPP, or an existing webserver?

Not using Xampp

#### 3b. If not XAMPP, what WebServer stack are you using?

the one from Docker

#### 4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?

This is already configured in Docker right? I haven't messed with anything regarding this question.

#### 5. Have you followed the (networking)[Talking-To-The-Outside-World] section?

Not yet, I first want to test locally

#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

n.a.

#### 7. What are the last six digits of your server's API Token? (Settings -> Flex TV)

n.a.

#### 8. Please describe the issue.

Hi! I'm having some trouble getting Phlex to work. I'm using the latest Docker image, but when I try to access `index.php` (or any other page), I get a blank page and no errors. (log files are empty!!!). I've added a `phpinfo.php` file to `/config/www` and that one isn't blank when I try to access it. So this means that the webserver and php is running correctly right? 

I'm not very experienced, I hope I'm not making a really stupid mistake here. I saw that the last update to the Docker was around 8 months ago, could it be that the Image it is based on has made some changes in those 8 months causing Phlex to no longer work?

**Comment by aMikeToThePast** [comment]
I'm also having this same issue with just seeing a blank pages(not using docker though, created an apache2 webserver). I'm also on a raspberry pi.

**Comment by aMikeToThePast** [comment]
check your apache error log seems like this is a simillair issue as issue 440 (https://github.com/d8ahazard/Phlex/issues/440)

you'll probably see the fatal error:
PHP Fatal error:  Uncaught Error: Call to a member function get() on boolean in /var/www/html/Phlex/php/webApp.php:108\nStack trace:\n#0 /var/www/html/Phlex/php/webApp.php(446): getPreference('general', 'value', 'http://localhos...', 'name', 'publicAddress')\n#1 /var/www/html/Phlex/php/webApp.php(12): serverAddress()\n#2 /var/www/html/Phlex/index.php(3): require_once('/var/www/html/P...')\n#3 {main}\n  thrown in /var/www/html/Phlex/php/webApp.php on line 108

Thats what I've found with mine so far.
No resolution yet.

**Comment by d8ahazard** [comment]
This issue should now be fixed.
