### ISSUE TITLE
Whats wrong with my install? How to install in docker?

### ISSUE THREAD

**Issue by Spacehoq** [d8ahazard/Phlex#433]
### IMPORANT, PLEASE READ FIRST:

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 8. Please describe the issue.

**Comment by Spacehoq** [comment]
docker create --name=FlexTV -v /configpath:/config -p 5666:5666 -p 5667:5667 -e HTTPPORT=5666 -e HTTPSPORT=5667 digitalhigh/phlex 

...this create the container and i can start it but it just dosnt work, i get no respone when browsing to <ip>:5666

**Comment by rjhilgefort** [comment]
I'm seeing this as well and I can't figure it out. I just saw your issue and mine might be a duplicate.
https://github.com/d8ahazard/Phlex/issues/436

**Comment by jokerigno** [comment]
did you change /configpath with a real folder?

**Comment by rjhilgefort** [comment]
@Spacehoq Check out my comment in #436: https://github.com/d8ahazard/Phlex/issues/436#issuecomment-457972674
