### ISSUE TITLE
Alexa support

### ISSUE THREAD

**Issue by ezraholm50** [d8ahazard/Phlex#435]
Hey Ben!

Any update on the dev with the Alexa device i've sent over? If you need help just point me in the right direction!

Ezra

**Comment by d8ahazard** [comment]
Hey Ezra,

Still slacking on my part. Basically just haven't had a lot of time to work
on the project lately, but I'm trying to get some more resources together
so I can get things moving again. I will keep you updated when I've got
something new for you.

-Ben

**Comment by ezraholm50** [comment]
No problem, if you need a hand, just point me in the right direction and i'll help out! Good to hear from you!

**Comment by ezraholm50** [comment]
Hey Ben,

I've tried linking my amazon account at https://phlexchat.com/alexaAuth.php?apiToken=8ca1e31d2325673f84ac825d5b691e293febd698f4&serverAddress=https%3A%2F%2F192.168.3.9%3A1778%2F

but it gives a file not found. Again if you need help with this, let me know.

**Comment by ezraholm50** [comment]
Anything?
