### ISSUE TITLE
Plex+Docker+Overlay network: Wrong URL

### ISSUE THREAD

**Issue by tboyce021** [d8ahazard/Phlex#44]
When Plex is running under docker with an overlay network, the server URI used to connect is the one for the overlay network, so running Phlex from a container not connected to this network causes the connection to Plex to fail.

From the Plex API, it's getting
```
<Connection protocol="https" address="192.168.86.45" port="32400" uri="https://192-168-86-45.XXXXXXXXXX.plex.direct:32400" local="1"/>
<Connection protocol="https" address="172.17.0.1" port="32400" uri="https://172-17-0-1.XXXXXXXXXX.plex.direct:32400" local="1"/>
<Connection protocol="https" address="10.42.0.1" port="32400" uri="https://10-42-0-1.XXXXXXXXXX.plex.direct:32400" local="1"/>
<Connection protocol="https" address="XXX.XX.XXX.XXX" port="32400" uri="https://XXX-XX-XXX-XXX.XXXXXXXXXX.plex.direct:32400" local="0"/>
```
and is picking the `10.42.0.1` one:
```
URL is: https://10-42-0-1.XXXXXXXXXX.plex.direct:32400?X-Plex-Token=XXXXXXXXXX
```

The `XXX.XX.XXX.XXX` is the public IP address, and the `192.168.86.45` is my home network IP. The other two are both for Docker.

For clarification, I'm running Phlex on two separate machines for different people and they aren't connected to each via the Docker overlay network. They both connect to the same Plex machine, one through the overlay network and one through the public IP address. The one that connects via the overlay network works with Phlex, the other one doesn't.

**Comment by tboyce021** [comment]
Honestly, I'm not sure why it picked that one. Plex API also has `publicAddressMatches="0"`, so it should have picked the last one based on the logic I see for this.

**Comment by tboyce021** [comment]
Interesting. Even though going to the URL printed in the logs I see that `publicAddressMatches="0"`, if I add
```
write_log('publicAddressMatches: '.$device['publicAddressMatches']);
```
it says the value is `1`. That's why it's choosing the local addresses instead of the public one.

**Comment by d8ahazard** [comment]
@tboyce021 - That's interesting.  I'll double-check the logic.

**Comment by d8ahazard** [comment]
Everybody, please give a try with commit 6bfb554, I've added logic for checking the validity of server URL's before assigning that URI to the device.  Hopefully, this should resolve these type of issues.

**Comment by d8ahazard** [comment]
Dockerfile has been updated to use host network, this should both fix casting, and resolve issues like above.

**Comment by dcarrion87** [comment]
This is still happening testing with latest docker image.
