### ISSUE TITLE
Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by Sman42** [d8ahazard/Phlex#440]
### IMPORANT, PLEASE READ FIRST:

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
Hosting

#### 2. On what OS are you running Flex TV?
Windows 10 Pro 1803

#### 3. Are you using a new instance of XAMPP, or an existing webserver?
New instance of XAMPP

#### 4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?

PHP has write-access

#### 5. Have you followed the (networking)[Talking-To-The-Outside-World] section?

Yes

#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 8. Please describe the issue.

Fatal error: Uncaught Error: Call to a member function get() on bool in C:\xampp\htdocs\php\webApp.php:108 Stack trace: #0 C:\xampp\htdocs\php\webApp.php(446): getPreference('general', 'value', 'http://localhos...', 'name', 'publicAddress') #1 C:\xampp\htdocs\php\webApp.php(12): serverAddress() #2 C:\xampp\htdocs\index.php(3): require_once('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\php\webApp.php on line 108

**Comment by joshmckinney** [comment]
I have the same thing happening on my Linux server since the last update.

PHP Fatal error:  Uncaught Error: Call to a member function get() on boolean in /var/www/html/Phlex/php/webApp.php:108\nStack trace:\n#0 /var/www/html/Phlex/php/webApp.php(446): getPreference('general', 'value', 'http://localhos...', 'name', 'publicAddress')\n#1 /var/www/html/Phlex/php/webApp.php(12): serverAddress()\n#2 /var/www/html/Phlex/index.php(3): require_once('/var/www/html/P...')\n#3 {main}\n  thrown in /var/www/html/Phlex/php/webApp.php on line 108

**Comment by aMikeToThePast** [comment]
I am also getting the same error

PHP Fatal error:  Uncaught Error: Call to a member function get() on boolean in /var/www/html/Phlex/php/webApp.php:108\nStack trace:\n#0 /var/www/html/Phlex/php/webApp.php(446): getPreference('general', 'value', 'http://localhos...', 'name', 'publicAddress')\n#1 /var/www/html/Phlex/php/webApp.php(12): serverAddress()\n#2 /var/www/html/Phlex/index.php(3): require_once('/var/www/html/P...')\n#3 {main}\n  thrown in /var/www/html/Phlex/php/webApp.php on line 108

**Comment by d8ahazard** [comment]
This should be fixed now.

**Comment by Sman42** [comment]
It's working now. Thank you.
