### ISSUE TITLE
“FlexTV is no longer available” from google assistant

### ISSUE THREAD

**Issue by huntersli** [d8ahazard/Phlex#443]
### IMPORANT, PLEASE READ FIRST:

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
Self hosted

#### 2. On what OS are you running Flex TV?
CentOS
#### 3. Are you using a new instance of XAMPP, or an existing webserver?
XAMP

#### 4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes
#### 5. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 8. Please describe the issue.
When asking the assistant to speak to FlexTV I get the response FlexTV is no longer available

**Comment by d8ahazard** [comment]
It's been temporarily taken offline...

**Comment by huntersli** [comment]
No problem d8ahazard I thought that might be the case. Is it likely to be down for a while? :-)

**Comment by huntersli** [comment]
Sorry d8ahazard I have just read your post on the Plex forum. I should have checked their first :-S keep up the good work and I look forward to the update.
