### ISSUE TITLE
Can not link to Google

### ISSUE THREAD

**Issue by iTurgon** [d8ahazard/Phlex#444]
### IMPORANT, PLEASE READ FIRST:

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
Own Version

#### 2. On what OS are you running Flex TV?
Windows 7 64bit

#### 3. Are you using a new instance of XAMPP, or an existing webserver?
New Instance

#### 4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes

#### 5. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes

#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 7. What are the last six digits of your server's API Token? (Settings -> Flex TV)
9061a3

#### 8. Please describe the issue.
I have done all the steps including downloading Cert. I was getting the BS message for the first while, now just getting "File not found"

**Comment by mattpurnell** [comment]
Me too

**Comment by codymhorton** [comment]
Same seeing it with link Google and Amazon. Going here: https://phlexchat.com/ says services are temporarily disabled? Maybe that's related.

**Comment by mattpurnell** [comment]
I commented before looking into it - the missing file is (was) located  on their own hosting (somewhere at phlexchat.com I think).

The guy behind D8aHazard has stated that the project is pretty much on hold until the next version. I contributed to his efforts to help it along - there is a link somewhere here

**Comment by Ziggid** [comment]
I've been having the same issue since I started setting it up a couple of weeks ago. Really eager to voice control my Plex server! Any indication on when this will be back up again, or has anyone found a workaround?
