### ISSUE TITLE
Google assistant

### ISSUE THREAD

**Issue by marcojo** [d8ahazard/Phlex#445]
Flex tv### IMPORANT, PLEASE READ FIRST:

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 6. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 8. Please describe the issue.
Flex tv seems to have been pulled by Google home.

**Comment by Dave-Still** [comment]
Hi marcojo
See the latest copy on the forum
https://forums.plex.tv/t/flex-tv-temporarily-down-for-updates/174627/2166

**Comment by mattgphoto** [comment]
Oof, that's rough. In combination with the dual names listed everywhere, will there be another new name if this re-relaunches listed in the documentation?

**Comment by d8ahazard** [comment]
It will be "flex tv" for everything.
