### ISSUE TITLE
change listening port?

### ISSUE THREAD

**Issue by dony71** [d8ahazard/Phlex#446]
By default phlex listen to port 80 
I don't use docker, 
what should I do if I want to change phlex listening port ?

**Comment by Linkzy01** [comment]
Did you even *bother* to check the Wiki at all?:

"If you wish to change the listening port for Phlex to something other than 80, you can do so in the Xampp control panel by clicking the "config" button next to Apache, and then opening httpd.conf.

In httpd.conf, you will see a line that reads "Listen 80". Change 80 to whichever port you want. Restart apache, and forward to that port. If you are on Windows, you will need to make a rule in Windows Firewall to allow that port's traffic as well."
