### ISSUE TITLE
Stuck loading

### ISSUE THREAD

**Issue by sekkr1** [d8ahazard/Phlex#449]
After launching the container i can access the web ui however after logging in to my plex it's just stuck on a loading screen indefinitely as so
![image](https://user-images.githubusercontent.com/23114730/55782324-b3e12280-5ab4-11e9-9ad2-799795a5f184.png)

Is this a problem on my end or it's related to the hosted version being down as well?

#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
Hosting my own on Docker

#### 2. On what OS are you running Flex TV?
Docker

**Comment by benjaminsherwood** [comment]
Have you port forwarded on your router, to whatever you've set the host (not container) port(s) to?

**Comment by Linkzy01** [comment]
> Have you port forwarded on your router, to whatever you've set the host (not container) port(s) to?

I'm experiencing the same issue after linking Plex, ports are forwarding, but I'm not sure how this is relevant, the issue is just whilst setting up Phlex on the local host (in my case anyway), external access hasn't come into play for me yet.

**Comment by SethDamiani** [comment]
> Have you port forwarded on your router, to whatever you've set the host (not container) port(s) to?

Haven't gotten to that stage yet - still isn't loading on localhost.

**Comment by tdelesio** [comment]
I had the same problem (am using docker as well).  It eventually came up.  Even when it does work however, you will encounter the same problem as the host service is not up.  If you want to see how I did it, here is my docker-compose file:

https://github.com/tdelesio/htpmanager/blob/traefik/docker-compose.yml

**Comment by Adzter** [comment]
I've tried both the Docker and just an Apache2 install. The only logs of value I can find look to be coming from calling a git command?

`fatal: $HOME not set`

I'm not sure how the Docker container is configured but it looks that when Apache starts it unsets the $HOME variable. I'm guessing that when the setup for Phlex is running it relies on using $HOME and falls over otherwise.

**Comment by lkgarrison** [comment]
I'm experiencing the same error as the OP, running on my own server, currently on localhost.

Everything in the console seems to be ok except for a 404 Not Found for manifest.json. Is that file important/worth digging into?
