### ISSUE TITLE
Feature Request - Link to multiple Google accounts

### ISSUE THREAD

**Issue by tboyce021** [d8ahazard/Phlex#45]
We have multiple people in our house that have Assistant and share a Google Home with linked accounts. I've registered my server with one account but get an error when trying to link any more. Is this possible or would I need to set up a separate server for each user?

**Comment by d8ahazard** [comment]
Fixed and working.  

To do the magic, just have your 'other' user open up the Phlex web UI and hit the 'link account' button.  When prompted to select their account, they do so.  Then have them ask to "Talk to Flex TV", and it should prompt them to finish linking.  :D
