### ISSUE TITLE
Feature Request - Login with either email or username

### ISSUE THREAD

**Issue by tboyce021** [d8ahazard/Phlex#46]
Currently, logging in with your email and username creates separate accounts for each and the settings are not shared between the two. Would it be possible to use something like the Plex token to link them as being the same account and share the settings between the two?

**Comment by d8ahazard** [comment]
To what end?  If you're looking to allow multiple Google Home users to control *your* Phlex setup, then you're in luck.  I've just updated the server-side of things to allow multiple google users to share an API token.  Just hit the "link account" button in the phlex UI and have them sign in with their google credentials, then ask to talk to Flex TV and good to go!

Let me know if this is what you mean, or if you want the ability to use different Plex accounts to share settings?

**Comment by tboyce021** [comment]
Actually, I think this was more of a bug. If you log in using your Plex email address, set everything up, log out, then log back in with your Plex username, everything you set up while logged in using your email address will be gone. This is because Phlex treats them as two different accounts, even though they're for the same Plex account.

**Comment by d8ahazard** [comment]
AH!  Gotcha.  I can fix this tomorrow.  Didn't even know email address
would work.  😂

**Comment by d8ahazard** [comment]
Fixed and improved!  Enjoy.  :D
