### ISSUE TITLE
Artwork not showing for results

### ISSUE THREAD

**Issue by tboyce021** [d8ahazard/Phlex#47]
![image](https://cloud.githubusercontent.com/assets/1326315/25647125/da71418a-2f84-11e7-81f4-a3f1f6cd2acc.png)

The logs say the URL should be using my `plexToken`, but doing so results in a `404 Unauthorized` error. Using my `plexServerToken` instead works.

**Comment by chrisstaite** [comment]
It's not working for me, showing 404 Not Found rather than 401 Unauthorized.  Changing the token gives me a 401.

**Comment by d8ahazard** [comment]
@tboyce021 , @chrisstaite  - Please try with the latest commits - I've changed the behavior for caching images to use the correct value of "token_plexserver" - versus the generic "plextoken".  I'm thinking commit 9cc9cf2 should resolve this problem.

Please confirm.

**Comment by thomaslittle** [comment]
I'm also having this issue. devtools says:
`Failed to load resource: net::ERR_INSECURE_RESPONSE` and 
`Failed to load resource: net::ERR_CONNECTION_REFUSED` for the images.

I'm also seeing
`Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` for some json files.

**Comment by chrisstaite** [comment]
I have updated to the latest head... I have a different error now, but still no photos:

https://xxxxxxxxxx.com/photo/:/transcode?width=1920&height=1920&minSize=1&url=/library/metadata/12771/thumb/1327920418&X-Plex-Token=xxxxxxxxxxxxxxx

The server is at https://xxxxxxxxxx.com/Phlex/  I tried adding that prefix, but there's no folder photo?

**Comment by d8ahazard** [comment]
@chrisstaite - Is phlex and your Plex server installed on the same computer?  https://xxxxxx.com *should* be an address for your Plex server...not the public address for Phlex.  You should be able to replace that with the IP of your server...

**Comment by chrisstaite** [comment]
They are installed on the same server.  I found the issue was that it was appending "plexServerpublicUri" from the configuration which wasn't set.  I set it and that fixed it.  However it's not referred to anywhere else in the code, so I imagine it's a typo.

**Comment by d8ahazard** [comment]
Just an update - this is just a big headache of an issue.  It depends on where the Plex server is, if it's owned, etc.  I'm still working out the bugs with this...

**Comment by d8ahazard** [comment]
Closed.
