### ISSUE TITLE
Music Playback Broken?

### ISSUE THREAD

**Issue by hyvenglaven** [d8ahazard/Phlex#53]
Hi,

I posted a feature request a couple weeks ago for better music playback, and I finally go around to pulling the latest and trying it out (thanks!). However, I still can't seem to get songs to play. When I ask for something like "songs by Queen", I get: 

```
Initial command: "ask Flex TV to play songs by Queen"
Parsed command: "Play a media item with the title of 'songs.'"
Search status:  No results found, prompting to download.

Speech Response:  I'm sorry, I was unable to find songs in your library.  Would you like me to add it to your watch list?
```

If I ask for a specific song, I get:

```
Initial command: "ask Flex TV to play another one bites the dust"
Parsed command: "Play the  named ."
Search status:  Fuzzy result found
Playback URL:  undefined
Playback status:  error
Speech Response:  Okay, Playing  ().
```

I'm running the server on Ubuntu 16.04, I've pulled the latest from master, and I've restarted apache.

Thanks!

**Comment by d8ahazard** [comment]
I'll download some queen and have a try.

**Comment by d8ahazard** [comment]
Hey, give it a try again after pulling the latest.  I've updated the voice recognition model to be a bit more flexible with keywords - "songs by", "tracks by", "music by" should all tell it you want music.

For the "specific tracks", again, give it another try.   I think that might have been an error on my end.

**Comment by hyvenglaven** [comment]
Thanks for taking a look. Both features seem to work now, though not consistently. The issues I've observed are:

1. The first request for a song turns on my Nvidia shield & TV and opens the plex app, but does not actually start playback. The second request works as intended. (this happens with other types of media as well, so this is more of an FYI unrelated to the music issue).

2. Music playback seemed to be working well on Nvidia Shield attached to TV. However, when I changed to the client to audio-only devices (google home or chromecast audio) I get no responses from Phlex ("Phlex TV isn't responding right now" or noncommital Phlex responses like "I'll try to do that for you" and my request does not get added to the web log). This may be unrelated to music playback as well, since it continued to fail even after changing the client back to the shield/TV. I  eventually had to restart the server, at which point I could switch to an audio device, but it did not understand phrases that had been working before (i.e. "play songs by queen" reverts to the old behavior of searching for something titled 'songs' in my library). The same phrase works on shield/TV, but again, switching from shield to an audio device causes phlex to go into non-responsive mode until the server is restarted. So my guess is there's something up with device switching and/or audio-only devices that a bit wonky.

Anyway, I really appreciate your responsiveness. I've been enjoying being a beta tester.

**Comment by d8ahazard** [comment]
Just an update to this - I've got the initial playback working now for cast devices with audio - turns out I was replacing the regular 'key' value for the media object with the queue ID, which works in one spot but not another.  :D  

Still got some other stuff with casting I want to tinker with, so I'm not going to close this issue just yet, just letting you know it's half-resolved.

**Comment by d8ahazard** [comment]
@hyvenglaven - Would you mind giving a try now with today's commits?  Lots of work has been done on the cast stuff, I'm curious to see how it works for you now.

**Comment by hyvenglaven** [comment]
Thanks. I just pulled the latest. At first, it could not recognize any of my devices (there were no options in the web interface dropdown). I tried to refresh the page to see if the list would populate, but the returned page is just black. I restarted apache a lot, but no luck.

Interestingly, I can load the web interface in an incognito window, but the device selector is still empty. In the incognito window, I clicked the gear icon, and clicked register server (under 'Google Action Account Linking'), even though I'd already liked my account earlier. It gave me an error saying to "check the setting for 'Public Address' in the Phlex UI." However, I have not changed this address since the last time I was successfully able to interact with Phlex. My guess is that google cannot reach the public address for the same reason I cannot (except, oddly, within an incognito window). What that reason is... I haven't a clue.

**Comment by d8ahazard** [comment]
Try now!  Cast stuff has been reworked again, I think music playback should be fairly reliable now.  :D

**Comment by hyvenglaven** [comment]
Sorry, not sure what's going on. I'm having trouble getting any media playback right now. And the list of available cast devices has shrunk to only my nvidia shield (listed twice, once as "Nvidia Shield Android TV" and once and "Shield"). I can get playback by typing directly into the web interface, and I can get recognition (sometimes) by speaking to google home (recognizes that the items exist in my library), but no playback. I'm starting to wonder if I've messed something up locally. To update each time, I just do:

`sudo git pull origin master`
`sudo chown -R www-data:www-data *`
`sudo /etc/init.d/apache2 restart`

**Comment by d8ahazard** [comment]
@hyvenglaven - Those commands should work fine to pull and update - you can even shorten the first one to just "git pull".

Try doing another update.  Make sure you're signed out of the Phlex UI, then open up your config.ini.php file and remove the line for dlist="adfada...".  Then log in, and hit the "refresh devices" button in the device selector list.  

If you're still missing devices, post some logs from the device refresh.

**Comment by d8ahazard** [comment]
@hyvenglaven - Haven't heard from you in a bit.  I'm going to close this for now.  If it's still an issue for you, feel free to reopen or repost.  Thanks!
