### ISSUE TITLE
Unable to Access Phlex Web UI

### ISSUE THREAD

**Issue by Monstar316** [d8ahazard/Phlex#54]
Hi,
I've tried to install install and configure Phlex but getting the attached error when I navigate to the web UI. I've already got an Apache webserver set up so don't need to isntall XAMPP
OS: Ubuntu 16.04
Curl: 7.47
PHP: 7.0.15
I cloned Phlex into /var/www/html and restarted Apache but still doesn't load correctly.
I know in the attached error it mentions about checking the write access to Phlex root. What access do I need to give to the Phlex folder and what user / group should this access be given to?
![phlexerror](https://cloud.githubusercontent.com/assets/16082971/26063233/4fe1d8e4-3985-11e7-980e-ba3517813aaf.png)

**Comment by pfmephisto** [comment]
hey Monstar316,

how did you enable Curl and PHP7 in apache? i imagine you solved your problem since you closed the issue.
