### ISSUE TITLE
Problem playing music via Phlex command line

### ISSUE THREAD

**Issue by TonyFrend** [d8ahazard/Phlex#55]
I am trying to use Phlex to play my audio files via the command line.

These files are mp3 files that have been cataloged by my Plex server. My Plex android app can locate and play these files OK.

My test audio file has the title 'Blackbird'. When I try to play it via the Phlex command line, I get the following JSON result (my cast device is 'Google Home'):

{
"initialCommand": "blackbird",
"parsedCommand": "Play the named blackbird.",
"mediaResult": false,
"playResult": {
"status": "error"
},
"mediaStatus": "SUCCESS: Approximate match found.",
"timestamp": " 07:38:40 AM - 05/16/2017",
"serverURI": "https://192-168-2-2.2da40387bdce4f91b3be4a43d45d47f7.plex.direct:32400",
"serverToken": "RZZ3sYy8obECXS7RWsqH",
"clientURI": "https://192.168.2.8:8009",
"clientName": "Google Home",
"commandType": "play"
}
The relevant lines from the Phlex.log file are as follows:

Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php - Got a request to play blackbird
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::parsePlayCommand - ################parsePlayCommand_START$##########################
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::parsePlayCommand - Function Fired.
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::parsePlayCommand - Initial command - blackbird
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::parsePlayCommand - Resulting string is:blackbird
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchInfo - Function Fired.
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchInfo - Mod string: num: 
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchInfo - Mod string: filter: 
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchInfo - Mod string: media: 
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchInfo - Mod string: preFilter: 
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchInfo - We have a preFilter: blackbird
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchInfo - Mod counts are 0 and 0
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchInfo - Number doesn't appear to be related to a context, re-appending.
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchInfo - Offset has been set to 0
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchHubResults - Function Fired.
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchHubResults - Type is 
Tue, 16 May 2017 07:38:39 -0500 [ DEBUG ] api.php::fetchHubResults - URL is : [url]https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:32400/hubs/search?query=blackbird&limit=30&X-Plex-Token=XXXXXXXXXXXXXXXXXXXX[/url]
Tue, 16 May 2017 07:38:40 -0500 [ DEBUG ] api.php::fetchHubResults - Title matches exactly: blackbird
Tue, 16 May 2017 07:38:40 -0500 [ DEBUG ] api.php::queueAudio - Function fired.
Tue, 16 May 2017 07:38:40 -0500 [ DEBUG ] api.php::queueAudio - MEDIA: {"@attributes":{"ratingKey":"99","key":"\/library\/metadata\/99","parentRatingKey":"91","grandparentRatingKey":"90","type":"track","title":"Blackbird","grandparentKey":"\/library\/metadata\/90","parentKey":"\/library\/metadata\/91","grandparentTitle":"The Warblers","parentTitle":"Glee: The Music Presents the Warblers","index":"8","parentIndex":"1","year":"2017","thumb":"\/library\/metadata\/91\/thumb\/1493399351","parentThumb":"\/library\/metadata\/91\/thumb\/1493399351","duration":"142811","originallyAvailableAt":"2017-04-28","addedAt":"1493399241","updatedAt":"1493399350","createdAtAccuracy":"epoch","createdAtTZOffset":"3600"},"Media":{"@attributes":{"id":"81","duration":"142811","bitrate":"210","audioChannels":"2","audioCodec":"mp3","container":"mp3"},"Part":{"@attributes":{"id":"85","key":"\/library\/parts\/85\/1493368059\/file.mp3","duration":"142811","file":"\/volume1\/music\/Glee\/Glee The Music Presents the Warblers\/08 Blackbird.mp3","size":"3751217","container":"mp3","hasThumbnail":"1"}}}}
Tue, 16 May 2017 07:38:40 -0500 [ DEBUG ] api.php::fetchSections - Function fired.
Tue, 16 May 2017 07:38:40 -0500 [ DEBUG ] api.php::queueAudio - Media URI is library%3A%2F%2F%2Fitem%2F%252Flibrary%252Fmetadata%252F99
Tue, 16 May 2017 07:38:40 -0500 [ DEBUG ] api.php::queueAudio - Final response: false
Tue, 16 May 2017 07:38:40 -0500 [ DEBUG ] api.php::fetchHubResults - Returning music queue: false
Tue, 16 May 2017 07:38:40 -0500 [ ERROR ] api.php::playMedia - No media to play!!
Tue, 16 May 2017 07:38:40 -0500 [ DEBUG ] api.php::log_command - Art Path is 
Tue, 16 May 2017 07:38:40 -0500 [ DEBUG ] api.php::log_command - Thumb path is 

Phlex seems to identify what I am looking for OK but, when it tries to play it, Phlex returns an error.

Please advise.

Many thanks,

Tony

**Comment by d8ahazard** [comment]
Give this a try now, I've fixed the bit that fetches the sections - I was hardcoding it to assume "music" is section number 3, when that's not the case.  It should now work as expected.  :D

**Comment by d8ahazard** [comment]
Well, I know music playback works, and I've rewritten the UI use the same language parsing as Google Assistant.  There is an issue with playing music to cast devices, but this is known and I'm working on it.  I'm going to close this for now.
