### ISSUE TITLE
error:  "I was unable to find any information on your user. Please relink your......."

### ISSUE THREAD

**Issue by seanvree** [d8ahazard/Phlex#56]
Running PHLEX on Windows 10E behind IIS reverse proxy. Running latest version on MASTER branch.

I can get to the WebUI and link radarr, sonarr fine. I can even see the available "cast to" devices. 

I can register my server fine:
"https://www.google.com/?result_code=SUCCESS&result_message=Accounts+now+linked."

However, when I invoke PHLEX via "okay, google, tell phlex TV to play a movie"  I get:

"I was unable to find any information on your user. Please relink your......."

I've tried to relink my server several times, and it's successful, but I always get that audio error above .

Any ideas?

THX

**Comment by d8ahazard** [comment]
Just made some updates to the server linking - see if that fixes you up.  Also, have you hit the "link account" card in the Ghome app (if it's there)?

**Comment by seanvree** [comment]
@d8ahazard  - 

So, now I'm unable to link the account at all. After I click Register server I get:

```
Unable to connect to Client at http://hostname.com/Phlex, please check the setting for 'Public Address' in the Phlex UI.
```
However, if I click on that address, it goes right to the login page. 

Error logs:
https://pastebin.com/Nytt2MdM

**Comment by seanvree** [comment]
@d8ahazard  - 

Looks like it was fixed with the latest update!

THANKS!
