### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by trackermb** [d8ahazard/Phlex#58]
Hi there, just created a test server installed xampp and plex. Can access the login page but when i enter plex username and password. It fails to log in - no error message just refreshes the page.  Could you advise me on what I have missed.

Many Thanks

**Comment by d8ahazard** [comment]
Check CURL is enabled. 😂

**Comment by nettosama** [comment]
Also running into this problem, and I have curl and sockets enabled:

[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
hash
json
libxml
mbstring
mysqlnd
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
SimpleXML
sockets
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

**Comment by trackermb** [comment]
Hi curl is enabled 
http://imgur.com/a/DTsdL

**Comment by nettosama** [comment]
In my case, changing the file permissions helped, not the config.ini.php file is created, but the php process stays at 100% CPU usage and never completes.

**Comment by mbze430** [comment]
Same here uncommented php_curl and php_openssl and it just sits at the the login

**Comment by nettosama** [comment]
It fails when accesing commands.php in my case, apparently it's not being created:

[21-May-2017 23:39:08 UTC] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /usr/share/nginx/html/Phlex/api.php on line 3313

**Comment by nettosama** [comment]
Well fixed my error doing "touch commands.php" on the root folder of Phlex, you could try to see if that fixes it.

**Comment by mbze430** [comment]
I am running it on a Win 8 machine in C:\xampp... for testing I gave 'phlex' directory and all sub directory "everyone" full access.

**Comment by nettosama** [comment]
Check the Phlex_error.log file

**Comment by mbze430** [comment]
that's the other thing... there is no phlex_error.log
`C:\xampp>dir Phlex_error.log /s
 Volume in drive C has no label.
 Volume Serial Number is F4AC-87E1
File Not Found`

**Comment by mbze430** [comment]
so I loaded up a Ubuntu 16.xx VM and installed LAMPP and Phlex.  Getting the same exact problem.  After entering username and password, it just sits there.  And the cpu runs up to 100%

So my question is... do you need a Plex Pass to run this add-on/app??  

I can't think of anything else

**Comment by nettosama** [comment]
Told you what I did to fix it. Manually create an empty file "commands.php" in the main web folder.

**Comment by mbze430** [comment]
Ahh, thanks.  That fixed it!
