### ISSUE TITLE
Chromecasts not showing

### ISSUE THREAD

**Issue by mochflix** [d8ahazard/Phlex#60]
I've tried multiple commits and run phlex on different machines, but phlex doesn't show my chromecasts as player.

It will show my phone and my gf's ipad as a player when plex app is started on these devices

**Comment by d8ahazard** [comment]
What OS do you have Phlex installed on?  

Give a pull of today's commits, I've reworked cast stuff, AGAIN.  I think it may help.

**Comment by mochflix** [comment]
I'm on Server 2012 R2.
I just updated but still cant see my ccs.

I also set the php filepath

**Comment by mochflix** [comment]
By the way... Copy/pasting the new pull into my existing phlex folder should be sufficient right?

**Comment by d8ahazard** [comment]
@mochflix - On your server 2k12 box, are you able to see cast devices from a web browser in the Plex app?

Yes, copy/pasting the new pull into the existing folder should be sufficient.

**Comment by mochflix** [comment]
Yes I can. I just sorted this this morning. I put the CC'S in the same v-lan as the server after which they showed up directly.
Funny though because the difference in vlans isn't a problem for the chrome browser on the same server

**Comment by d8ahazard** [comment]
@mochflix - Give today's commits a try, we cranked cast discovery up to 10 now.  It works on my server 2016 box, Synology NAS, and under Docker.

**Comment by mochflix** [comment]
You are a king! That worked!

**Comment by d8ahazard** [comment]
Thanks to @ChrisRidings for the help!!
