### ISSUE TITLE
Playback status:  error **New Pull, Same Error**

### ISSUE THREAD

**Issue by farmjope** [d8ahazard/Phlex#61]
No matter what I try I can't get media to play in my Plex player.  Even when I type in some sort of media and Phlex finds it:

  "mediaStatus": "SUCCESS: Approximate match found.",
  "timestamp": " 07:23:25 PM - 05/23/2017",
  "serverURI": "https://192-168-1-111.96de9e810071429194696ad2a8f698d2.plex.direct:32400",
  "serverToken": "ntxpbd1pF2hsjnk63H4m",
  "clientURI": "https://192-168-1-111.96de9e810071429194696ad2a8f698d2.plex.direct:32400",
  "clientName": "Plex Web (Chrome)",
  "commandType": "play"

You can see that it's trying to play it in my "Plex Web (Chrome)"

Looking in the error logs I see the below:

Tue, 16 May 2017 20:03:18 -0500 [ DEBUG ] api.php::playMediaQueued - Result is error

Any idea how to get Phlex correctly in sync with Plex to actually play the media?

Thank you for the help!!

**Comment by anick08** [comment]
I'm also having this issue.

**Comment by d8ahazard** [comment]
Please provided lines from Phlex.log showing what the function api.php::scanDevices is doing.  You can trigger a full scan by clicking the link in the device selection sceen.

**Comment by farmjope** [comment]
When I click "Scan Devices" it returns the same devices.  I make sure to select the "Plex (Chrome)" option again, still get the same error.
My "Google Home" is called "Dining Room Home" FYI

See below

Wed, 24 May 2017 10:13:20 -0500 [ DEBUG ] Chromecast.php::scansub - Function fired.
Wed, 24 May 2017 10:13:23 -0500 [ DEBUG ] api.php::scanDevices - Final hooplah is {"servers":[],"clients":[{"name":"Dining Room Home","product":"cast","id":"483a01ae1423c0071b9d0e8678e0c8fb","token":"none","uri":"https:\/\/192.168.1.120:8009"}],"dvrs":[]}
Wed, 24 May 2017 10:13:27 -0500 [ DEBUG ] api.php::scanDevices - URL is: https://plex.tv/api/resources?includeHttps=1&X-Plex-Token=ntxpbd1pF2hsjnk63H4m

**Comment by d8ahazard** [comment]
Give a pull now, I think I've cleaned some stuff up.

**Comment by farmjope** [comment]
Now Phlex doesn't appear to work at all.  The program seems to load but the screen is completely black.  So instead of the log in I get nothing at all....

How do I troubleshoot this?

**Comment by farmjope** [comment]
The UI started to come up.  It doesn't work properly like the old version of the code did, but I can at least see the JSON and can see that I'm still getting a playback error.  This is if I type in the command manually.

With the latest code, I say "OK Google, tell Phlex TV to play The Dark Knight"
Phlex comes back with "I'll work on that for you" and then does nothing at all.

**Comment by d8ahazard** [comment]
See my comment in the Plex forums, give that a try.  If you still need help, pm me full logs there, and I'll go over them.

**Comment by farmjope** [comment]
Thank you for the help, that did the trick, switching to a new "app" (PMP).

Do you happen to have a list of supported apps?

**Comment by d8ahazard** [comment]
Is it a Plex app, not the web app?  It should be supported.  Does the web
app sometimes work anyway?  Yes.  I should just filter the web app out of
the list.  😂
