### ISSUE TITLE
Phlex - Seems to be broken

### ISSUE THREAD

**Issue by anick08** [d8ahazard/Phlex#62]
I'm having a few issues.
1) When I say "Talk to Flex" it does not allow for conversation.
2) Media will not play in the local host or public IP browser. 
3) Phlex seems to think that it is successfully playing media, but is not actually doing so. 

On what OS are you running Phlex?
Win10

Are you using a new instance of XAMPP, or an existing webserver?
Freshly downloaded today.

If Using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
N/A

If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
Win10/Plex

Is Phlex using http or https?
http

If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files. Paste anything that looks related as well.
erm.... its a blank document.

**Comment by d8ahazard** [comment]
I've done a bunch of stuff today with logging and extra checking, please do a pull and let me know how things work for you.
