### ISSUE TITLE
Phlex: "Ask Phlex TV to play Jersey Shore" but resumes playback of current show instead.

### ISSUE THREAD

**Issue by jmcree** [d8ahazard/Phlex#66]
After testing about a dozen shows, all tested will change except Jersey Shore.  Phlex lives on a Win7 box with XAMPP and Plex is an Unraid Plugin on it's own machine if it matters.

You said: "Ask Flex TV to play Jersey Shore."
My reply: "Resuming playback.

{
  "initialCommand": "ask Flex TV to play Jersey Shore",
  "parsedCommand": "play",
  "playResult": {
    "url": "http://[ip]:8324/player/playback/play?X-Plex-Token=2rMwb8qAVovMvgjdeZC1&commandID=19",
    "status": "success"
  },
  "mediaStatus": "SUCCESS: Not a media command",
  "commandType": "control",
  "clientURI": "http://[ip]:8324",
  "clientName": "Roku Premiere - YT000N895155",
  "serverURI": "https://[ip].f521f02e1536499fb6a81a12124fd384.plex.direct:32400",
  "serverToken": "LaQ8SRS8HXYBuVvhpakZ",
  "timestamp": " 07:12:44 PM - 05/27/2017",
  "speech": "Resuming playback."
}

**Comment by d8ahazard** [comment]
Try this command again, please.  Then, in your Phlex.log file, look for the line that says:

  [ DEBUG ] api.php::parseApiCommand - Full request text is {"originalRequest":{"source":"google","data":{"surface":{"capabilities":[{"name":"actions.capability.AUDIO_OUTPUT"},{"name":"actions.capability.SCREEN_OUTPUT"}]},"inputs":[{"arguments":[{"raw_text":"stop","text_value":"Stop","name":"Controls"},{"raw_text":"stop playback","text_value":"stop playback","name":"trigger_query"}],"intent":"assistant.intent.action.MAIN","raw_inputs":[{"query":"ask flex tv to stop playback","input_type":3}]}],"user":{"access_token":"XXXXXXXXXXXXXXXXXXXXXXXXXX","user_id":"XXXXXXXXXXXXXXXXXXXXXXXXX=","locale":"en-US"},"is_in_sandbox":true,"conversation":{"conversation_id":"1496180347413","type":1}}},"id":"34990334-7513-4cf0-9ae8-9b316de90537","timestamp":"2017-05-30T21:39:07.471Z","lang":"en","result":{"source":"agent","resolvedQuery":"stop playback","action":"Playmedia","parameters":{"Controls":"Stop"},"contexts":[{"name":"promptfortitle","parameters":{"Controls":"Stop","Controls.original":"stop playback"},"lifespan":3},{"name":"google_assistant_welcome","parameters":{"Controls":"Stop","Controls.original":"stop playback"}},{"name":"waitforplayer","parameters":{"Controls":"Stop","Controls.original":"stop playback"},"lifespan":3},{"name":"actions_capability_screen_output","parameters":{"Controls":"Stop","Controls.original":"stop playback"}},{"name":"yes","parameters":{"Controls":"Stop","Controls.original":"stop playback"},"lifespan":3},{"name":"actions_capability_audio_output","parameters":{"Controls":"Stop","Controls.original":"stop playback"}},{"name":"google_assistant_input_type_keyboard","parameters":{"Controls":"Stop","Controls.original":"stop playback"}}],"metadata":{"intentId":"b8151275-afad-4f3f-bd9a-3a17f390cb75","webhookUsed":"true","webhookForSlotFillingUsed":"false","nluResponseTime":8,"intentName":"PlayMedia"},"fulfillment":{"messages":[[]]},"score":1},"status":{"code":200,"errorType":"success"},"sessionId":"1496180347413"}

Paste me some of that, be sure to obscure your user id and access token.

**Comment by jmcree** [comment]
Sure thing: 

Wed, 31 May 2017 00:23:23 +0000 [ DEBUG ] api.php::parseApiCommand - Full request text is {"originalRequest":{"source":"google","data":{"surface":{"capabilities":[{"name":"actions.capability.AUDIO_OUTPUT"}]},"inputs":[{"arguments":[{"raw_text":"play","text_value":"play","name":"action"},{"raw_text":"Jersey Shore","text_value":"Jersey Shore","name":"command"},{"raw_text":"play Jersey Shore","text_value":"play Jersey Shore","name":"trigger_query"}],"intent":"assistant.intent.action.MAIN","raw_inputs":[{"query":"ask Flex TV to play Jersey Shore","input_type":2}]}],"user":{"access_token":"[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]","user_id":"[xxxxxxxxxxxxxxxxxxxxxxxxxxxxx]","locale":"en-US"},"conversation":{"conversation_id":"1496190207357","type":1}}},"id":"95898736-bdd2-47f0-8d83-342436788fa4","timestamp":"2017-05-31T00:23:27.476Z","lang":"en","result":{"source":"agent","resolvedQuery":"play Jersey Shore","action":"Playmedia","parameters":{"geo-city":"Jersey Shore","action":"play"},"contexts":[{"name":"promptfortitle","parameters":{"geo-city":"Jersey Shore","action.original":"play","action":"play","geo-city.original":"Jersey Shore"},"lifespan":3},{"name":"waitforplayer","parameters":{"geo-city":"Jersey Shore","action.original":"play","action":"play","geo-city.original":"Jersey Shore"},"lifespan":3},{"name":"google_assistant_welcome","parameters":{"geo-city":"Jersey Shore","action.original":"play","action":"play","geo-city.original":"Jersey Shore"}},{"name":"yes","parameters":{"geo-city":"Jersey Shore","action.original":"play","action":"play","geo-city.original":"Jersey Shore"},"lifespan":3},{"name":"actions_capability_audio_output","parameters":{"geo-city":"Jersey Shore","action.original":"play","action":"play","geo-city.original":"Jersey Shore"}},{"name":"google_assistant_input_type_voice","parameters":{"geo-city":"Jersey Shore","action.original":"play","action":"play","geo-city.original":"Jersey Shore"}}],"metadata":{"intentId":"b8151275-afad-4f3f-bd9a-3a17f390cb75","webhookUsed":"true","webhookForSlotFillingUsed":"false","nluResponseTime":81,"intentName":"PlayMedia"},"fulfillment":{"messages":[[]]},"score":1},"status":{"code":200,"errorType":"success"},"sessionId":"1496190207357"}

**Comment by d8ahazard** [comment]
Got it!  It's parsing "Jersey Shore" as an actual location...

"geo-city":"Jersey Shore.

Try now, I've retrained the agent.  If that doesn't work, I'll have to
manually filter.

**Comment by jmcree** [comment]
Worked man! You are awesome! Just curious, does it pick the first listed non-watched episode? or how does it select which episode to play if i just say the series name?

**Comment by d8ahazard** [comment]
Yeah, it should pick the first unwatched episode if you just say the show
name.  :D
