### ISSUE TITLE
Cannot get shows to fetch - Probably ID-10-T error

### ISSUE THREAD

**Issue by jmcree** [d8ahazard/Phlex#67]
Could you provide some direction on getting Phlex to add shows to either SickBeard or Sonarr. I cannot get either to work so I'm assuming it's something I'm doing. I was successfully able to get movies to fetch via CouchPotato but i took looking through the logs at the api call to see what I was doing wrong. I do not see any api calls for the TV shows though.

**Comment by d8ahazard** [comment]
It should all work the same.  Pop in the ip address, port, and api key/token from that app.  Hit the "test" button, and it should show you a snackbar(popup) that tells you whether or not it succeeded.  

This should also generate information in Phlex.log that can be used to debug a connection failure.  ;)

**Comment by jmcree** [comment]
i get a successful alert but it never adds. I was testing with Doctor Who. I noticed when testing with the movie Logan i had to give it the year as well. Am I not being specific enough with the naming? Do you have a suggestion of a series I can test with?

**Comment by d8ahazard** [comment]
I always test with "Gunsmoke"

On May 30, 2017 7:30 PM, "jmcree" <notifications@github.com> wrote:

i get a successful alert but it never adds. I was testing with Doctor Who.
I noticed when testing with the movie Logan i had to give it the year as
well. Am I not being specific enough with the naming? Do you have a
suggestion of a series I can test with?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/d8ahazard/Phlex/issues/67#issuecomment-305047123>, or mute
the thread

**Comment by jmcree** [comment]
I tested with GunSmoke. Here is the log: It thought it was a movie.

Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::parseApiCommand - Full request text is {"originalRequest":{"source":"google","data":{"surface":{"capabilities":[{"name":"actions.capability.AUDIO_OUTPUT"}]},"inputs":[{"arguments":[{"raw_text":"yes","text_value":"yes","name":"text"}],"intent":"assistant.intent.action.TEXT","raw_inputs":[{"query":"yes","input_type":2}]}],"user":{"access_token":"[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]","user_id":"[xxxxxxxxxxxxxxxxxxxxxxxxxxxx]","locale":"en-US"},"conversation":{"conversation_token":"[\"waitforplayer\",\"yes\"]","conversation_id":"1496192804350","type":2}}},"id":"c6d2f7e4-f6af-4876-a242-9222f8a04a5a","timestamp":"2017-05-31T01:06:56.66Z","lang":"en","result":{"source":"agent","resolvedQuery":"yes","parameters":{"action":"fetchAPI","YesNo":"yes"},"contexts":[{"name":"waitforplayer","parameters":{"YesNo.original":"yes","command":"Gunsmoke","command.original":"Gunsmoke","action":"fetchAPI","YesNo":"yes"},"lifespan":2},{"name":"yes","parameters":{"YesNo.original":"yes","command":"Gunsmoke","command.original":"Gunsmoke","action":"fetchAPI","YesNo":"yes"},"lifespan":1},{"name":"google_assistant_input_type_voice","parameters":{"YesNo.original":"yes","action":"fetchAPI","YesNo":"yes"}},{"name":"actions_capability_audio_output","parameters":{"YesNo.original":"yes","action":"fetchAPI","YesNo":"yes"}}],"metadata":{"intentId":"99fd7a7b-33f5-43eb-b423-3ef008ee6c8a","webhookUsed":"true","webhookForSlotFillingUsed":"true","nluResponseTime":4,"intentName":"AcceptDownloadResponse"},"fulfillment":{"messages":[[]]},"score":1},"status":{"code":200,"errorType":"success"},"sessionId":"1496192804350"}
Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::parseApiCommand - Raw speech is yes
Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::parseApiCommand - Action is currently fetchAPI
Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::parseApiCommand - Context JSON should be {"name":"yes","parameters":{"YesNo.original":"yes","command":"Gunsmoke","command.original":"Gunsmoke","action":"fetchAPI","YesNo":"yes"},"lifespan":1}
Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::parseApiCommand - Final params should be an action of fetchAPI, a command of gunsmoke, a type of , and a control of .
Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::parseFetchCommand - Function Fired.
Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::parseFetchCommand - Searching for first media matching title.
Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::downloadMovie - Function fired.
Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::downloadMovie - Using Couchpotoato for Movie agent
Wed, 31 May 2017 01:06:52 +0000 [ DEBUG ] api.php::couchDownload - Sending request to http://hook:5050/api/d5b14f7fad784ca08c3210f6b1d29943/movie.search/?q=gunsmoke
Wed, 31 May 2017 01:06:56 +0000 [ DEBUG ] api.php::couchDownload - body:
Wed, 31 May 2017 01:06:56 +0000 [ DEBUG ] api.php::parseFetchCommand - Final result: {"initialCommand":"gunsmoke","parsedCommand":"Fetch the first movie or show named gunsmoke","status":"ERROR: No results for query.","mediaStatus":"ERROR: No results for query."}
Wed, 31 May 2017 01:06:56 +0000 [ DEBUG ] api.php::parseApiCommand - MediaResult: {"initialCommand":"gunsmoke","parsedCommand":"Fetch the first movie or show named gunsmoke","status":"ERROR: No results for query.","mediaStatus":"ERROR: No results for query."}
Wed, 31 May 2017 01:06:56 +0000 [ DEBUG ] api.php::returnSpeech - Final Speech should be: Unfortunately, I was not able to find anything with that title to download.
Wed, 31 May 2017 01:06:56 +0000 [ DEBUG ] api.php::returnSpeech - Card array is false
Wed, 31 May 2017 01:06:56 +0000 [ DEBUG ] api.php::returnSpeech - Expect response is 
Wed, 31 May 2017 01:06:56 +0000 [ DEBUG ] api.php::returnSpeech - JSON out is {"speech":"Unfortunately, I was not able to find anything with that title to download.","contextOut":[{"name":"yes","lifespan":2},{"name":"yes","lifespan":2},{"name":"promptfortitle","lifespan":0}],"data":{"google":{"expect_user_response":false,"rich_response":{"items":[{"simple_response":{"display_text":"Unfortunately, I was not able to find anything with that title to download.","text_to_speech":"Unfortunately, I was not able to find anything with that title to download."}}]}}},"displayText":"Unfortunately, I was not able to find anything with that title to download.","source":"api.php"}


Here I am specifying that it is a TV Show:

Wed, 31 May 2017 01:10:17 +0000 [ DEBUG ] api.php::parseApiCommand - Full request text is {"originalRequest":{"source":"google","data":{"surface":{"capabilities":[{"name":"actions.capability.AUDIO_OUTPUT"}]},"inputs":[{"arguments":[{"raw_text":"yes","text_value":"yes","name":"text"}],"intent":"assistant.intent.action.TEXT","raw_inputs":[{"query":"yes","input_type":2}]}],"user":{"access_token":"[xxxxxxxxxxxxxxxxxxxxxxxxxx]","user_id":"[xxxxxxxxxxxxxxxxxxxxxxxxxxxxx]","locale":"en-US"},"conversation":{"conversation_token":"[\"waitforplayer\",\"yes\"]","conversation_id":"1496193008001","type":2}}},"id":"3d48e4fe-8fac-407a-ad8d-a1792712925b","timestamp":"2017-05-31T01:10:20.401Z","lang":"en","result":{"source":"agent","resolvedQuery":"yes","parameters":{"action":"fetchAPI","YesNo":"yes"},"contexts":[{"name":"waitforplayer","parameters":{"YesNo.original":"yes","type":"show","command":"Gunsmoke","command.original":"Gunsmoke","type.original":"TV show","action":"fetchAPI","YesNo":"yes"},"lifespan":2},{"name":"yes","parameters":{"YesNo.original":"yes","type":"show","command":"Gunsmoke","command.original":"Gunsmoke","type.original":"TV show","action":"fetchAPI","YesNo":"yes"},"lifespan":1},{"name":"google_assistant_input_type_voice","parameters":{"YesNo.original":"yes","action":"fetchAPI","YesNo":"yes"}},{"name":"actions_capability_audio_output","parameters":{"YesNo.original":"yes","action":"fetchAPI","YesNo":"yes"}}],"metadata":{"intentId":"99fd7a7b-33f5-43eb-b423-3ef008ee6c8a","webhookUsed":"true","webhookForSlotFillingUsed":"true","nluResponseTime":4,"intentName":"AcceptDownloadResponse"},"fulfillment":{"messages":[[]]},"score":1},"status":{"code":200,"errorType":"success"},"sessionId":"1496193008001"}
Wed, 31 May 2017 01:10:17 +0000 [ DEBUG ] api.php::parseApiCommand - Raw speech is yes
Wed, 31 May 2017 01:10:17 +0000 [ DEBUG ] api.php::parseApiCommand - Action is currently fetchAPI
Wed, 31 May 2017 01:10:17 +0000 [ DEBUG ] api.php::parseApiCommand - Context JSON should be {"name":"yes","parameters":{"YesNo.original":"yes","type":"show","command":"Gunsmoke","command.original":"Gunsmoke","type.original":"TV show","action":"fetchAPI","YesNo":"yes"},"lifespan":1}
Wed, 31 May 2017 01:10:17 +0000 [ DEBUG ] api.php::parseApiCommand - Final params should be an action of fetchAPI, a command of gunsmoke, a type of show, and a control of .
Wed, 31 May 2017 01:10:17 +0000 [ DEBUG ] api.php::parseFetchCommand - Function Fired.
Wed, 31 May 2017 01:10:17 +0000 [ DEBUG ] api.php::parseFetchCommand - Searching explicitely for a show.
Wed, 31 May 2017 01:10:17 +0000 [ DEBUG ] api.php::downloadSeries - Using Sonarr for Episode agent
Wed, 31 May 2017 01:10:18 +0000 [ ERROR ] api.php::sonarrDownload - Error retrieving root path.
Wed, 31 May 2017 01:10:18 +0000 [ DEBUG ] api.php::parseFetchCommand - Result false
Wed, 31 May 2017 01:10:18 +0000 [ DEBUG ] api.php::parseFetchCommand - Final result: {"mediaStatus":null,"parsedCommand":"Fetch the show named ","initialCommand":"gunsmoke"}
Wed, 31 May 2017 01:10:18 +0000 [ DEBUG ] api.php::parseApiCommand - MediaResult: {"mediaStatus":null,"parsedCommand":"Fetch the show named ","initialCommand":"gunsmoke"}
Wed, 31 May 2017 01:10:18 +0000 [ DEBUG ] api.php::returnSpeech - Final Speech should be: Unfortunately, I was not able to find anything with that title to download.
Wed, 31 May 2017 01:10:18 +0000 [ DEBUG ] api.php::returnSpeech - Card array is false
Wed, 31 May 2017 01:10:18 +0000 [ DEBUG ] api.php::returnSpeech - Expect response is 
Wed, 31 May 2017 01:10:18 +0000 [ DEBUG ] api.php::returnSpeech - JSON out is {"speech":"Unfortunately, I was not able to find anything with that title to download.","contextOut":[{"name":"yes","lifespan":2},{"name":"yes","lifespan":2},{"name":"promptfortitle","lifespan":0}],"data":{"google":{"expect_user_response":false,"rich_response":{"items":[{"simple_response":{"display_text":"Unfortunately, I was not able to find anything with that title to download.","text_to_speech":"Unfortunately, I was not able to find anything with that title to download."}}]}}},"displayText":"Unfortunately, I was not able to find anything with that title to download.","source":"api.php"}

Any help is greatly appreciated

**Comment by d8ahazard** [comment]
@jmcree - Please give today's commit a try.  I've fixed a bunch of things, including tinkering with show stuff last night.  I believe I fixed both issues I saw in your logs.

**Comment by jmcree** [comment]
Thanks man! Forgive my ignorance, but what does it mean to give the commit a try? Do I need to re-download?

**Comment by d8ahazard** [comment]
Yeah, a commit is "committing new code to the git repository".  So, "try
the latest commit" = "there's new stuff on github to download"  :D

>

**Comment by jmcree** [comment]
Thanks!. I tried the new code (copied down and overwrote the existing files) but it was giving me errors with the double ?? marks. I was able to work my way through the util.php file and get the login page to load but then it gave me the same message with the api.php file so I stopped. Did I do something wrong?

**Comment by jmcree** [comment]
Good news! Its now fetching shows!. But something else has happened. I will open a separate ticket.
