### ISSUE TITLE
Google Home and other languages

### ISSUE THREAD

**Issue by Tawmu** [d8ahazard/Phlex#68]
Hey,

Just tried to link my Google Home to Phlex but get "Sorry, this service is not available to users of British English language yet" (or something very close to that).

Is there something I'm missing, or could you please enable Phlex support outside of the USA?

Cheers :)

**Comment by d8ahazard** [comment]
Hello, thanks for the submission.  Unfortunately, this is a known issue relating to Google's side of things, not mine.  If I had a way to disable that error, it would be done already.  The only workaround for this at the moment is to change Assistant's language to US English, or use IFTTT.

Once google opens up multilanguage support to developers, you can be assured I will enable it.
