### ISSUE TITLE
Please for the love of god, let us make our own trigger phrase!

### ISSUE THREAD

**Issue by leram84** [d8ahazard/Phlex#7]
First of all, this looks downright glorious!  It is the thing i have wanted since i was 12 years old! lol. I haven't installed this yet. But the one thing i am going to want more than anything is the ability to trigger by using my own plex servers name. Its already ridiculous that google forces us to profess their name every time we want to use their service (no matter how many god damn devices you have that are forced to use the same god damn trigger word... ok google is literally voldemort in my house... we do not speak it. But i digress), but since you're not generating any revenue from the phlex trademark im hopping you will be amenable to letting us personalize this a little :)

**Comment by d8ahazard** [comment]
Really it's largely out of my control.  The "OK Google" bit is totally up to google, and nothing I can control for Ghome/assistant.  "Flex TV" is the closet thing I could come up with to the app name, and is tied to the actual deployed "package" with google, so again, there's not like some way for me to change it via code.  

The best you can do is use the IFTTT links in settings.  By setting it up with Assistant+IFTTT, you can set your own invocation phrase "Ok Google, My flappy meat thrusters Batman Begins".  Make "My flappy meat thrusters" your invocation phrase for the play command, and then paste in the link for your server.  Presto commando.  

Sorry I can't do more, but it's literally out of my hands.

**Comment by leram84** [comment]
> Sorry I can't do more, but it's literally out of my hands.

i don't understand... didn't you literally just give me a way to do what i was asking for?

**Comment by leram84** [comment]
lol... and THANK YOU
