### ISSUE TITLE
Feature Request: Outgoing web requests

### ISSUE THREAD

**Issue by mgiljum** [d8ahazard/Phlex#76]
It would be great to have the option to send an outgoing specific web GET or POST request from Phlex when a certain action is performed. This would allow folks to control a smarthome device, for example, dimming the lights, or hook it up to another IFTTT app using a webhook.

An example would be something like:

When a movie is played -> send a HTTP get request to an IFTTT webhook -> IFTTT does something (dim lights, turn on your $1500 smart popcorn popper, etc)

My personal set up could possibly look something like this:

When a movie is played "in cinema mode" -> send http GET request to smartthings hub -> hub turns on the projector, dims the lights

**Comment by d8ahazard** [comment]
Easy enough to implement, it'd take more work to sort out which parameters
to expose and create an interface or list of values, and some kind of form
with multiple, addable inputs.

So, most commands are broken up into "action" and "command", where action
is "play, control, fetch, ondeck, recent, server, player" - and the command
is the media title or 'play/pause/stop/skip" etc.

It would need an option, I imagine, to only send a webhook if a certain
player is triggered, so it would also need to consider what session
variables are set and provide filters for those.

I'm currently working on finishing a retrieve function for a sort of
"what's on tv today" command - once that's done, I've got some finalization
to do with Google support for some card returns.  When I get both of those
sorted, I will take a crack at this.  :D

**Comment by d8ahazard** [comment]
@mgiljum -

Here's a preview of the layout I've come up with to accommodate this:

![image](https://user-images.githubusercontent.com/1633844/26842660-3974f836-4ab3-11e7-842f-54a085499641.png)

![image](https://user-images.githubusercontent.com/1633844/26842675-451e7eb4-4ab3-11e7-9121-e62efb9f8ebd.png)

The idea being, you can either have one URL that you can toggle hooks on/off for, OR, you can have a separate webhook URL for each command.  

Additionally, you can set up a custom trigger phrase that is completely independent of any other Phlex command, which could then be used to do whatever you can do with a webhook.  :D 

This is just a very initial layout...as I mentioned earlier, I can imagine use-cases where people only want it to trigger if played to a specific player, or maybe some situation where you want to get an email with the name of what's played or downloaded, which will require me to cook up a list of parameters that can be grabbed from the return cards and passed out to the webhook as {{VALUE}} params in a GET query.

Oh, and submitting a GET vs a POST...sometimes these require headers or something as well.

So, what use-cases did you have in mind considering the direction in which I'm going, and am I missing anything that would be applicable to this request?

**Comment by d8ahazard** [comment]
![hooks1](https://user-images.githubusercontent.com/1633844/26843109-b7aca61c-4ab4-11e7-8275-eccd845f38bd.png)

**Comment by d8ahazard** [comment]
![image](https://user-images.githubusercontent.com/1633844/27386203-b13b4d72-565a-11e7-8441-bf1cf291834c.png)

Webooks are now implemented and working!

**Comment by d8ahazard** [comment]
Added with commit 3da958151f735eddab3ca5ad758038558d1690e1
