### ISSUE TITLE
Can't find chrome cast

### ISSUE THREAD

**Issue by csalajan** [d8ahazard/Phlex#78]
I've gone through all the steps trying to setup to cast to my chromecast. Everything else is working fine, except it can not find my chromecast.

my Phlex_error.log file is empty.

Phlex.log:
```
Thu, 08 Jun 2017 04:42:37 +0000 [ DEBUG ] api.php::scanDevices - Results::Servers: [{<Removed Data for privacy>]
Thu, 08 Jun 2017 04:42:37 +0000 [ DEBUG ] api.php::scanDevices - Results::Clients: []
Thu, 08 Jun 2017 04:42:37 +0000 [ DEBUG ] api.php::scanDevices - Results::Dvrs: []
```
(I removed any personal data from it, but all the plex server info is there and it connects to plex just fine)

I have the sockets module enabled

![image](https://user-images.githubusercontent.com/4378272/26912654-fd90d506-4be3-11e7-8cf4-73c9c508f313.png)

Router is a Motorola SBG6580. I have multicast enabled on my router.

![image](https://user-images.githubusercontent.com/4378272/26912676-24eb4ef6-4be4-11e7-9127-c3a53f48f90c.png)

Any advice on how to get it to connect to my chromecast?

**Comment by d8ahazard** [comment]
I don't see fetchCastDevices being called.  Did you enable them in settings?

**Comment by csalajan** [comment]
Yes, the setting is enabled. I just didn't copy over enough of the log.

```
Thu, 08 Jun 2017 13:38:25 +0000 [ INFO ] api.php::scanDevices - Force-recaching devices.
Thu, 08 Jun 2017 13:38:25 +0000 [ DEBUG ] util.php::fetchCastDevices - Function fired.
Thu, 08 Jun 2017 13:38:25 +0000 [ DEBUG ] Chromecast.php::scan - Function fired.
Thu, 08 Jun 2017 13:38:25 +0000 [ DEBUG ] Chromecast.php::scansub - Function fired.
Thu, 08 Jun 2017 13:38:30 +0000 [ DEBUG ] util.php::fetchCastDevices - Returns: []
Thu, 08 Jun 2017 13:38:30 +0000 [ DEBUG ] api.php::scanDevices - URL is: https://plex.tv/api/resources?includeHttps=1&includeRelay=0&X-Plex-Token=dyLgMYKexTGo7LB9xhBE
Thu, 08 Jun 2017 13:38:31 +0000 [ DEBUG ] api.php::scanDevices - Checking connections for mint-test
Thu, 08 Jun 2017 13:38:31 +0000 [ DEBUG ] api.php::scanDevices - Results::Servers: [{<Removed Server Data>}]
Thu, 08 Jun 2017 13:38:31 +0000 [ DEBUG ] api.php::scanDevices - Results::Clients: []
Thu, 08 Jun 2017 13:38:31 +0000 [ DEBUG ] api.php::scanDevices - Results::Dvrs: []
```

**Comment by d8ahazard** [comment]
On what OS are you hosting Phlex?

**Comment by d8ahazard** [comment]
@csaljan - Awaiting feedback, i tried to contact you on hangouts via GPlus.

**Comment by d8ahazard** [comment]
@csalajan Still awaiting feedback.  I'm going to close this for now, if you still require assistance, feel free to re-open the ticket or create a new issue.
