### ISSUE TITLE
PlexKodiConnect does not show up as a device

### ISSUE THREAD

**Issue by tomatosoupcan** [d8ahazard/Phlex#79]
Trying to get this set up, I am able to select my phone or browser (although that also doesn't seem to work, just to the phone), however PlexKodiConnect does not show up properly, I can cast to it from my phone or the web interface with no issues:

![image](https://user-images.githubusercontent.com/11912393/26913993-97f6187e-4bec-11e7-8d12-d571e074b1e8.png)

![image](https://user-images.githubusercontent.com/11912393/26913998-a0983124-4bec-11e7-9df7-6601c3c0f47e.png)

Saw a similar issue on here with Plex Media Center, so hoping it is a similar problem and an easy fix 😄

**Comment by d8ahazard** [comment]
@tomatosoupcan - Give a pull of the latest code, I added a fix for Samsung Smart TV's that don't register with plex.tv, I suspect this is what PlexKodiConnect is doing as well, so you may suddenly find it in the device list now.  Totally forgot I did that!  :D  

If it's still not showing, let me know here, and I'll have you email me contact info so we can discuss more.

**Comment by tomatosoupcan** [comment]
Get an error about new_body.php not existing, remove the line about it in api.php and I start getting the following when scanning for devices:
`[13-Jun-2017 01:42:44 Europe/Berlin] PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in C:\xampp\htdocs\api.php:3037
Stack trace:
#0 C:\xampp\htdocs\api.php(3037): SimpleXMLElement->__construct('<head>\n<title>E...')
#1 C:\xampp\htdocs\api.php(65): playerStatus()
#2 C:\xampp\htdocs\api.php(24): initialize()
#3 {main}
  thrown in C:\xampp\htdocs\api.php on line 3037`

**Comment by d8ahazard** [comment]
Gah!  Fixed!

**Comment by tomatosoupcan** [comment]
Looks like that fixed it, there are some new issues that I will throw into a separate issue since they seem to possibly be unrelated <3
