### ISSUE TITLE
Problem linking Google account

### ISSUE THREAD

**Issue by Fishqt** [d8ahazard/Phlex#8]
Hey. Great looking app, I'm trying to get this working.

I already had a web server running, although it's on Nginx so I hope that's not the cause of my problem.

When I try to link my Google account, I get to the API verification site, paste in my API token and press Link, but that just takes me to a standard Google search page with no confirmation message, and my account hasn't been linked.

Any idea what might cause this?

**Comment by Rytharr** [comment]
Check here to see if it linked https://myaccount.google.com/permissions

It says my account is linked on google but GH still tells me that it is not linked.

**Comment by XmemphistoX** [comment]
I ran into the same.  Try getting the google home app on your IOS/Android phone and check under the google home services section.  You'll see Flex TV there, theres an option to link your account.  Do it this way - Copy the API from your web gui and paste it in here as well.

**Comment by allanak** [comment]
I've tried linking my account both in Chrome on my desktop and GHome app on iOS. The app shows as linked in the permissions page, but GHome tells me "it looks like your phlex tv account is not linked yet"

I am also using nginx as a reverse proxy with letsencrypt SSL certs, what about you @Fishqt ? Wonder if it's an SSL thing?

**Comment by Fishqt** [comment]
I've tried adding it from the Google Home app as well, but the same thing happens here. Phlex is listed as having basic right on my permissions page, and I've tried removing and readding it, but still nothing.

@allanak I'm not using SSL for this particular vhost, just to eliminate any potential issues. I guess I could set up a temporary apache server just to see if it actually is an nginx issue.

**Comment by Vader699** [comment]
what's your nginx config look like?

**Comment by allanak** [comment]
@Vader699 I'm using the default config from the docker container jwilder/nginx-proxy. Sanitized for my domain name/IP.

`upstream phlex.packetplayground.com {
                                ## Can be connect with "media" network
                        # phlex
                        server 172.19.x.x:80;
}
server {
        server_name phlex.x.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name phlex.x.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_certificate /etc/nginx/certs/phlex.x.com.crt;
        ssl_certificate_key /etc/nginx/certs/phlex.x.com.key;
        ssl_dhparam /etc/nginx/certs/phlex.x.com.dhparam.pem;
        add_header Strict-Transport-Security "max-age=31536000";
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://phlex.x.com;
        }
}`

**Comment by Vader699** [comment]
Sorry, I'm of little help.  I have no experience with docker.

**Comment by Fishqt** [comment]
Well, here's my nginx config for the host I'm using. I've tried not using SSL too, didn't seem to act any differently.

````
server{
	listen 80;
	server_name example.com;
	rewrite ^ https://$server_name$request_uri? permanent;

}

server{
    listen 443 ssl;
    server_name example.com;
    root /var/www/;
    ssl_certificate "/etc/letsencrypt/live/example.com/fullchain.pem";
    ssl_certificate_key "/etc/letsencrypt/live/example.com/privkey.pem";
    ssl_dhparam "/home/fish/dhparams.key";
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout 10m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:SEED:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!RSAPSK:!aDH:!aECDH:!EDH-DSS-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!SRP;
    ssl_prefer_server_ciphers on;
    autoindex off;
    index index.html index.php;
    location ~* \.php$ {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_index index.php;
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
        error_page 404 /404.html;
        error_page 403 /404.html;
        location /404.html {
        root /var/www/;
        }
}

**Comment by Vader699** [comment]
The only difference I see with mine is this line
fastcgi_split_path_info ^(.+\.php)(/.*)$;
And I am using php 7.0.  Though I doubt that makes a difference as well. 

Also you can use 
https://example.com/api.php?testclient&apiToken=90bXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
to test if your setup is working correctly.  I had to use this to figure out my setup problem.  Obviously use your apiToken and your address to test.

**Comment by Fishqt** [comment]
Yeah, I doubt those settings are part of my issue.

The api test gives me "success" so I assume everything there is okay. It doesn't say anything else, though.

**Comment by d8ahazard** [comment]
There were some issues last night as a result of an upgrade to setting storage for the server - these issues should be resolved.  Please try re-linking your account and see if voice commands work.  :D

**Comment by jmeehan11** [comment]
I am having the exact same issue.
Google home keeps saying: my account is not linked
Checking google apps showed flex tv had basic access to my google account.
I removed it to try to relink it, and now it wont work at all.

**Comment by d8ahazard** [comment]
You should now be able to link your account with no issues, I've re-done the whole process.

**Comment by d8ahazard** [comment]
Going to close this for now - please open a new issue or comment on an existing one if you continue to have issues.
