### ISSUE TITLE
Unable to link phlex tv to google home

### ISSUE THREAD

**Issue by hermy65** [d8ahazard/Phlex#82]
Ive got it installed and running, clicked the Register Server button and picked my google account and after that is done as per your instructions i asked to talk to Flex TV which it responded to with a: i'll try to do that for you. The next step according to the instructions was to look through the Google Home app and i should see a place to link my account to Phlex again but im not seeing anything. Any insight?

**Comment by d8ahazard** [comment]
If you don't see a link card in the Ghome app, you can manually link/unlink Phlex by finding Flex TV in the services section.

**Comment by hermy65** [comment]
The only place i can find services is if i go to More Settings then Services. Ive looked through every category there and am not seeing anything named Phlex (or Flex) TV.

**Comment by d8ahazard** [comment]
It's there, just hidden.  I just found it in the Google home app, under
settings, then Services, then assistant apps.

**Comment by hermy65** [comment]
Ok, found it buried in there and it says Account Linked. I unlinked it and relinked it to see if that would do anything for me but i still am unable to get phlex to do anything for me. No matter what i ask i get a "Sure let me do that for you" or "Ill see what i can do" with not actual actions.

**Comment by d8ahazard** [comment]
Check my donation address in the readme, send me your gmail info, I'll take a look at the server logs once.

**Comment by sumeetgoutam** [comment]
So I was having this same issue and I could not find the Assistant Apps option. I then realized this is something not supported to Canada :(.

**Comment by itova** [comment]
Have there been any updates? Was wondering if there was anyway to get it to work in Canada?
