### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by tomatosoupcan** [d8ahazard/Phlex#83]
I'm sure a few of these are the result of using PlexKodiConnect, but I could be incorrect as it is happening Plexbmc helper as well, however some commands do work when controlling my phone:

- Playback controls are not working, e.g. saying stop playback responds with "Plex should now be stopped." however, it does not stop. Any player adjustment results in an error such as:
`[13-Jun-2017 02:29:26 Europe/Berlin] PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in C:\xampp\htdocs\api.php:3038
Stack trace:
#0 C:\xampp\htdocs\api.php(3038): SimpleXMLElement->__construct('<head>\n<title>E...')
#1 C:\xampp\htdocs\api.php(625): playerStatus()
#2 C:\xampp\htdocs\api.php(1633): parseControlCommand('set volume DOWN')
#3 C:\xampp\htdocs\api.php(228): parseApiCommand(Array)
#4 C:\xampp\htdocs\api.php(25): initialize()
#5 {main}
  thrown in C:\xampp\htdocs\api.php on line 3038`
Overall it seems that this applies to Play, Resume, Pause, Stop, Skip F/B, Seek F/B, Jump To, Stop, Volume, and Currently Playing

- Asking for the newest episode of something results in an error, Phlex responds with
`"I'm sorry, I was unable to find newest episode american gods in your library.  Would you like me to add it to your`

**Comment by tomatosoupcan** [comment]
For reference, these controls all work properly when the commands are issued from the Plex app on my phone, if I am casting to PlexKodiConnect from there

**Comment by d8ahazard** [comment]
@tomatosoupcan - Please give a pull of the latest commit, I've added initial playback and command support for PlexKodiConnect.  

I've verified that stop/play/pause commands work, and the syntax to initiate playback *should* work, however, I can't even get the plex.tv web app to connect to PCC - it throws the same error as Phlex when i try to connect to it.  So, let me know if playback works, and then I'll start fixing up the remaining control commands.

**Comment by tomatosoupcan** [comment]
Welp, newest build playback isn't working at all, just says "Hmm it's a taking a little longer to get a response back than usual but I will try to do that for you"
`[16-Jun-2017 04:04:18 Europe/Berlin] PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in C:\xampp\htdocs\api.php:3080
Stack trace:
#0 C:\xampp\htdocs\api.php(3080): SimpleXMLElement->__construct('<head>\n<title>E...')
#1 C:\xampp\htdocs\api.php(65): playerStatus()
#2 C:\xampp\htdocs\api.php(24): initialize()
#3 {main}
  thrown in C:\xampp\htdocs\api.php on line 3080
`

**Comment by d8ahazard** [comment]
@tomatosoupcan - My apologies, I apparently didn't read that playback commands were already working.  I've reverted the playback command to the way it was before I started meddling, I've left the control commands as they were.  Please LMK if this helps.

Updated with commit ba5c1af11b29f6541c4e213fbae4989c5252adf0

**Comment by d8ahazard** [comment]
@tomatosoupcan - Any update?

**Comment by d8ahazard** [comment]
@tomatosoupcan - If you choose to revisit this project and still have this issue, feel free to re-open and comment.
