### ISSUE TITLE
Resume Playback

### ISSUE THREAD

**Issue by codymhorton** [d8ahazard/Phlex#87]
So far when I stop playback then come back later (so not pause resume) the movie or episode starts completely over. Could you implement a resume playback feature? Thanks!

For reference: https://forums.plex.tv/discussion/comment/1459915#Comment_1459915

**Comment by d8ahazard** [comment]
Fixed with 02b2b6c and cbf4d18 .

**Comment by codymhorton** [comment]
I'm not sure if this worked. I tried to play a movie then stop it. I then told flex tv to play the movie again but that starts the movie over. I also tried to say resume playback but that doesn't do anything.

**Comment by juniperhill** [comment]
Did you get this to work? Cod I have the same problem.

**Comment by mattpurnell** [comment]
I can't get this to work either?
