### ISSUE TITLE
Promising.. but.... need a little help

### ISSUE THREAD

**Issue by sambomartin** [d8ahazard/Phlex#88]
so Im en-gb, so can use google interface, but got the IFTTT sorted.

i would like however to play music from phlex to the google home speaker?  is this possible without having to get another chromecast device?

thanks
sam

**Comment by d8ahazard** [comment]
Yes, it should be.  Music Playback is still not 100% perfect, but you are able to play music from Plex to any device that supports the cast protocol, which includes Google Home, Android TV devices, and even most Vizio TV's.  

Also, if you wish to use Google Home without IFTTT, you can set the language to EN-US in the ghome app until Google adds full support for actions in the UK.
