### ISSUE TITLE
Error 6 could not resolve host

### ISSUE THREAD

**Issue by jfjallid** [d8ahazard/Phlex#89]
I'm running phlex in a docker build (digitalhigh/phlex) and Phlex is using https.
When I try to register my phlex instance to my Google account it complains that it can't connect to the client at my public address. I have successfully connected to my phlex instance using that address from my mobile phone over mobile data.

I can link my Google account to Flex TV in the Google home app but asking to talk to Flex TV returns "error 6 could not resolve host <my public domain name>.

I have successfully linked and used Flex TV before but after I reinstall of the Phlex instance and change of hostname it seems that I can't relink the account properly. The hostname that results in error 6 is also incorrect and I'm assuming it is stored in a database from the previous install and not removed when I unlinked the account.

**Comment by d8ahazard** [comment]
Is your SSL cert self-signed?

**Comment by jfjallid** [comment]
No, it is a certificate from Lets Encrypt.

**Comment by geneccx** [comment]
Having the same issue using a Let's Encrypt cert.

**Comment by d8ahazard** [comment]
I see the cacert from Mozilla has been updated from the one I'm using for
verification, I've updated this on the server. Why don't you guys try now
and see if having it updated helps.

**Comment by jfjallid** [comment]
The problem remains for me. 

How can I change the public address for my server? I change the public address from the Phlex web interface and then tries to register my server but it complains that the address is not reachable although I can reach it just fine from a mobile device. 

Linking from the Google Home app is successful but when trying to talk to Flex TV it complains that it can't reach a public address I have used previously but not using anymore. It seems as though it remebers what address I have used even after unlinking the account and preventing me from updating to a new one.

**Comment by d8ahazard** [comment]
Send me an email to my donate address in the readme with your server
address and email used to register.  We can chat more about it there so I
can do some diagnostics.

**Comment by d8ahazard** [comment]
@jfjallid @geneccx - Try now, I've modified some things on the server a bit more.

**Comment by geneccx** [comment]
It allows me to register now. The return url seems to be set to the Google homepage, so there's no confirmation that it worked, but testing with my Google Home, I am able to issue commands. Resolved on my end, thank you.

**Comment by jfjallid** [comment]
@d8ahazard When trying to link from the Phlex web gui I get the same result as before. Trying to link from google home app now redirects me to plexchat.com without linking the account. I'll send you an email with my details.
