### ISSUE TITLE
Radarr Download Issue - Larger Libraries

### ISSUE THREAD

**Issue by nickmodernized** [d8ahazard/Phlex#91]
It appears that Radarr is not working for downloads (possibly Sonarr too).  The JSON result shows mediaStatus of "null", and when I look in Phlex.log, I see this for the request:

Sat, 24 Jun 2017 19:01:15 +0200 [ DEBUG ] api.php::radarrDownload - Search URL is http://localhost:38086/api/movies/lookup?term=die+hard+2&apikey=a48b47db080b4a3db8379434ba9b0ebc
Sat, 24 Jun 2017 19:01:20 +0200 [ DEBUG ] api.php::radarrDownload - Unable to fetch current library info!

When I manually type http://localhost:38086/api/movies/lookup?term=die+hard+2&apikey=a48b47db080b4a3db8379434ba9b0ebc in the browser, I get a JSON response that shows correct data:

[
  {
    "title": "Die Hard 2",
    "sortTitle": "die hard 2",
    "sizeOnDisk": 0,
    "status": "released",
    "overview": "John McClane is an off-duty cop gripped with a feeling of déjà vu when on a snowy Christmas Eve in the nation's capital, terrorists seize a major international airport, holding thousands of holiday travelers hostage. Renegade military commandos led by a murderous rogue officer plot to rescue a drug lord from justice and are prepared for every contingency except one: McClane's smart-mouthed heroics.",
    "inCinemas": "1990-07-02T00:00:00Z",
    "images": [
      {
        "coverType": "poster",
        "url": "http://image.tmdb.org/t/p/original/zSgL998DXaljsCmwQuwDM8Ak4rV.jpg"
      }
    ],
    "downloaded": false,
    "remotePoster": "http://image.tmdb.org/t/p/original/zSgL998DXaljsCmwQuwDM8Ak4rV.jpg",
    "year": 1990,
    "hasFile": false,
    "profileId": 0,
    "pathState": "dynamic",
    "monitored": false,
    "minimumAvailability": "tba",
    "isAvailable": true,
    "folderName": "",
    "runtime": 0,
    "tmdbId": 1573,
    "titleSlug": "die-hard-2-1573",
    "genres": [],
    "tags": [],
    "added": "0001-01-01T00:00:00Z",
    "ratings": {
      "votes": 1711,
      "value": 6.6
    },
    "alternativeTitles": [],
    "qualityProfileId": 0
  },
  {
    "title": "The Last Blood",
    "sortTitle": "last blood",
    "sizeOnDisk": 0,
    "status": "released",
    "overview": "Tam is Lui Tai, an Interpol agent assigned to protect a famous religious leader, the Daka Lama, who's targeted for death by the militant Japanese terrorist group, the Red Army. Lui Tai hooks up with the Daka Lama in Singapore, but a Red Army attack leaves the Daka Lama in critical condition. Unfortunately, the Daka Lama has a rare blood type, and there are only three possible donors in all of Singapore. Two are quickly offed, with only annoying lowlife Fatty (Eric Tsang) remaining. Liu Tai and local Singapore cop Stone (Leung Ka-Yan) try to beat the Red Army to Fatty, but they also have to deal with Hong Kong triad boy B (Andy Lau), who wants to make sure Fatty's blood goes to his girlfriend (May Lo) first. She was also wounded in the same attack as the Daka Lama, and also needs the ultra-rare blood. Will everyone work together to make sure both the Daka Lama and B's girl are saved? Or will they get in each other's way and allow the two to die?",
    "inCinemas": "1991-03-13T00:00:00Z",
    "images": [
      {
        "coverType": "poster",
        "url": "http://image.tmdb.org/t/p/original/cqV4hE1KQbketHWXhH53NWZnNK7.jpg"
      }
    ],
    "downloaded": false,
    "remotePoster": "http://image.tmdb.org/t/p/original/cqV4hE1KQbketHWXhH53NWZnNK7.jpg",
    "year": 1991,
    "hasFile": false,
    "profileId": 0,
    "pathState": "dynamic",
    "monitored": false,
    "minimumAvailability": "tba",
    "isAvailable": true,
    "folderName": "",
    "runtime": 0,
    "tmdbId": 45460,
    "titleSlug": "the-last-blood-45460",
    "genres": [],
    "tags": [],
    "added": "0001-01-01T00:00:00Z",
    "ratings": {
      "votes": 2,
      "value": 4.3
    },
    "alternativeTitles": [],
    "qualityProfileId": 0
  }
]

**Comment by nickmodernized** [comment]
Looking deeper into the issue, it looks like that error corresponds with the radarr "movie" command:

http://localhost:38086/api/movie?apikey=a48b47db080b4a3db8379434ba9b0ebc

When I run that command, it responds...but it takes a while because my movie library has grown substantially.

Should I do some sort of timeout modification or summat for people like me?

**Comment by nickmodernized** [comment]
So...changing these lines:

$movieCollectionURL = $baseURL.'/movie?apikey='.$radarrApiKey;
		$movieCollection = curlGet($movieCollectionURL,null,60);
		if ($movieCollection) {
			//write_log("Collection data retrieved: ".$movieCollection);
			$movieJSON = json_decode($movieCollection,true);
		} else {
			write_log("Unable to fetch current library info!");
			return false;
		}

To this:

$movieCollectionURL = $baseURL.'/movie?apikey='.$radarrApiKey;
		$movieCollection = curlGet($movieCollectionURL);
		if ($movieCollection) {
			//write_log("Collection data retrieved: ".$movieCollection);
			$movieJSON = json_decode($movieCollection,true);
		} else {
			write_log("Unable to fetch current library info!");
			return false;
		}

Works.  However, Phlex responds with an "I'm sorry, it's taking a little bit longer than usual" message .  When I say "Okay" to that message, it says "I'm sorry, I didn't understand that response."

I'm going to edit the task title to "Radarr for larger libraries".  Not sure what fix we want to put in...the longer timeout is a bit of a hack-ish solve, but it does get it working again.

**Comment by d8ahazard** [comment]
Ohai, looks like I implemented this a while ago.  Closed!  :D
