### ISSUE TITLE
Feature Request: Alexa Integration

### ISSUE THREAD

**Issue by KaraokeStu** [d8ahazard/Phlex#92]
Hi,

The current Plex skill just isn't up to the job - please please make this work with Alexa! 

Happy to test for you, I'm a developer too! (Although .net!)

**Comment by d8ahazard** [comment]
Hey Stu!  Been messaging you on the forums, but I'll need an Alexa tester soon, as I don't actually own a device.  PM me on the Plex forum with your contact info (hangouts preferred) if you want to test.

**Comment by KaraokeStu** [comment]
I've sent you a message!

**Comment by d8ahazard** [comment]
Integration has been implemented, you should know, you're my beta tester.
