### ISSUE TITLE
Images in readme.md say "3rd party hosting disabled"

### ISSUE THREAD

**Issue by waterapi** [d8ahazard/Phlex#93]
<img width="690" alt="screen shot 2017-07-02 at 6 05 45 am" src="https://user-images.githubusercontent.com/29823690/27765319-96955090-5ef1-11e7-8a59-07f3ad1d6e75.png">

You can upload them to imgur or edit it https://help.github.com/articles/editing-files-in-your-repository/ and drag and drop the image in GitHub.

Hope this helps.

**Comment by d8ahazard** [comment]
Fixed!
